pool:
  vmImage: 'ubuntu-latest'

trigger:
  batch: true
  branches:
    include:
      - main
  paths:
    include:
      - documentation
      - pipelines/documentation

pr: none

variables:
  WorkingDir: 'documentation'
  FullWorkingDir: '$(System.DefaultWorkingDirectory)/$(WorkingDir)'
  DataDir: '$(FullWorkingDir)/tools'

steps:
  - bash: sudo apt-get update
    displayName: 'Update the package list'

  - bash: sudo apt-get install -y pandoc texlive-latex-extra
    displayName: 'Install pandoc & latex'

  - bash: sudo apt-get install texlive-fonts-recommended texlive-fonts-extra
    displayName: 'Install tex fonts'

  - task: Npm@1
    displayName: 'Install mermaid cli'
    inputs:
      command: 'custom'
      customCommand: 'install -g @mermaid-js/mermaid-cli'

  - template: generate-docs.yaml
    parameters:
      folder: 'architecture'

  - template: generate-docs.yaml
    parameters:
      folder: 'developers'

  - template: generate-docs.yaml
    parameters:
      folder: 'feature'

  - template: generate-docs.yaml
    parameters:
      folder: 'testing'

  - template: generate-docs.yaml
    parameters:
      folder: 'prototype'

  - template: generate-docs.yaml
    parameters:
      folder: 'operational'

  - template: generate-docs.yaml
    parameters:
      folder: 'data'

  - task: PublishPipelineArtifact@1
    displayName: 'Publish artifacts'
    inputs:
      targetPath: '$(WorkingDir)/pub'
      artifact: 'docs'
      publishLocation: 'pipeline'