pool:
  vmImage: 'ubuntu-latest'

trigger:
  batch: true
  branches:
    include:
      - main
  paths:
    include:
      - documentation

pr: none

variables:
  WorkingDir: 'documentation'

steps:
  - bash: sudo apt-get install -y pandoc texlive-latex-extra

  - task: Npm@1
    inputs:
      command: 'custom'
      customCommand: 'install -g @mermaid-js/mermaid-cli'

  - bash: ./tools/build-docs.sh architecture architecture.pdf -build --strip-comments --toc -f markdown -t pdf --pdf-engine=pdflatex --wrap=preserve --template=tools/templates/pdf-template.latex
    workingDirectory: $(WorkingDir)

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(WorkingDir)'
      artifact: 'docs'
      publishLocation: 'pipeline'