pool:
  vmImage: 'ubuntu-latest'

trigger:
  batch: true
  branches:
    include:
      - main
  paths:
    include:
      - documentation

pr: none

variables:
  WorkingDir: 'documentation'

steps:
  - bash: sudo apt-get install -y pandoc texlive-latex-extra make

  - task: Npm@1
    inputs:
      command: 'custom'
      customCommand: 'install -g @mermaid-js/mermaid-cli'

  - bash: make architecture-pdf
    workingDirectory: $(WorkingDir)

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(WorkingDir)'
      artifact: 'docs'
      publishLocation: 'pipeline'