pool:
  vmImage: 'ubuntu-latest'

trigger:
  batch: true
  branches:
    include:
      - main
  paths:
    include:
      - documentation
      - pipelines/documentation

pr: none

variables:
  - group: 'sharepoint'
  - name: WorkingDir
    value: 'documentation'
  - name: FullWorkingDir
    value: '$(System.DefaultWorkingDirectory)/$(WorkingDir)'
  - name: DataDir
    value: '$(FullWorkingDir)/tools'

steps:
  - bash: sudo apt-get update
    displayName: 'Update the package list'

  - bash: sudo apt-get install -y pandoc texlive-latex-extra
    displayName: 'Install pandoc & latex'

  - bash: sudo apt-get install texlive-fonts-recommended texlive-fonts-extra
    displayName: 'Install tex fonts'

  - task: Npm@1
    displayName: 'Install mermaid cli'
    inputs:
      command: 'custom'
      customCommand: 'install -g @mermaid-js/mermaid-cli'

  - template: generate-docs.yaml
    parameters:
      folder: 'architecture'

  # - template: generate-docs.yaml
  #   parameters:
  #     folder: 'developers'

  # - template: generate-docs.yaml
  #   parameters:
  #     folder: 'feature'

  # - template: generate-docs.yaml
  #   parameters:
  #     folder: 'quality-assurance'

  # - template: generate-docs.yaml
  #   parameters:
  #     folder: 'prototype'

  # - template: generate-docs.yaml
  #   parameters:
  #     folder: 'operational'

  # - template: generate-docs.yaml
  #   parameters:
  #     folder: 'data'

  - task: PublishPipelineArtifact@1
    displayName: 'Publish artifacts'
    inputs:
      targetPath: '$(WorkingDir)/pub'
      artifact: 'docs'
      publishLocation: 'pipeline'

  - task: halliba.az-pipelines-2-sharepoint.az-pipelines-2-sharepoint.az-pipelines-2-sharepoint@0
    displayName: 'Upload files to SharePoint'
    inputs:
      tenantId: $(SharePoint_TenantId)
      clientId: $(SharePoint_ClientId)
      clientSecret: $(SharePoint_ClientSecret)
      driveId: $(SharePoint_DocumentsRootUrl)
      targetFolder: '/FBIT%20support/Documentation/'
      contents: '$(WorkingDir)/pub/**'
      conflictBehaviour: 'replace'