pool:
  vmImage: 'ubuntu-latest'

trigger:
  batch: true
  branches:
    include:
      - main
  paths:
    include:
      - documentation

pr: none

variables:
  WorkingDir: 'documentation'

steps:
  - bash: sudo apt-get install -qq -y pandoc texlive

  - task: Npm@1
    inputs:
      command: 'custom'
      customCommand: 'install -g @mermaid-js/mermaid-cli'

  - bash: ./tools/make-pdf.sh architecture architecture architecture.pdf
    workingDir: $(WorkingDir)
