export type ExpenditureData = {
  urn: string;
  name: string;
  schoolType: string;
  localAuthority: string;
  totalExpenditure: number;
  totalIncome: number;
  numberOfPupils: bigint;
  totalTeachingSupportStaffCosts: number;
  teachingStaffCosts: number;
  supplyTeachingStaffCosts: number;
  educationalConsultancyCosts: number;
  educationSupportStaffCosts: number;
  agencySupplyTeachingStaffCosts: number;
  netCateringCosts: number;
  cateringStaffCosts: number;
  cateringSuppliesCosts: number;
  incomeCatering: number;
  administrativeSuppliesCosts: number;
  learningResourcesIctCosts: number;
  totalEducationalSuppliesCosts: number;
  examinationFeesCosts: number;
  breakdownEducationalSuppliesCosts: number;
  learningResourcesNonIctCosts: number;
  totalNonEducationalSupportStaffCosts: number;
  administrativeClericalStaffCosts: number;
  auditorsCosts: number;
  otherStaffCosts: number;
  professionalServicesNonCurriculumCosts: number;
  totalPremisesStaffServiceCosts: number;
  cleaningCaretakingCosts: number;
  maintenancePremisesCosts: number;
  otherOccupationCosts: number;
  premisesStaffCosts: number;
  totalOtherCosts: number;
  otherInsurancePremiumsCosts: number;
  directRevenueFinancingCosts: number;
  groundsMaintenanceCosts: number;
  indirectEmployeeExpenses: number;
  interestChargesLoanBank: number;
  privateFinanceInitiativeCharges: number;
  rentRatesCosts: number;
  specialFacilitiesCosts: number;
  staffDevelopmentTrainingCosts: number;
  staffRelatedInsuranceCosts: number;
  supplyTeacherInsurableCosts: number;
  communityFocusedSchoolStaff: number;
  communityFocusedSchoolCosts: number;
  totalUtilitiesCosts: number;
  energyCosts: number;
  waterSewerageCosts: number;
  hasIncompleteData: boolean;
  totalPupils: bigint;
  schoolName: string;
  laName: string;
};

export type Balance = {
  yearEnd: string;
  term: string;
  dimension: string;
  inYearBalance: number;
  revenueReserve: number;
  totalPupils: bigint;
  schoolName: string;
  laName: string;
};

export type Census = {
  urn: string;
  totalPupils: bigint;
  workforceFTE: number;
  workforceHeadcount: number;
  teachersFTE: number;
  seniorLeadershipFTE: number;
  teachingAssistantFTE: number;
  nonClassroomSupportStaffFTE: number;
  auxiliaryStaffFTE: number;
  percentTeacherWithQualifiedStatus: number;
  schoolName: string;
  schoolType: string;
  laName: string;
};

export type CensusHistory = {
  year: string;
  term: string;
  urn: string;
  totalPupils: bigint;
  workforceFTE: number;
  workforceHeadcount: number;
  teachersFTE: number;
  seniorLeadershipFTE: number;
  teachingAssistantFTE: number;
  nonClassroomSupportStaffFTE: number;
  auxiliaryStaffFTE: number;
  percentTeacherWithQualifiedStatus: number;
};

export type Income = {
  yearEnd: string;
  term: string;
  dimension: string;
  totalIncome: number;
  totalGrantFunding: number;
  totalSelfGeneratedFunding: number;
  directRevenueFinancing: number;
  directGrants: number;
  prePost16Funding: number;
  otherDfeGrants: number;
  otherIncomeGrants: number;
  governmentSource: number;
  communityGrants: number;
  academies: number;
  incomeFacilitiesServices: number;
  incomeCatering: number;
  donationsVoluntaryFunds: number;
  receiptsSupplyTeacherInsuranceClaims: number;
  investmentIncome: number;
  otherSelfGeneratedIncome: number;
  totalPupils: bigint;
  schoolName: string;
  laName: string;
};

export type Expenditure = {
  yearEnd: string;
  term: string;
  dimension: string;
  totalExpenditure: number;
  totalTeachingSupportStaffCosts: number;
  teachingStaffCosts: number;
  supplyTeachingStaffCosts: number;
  educationalConsultancyCosts: number;
  educationSupportStaffCosts: number;
  agencySupplyTeachingStaffCosts: number;
  totalNonEducationalSupportStaffCosts: number;
  administrativeClericalStaffCosts: number;
  auditorsCosts: number;
  otherStaffCosts: number;
  professionalServicesNonCurriculumCosts: number;
  totalEducationalSuppliesCosts: number;
  examinationFeesCosts: number;
  learningResourcesNonIctCosts: number;
  learningResourcesIctCosts: number;
  totalPremisesStaffServiceCosts: number;
  cleaningCaretakingCosts: number;
  maintenancePremisesCosts: number;
  otherOccupationCosts: number;
  premisesStaffCosts: number;
  totalUtilitiesCosts: number;
  energyCosts: number;
  waterSewerageCosts: number;
  administrativeSuppliesCosts: number;
  totalGrossCateringCosts: number;
  cateringStaffCosts: number;
  cateringSuppliesCosts: number;
  totalOtherCosts: number;
  otherInsurancePremiumsCosts: number;
  directRevenueFinancingCosts: number;
  groundsMaintenanceCosts: number;
  indirectEmployeeExpenses: number;
  interestChargesLoanBank: number;
  privateFinanceInitiativeCharges: number;
  rentRatesCosts: number;
  specialFacilitiesCosts: number;
  staffDevelopmentTrainingCosts: number;
  staffRelatedInsuranceCosts: number;
  supplyTeacherInsurableCosts: number;
  communityFocusedSchoolStaff: number;
  communityFocusedSchoolCosts: number;
  totalPupils: bigint;
  schoolName: string;
  laName: string;
};
