export type ExpenditureBase = {
  schoolTotalExpenditure: number;
  schoolTotalTeachingSupportStaffCosts: number;
  schoolTeachingStaffCosts: number;
  schoolSupplyTeachingStaffCosts: number;
  schoolEducationalConsultancyCosts: number;
  schoolEducationSupportStaffCosts: number;
  schoolAgencySupplyTeachingStaffCosts: number;
  schoolTotalNonEducationalSupportStaffCosts: number;
  schoolAdministrativeClericalStaffCosts: number;
  schoolAuditorsCosts: number;
  schoolOtherStaffCosts: number;
  schoolProfessionalServicesNonCurriculumCosts: number;
  schoolTotalEducationalSuppliesCosts: number;
  schoolExaminationFeesCosts: number;
  schoolLearningResourcesNonIctCosts: number;
  schoolLearningResourcesIctCosts: number;
  schoolTotalPremisesStaffServiceCosts: number;
  schoolCleaningCaretakingCosts: number;
  schoolMaintenancePremisesCosts: number;
  schoolOtherOccupationCosts: number;
  schoolPremisesStaffCosts: number;
  schoolTotalUtilitiesCosts: number;
  schoolEnergyCosts: number;
  schoolWaterSewerageCosts: number;
  schoolAdministrativeSuppliesCosts: number;
  schoolTotalGrossCateringCosts: number;
  schoolCateringStaffCosts: number;
  schoolCateringSuppliesCosts: number;
  schoolTotalOtherCosts: number;
  schoolDirectRevenueFinancingCosts: number;
  schoolGroundsMaintenanceCosts: number;
  schoolIndirectEmployeeExpenses: number;
  schoolInterestChargesLoanBank: number;
  schoolOtherInsurancePremiumsCosts: number;
  schoolPrivateFinanceInitiativeCharges: number;
  schoolRentRatesCosts: number;
  schoolSpecialFacilitiesCosts: number;
  schoolStaffDevelopmentTrainingCosts: number;
  schoolStaffRelatedInsuranceCosts: number;
  schoolSupplyTeacherInsurableCosts: number;
  schoolCommunityFocusedSchoolStaff: number;
  schoolCommunityFocusedSchoolCosts: number;

  centralTotalExpenditure: number;
  centralTotalTeachingSupportStaffCosts: number;
  centralTeachingStaffCosts: number;
  centralSupplyTeachingStaffCosts: number;
  centralEducationalConsultancyCosts: number;
  centralEducationSupportStaffCosts: number;
  centralAgencySupplyTeachingStaffCosts: number;
  centralTotalNonEducationalSupportStaffCosts: number;
  centralAdministrativeClericalStaffCosts: number;
  centralAuditorsCosts: number;
  centralOtherStaffCosts: number;
  centralProfessionalServicesNonCurriculumCosts: number;
  centralTotalEducationalSuppliesCosts: number;
  centralExaminationFeesCosts: number;
  centralLearningResourcesNonIctCosts: number;
  centralLearningResourcesIctCosts: number;
  centralTotalPremisesStaffServiceCosts: number;
  centralCleaningCaretakingCosts: number;
  centralMaintenancePremisesCosts: number;
  centralOtherOccupationCosts: number;
  centralPremisesStaffCosts: number;
  centralTotalUtilitiesCosts: number;
  centralEnergyCosts: number;
  centralWaterSewerageCosts: number;
  centralAdministrativeSuppliesCosts: number;
  centralTotalGrossCateringCosts: number;
  centralCateringStaffCosts: number;
  centralCateringSuppliesCosts: number;
  centralTotalOtherCosts: number;
  centralDirectRevenueFinancingCosts: number;
  centralGroundsMaintenanceCosts: number;
  centralIndirectEmployeeExpenses: number;
  centralInterestChargesLoanBank: number;
  centralOtherInsurancePremiumsCosts: number;
  centralPrivateFinanceInitiativeCharges: number;
  centralRentRatesCosts: number;
  centralSpecialFacilitiesCosts: number;
  centralStaffDevelopmentTrainingCosts: number;
  centralStaffRelatedInsuranceCosts: number;
  centralSupplyTeacherInsurableCosts: number;
  centralCommunityFocusedSchoolStaff: number;
  centralCommunityFocusedSchoolCosts: number;

  totalExpenditure: number;
  totalTeachingSupportStaffCosts: number;
  teachingStaffCosts: number;
  supplyTeachingStaffCosts: number;
  educationalConsultancyCosts: number;
  educationSupportStaffCosts: number;
  agencySupplyTeachingStaffCosts: number;
  totalNonEducationalSupportStaffCosts: number;
  administrativeClericalStaffCosts: number;
  auditorsCosts: number;
  otherStaffCosts: number;
  professionalServicesNonCurriculumCosts: number;
  totalEducationalSuppliesCosts: number;
  examinationFeesCosts: number;
  learningResourcesNonIctCosts: number;
  learningResourcesIctCosts: number;
  totalPremisesStaffServiceCosts: number;
  cleaningCaretakingCosts: number;
  maintenancePremisesCosts: number;
  otherOccupationCosts: number;
  premisesStaffCosts: number;
  totalUtilitiesCosts: number;
  energyCosts: number;
  waterSewerageCosts: number;
  administrativeSuppliesCosts: number;
  totalGrossCateringCosts: number;
  cateringStaffCosts: number;
  cateringSuppliesCosts: number;
  totalOtherCosts: number;
  directRevenueFinancingCosts: number;
  groundsMaintenanceCosts: number;
  indirectEmployeeExpenses: number;
  interestChargesLoanBank: number;
  otherInsurancePremiumsCosts: number;
  privateFinanceInitiativeCharges: number;
  rentRatesCosts: number;
  specialFacilitiesCosts: number;
  staffDevelopmentTrainingCosts: number;
  staffRelatedInsuranceCosts: number;
  supplyTeacherInsurableCosts: number;
  communityFocusedSchoolStaff: number;
  communityFocusedSchoolCosts: number;
};

export type SchoolExpenditure = ExpenditureBase & {
  urn: string;
  schoolName: string;
  schoolType: string;
  laName: string;
  totalPupils: bigint;
  totalInternalFloorArea: number;
};

export type SchoolExpenditureHistory = ExpenditureBase & {
  urn: string;
  year: number;
  term: string;
};

export type TrustExpenditure = ExpenditureBase & {
  companyNumber: string;
  trustName: string;
};

export type BalanceHistory = {
  yearEnd: string;
  term: string;
  inYearBalance: number;
  revenueReserve: number;
};

export type Census = {
  urn: string;
  totalPupils: bigint;
  workforceFTE: number;
  workforceHeadcount: number;
  teachersFTE: number;
  seniorLeadershipFTE: number;
  teachingAssistantFTE: number;
  nonClassroomSupportStaffFTE: number;
  auxiliaryStaffFTE: number;
  percentTeacherWithQualifiedStatus: number;
  schoolName: string;
  schoolType: string;
  laName: string;
};

export type CensusHistory = {
  year: string;
  term: string;
  urn: string;
  totalPupils: bigint;
  workforceFTE: number;
  workforceHeadcount: number;
  teachersFTE: number;
  seniorLeadershipFTE: number;
  teachingAssistantFTE: number;
  nonClassroomSupportStaffFTE: number;
  auxiliaryStaffFTE: number;
  percentTeacherWithQualifiedStatus: number;
};

export type Income = {
  yearEnd: string;
  term: string;
  dimension: string;
  totalIncome: number;
  totalGrantFunding: number;
  totalSelfGeneratedFunding: number;
  directRevenueFinancing: number;
  directGrants: number;
  prePost16Funding: number;
  otherDfeGrants: number;
  otherIncomeGrants: number;
  governmentSource: number;
  communityGrants: number;
  academies: number;
  incomeFacilitiesServices: number;
  incomeCatering: number;
  donationsVoluntaryFunds: number;
  receiptsSupplyTeacherInsuranceClaims: number;
  investmentIncome: number;
  otherSelfGeneratedIncome: number;
  totalPupils: bigint;
  schoolName: string;
  laName: string;
};
