DROP VIEW IF EXISTS VW_FinancialDefaultNormalised
GO

CREATE VIEW VW_FinancialDefaultNormalised AS
SELECT RunId,
       URN,
       FinanceType,
       OverallPhase,
       IIF(TotalPupils IS NULL OR TotalPupils <= 0.0, NULL, TotalPupils) AS TotalPupils,
       IIF(TotalInternalFloorArea IS NULL OR TotalInternalFloorArea <= 0.0, NULL, TotalInternalFloorArea) AS TotalInternalFloorArea,
       IIF(TotalExpenditure IS NULL OR TotalExpenditure <= 0.0, NULL, TotalExpenditure) AS TotalExpenditure,
       IIF(TotalIncome IS NULL OR TotalIncome <= 0.0, NULL, TotalIncome) AS TotalIncome,
       IIF(TotalTeachingSupportStaffCosts IS NULL OR TotalTeachingSupportStaffCosts <= 0.0, NULL, TotalTeachingSupportStaffCosts) AS TotalTeachingSupportStaffCosts,
       IIF(TeachingStaffCosts IS NULL OR TeachingStaffCosts <= 0.0, NULL, TeachingStaffCosts) AS TeachingStaffCosts,
       IIF(SupplyTeachingStaffCosts IS NULL OR SupplyTeachingStaffCosts <= 0.0, NULL, SupplyTeachingStaffCosts) AS SupplyTeachingStaffCosts,
       IIF(EducationalConsultancyCosts IS NULL OR EducationalConsultancyCosts <= 0.0, NULL, EducationalConsultancyCosts) AS EducationalConsultancyCosts,
       IIF(EducationSupportStaffCosts IS NULL OR EducationSupportStaffCosts <= 0.0, NULL, EducationSupportStaffCosts) AS EducationSupportStaffCosts,
       IIF(AgencySupplyTeachingStaffCosts IS NULL OR AgencySupplyTeachingStaffCosts <= 0.0, NULL, AgencySupplyTeachingStaffCosts) AS AgencySupplyTeachingStaffCosts,
       IIF(TotalNonEducationalSupportStaffCosts IS NULL OR TotalNonEducationalSupportStaffCosts <= 0.0, NULL, TotalNonEducationalSupportStaffCosts) AS TotalNonEducationalSupportStaffCosts,
       IIF(AdministrativeClericalStaffCosts IS NULL OR AdministrativeClericalStaffCosts <= 0.0, NULL, AdministrativeClericalStaffCosts) AS AdministrativeClericalStaffCosts,
       IIF(AuditorsCosts IS NULL OR AuditorsCosts <= 0.0, NULL, AuditorsCosts) AS AuditorsCosts,
       IIF(OtherStaffCosts IS NULL OR OtherStaffCosts <= 0.0, NULL, OtherStaffCosts) AS OtherStaffCosts,
       IIF(ProfessionalServicesNonCurriculumCosts IS NULL OR ProfessionalServicesNonCurriculumCosts <= 0.0, NULL, ProfessionalServicesNonCurriculumCosts) AS ProfessionalServicesNonCurriculumCosts,
       IIF(TotalEducationalSuppliesCosts IS NULL OR TotalEducationalSuppliesCosts <= 0.0, NULL, TotalEducationalSuppliesCosts) AS TotalEducationalSuppliesCosts,
       IIF(ExaminationFeesCosts IS NULL OR ExaminationFeesCosts <= 0.0, NULL, ExaminationFeesCosts) AS ExaminationFeesCosts,
       IIF(LearningResourcesNonIctCosts IS NULL OR LearningResourcesNonIctCosts <= 0.0, NULL, LearningResourcesNonIctCosts) AS LearningResourcesNonIctCosts,
       IIF(LearningResourcesIctCosts IS NULL OR LearningResourcesIctCosts <= 0.0, NULL, LearningResourcesIctCosts ) AS LearningResourcesIctCosts,
       IIF(TotalGrossCateringCosts IS NULL OR TotalGrossCateringCosts <= 0.0, NULL, TotalGrossCateringCosts) AS TotalGrossCateringCosts,
       IIF(TotalNetCateringCostsCosts IS NULL OR TotalNetCateringCostsCosts <= 0.0, NULL, TotalNetCateringCostsCosts) AS TotalNetCateringCosts,
       IIF(CateringStaffCosts IS NULL OR CateringStaffCosts <= 0.0, NULL, CateringStaffCosts) AS CateringStaffCosts,
       IIF(CateringSuppliesCosts IS NULL OR CateringSuppliesCosts <= 0.0, NULL, CateringSuppliesCosts) AS CateringSuppliesCosts,
       IIF(TotalOtherCosts IS NULL OR TotalOtherCosts <= 0.0, NULL, TotalOtherCosts) AS TotalOtherCosts,
       IIF(DirectRevenueFinancingCosts IS NULL OR DirectRevenueFinancingCosts <= 0.0, NULL, DirectRevenueFinancingCosts) AS DirectRevenueFinancingCosts,
       IIF(GroundsMaintenanceCosts IS NULL OR GroundsMaintenanceCosts <=0.0, NULL,GroundsMaintenanceCosts) AS GroundsMaintenanceCosts,
       IIF(IndirectEmployeeExpenses IS NULL OR IndirectEmployeeExpenses <=0.0, NULL,IndirectEmployeeExpenses) AS IndirectEmployeeExpenses,
       IIF(InterestChargesLoanBank IS NULL OR InterestChargesLoanBank <=0.0,NULL,InterestChargesLoanBank) AS InterestChargesLoanBank,
       IIF(OtherInsurancePremiumsCosts IS NULL OR OtherInsurancePremiumsCosts <=0.0,NULL,OtherInsurancePremiumsCosts) AS OtherInsurancePremiumsCosts,
       IIF(PrivateFinanceInitiativeCharges IS NULL OR PrivateFinanceInitiativeCharges <=0.0,NULL,PrivateFinanceInitiativeCharges) AS PrivateFinanceInitiativeCharges,
       IIF(RentRatesCosts IS NULL OR RentRatesCosts <=0.0,NULL,RentRatesCosts) AS RentRatesCosts,
       IIF(SpecialFacilitiesCosts IS NULL OR SpecialFacilitiesCosts <=0.0,NULL,SpecialFacilitiesCosts) AS SpecialFacilitiesCosts,
       IIF(StaffDevelopmentTrainingCosts IS NULL OR StaffDevelopmentTrainingCosts <=0.0,NULL,StaffDevelopmentTrainingCosts) AS StaffDevelopmentTrainingCosts,
       IIF(StaffRelatedInsuranceCosts IS NULL OR StaffRelatedInsuranceCosts <=0.0,NULL,StaffRelatedInsuranceCosts) AS StaffRelatedInsuranceCosts,
       IIF(SupplyTeacherInsurableCosts IS NULL OR SupplyTeacherInsurableCosts <=0.0,NULL,SupplyTeacherInsurableCosts) AS SupplyTeacherInsurableCosts,
       IIF(CommunityFocusedSchoolStaff IS NULL OR CommunityFocusedSchoolStaff <=0.0,NULL,CommunityFocusedSchoolStaff) AS CommunityFocusedSchoolStaff,
       IIF(CommunityFocusedSchoolCosts IS NULL OR CommunityFocusedSchoolCosts <=0.0,NULL,CommunityFocusedSchoolCosts) AS CommunityFocusedSchoolCosts,
       IIF(AdministrativeSuppliesNonEducationalCosts IS NULL OR AdministrativeSuppliesNonEducationalCosts <=0.0,NULL,AdministrativeSuppliesNonEducationalCosts) AS AdministrativeSuppliesNonEducationalCosts,
       IIF(TotalPremisesStaffServiceCosts IS NULL OR TotalPremisesStaffServiceCosts <=0.0,NULL,TotalPremisesStaffServiceCosts) AS TotalPremisesStaffServiceCosts,
       IIF(CleaningCaretakingCosts IS NULL OR CleaningCaretakingCosts <=0.0,NULL,CleaningCaretakingCosts) AS CleaningCaretakingCosts,
       IIF(MaintenancePremisesCosts IS NULL OR MaintenancePremisesCosts <=0.0,NULL,MaintenancePremisesCosts) AS MaintenancePremisesCosts,
       IIF(OtherOccupationCosts IS NULL OR OtherOccupationCosts <=0.0,NULL,OtherOccupationCosts) AS OtherOccupationCosts,
       IIF(PremisesStaffCosts IS NULL OR PremisesStaffCosts <=0.0,NULL,PremisesStaffCosts) AS PremisesStaffCosts,
       IIF(TotalUtilitiesCosts IS NULL OR TotalUtilitiesCosts <=0.0,NULL,TotalUtilitiesCosts) AS TotalUtilitiesCosts,
       IIF(EnergyCosts IS NULL OR EnergyCosts <=0.0,NULL,EnergyCosts) AS EnergyCosts,
       IIF(WaterSewerageCosts IS NULL OR WaterSewerageCosts <=0.0,NULL,WaterSewerageCosts) AS WaterSewerageCosts
FROM Financial f
WHERE RunType = 'default'
GO

DROP VIEW IF EXISTS VW_FinancialDefaultNormalisedActual
GO

CREATE VIEW VW_FinancialDefaultNormalisedActual AS
SELECT RunId,
       URN,
       FinanceType,
       OverallPhase,
       TotalExpenditure,
       TotalTeachingSupportStaffCosts,
       TeachingStaffCosts,
       SupplyTeachingStaffCosts,
       EducationalConsultancyCosts,
       EducationSupportStaffCosts,
       AgencySupplyTeachingStaffCosts,
       TotalNonEducationalSupportStaffCosts,
       AdministrativeClericalStaffCosts,
       AuditorsCosts,
       OtherStaffCosts,
       ProfessionalServicesNonCurriculumCosts,
       TotalEducationalSuppliesCosts,
       ExaminationFeesCosts,
       LearningResourcesNonIctCosts,
       LearningResourcesIctCosts,
       TotalGrossCateringCosts,
       TotalNetCateringCosts,
       CateringStaffCosts,
       CateringSuppliesCosts,
       TotalOtherCosts,
       DirectRevenueFinancingCosts,
       GroundsMaintenanceCosts,
       IndirectEmployeeExpenses,
       InterestChargesLoanBank,
       OtherInsurancePremiumsCosts,
       PrivateFinanceInitiativeCharges,
       RentRatesCosts,
       SpecialFacilitiesCosts,
       StaffDevelopmentTrainingCosts,
       StaffRelatedInsuranceCosts,
       SupplyTeacherInsurableCosts,
       CommunityFocusedSchoolStaff,
       CommunityFocusedSchoolCosts,
       AdministrativeSuppliesNonEducationalCosts,
       TotalPremisesStaffServiceCosts,
       CleaningCaretakingCosts,
       MaintenancePremisesCosts,
       OtherOccupationCosts,
       PremisesStaffCosts,
       TotalUtilitiesCosts,
       EnergyCosts,
       WaterSewerageCosts
FROM VW_FinancialDefaultNormalised
GO

DROP VIEW IF EXISTS VW_FinancialDefaultNormalisedPercentExpenditure
GO

CREATE VIEW VW_FinancialDefaultNormalisedPercentExpenditure AS
SELECT RunId,
       URN,
       FinanceType,
       OverallPhase,
       (TotalExpenditure / TotalExpenditure) * 100                          AS TotalExpenditure,
       (TotalTeachingSupportStaffCosts / TotalExpenditure) * 100            AS TotalTeachingSupportStaffCosts,
       (TeachingStaffCosts / TotalExpenditure) * 100                        AS TeachingStaffCosts,
       (SupplyTeachingStaffCosts / TotalExpenditure) * 100                  AS SupplyTeachingStaffCosts,
       (EducationalConsultancyCosts / TotalExpenditure) * 100               AS EducationalConsultancyCosts,
       (EducationSupportStaffCosts / TotalExpenditure) * 100                AS EducationSupportStaffCosts,
       (AgencySupplyTeachingStaffCosts / TotalExpenditure) * 100            AS AgencySupplyTeachingStaffCosts,
       (TotalNonEducationalSupportStaffCosts / TotalExpenditure) * 100      AS TotalNonEducationalSupportStaffCosts,
       (AdministrativeClericalStaffCosts / TotalExpenditure) * 100          AS AdministrativeClericalStaffCosts,
       (AuditorsCosts / TotalExpenditure) * 100                             AS AuditorsCosts,
       (OtherStaffCosts / TotalExpenditure) * 100                           AS OtherStaffCosts,
       (ProfessionalServicesNonCurriculumCosts / TotalExpenditure) * 100    AS ProfessionalServicesNonCurriculumCosts,
       (TotalEducationalSuppliesCosts / TotalExpenditure) * 100             AS TotalEducationalSuppliesCosts,
       (ExaminationFeesCosts / TotalExpenditure) * 100                      AS ExaminationFeesCosts,
       (LearningResourcesNonIctCosts / TotalExpenditure) * 100              AS LearningResourcesNonIctCosts,
       (LearningResourcesIctCosts / TotalExpenditure) * 100                 AS LearningResourcesIctCosts,
       (TotalGrossCateringCosts / TotalExpenditure) * 100                   AS TotalGrossCateringCosts,
       (TotalNetCateringCosts / TotalExpenditure) * 100                     AS TotalNetCateringCosts,
       (CateringStaffCosts / TotalExpenditure) * 100                        AS CateringStaffCosts,
       (CateringSuppliesCosts / TotalExpenditure) * 100                     AS CateringSuppliesCosts,
       (TotalOtherCosts / TotalExpenditure) * 100                           AS TotalOtherCosts,
       (DirectRevenueFinancingCosts / TotalExpenditure) * 100               AS DirectRevenueFinancingCosts,
       (GroundsMaintenanceCosts / TotalExpenditure) * 100                   AS GroundsMaintenanceCosts,
       (IndirectEmployeeExpenses / TotalExpenditure) * 100                  AS IndirectEmployeeExpenses,
       (InterestChargesLoanBank / TotalExpenditure) * 100                   AS InterestChargesLoanBank,
       (OtherInsurancePremiumsCosts / TotalExpenditure) * 100               AS OtherInsurancePremiumsCosts,
       (PrivateFinanceInitiativeCharges / TotalExpenditure) * 100           AS PrivateFinanceInitiativeCharges,
       (RentRatesCosts / TotalExpenditure) * 100                            AS RentRatesCosts,
       (SpecialFacilitiesCosts / TotalExpenditure) * 100                    AS SpecialFacilitiesCosts,
       (StaffDevelopmentTrainingCosts / TotalExpenditure) * 100             AS StaffDevelopmentTrainingCosts,
       (StaffRelatedInsuranceCosts / TotalExpenditure) * 100                AS StaffRelatedInsuranceCosts,
       (SupplyTeacherInsurableCosts / TotalExpenditure) * 100               AS SupplyTeacherInsurableCosts,
       (CommunityFocusedSchoolStaff / TotalExpenditure) * 100               AS CommunityFocusedSchoolStaff,
       (CommunityFocusedSchoolCosts / TotalExpenditure) * 100               AS CommunityFocusedSchoolCosts,
       (AdministrativeSuppliesNonEducationalCosts / TotalExpenditure) * 100 AS AdministrativeSuppliesNonEducationalCosts,
       (TotalPremisesStaffServiceCosts / TotalExpenditure) * 100            AS TotalPremisesStaffServiceCosts,
       (CleaningCaretakingCosts / TotalExpenditure) * 100                   AS CleaningCaretakingCosts,
       (MaintenancePremisesCosts / TotalExpenditure) * 100                  AS MaintenancePremisesCosts,
       (OtherOccupationCosts / TotalExpenditure) * 100                      AS OtherOccupationCosts,
       (PremisesStaffCosts / TotalExpenditure) * 100                        AS PremisesStaffCosts,
       (TotalUtilitiesCosts / TotalExpenditure) * 100                       AS TotalUtilitiesCosts,
       (EnergyCosts / TotalExpenditure) * 100                               AS EnergyCosts,
       (WaterSewerageCosts / TotalExpenditure) * 100                        AS WaterSewerageCosts
FROM VW_FinancialDefaultNormalised
GO

DROP VIEW IF EXISTS VW_FinancialDefaultNormalisedPercentIncome
GO

CREATE VIEW VW_FinancialDefaultNormalisedPercentIncome AS
SELECT RunId,
       URN,
       FinanceType,
       OverallPhase,
       (TotalExpenditure / TotalIncome) * 100                          AS TotalExpenditure,
       (TotalTeachingSupportStaffCosts / TotalIncome) * 100            AS TotalTeachingSupportStaffCosts,
       (TeachingStaffCosts / TotalIncome) * 100                        AS TeachingStaffCosts,
       (SupplyTeachingStaffCosts / TotalIncome) * 100                  AS SupplyTeachingStaffCosts,
       (EducationalConsultancyCosts / TotalIncome) * 100               AS EducationalConsultancyCosts,
       (EducationSupportStaffCosts / TotalIncome) * 100                AS EducationSupportStaffCosts,
       (AgencySupplyTeachingStaffCosts / TotalIncome) * 100            AS AgencySupplyTeachingStaffCosts,
       (TotalNonEducationalSupportStaffCosts / TotalIncome) * 100      AS TotalNonEducationalSupportStaffCosts,
       (AdministrativeClericalStaffCosts / TotalIncome) * 100          AS AdministrativeClericalStaffCosts,
       (AuditorsCosts / TotalIncome) * 100                             AS AuditorsCosts,
       (OtherStaffCosts / TotalIncome) * 100                           AS OtherStaffCosts,
       (ProfessionalServicesNonCurriculumCosts / TotalIncome) * 100    AS ProfessionalServicesNonCurriculumCosts,
       (TotalEducationalSuppliesCosts / TotalIncome) * 100             AS TotalEducationalSuppliesCosts,
       (ExaminationFeesCosts / TotalIncome) * 100                      AS ExaminationFeesCosts,
       (LearningResourcesNonIctCosts / TotalIncome) * 100              AS LearningResourcesNonIctCosts,
       (LearningResourcesIctCosts / TotalIncome) * 100                 AS LearningResourcesIctCosts,
       (TotalGrossCateringCosts / TotalIncome) * 100                   AS TotalGrossCateringCosts,
       (TotalNetCateringCosts / TotalIncome) * 100                     AS TotalNetCateringCosts,
       (CateringStaffCosts / TotalIncome) * 100                        AS CateringStaffCosts,
       (CateringSuppliesCosts / TotalIncome) * 100                     AS CateringSuppliesCosts,
       (TotalOtherCosts / TotalIncome) * 100                           AS TotalOtherCosts,
       (DirectRevenueFinancingCosts / TotalIncome) * 100               AS DirectRevenueFinancingCosts,
       (GroundsMaintenanceCosts / TotalIncome) * 100                   AS GroundsMaintenanceCosts,
       (IndirectEmployeeExpenses / TotalIncome) * 100                  AS IndirectEmployeeExpenses,
       (InterestChargesLoanBank / TotalIncome) * 100                   AS InterestChargesLoanBank,
       (OtherInsurancePremiumsCosts / TotalIncome) * 100               AS OtherInsurancePremiumsCosts,
       (PrivateFinanceInitiativeCharges / TotalIncome) * 100           AS PrivateFinanceInitiativeCharges,
       (RentRatesCosts / TotalIncome) * 100                            AS RentRatesCosts,
       (SpecialFacilitiesCosts / TotalIncome) * 100                    AS SpecialFacilitiesCosts,
       (StaffDevelopmentTrainingCosts / TotalIncome) * 100             AS StaffDevelopmentTrainingCosts,
       (StaffRelatedInsuranceCosts / TotalIncome) * 100                AS StaffRelatedInsuranceCosts,
       (SupplyTeacherInsurableCosts / TotalIncome) * 100               AS SupplyTeacherInsurableCosts,
       (CommunityFocusedSchoolStaff / TotalIncome) * 100               AS CommunityFocusedSchoolStaff,
       (CommunityFocusedSchoolCosts / TotalIncome) * 100               AS CommunityFocusedSchoolCosts,
       (AdministrativeSuppliesNonEducationalCosts / TotalIncome) * 100 AS AdministrativeSuppliesNonEducationalCosts,
       (TotalPremisesStaffServiceCosts / TotalIncome) * 100            AS TotalPremisesStaffServiceCosts,
       (CleaningCaretakingCosts / TotalIncome) * 100                   AS CleaningCaretakingCosts,
       (MaintenancePremisesCosts / TotalIncome) * 100                  AS MaintenancePremisesCosts,
       (OtherOccupationCosts / TotalIncome) * 100                      AS OtherOccupationCosts,
       (PremisesStaffCosts / TotalIncome) * 100                        AS PremisesStaffCosts,
       (TotalUtilitiesCosts / TotalIncome) * 100                       AS TotalUtilitiesCosts,
       (EnergyCosts / TotalIncome) * 100                               AS EnergyCosts,
       (WaterSewerageCosts / TotalIncome) * 100                        AS WaterSewerageCosts
FROM VW_FinancialDefaultNormalised
GO

DROP VIEW IF EXISTS VW_FinancialDefaultNormalisedPerUnit
GO

CREATE VIEW VW_FinancialDefaultNormalisedPerUnit AS
SELECT RunId,
       URN,
       FinanceType,
       OverallPhase,
       TotalExpenditure / TotalPupils                          AS TotalExpenditure,
       TotalTeachingSupportStaffCosts / TotalPupils            AS TotalTeachingSupportStaffCosts,
       TeachingStaffCosts / TotalPupils                        AS TeachingStaffCosts,
       SupplyTeachingStaffCosts / TotalPupils                  AS SupplyTeachingStaffCosts,
       EducationalConsultancyCosts / TotalPupils               AS EducationalConsultancyCosts,
       EducationSupportStaffCosts / TotalPupils                AS EducationSupportStaffCosts,
       AgencySupplyTeachingStaffCosts / TotalPupils            AS AgencySupplyTeachingStaffCosts,
       TotalNonEducationalSupportStaffCosts / TotalPupils      AS TotalNonEducationalSupportStaffCosts,
       AdministrativeClericalStaffCosts / TotalPupils          AS AdministrativeClericalStaffCosts,
       AuditorsCosts / TotalPupils                             AS AuditorsCosts,
       OtherStaffCosts / TotalPupils                           AS OtherStaffCosts,
       ProfessionalServicesNonCurriculumCosts / TotalPupils    AS ProfessionalServicesNonCurriculumCosts,
       TotalEducationalSuppliesCosts / TotalPupils             AS TotalEducationalSuppliesCosts,
       ExaminationFeesCosts / TotalPupils                      AS ExaminationFeesCosts,
       LearningResourcesNonIctCosts / TotalPupils              AS LearningResourcesNonIctCosts,
       LearningResourcesIctCosts / TotalPupils                 AS LearningResourcesIctCosts,
       TotalGrossCateringCosts / TotalPupils                   AS TotalGrossCateringCosts,
       TotalNetCateringCosts / TotalPupils                     AS TotalNetCateringCosts,
       CateringStaffCosts / TotalPupils                        AS CateringStaffCosts,
       CateringSuppliesCosts / TotalPupils                     AS CateringSuppliesCosts,
       TotalOtherCosts / TotalPupils                           AS TotalOtherCosts,
       DirectRevenueFinancingCosts / TotalPupils               AS DirectRevenueFinancingCosts,
       GroundsMaintenanceCosts / TotalPupils                   AS GroundsMaintenanceCosts,
       IndirectEmployeeExpenses / TotalPupils                  AS IndirectEmployeeExpenses,
       InterestChargesLoanBank / TotalPupils                   AS InterestChargesLoanBank,
       OtherInsurancePremiumsCosts / TotalPupils               AS OtherInsurancePremiumsCosts,
       PrivateFinanceInitiativeCharges / TotalPupils           AS PrivateFinanceInitiativeCharges,
       RentRatesCosts / TotalPupils                            AS RentRatesCosts,
       SpecialFacilitiesCosts / TotalPupils                    AS SpecialFacilitiesCosts,
       StaffDevelopmentTrainingCosts / TotalPupils             AS StaffDevelopmentTrainingCosts,
       StaffRelatedInsuranceCosts / TotalPupils                AS StaffRelatedInsuranceCosts,
       SupplyTeacherInsurableCosts / TotalPupils               AS SupplyTeacherInsurableCosts,
       CommunityFocusedSchoolStaff / TotalPupils               AS CommunityFocusedSchoolStaff,
       CommunityFocusedSchoolCosts / TotalPupils               AS CommunityFocusedSchoolCosts,
       AdministrativeSuppliesNonEducationalCosts / TotalPupils AS AdministrativeSuppliesNonEducationalCosts,
       TotalPremisesStaffServiceCosts / TotalInternalFloorArea AS TotalPremisesStaffServiceCosts,
       CleaningCaretakingCosts / TotalInternalFloorArea        AS CleaningCaretakingCosts,
       MaintenancePremisesCosts / TotalInternalFloorArea       AS MaintenancePremisesCosts,
       OtherOccupationCosts / TotalInternalFloorArea           AS OtherOccupationCosts,
       PremisesStaffCosts / TotalInternalFloorArea             AS PremisesStaffCosts,
       TotalUtilitiesCosts / TotalInternalFloorArea            AS TotalUtilitiesCosts,
       EnergyCosts / TotalInternalFloorArea                    AS EnergyCosts,
       WaterSewerageCosts / TotalInternalFloorArea             AS WaterSewerageCosts
FROM VW_FinancialDefaultNormalised
GO