DROP VIEW IF EXISTS VW_TrustFinancialDefault
GO

CREATE VIEW VW_TrustFinancialDefault AS
SELECT RunId,
       CompanyNumber,
       TotalPupils,
       TotalInternalFloorArea,
       TotalExpenditure,
       TotalExpenditureCS,
       TotalExpenditure - TotalExpenditureCS AS 'TotalExpenditureSchool',
       TotalIncome,
       TotalIncomeCS,
       TotalIncome - TotalExpenditureCS      AS 'TotalIncomeSchool',
       InYearBalance,
       InYearBalanceCS,
       InYearBalance - InYearBalanceCS       AS 'InYearBalanceSchool',
       RevenueReserve,
       TotalGrantFunding,
       TotalSelfGeneratedFunding,
       DirectGrants,
       PrePost16Funding,
       OtherDfeGrants,
       OtherIncomeGrants,
       GovernmentSource,
       CommunityGrants,
       Academies,
       IncomeFacilitiesServices,
       IncomeCateringServices,
       DonationsVoluntaryFunds,
       ReceiptsSupplyTeacherInsuranceClaims,
       InvestmentIncome,
       OtherSelfGeneratedIncome,
       TotalTeachingSupportStaffCosts,
       TeachingStaffCosts,
       SupplyTeachingStaffCosts,
       EducationalConsultancyCosts,
       EducationSupportStaffCosts,
       AgencySupplyTeachingStaffCosts,
       TotalNonEducationalSupportStaffCosts,
       AdministrativeClericalStaffCosts,
       AuditorsCosts,
       OtherStaffCosts,
       ProfessionalServicesNonCurriculumCosts,
       TotalEducationalSuppliesCosts,
       ExaminationFeesCosts,
       LearningResourcesNonIctCosts,
       LearningResourcesIctCosts,
       TotalGrossCateringCosts,
       TotalNetCateringCostsCosts AS 'TotalNetCateringCosts',
       CateringStaffCosts,
       CateringSuppliesCosts,
       TotalOtherCosts,
       DirectRevenueFinancingCosts,
       GroundsMaintenanceCosts,
       IndirectEmployeeExpenses,
       InterestChargesLoanBank,
       OtherInsurancePremiumsCosts,
       PrivateFinanceInitiativeCharges,
       RentRatesCosts,
       SpecialFacilitiesCosts,
       StaffDevelopmentTrainingCosts,
       StaffRelatedInsuranceCosts,
       SupplyTeacherInsurableCosts,
       AdministrativeSuppliesNonEducationalCosts,
       TotalPremisesStaffServiceCosts,
       CleaningCaretakingCosts,
       MaintenancePremisesCosts,
       OtherOccupationCosts,
       PremisesStaffCosts,
       TotalUtilitiesCosts,
       EnergyCosts,
       WaterSewerageCosts,
       TotalTeachingSupportStaffCostsCS,
       TeachingStaffCostsCS,
       SupplyTeachingStaffCostsCS,
       EducationalConsultancyCostsCS,
       EducationSupportStaffCostsCS,
       AgencySupplyTeachingStaffCostsCS,
       TotalNonEducationalSupportStaffCostsCS,
       AdministrativeClericalStaffCostsCS,
       AuditorsCostsCS,
       OtherStaffCostsCS,
       ProfessionalServicesNonCurriculumCostsCS,
       TotalEducationalSuppliesCostsCS,
       ExaminationFeesCostsCS,
       LearningResourcesNonIctCostsCS,
       LearningResourcesIctCostsCS,
       TotalGrossCateringCostsCS,
       TotalNetCateringCostsCostsCS AS 'TotalNetCateringCostsCS',
       CateringStaffCostsCS,
       CateringSuppliesCostsCS,
       TotalOtherCostsCS,
       DirectRevenueFinancingCostsCS,
       GroundsMaintenanceCostsCS,
       IndirectEmployeeExpensesCS,
       InterestChargesLoanBankCS,
       OtherInsurancePremiumsCostsCS,
       PrivateFinanceInitiativeChargesCS,
       RentRatesCostsCS,
       SpecialFacilitiesCostsCS,
       StaffDevelopmentTrainingCostsCS,
       StaffRelatedInsuranceCostsCS,
       SupplyTeacherInsurableCostsCS,
       AdministrativeSuppliesNonEducationalCostsCS,
       TotalPremisesStaffServiceCostsCS,
       CleaningCaretakingCostsCS,
       MaintenancePremisesCostsCS,
       OtherOccupationCostsCS,
       PremisesStaffCostsCS,
       TotalUtilitiesCostsCS,
       EnergyCostsCS,
       WaterSewerageCostsCS,
       TotalTeachingSupportStaffCosts - TotalTeachingSupportStaffCostsCS AS 'TotalTeachingSupportStaffCostsSchool',
       TeachingStaffCosts - TeachingStaffCostsCS AS 'TeachingStaffCostsSchool',
       SupplyTeachingStaffCosts - SupplyTeachingStaffCostsCS AS 'SupplyTeachingStaffCostsSchool',
       EducationalConsultancyCosts - EducationalConsultancyCostsCS AS 'EducationalConsultancyCostsSchool',
       EducationSupportStaffCosts - EducationSupportStaffCostsCS AS 'EducationSupportStaffCostsSchool',
       AgencySupplyTeachingStaffCosts - AgencySupplyTeachingStaffCostsCS AS 'AgencySupplyTeachingStaffCostsSchool',
       TotalNonEducationalSupportStaffCosts - TotalNonEducationalSupportStaffCostsCS AS 'TotalNonEducationalSupportStaffCostsSchool',
       AdministrativeClericalStaffCosts - AdministrativeClericalStaffCostsCS AS 'AdministrativeClericalStaffCostsSchool',
       AuditorsCosts - AuditorsCostsCS AS 'AuditorsCostsSchool',
       OtherStaffCosts - OtherStaffCostsCS AS 'OtherStaffCostsSchool',
       ProfessionalServicesNonCurriculumCosts - ProfessionalServicesNonCurriculumCostsCS AS 'ProfessionalServicesNonCurriculumCostsSchool',
       TotalEducationalSuppliesCosts - TotalEducationalSuppliesCostsCS AS 'TotalEducationalSuppliesCostsSchool',
       ExaminationFeesCosts - ExaminationFeesCostsCS AS 'ExaminationFeesCostsSchool',
       LearningResourcesNonIctCosts - LearningResourcesNonIctCostsCS AS 'LearningResourcesNonIctCostsSchool',
       LearningResourcesIctCosts - LearningResourcesIctCosts AS 'LearningResourcesIctCostsSchool',
       TotalGrossCateringCosts - TotalGrossCateringCostsCS AS 'TotalGrossCateringCostsSchool',
       TotalNetCateringCostsCosts - TotalNetCateringCostsCostsCS AS 'TotalNetCateringCostsSchool',
       CateringStaffCosts - CateringStaffCostsCS AS 'CateringStaffCostsSchool',
       CateringSuppliesCosts - CateringSuppliesCostsCS AS 'CateringSuppliesCostsSchool',
       TotalOtherCosts - TotalOtherCostsCS AS 'TotalOtherCostsSchool',
       DirectRevenueFinancingCosts - DirectRevenueFinancingCostsCS AS 'DirectRevenueFinancingCostsSchool',
       GroundsMaintenanceCosts - GroundsMaintenanceCostsCS AS 'GroundsMaintenanceCostsSchool',
       IndirectEmployeeExpenses - IndirectEmployeeExpensesCS AS 'IndirectEmployeeExpensesSchool',
       InterestChargesLoanBank - InterestChargesLoanBankCS AS 'InterestChargesLoanBankSchool',
       OtherInsurancePremiumsCosts - OtherInsurancePremiumsCostsCS AS 'OtherInsurancePremiumsCostsSchool',
       PrivateFinanceInitiativeCharges - PrivateFinanceInitiativeChargesCS AS 'PrivateFinanceInitiativeChargesSchool',
       RentRatesCosts - RentRatesCostsCS AS 'RentRatesCostsSchool',
       SpecialFacilitiesCosts - SpecialFacilitiesCostsCS AS 'SpecialFacilitiesCostsSchool',
       StaffDevelopmentTrainingCosts - StaffDevelopmentTrainingCostsCS AS 'StaffDevelopmentTrainingCostsSchool',
       StaffRelatedInsuranceCosts - StaffRelatedInsuranceCostsCS AS 'StaffRelatedInsuranceCostsSchool',
       SupplyTeacherInsurableCosts - SupplyTeacherInsurableCostsCS AS 'SupplyTeacherInsurableCostsSchool',
       AdministrativeSuppliesNonEducationalCosts - AdministrativeSuppliesNonEducationalCostsCS AS 'AdministrativeSuppliesNonEducationalCostsSchool',
       TotalPremisesStaffServiceCosts - TotalPremisesStaffServiceCostsCS AS 'TotalPremisesStaffServiceCostsSchool',
       CleaningCaretakingCosts - CleaningCaretakingCostsCS AS 'CleaningCaretakingCostsSchool',
       MaintenancePremisesCosts - MaintenancePremisesCostsCS AS 'MaintenancePremisesCostsSchool',
       OtherOccupationCosts - OtherOccupationCostsCS AS 'OtherOccupationCostsSchool',
       PremisesStaffCosts - PremisesStaffCostsCS AS 'PremisesStaffCostsSchool',
       TotalUtilitiesCosts - TotalUtilitiesCostsCS AS 'TotalUtilitiesCostsSchool',
       EnergyCosts - EnergyCostsCS AS 'EnergyCostsSchool',
       WaterSewerageCosts - WaterSewerageCostsCS AS 'WaterSewerageCostsSchool'
FROM TrustFinancial
WHERE RunType = 'default'
GO


DROP VIEW IF EXISTS VW_TrustFinancialDefaultCurrent
GO

CREATE VIEW VW_TrustFinancialDefaultCurrent AS
SELECT *
FROM VW_TrustFinancialDefault
WHERE RunId = (SELECT Value FROM Parameters WHERE Name = 'CurrentYear')
GO