DROP VIEW IF EXISTS VW_TrustFinancialDefault
GO

CREATE VIEW VW_TrustFinancialDefault AS
SELECT RunId,
       CompanyNumber,
       TotalPupils,
       TotalInternalFloorArea,
       TotalExpenditure,
       ISNULL(TotalExpenditureCS,0) AS 'TotalExpenditureCS',
       TotalExpenditure - ISNULL(TotalExpenditureCS, 0) AS 'TotalExpenditureSchool',
       TotalIncome,
       ISNULL(TotalIncomeCS,0) AS 'TotalIncomeCS',
       TotalIncome - ISNULL(TotalIncomeCS, 0)      AS 'TotalIncomeSchool',
       InYearBalance,
       ISNULL(InYearBalanceCS, 0) AS 'InYearBalanceCS',
       InYearBalance - ISNULL(InYearBalanceCS, 0)       AS 'InYearBalanceSchool',
       RevenueReserve,
       TotalGrantFunding,
       TotalSelfGeneratedFunding,
       DirectGrants,
       PrePost16Funding,
       OtherDfeGrants,
       OtherIncomeGrants,
       GovernmentSource,
       CommunityGrants,
       Academies,
       IncomeFacilitiesServices,
       IncomeCateringServices,
       DonationsVoluntaryFunds,
       ReceiptsSupplyTeacherInsuranceClaims,
       InvestmentIncome,
       OtherSelfGeneratedIncome,
       TotalTeachingSupportStaffCosts,
       TeachingStaffCosts,
       SupplyTeachingStaffCosts,
       EducationalConsultancyCosts,
       EducationSupportStaffCosts,
       AgencySupplyTeachingStaffCosts,
       TotalNonEducationalSupportStaffCosts,
       AdministrativeClericalStaffCosts,
       AuditorsCosts,
       OtherStaffCosts,
       ProfessionalServicesNonCurriculumCosts,
       TotalEducationalSuppliesCosts,
       ExaminationFeesCosts,
       LearningResourcesNonIctCosts,
       LearningResourcesIctCosts,
       TotalGrossCateringCosts,
       TotalNetCateringCostsCosts AS 'TotalNetCateringCosts',
       CateringStaffCosts,
       CateringSuppliesCosts,
       TotalOtherCosts,
       GroundsMaintenanceCosts,
       IndirectEmployeeExpenses,
       InterestChargesLoanBank,
       OtherInsurancePremiumsCosts,
       PrivateFinanceInitiativeCharges,
       RentRatesCosts,
       SpecialFacilitiesCosts,
       StaffDevelopmentTrainingCosts,
       StaffRelatedInsuranceCosts,
       SupplyTeacherInsurableCosts,
       AdministrativeSuppliesNonEducationalCosts,
       TotalPremisesStaffServiceCosts,
       CleaningCaretakingCosts,
       MaintenancePremisesCosts,
       OtherOccupationCosts,
       PremisesStaffCosts,
       TotalUtilitiesCosts,
       EnergyCosts,
       WaterSewerageCosts,
       ISNULL(TotalTeachingSupportStaffCostsCS, 0) AS 'TotalTeachingSupportStaffCostsCS',
       ISNULL(TeachingStaffCostsCS, 0) AS 'TeachingStaffCostsCS',
       ISNULL(SupplyTeachingStaffCostsCS, 0) AS 'SupplyTeachingStaffCostsCS',
       ISNULL(EducationalConsultancyCostsCS, 0) AS 'EducationalConsultancyCostsCS',
       ISNULL(EducationSupportStaffCostsCS, 0) AS 'EducationSupportStaffCostsCS',
       ISNULL(AgencySupplyTeachingStaffCostsCS, 0) AS 'AgencySupplyTeachingStaffCostsCS',
       ISNULL(TotalNonEducationalSupportStaffCostsCS, 0) AS 'TotalNonEducationalSupportStaffCostsCS',
       ISNULL(AdministrativeClericalStaffCostsCS, 0) AS 'AdministrativeClericalStaffCostsCS',
       ISNULL(AuditorsCostsCS, 0) AS 'AuditorsCostsCS',
       ISNULL(OtherStaffCostsCS, 0) AS 'OtherStaffCostsCS',
       ISNULL(ProfessionalServicesNonCurriculumCostsCS, 0) AS 'ProfessionalServicesNonCurriculumCostsCS',
       ISNULL(TotalEducationalSuppliesCostsCS, 0) AS 'TotalEducationalSuppliesCostsCS',
       ISNULL(ExaminationFeesCostsCS, 0) AS 'ExaminationFeesCostsCS',
       ISNULL(LearningResourcesNonIctCostsCS, 0) AS 'LearningResourcesNonIctCostsCS',
       ISNULL(LearningResourcesIctCostsCS, 0) AS 'LearningResourcesIctCostsCS',
       ISNULL(TotalGrossCateringCostsCS, 0) AS 'TotalGrossCateringCostsCS',
       ISNULL(TotalNetCateringCostsCostsCS, 0) AS 'TotalNetCateringCostsCS',
       ISNULL(CateringStaffCostsCS, 0) AS 'CateringStaffCostsCS',
       ISNULL(CateringSuppliesCostsCS, 0) AS 'CateringSuppliesCostsCS',
       ISNULL(TotalOtherCostsCS, 0) AS 'TotalOtherCostsCS',
       ISNULL(GroundsMaintenanceCostsCS, 0) AS 'GroundsMaintenanceCostsCS',
       ISNULL(IndirectEmployeeExpensesCS, 0) AS 'IndirectEmployeeExpensesCS',
       ISNULL(InterestChargesLoanBankCS, 0) AS 'InterestChargesLoanBankCS',
       ISNULL(OtherInsurancePremiumsCostsCS, 0) AS 'OtherInsurancePremiumsCostsCS',
       ISNULL(PrivateFinanceInitiativeChargesCS, 0) AS 'PrivateFinanceInitiativeChargesCS',
       ISNULL(RentRatesCostsCS, 0) AS 'RentRatesCostsCS',
       ISNULL(SpecialFacilitiesCostsCS, 0) AS 'SpecialFacilitiesCostsCS',
       ISNULL(StaffDevelopmentTrainingCostsCS, 0) AS 'StaffDevelopmentTrainingCostsCS',
       ISNULL(StaffRelatedInsuranceCostsCS, 0) AS 'StaffRelatedInsuranceCostsCS',
       ISNULL(SupplyTeacherInsurableCostsCS, 0) AS 'SupplyTeacherInsurableCostsCS',
       ISNULL(AdministrativeSuppliesNonEducationalCostsCS, 0) AS 'AdministrativeSuppliesNonEducationalCostsCS',
       ISNULL(TotalPremisesStaffServiceCostsCS, 0) AS 'TotalPremisesStaffServiceCostsCS',
       ISNULL(CleaningCaretakingCostsCS, 0) AS 'CleaningCaretakingCostsCS',
       ISNULL(MaintenancePremisesCostsCS, 0) AS 'MaintenancePremisesCostsCS',
       ISNULL(OtherOccupationCostsCS, 0) AS 'OtherOccupationCostsCS',
       ISNULL(PremisesStaffCostsCS, 0) AS 'PremisesStaffCostsCS',
       ISNULL(TotalUtilitiesCostsCS, 0) AS 'TotalUtilitiesCostsCS',
       ISNULL(EnergyCostsCS, 0) AS 'EnergyCostsCS',
       ISNULL(WaterSewerageCostsCS, 0) AS 'WaterSewerageCostsCS',
       TotalTeachingSupportStaffCosts - ISNULL(TotalTeachingSupportStaffCostsCS, 0) AS 'TotalTeachingSupportStaffCostsSchool',
       TeachingStaffCosts - ISNULL(TeachingStaffCostsCS, 0) AS 'TeachingStaffCostsSchool',
       SupplyTeachingStaffCosts - ISNULL(SupplyTeachingStaffCostsCS, 0) AS 'SupplyTeachingStaffCostsSchool',
       EducationalConsultancyCosts - ISNULL(EducationalConsultancyCostsCS, 0) AS 'EducationalConsultancyCostsSchool',
       EducationSupportStaffCosts - ISNULL(EducationSupportStaffCostsCS, 0) AS 'EducationSupportStaffCostsSchool',
       AgencySupplyTeachingStaffCosts - ISNULL(AgencySupplyTeachingStaffCostsCS, 0) AS 'AgencySupplyTeachingStaffCostsSchool',
       TotalNonEducationalSupportStaffCosts - ISNULL(TotalNonEducationalSupportStaffCostsCS, 0) AS 'TotalNonEducationalSupportStaffCostsSchool',
       AdministrativeClericalStaffCosts - ISNULL(AdministrativeClericalStaffCostsCS, 0) AS 'AdministrativeClericalStaffCostsSchool',
       AuditorsCosts - ISNULL(AuditorsCostsCS, 0) AS 'AuditorsCostsSchool',
       OtherStaffCosts - ISNULL(OtherStaffCostsCS, 0) AS 'OtherStaffCostsSchool',
       ProfessionalServicesNonCurriculumCosts - ISNULL(ProfessionalServicesNonCurriculumCostsCS, 0) AS 'ProfessionalServicesNonCurriculumCostsSchool',
       TotalEducationalSuppliesCosts - ISNULL(TotalEducationalSuppliesCostsCS, 0) AS 'TotalEducationalSuppliesCostsSchool',
       ExaminationFeesCosts - ISNULL(ExaminationFeesCostsCS, 0) AS 'ExaminationFeesCostsSchool',
       LearningResourcesNonIctCosts - ISNULL(LearningResourcesNonIctCostsCS, 0) AS 'LearningResourcesNonIctCostsSchool',
       LearningResourcesIctCosts - ISNULL(LearningResourcesIctCostsCS, 0) AS 'LearningResourcesIctCostsSchool',
       TotalGrossCateringCosts - ISNULL(TotalGrossCateringCostsCS, 0) AS 'TotalGrossCateringCostsSchool',
       TotalNetCateringCostsCosts - ISNULL(TotalNetCateringCostsCostsCS, 0) AS 'TotalNetCateringCostsSchool',
       CateringStaffCosts - ISNULL(CateringStaffCostsCS, 0) AS 'CateringStaffCostsSchool',
       CateringSuppliesCosts - ISNULL(CateringSuppliesCostsCS, 0) AS 'CateringSuppliesCostsSchool',
       TotalOtherCosts - ISNULL(TotalOtherCostsCS, 0) AS 'TotalOtherCostsSchool',
       GroundsMaintenanceCosts - ISNULL(GroundsMaintenanceCostsCS, 0) AS 'GroundsMaintenanceCostsSchool',
       IndirectEmployeeExpenses - ISNULL(IndirectEmployeeExpensesCS, 0) AS 'IndirectEmployeeExpensesSchool',
       InterestChargesLoanBank - ISNULL(InterestChargesLoanBankCS, 0) AS 'InterestChargesLoanBankSchool',
       OtherInsurancePremiumsCosts - ISNULL(OtherInsurancePremiumsCostsCS, 0) AS 'OtherInsurancePremiumsCostsSchool',
       PrivateFinanceInitiativeCharges - ISNULL(PrivateFinanceInitiativeChargesCS, 0) AS 'PrivateFinanceInitiativeChargesSchool',
       RentRatesCosts - ISNULL(RentRatesCostsCS, 0) AS 'RentRatesCostsSchool',
       SpecialFacilitiesCosts - ISNULL(SpecialFacilitiesCostsCS, 0) AS 'SpecialFacilitiesCostsSchool',
       StaffDevelopmentTrainingCosts - ISNULL(StaffDevelopmentTrainingCostsCS, 0) AS 'StaffDevelopmentTrainingCostsSchool',
       StaffRelatedInsuranceCosts - ISNULL(StaffRelatedInsuranceCostsCS, 0) AS 'StaffRelatedInsuranceCostsSchool',
       SupplyTeacherInsurableCosts - ISNULL(SupplyTeacherInsurableCostsCS, 0) AS 'SupplyTeacherInsurableCostsSchool',
       AdministrativeSuppliesNonEducationalCosts - ISNULL(AdministrativeSuppliesNonEducationalCostsCS, 0) AS 'AdministrativeSuppliesNonEducationalCostsSchool',
       TotalPremisesStaffServiceCosts - ISNULL(TotalPremisesStaffServiceCostsCS, 0) AS 'TotalPremisesStaffServiceCostsSchool',
       CleaningCaretakingCosts - ISNULL(CleaningCaretakingCostsCS, 0) AS 'CleaningCaretakingCostsSchool',
       MaintenancePremisesCosts - ISNULL(MaintenancePremisesCostsCS, 0) AS 'MaintenancePremisesCostsSchool',
       OtherOccupationCosts - ISNULL(OtherOccupationCostsCS, 0) AS 'OtherOccupationCostsSchool',
       PremisesStaffCosts - ISNULL(PremisesStaffCostsCS, 0) AS 'PremisesStaffCostsSchool',
       TotalUtilitiesCosts - ISNULL(TotalUtilitiesCostsCS, 0) AS 'TotalUtilitiesCostsSchool',
       EnergyCosts - ISNULL(EnergyCostsCS, 0) AS 'EnergyCostsSchool',
       WaterSewerageCosts - ISNULL(WaterSewerageCostsCS, 0) AS 'WaterSewerageCostsSchool',
       EMLBand
FROM TrustFinancial
WHERE RunType = 'default'
GO


DROP VIEW IF EXISTS VW_TrustFinancialDefaultCurrent
GO

CREATE VIEW VW_TrustFinancialDefaultCurrent AS
SELECT *
FROM VW_TrustFinancialDefault
WHERE RunId = (SELECT Value FROM Parameters WHERE Name = 'CurrentYear')
GO