DROP VIEW IF EXISTS VW_ExpenditureTrustDefaultActual
GO

CREATE VIEW VW_ExpenditureTrustDefaultActual AS
SELECT CompanyNumber,
       RunId,
       TotalExpenditure,
       TotalTeachingSupportStaffCosts,
       TeachingStaffCosts,
       SupplyTeachingStaffCosts,
       EducationalConsultancyCosts,
       EducationSupportStaffCosts,
       AgencySupplyTeachingStaffCosts,
       TotalNonEducationalSupportStaffCosts,
       AdministrativeClericalStaffCosts,
       AuditorsCosts,
       OtherStaffCosts,
       ProfessionalServicesNonCurriculumCosts,
       TotalEducationalSuppliesCosts,
       ExaminationFeesCosts,
       LearningResourcesNonIctCosts,
       LearningResourcesIctCosts,
       TotalGrossCateringCosts,
       TotalNetCateringCosts,
       CateringStaffCosts,
       CateringSuppliesCosts,
       TotalOtherCosts,
       GroundsMaintenanceCosts,
       IndirectEmployeeExpenses,
       InterestChargesLoanBank,
       OtherInsurancePremiumsCosts,
       PrivateFinanceInitiativeCharges,
       RentRatesCosts,
       SpecialFacilitiesCosts,
       StaffDevelopmentTrainingCosts,
       StaffRelatedInsuranceCosts,
       SupplyTeacherInsurableCosts,
       AdministrativeSuppliesNonEducationalCosts,
       TotalPremisesStaffServiceCosts,
       CleaningCaretakingCosts,
       MaintenancePremisesCosts,
       OtherOccupationCosts,
       PremisesStaffCosts,
       TotalUtilitiesCosts,
       EnergyCosts,
       WaterSewerageCosts,
       TotalExpenditureCS,
       TotalTeachingSupportStaffCostsCS,
       TeachingStaffCostsCS,
       SupplyTeachingStaffCostsCS,
       EducationalConsultancyCostsCS,
       EducationSupportStaffCostsCS,
       AgencySupplyTeachingStaffCostsCS,
       TotalNonEducationalSupportStaffCostsCS,
       AdministrativeClericalStaffCostsCS,
       AuditorsCostsCS,
       OtherStaffCostsCS,
       ProfessionalServicesNonCurriculumCostsCS,
       TotalEducationalSuppliesCostsCS,
       ExaminationFeesCostsCS,
       LearningResourcesNonIctCostsCS,
       LearningResourcesIctCostsCS,
       TotalGrossCateringCostsCS,
       TotalNetCateringCostsCS,
       CateringStaffCostsCS,
       CateringSuppliesCostsCS,
       TotalOtherCostsCS,
       GroundsMaintenanceCostsCS,
       IndirectEmployeeExpensesCS,
       InterestChargesLoanBankCS,
       OtherInsurancePremiumsCostsCS,
       PrivateFinanceInitiativeChargesCS,
       RentRatesCostsCS,
       SpecialFacilitiesCostsCS,
       StaffDevelopmentTrainingCostsCS,
       StaffRelatedInsuranceCostsCS,
       SupplyTeacherInsurableCostsCS,
       AdministrativeSuppliesNonEducationalCostsCS,
       TotalPremisesStaffServiceCostsCS,
       CleaningCaretakingCostsCS,
       MaintenancePremisesCostsCS,
       OtherOccupationCostsCS,
       PremisesStaffCostsCS,
       TotalUtilitiesCostsCS,
       EnergyCostsCS,
       WaterSewerageCostsCS,
       TotalExpenditureSchool,
       TotalTeachingSupportStaffCostsSchool,
       TeachingStaffCostsSchool,
       SupplyTeachingStaffCostsSchool,
       EducationalConsultancyCostsSchool,
       EducationSupportStaffCostsSchool,
       AgencySupplyTeachingStaffCostsSchool,
       TotalNonEducationalSupportStaffCostsSchool,
       AdministrativeClericalStaffCostsSchool,
       AuditorsCostsSchool,
       OtherStaffCostsSchool,
       ProfessionalServicesNonCurriculumCostsSchool,
       TotalEducationalSuppliesCostsSchool,
       ExaminationFeesCostsSchool,
       LearningResourcesNonIctCostsSchool,
       LearningResourcesIctCostsSchool,
       TotalGrossCateringCostsSchool,
       TotalNetCateringCostsSchool,
       CateringStaffCostsSchool,
       CateringSuppliesCostsSchool,
       TotalOtherCostsSchool,
       GroundsMaintenanceCostsSchool,
       IndirectEmployeeExpensesSchool,
       InterestChargesLoanBankSchool,
       OtherInsurancePremiumsCostsSchool,
       PrivateFinanceInitiativeChargesSchool,
       RentRatesCostsSchool,
       SpecialFacilitiesCostsSchool,
       StaffDevelopmentTrainingCostsSchool,
       StaffRelatedInsuranceCostsSchool,
       SupplyTeacherInsurableCostsSchool,
       AdministrativeSuppliesNonEducationalCostsSchool,
       TotalPremisesStaffServiceCostsSchool,
       CleaningCaretakingCostsSchool,
       MaintenancePremisesCostsSchool,
       OtherOccupationCostsSchool,
       PremisesStaffCostsSchool,
       TotalUtilitiesCostsSchool,
       EnergyCostsSchool,
       WaterSewerageCostsSchool,
       EMLBand,
       TotalPupils
FROM VW_TrustFinancialDefault
GO

DROP VIEW IF EXISTS VW_ExpenditureTrustDefaultPercentExpenditure
GO

CREATE VIEW VW_ExpenditureTrustDefaultPercentExpenditure AS
SELECT CompanyNumber,
       RunId,
       IIF(TotalExpenditure != 0, (TotalExpenditure / TotalExpenditure) * 100, NULL) AS 'TotalExpenditure',
       IIF(TotalExpenditure != 0, (TotalTeachingSupportStaffCosts / TotalExpenditure) * 100, NULL) AS 'TotalTeachingSupportStaffCosts',
       IIF(TotalExpenditure != 0, (TeachingStaffCosts / TotalExpenditure) * 100, NULL) AS 'TeachingStaffCosts',
       IIF(TotalExpenditure != 0, (SupplyTeachingStaffCosts / TotalExpenditure) * 100, NULL) AS 'SupplyTeachingStaffCosts',
       IIF(TotalExpenditure != 0, (EducationalConsultancyCosts / TotalExpenditure) * 100, NULL) AS 'EducationalConsultancyCosts',
       IIF(TotalExpenditure != 0, (EducationSupportStaffCosts / TotalExpenditure) * 100, NULL) AS 'EducationSupportStaffCosts',
       IIF(TotalExpenditure != 0, (AgencySupplyTeachingStaffCosts / TotalExpenditure) * 100, NULL) AS 'AgencySupplyTeachingStaffCosts',
       IIF(TotalExpenditure != 0, (TotalNonEducationalSupportStaffCosts / TotalExpenditure) * 100, NULL) AS 'TotalNonEducationalSupportStaffCosts',
       IIF(TotalExpenditure != 0, (AdministrativeClericalStaffCosts / TotalExpenditure) * 100, NULL) AS 'AdministrativeClericalStaffCosts',
       IIF(TotalExpenditure != 0, (AuditorsCosts / TotalExpenditure) * 100, NULL) AS 'AuditorsCosts',
       IIF(TotalExpenditure != 0, (OtherStaffCosts / TotalExpenditure) * 100, NULL) AS 'OtherStaffCosts',
       IIF(TotalExpenditure != 0, (ProfessionalServicesNonCurriculumCosts / TotalExpenditure) * 100, NULL) AS 'ProfessionalServicesNonCurriculumCosts',
       IIF(TotalExpenditure != 0, (TotalEducationalSuppliesCosts / TotalExpenditure) * 100, NULL) AS 'TotalEducationalSuppliesCosts',
       IIF(TotalExpenditure != 0, (ExaminationFeesCosts / TotalExpenditure) * 100, NULL) AS 'ExaminationFeesCosts',
       IIF(TotalExpenditure != 0, (LearningResourcesNonIctCosts / TotalExpenditure) * 100, NULL) AS 'LearningResourcesNonIctCosts',
       IIF(TotalExpenditure != 0, (LearningResourcesIctCosts / TotalExpenditure) * 100, NULL) AS 'LearningResourcesIctCosts',
       IIF(TotalExpenditure != 0, (TotalGrossCateringCosts / TotalExpenditure) * 100, NULL) AS 'TotalGrossCateringCosts',
       IIF(TotalExpenditure != 0, (TotalNetCateringCosts / TotalExpenditure) * 100, NULL) AS 'TotalNetCateringCosts',
       IIF(TotalExpenditure != 0, (CateringStaffCosts / TotalExpenditure) * 100, NULL) AS 'CateringStaffCosts',
       IIF(TotalExpenditure != 0, (CateringSuppliesCosts / TotalExpenditure) * 100, NULL) AS 'CateringSuppliesCosts',
       IIF(TotalExpenditure != 0, (TotalOtherCosts / TotalExpenditure) * 100, NULL) AS 'TotalOtherCosts',
       IIF(TotalExpenditure != 0, (GroundsMaintenanceCosts / TotalExpenditure) * 100, NULL) AS 'GroundsMaintenanceCosts',
       IIF(TotalExpenditure != 0, (IndirectEmployeeExpenses / TotalExpenditure) * 100, NULL) AS 'IndirectEmployeeExpenses',
       IIF(TotalExpenditure != 0, (InterestChargesLoanBank / TotalExpenditure) * 100, NULL) AS 'InterestChargesLoanBank',
       IIF(TotalExpenditure != 0, (OtherInsurancePremiumsCosts / TotalExpenditure) * 100, NULL) AS 'OtherInsurancePremiumsCosts',
       IIF(TotalExpenditure != 0, (PrivateFinanceInitiativeCharges / TotalExpenditure) * 100, NULL) AS 'PrivateFinanceInitiativeCharges',
       IIF(TotalExpenditure != 0, (RentRatesCosts / TotalExpenditure) * 100, NULL) AS 'RentRatesCosts',
       IIF(TotalExpenditure != 0, (SpecialFacilitiesCosts / TotalExpenditure) * 100, NULL) AS 'SpecialFacilitiesCosts',
       IIF(TotalExpenditure != 0, (StaffDevelopmentTrainingCosts / TotalExpenditure) * 100, NULL) AS 'StaffDevelopmentTrainingCosts',
       IIF(TotalExpenditure != 0, (StaffRelatedInsuranceCosts / TotalExpenditure) * 100, NULL) AS 'StaffRelatedInsuranceCosts',
       IIF(TotalExpenditure != 0, (SupplyTeacherInsurableCosts / TotalExpenditure) * 100, NULL) AS 'SupplyTeacherInsurableCosts',
       IIF(TotalExpenditure != 0, (AdministrativeSuppliesNonEducationalCosts / TotalExpenditure) * 100, NULL) AS 'AdministrativeSuppliesNonEducationalCosts',
       IIF(TotalExpenditure != 0, (TotalPremisesStaffServiceCosts / TotalExpenditure) * 100, NULL) AS 'TotalPremisesStaffServiceCosts',
       IIF(TotalExpenditure != 0, (CleaningCaretakingCosts / TotalExpenditure) * 100, NULL) AS 'CleaningCaretakingCosts',
       IIF(TotalExpenditure != 0, (MaintenancePremisesCosts / TotalExpenditure) * 100, NULL) AS 'MaintenancePremisesCosts',
       IIF(TotalExpenditure != 0, (OtherOccupationCosts / TotalExpenditure) * 100, NULL) AS 'OtherOccupationCosts',
       IIF(TotalExpenditure != 0, (PremisesStaffCosts / TotalExpenditure) * 100, NULL) AS 'PremisesStaffCosts',
       IIF(TotalExpenditure != 0, (TotalUtilitiesCosts / TotalExpenditure) * 100, NULL) AS 'TotalUtilitiesCosts',
       IIF(TotalExpenditure != 0, (EnergyCosts / TotalExpenditure) * 100, NULL) AS 'EnergyCosts',
       IIF(TotalExpenditure != 0, (WaterSewerageCosts / TotalExpenditure) * 100, NULL) AS 'WaterSewerageCosts',
       IIF(TotalExpenditure != 0, (TotalExpenditureCS / TotalExpenditure) * 100, NULL) AS 'TotalExpenditureCS',
       IIF(TotalExpenditure != 0, (TotalTeachingSupportStaffCostsCS / TotalExpenditure) * 100, NULL) AS 'TotalTeachingSupportStaffCostsCS',
       IIF(TotalExpenditure != 0, (TeachingStaffCostsCS / TotalExpenditure) * 100, NULL) AS 'TeachingStaffCostsCS',
       IIF(TotalExpenditure != 0, (SupplyTeachingStaffCostsCS / TotalExpenditure) * 100, NULL) AS 'SupplyTeachingStaffCostsCS',
       IIF(TotalExpenditure != 0, (EducationalConsultancyCostsCS / TotalExpenditure) * 100, NULL) AS 'EducationalConsultancyCostsCS',
       IIF(TotalExpenditure != 0, (EducationSupportStaffCostsCS / TotalExpenditure) * 100, NULL) AS 'EducationSupportStaffCostsCS',
       IIF(TotalExpenditure != 0, (AgencySupplyTeachingStaffCostsCS / TotalExpenditure) * 100, NULL) AS 'AgencySupplyTeachingStaffCostsCS',
       IIF(TotalExpenditure != 0, (TotalNonEducationalSupportStaffCostsCS / TotalExpenditure) * 100, NULL) AS 'TotalNonEducationalSupportStaffCostsCS',
       IIF(TotalExpenditure != 0, (AdministrativeClericalStaffCostsCS / TotalExpenditure) * 100, NULL) AS 'AdministrativeClericalStaffCostsCS',
       IIF(TotalExpenditure != 0, (AuditorsCostsCS / TotalExpenditure) * 100, NULL) AS 'AuditorsCostsCS',
       IIF(TotalExpenditure != 0, (OtherStaffCostsCS / TotalExpenditure) * 100, NULL) AS 'OtherStaffCostsCS',
       IIF(TotalExpenditure != 0, (ProfessionalServicesNonCurriculumCostsCS / TotalExpenditure) * 100, NULL) AS 'ProfessionalServicesNonCurriculumCostsCS',
       IIF(TotalExpenditure != 0, (TotalEducationalSuppliesCostsCS / TotalExpenditure) * 100, NULL) AS 'TotalEducationalSuppliesCostsCS',
       IIF(TotalExpenditure != 0, (ExaminationFeesCostsCS / TotalExpenditure) * 100, NULL) AS 'ExaminationFeesCostsCS',
       IIF(TotalExpenditure != 0, (LearningResourcesNonIctCostsCS / TotalExpenditure) * 100, NULL) AS 'LearningResourcesNonIctCostsCS',
       IIF(TotalExpenditure != 0, (LearningResourcesIctCostsCS / TotalExpenditure) * 100, NULL) AS 'LearningResourcesIctCostsCS',
       IIF(TotalExpenditure != 0, (TotalGrossCateringCostsCS / TotalExpenditure) * 100, NULL) AS 'TotalGrossCateringCostsCS',
       IIF(TotalExpenditure != 0, (TotalNetCateringCostsCS / TotalExpenditure) * 100, NULL) AS 'TotalNetCateringCostsCS',
       IIF(TotalExpenditure != 0, (CateringStaffCostsCS / TotalExpenditure) * 100, NULL) AS 'CateringStaffCostsCS',
       IIF(TotalExpenditure != 0, (CateringSuppliesCostsCS / TotalExpenditure) * 100, NULL) AS 'CateringSuppliesCostsCS',
       IIF(TotalExpenditure != 0, (TotalOtherCostsCS / TotalExpenditure) * 100, NULL) AS 'TotalOtherCostsCS',
       IIF(TotalExpenditure != 0, (GroundsMaintenanceCostsCS / TotalExpenditure) * 100, NULL) AS 'GroundsMaintenanceCostsCS',
       IIF(TotalExpenditure != 0, (IndirectEmployeeExpensesCS / TotalExpenditure) * 100, NULL) AS 'IndirectEmployeeExpensesCS',
       IIF(TotalExpenditure != 0, (InterestChargesLoanBankCS / TotalExpenditure) * 100, NULL) AS 'InterestChargesLoanBankCS',
       IIF(TotalExpenditure != 0, (OtherInsurancePremiumsCostsCS / TotalExpenditure) * 100, NULL) AS 'OtherInsurancePremiumsCostsCS',
       IIF(TotalExpenditure != 0, (PrivateFinanceInitiativeChargesCS / TotalExpenditure) * 100, NULL) AS 'PrivateFinanceInitiativeChargesCS',
       IIF(TotalExpenditure != 0, (RentRatesCostsCS / TotalExpenditure) * 100, NULL) AS 'RentRatesCostsCS',
       IIF(TotalExpenditure != 0, (SpecialFacilitiesCostsCS / TotalExpenditure) * 100, NULL) AS 'SpecialFacilitiesCostsCS',
       IIF(TotalExpenditure != 0, (StaffDevelopmentTrainingCostsCS / TotalExpenditure) * 100, NULL) AS 'StaffDevelopmentTrainingCostsCS',
       IIF(TotalExpenditure != 0, (StaffRelatedInsuranceCostsCS / TotalExpenditure) * 100, NULL) AS 'StaffRelatedInsuranceCostsCS',
       IIF(TotalExpenditure != 0, (SupplyTeacherInsurableCostsCS / TotalExpenditure) * 100, NULL) AS 'SupplyTeacherInsurableCostsCS',
       IIF(TotalExpenditure != 0, (AdministrativeSuppliesNonEducationalCostsCS / TotalExpenditure) * 100, NULL) AS 'AdministrativeSuppliesNonEducationalCostsCS',
       IIF(TotalExpenditure != 0, (TotalPremisesStaffServiceCostsCS / TotalExpenditure) * 100, NULL) AS 'TotalPremisesStaffServiceCostsCS',
       IIF(TotalExpenditure != 0, (CleaningCaretakingCostsCS / TotalExpenditure) * 100, NULL) AS 'CleaningCaretakingCostsCS',
       IIF(TotalExpenditure != 0, (MaintenancePremisesCostsCS / TotalExpenditure) * 100, NULL) AS 'MaintenancePremisesCostsCS',
       IIF(TotalExpenditure != 0, (OtherOccupationCostsCS / TotalExpenditure) * 100, NULL) AS 'OtherOccupationCostsCS',
       IIF(TotalExpenditure != 0, (PremisesStaffCostsCS / TotalExpenditure) * 100, NULL) AS 'PremisesStaffCostsCS',
       IIF(TotalExpenditure != 0, (TotalUtilitiesCostsCS / TotalExpenditure) * 100, NULL) AS 'TotalUtilitiesCostsCS',
       IIF(TotalExpenditure != 0, (EnergyCostsCS / TotalExpenditure) * 100, NULL) AS 'EnergyCostsCS',
       IIF(TotalExpenditure != 0, (WaterSewerageCostsCS / TotalExpenditure) * 100, NULL) AS 'WaterSewerageCostsCS',
       IIF(TotalExpenditure != 0, (TotalExpenditureSchool / TotalExpenditure) * 100, NULL) AS 'TotalExpenditureSchool',
       IIF(TotalExpenditure != 0, (TotalTeachingSupportStaffCostsSchool / TotalExpenditure) * 100, NULL) AS 'TotalTeachingSupportStaffCostsSchool',
       IIF(TotalExpenditure != 0, (TeachingStaffCostsSchool / TotalExpenditure) * 100, NULL) AS 'TeachingStaffCostsSchool',
       IIF(TotalExpenditure != 0, (SupplyTeachingStaffCostsSchool / TotalExpenditure) * 100, NULL) AS 'SupplyTeachingStaffCostsSchool',
       IIF(TotalExpenditure != 0, (EducationalConsultancyCostsSchool / TotalExpenditure) * 100, NULL) AS 'EducationalConsultancyCostsSchool',
       IIF(TotalExpenditure != 0, (EducationSupportStaffCostsSchool / TotalExpenditure) * 100, NULL) AS 'EducationSupportStaffCostsSchool',
       IIF(TotalExpenditure != 0, (AgencySupplyTeachingStaffCostsSchool / TotalExpenditure) * 100, NULL) AS 'AgencySupplyTeachingStaffCostsSchool',
       IIF(TotalExpenditure != 0, (TotalNonEducationalSupportStaffCostsSchool / TotalExpenditure) * 100, NULL) AS 'TotalNonEducationalSupportStaffCostsSchool',
       IIF(TotalExpenditure != 0, (AdministrativeClericalStaffCostsSchool / TotalExpenditure) * 100, NULL) AS 'AdministrativeClericalStaffCostsSchool',
       IIF(TotalExpenditure != 0, (AuditorsCostsSchool / TotalExpenditure) * 100, NULL) AS 'AuditorsCostsSchool',
       IIF(TotalExpenditure != 0, (OtherStaffCostsSchool / TotalExpenditure) * 100, NULL) AS 'OtherStaffCostsSchool',
       IIF(TotalExpenditure != 0, (ProfessionalServicesNonCurriculumCostsSchool / TotalExpenditure) * 100, NULL) AS 'ProfessionalServicesNonCurriculumCostsSchool',
       IIF(TotalExpenditure != 0, (TotalEducationalSuppliesCostsSchool / TotalExpenditure) * 100, NULL) AS 'TotalEducationalSuppliesCostsSchool',
       IIF(TotalExpenditure != 0, (ExaminationFeesCostsSchool / TotalExpenditure) * 100, NULL) AS 'ExaminationFeesCostsSchool',
       IIF(TotalExpenditure != 0, (LearningResourcesNonIctCostsSchool / TotalExpenditure) * 100, NULL) AS 'LearningResourcesNonIctCostsSchool',
       IIF(TotalExpenditure != 0, (LearningResourcesIctCostsSchool / TotalExpenditure) * 100, NULL) AS 'LearningResourcesIctCostsSchool',
       IIF(TotalExpenditure != 0, (TotalGrossCateringCostsSchool / TotalExpenditure) * 100, NULL) AS 'TotalGrossCateringCostsSchool',
       IIF(TotalExpenditure != 0, (TotalNetCateringCostsSchool / TotalExpenditure) * 100, NULL) AS 'TotalNetCateringCostsSchool',
       IIF(TotalExpenditure != 0, (CateringStaffCostsSchool / TotalExpenditure) * 100, NULL) AS 'CateringStaffCostsSchool',
       IIF(TotalExpenditure != 0, (CateringSuppliesCostsSchool / TotalExpenditure) * 100, NULL) AS 'CateringSuppliesCostsSchool',
       IIF(TotalExpenditure != 0, (TotalOtherCostsSchool / TotalExpenditure) * 100, NULL) AS 'TotalOtherCostsSchool',
       IIF(TotalExpenditure != 0, (GroundsMaintenanceCostsSchool / TotalExpenditure) * 100, NULL) AS 'GroundsMaintenanceCostsSchool',
       IIF(TotalExpenditure != 0, (IndirectEmployeeExpensesSchool / TotalExpenditure) * 100, NULL) AS 'IndirectEmployeeExpensesSchool',
       IIF(TotalExpenditure != 0, (InterestChargesLoanBankSchool / TotalExpenditure) * 100, NULL) AS 'InterestChargesLoanBankSchool',
       IIF(TotalExpenditure != 0, (OtherInsurancePremiumsCostsSchool / TotalExpenditure) * 100, NULL) AS 'OtherInsurancePremiumsCostsSchool',
       IIF(TotalExpenditure != 0, (PrivateFinanceInitiativeChargesSchool / TotalExpenditure) * 100, NULL) AS 'PrivateFinanceInitiativeChargesSchool',
       IIF(TotalExpenditure != 0, (RentRatesCostsSchool / TotalExpenditure) * 100, NULL) AS 'RentRatesCostsSchool',
       IIF(TotalExpenditure != 0, (SpecialFacilitiesCostsSchool / TotalExpenditure) * 100, NULL) AS 'SpecialFacilitiesCostsSchool',
       IIF(TotalExpenditure != 0, (StaffDevelopmentTrainingCostsSchool / TotalExpenditure) * 100, NULL) AS 'StaffDevelopmentTrainingCostsSchool',
       IIF(TotalExpenditure != 0, (StaffRelatedInsuranceCostsSchool / TotalExpenditure) * 100, NULL) AS 'StaffRelatedInsuranceCostsSchool',
       IIF(TotalExpenditure != 0, (SupplyTeacherInsurableCostsSchool / TotalExpenditure) * 100, NULL) AS 'SupplyTeacherInsurableCostsSchool',
       IIF(TotalExpenditure != 0, (AdministrativeSuppliesNonEducationalCostsSchool / TotalExpenditure) * 100, NULL) AS 'AdministrativeSuppliesNonEducationalCostsSchool',
       IIF(TotalExpenditure != 0, (TotalPremisesStaffServiceCostsSchool / TotalExpenditure) * 100, NULL) AS 'TotalPremisesStaffServiceCostsSchool',
       IIF(TotalExpenditure != 0, (CleaningCaretakingCostsSchool / TotalExpenditure) * 100, NULL) AS 'CleaningCaretakingCostsSchool',
       IIF(TotalExpenditure != 0, (MaintenancePremisesCostsSchool / TotalExpenditure) * 100, NULL) AS 'MaintenancePremisesCostsSchool',
       IIF(TotalExpenditure != 0, (OtherOccupationCostsSchool / TotalExpenditure) * 100, NULL) AS 'OtherOccupationCostsSchool',
       IIF(TotalExpenditure != 0, (PremisesStaffCostsSchool / TotalExpenditure) * 100, NULL) AS 'PremisesStaffCostsSchool',
       IIF(TotalExpenditure != 0, (TotalUtilitiesCostsSchool / TotalExpenditure) * 100, NULL) AS 'TotalUtilitiesCostsSchool',
       IIF(TotalExpenditure != 0, (EnergyCostsSchool / TotalExpenditure) * 100, NULL) AS 'EnergyCostsSchool',
       IIF(TotalExpenditure != 0, (WaterSewerageCostsSchool / TotalExpenditure) * 100, NULL) AS 'WaterSewerageCostsSchool',
       EMLBand,
       TotalPupils
FROM VW_TrustFinancialDefault
GO

DROP VIEW IF EXISTS VW_ExpenditureTrustDefaultPercentIncome
GO

CREATE VIEW VW_ExpenditureTrustDefaultPercentIncome AS
SELECT CompanyNumber,
       RunId,
       IIF(TotalIncome != 0, (TotalExpenditure / TotalIncome) * 100, NULL) AS 'TotalExpenditure',
       IIF(TotalIncome != 0, (TotalTeachingSupportStaffCosts / TotalIncome) * 100, NULL) AS 'TotalTeachingSupportStaffCosts',
       IIF(TotalIncome != 0, (TeachingStaffCosts / TotalIncome) * 100, NULL) AS 'TeachingStaffCosts',
       IIF(TotalIncome != 0, (SupplyTeachingStaffCosts / TotalIncome) * 100, NULL) AS 'SupplyTeachingStaffCosts',
       IIF(TotalIncome != 0, (EducationalConsultancyCosts / TotalIncome) * 100, NULL) AS 'EducationalConsultancyCosts',
       IIF(TotalIncome != 0, (EducationSupportStaffCosts / TotalIncome) * 100, NULL) AS 'EducationSupportStaffCosts',
       IIF(TotalIncome != 0, (AgencySupplyTeachingStaffCosts / TotalIncome) * 100, NULL) AS 'AgencySupplyTeachingStaffCosts',
       IIF(TotalIncome != 0, (TotalNonEducationalSupportStaffCosts / TotalIncome) * 100, NULL) AS 'TotalNonEducationalSupportStaffCosts',
       IIF(TotalIncome != 0, (AdministrativeClericalStaffCosts / TotalIncome) * 100, NULL) AS 'AdministrativeClericalStaffCosts',
       IIF(TotalIncome != 0, (AuditorsCosts / TotalIncome) * 100, NULL) AS 'AuditorsCosts',
       IIF(TotalIncome != 0, (OtherStaffCosts / TotalIncome) * 100, NULL) AS 'OtherStaffCosts',
       IIF(TotalIncome != 0, (ProfessionalServicesNonCurriculumCosts / TotalIncome) * 100, NULL) AS 'ProfessionalServicesNonCurriculumCosts',
       IIF(TotalIncome != 0, (TotalEducationalSuppliesCosts / TotalIncome) * 100, NULL) AS 'TotalEducationalSuppliesCosts',
       IIF(TotalIncome != 0, (ExaminationFeesCosts / TotalIncome) * 100, NULL) AS 'ExaminationFeesCosts',
       IIF(TotalIncome != 0, (LearningResourcesNonIctCosts / TotalIncome) * 100, NULL) AS 'LearningResourcesNonIctCosts',
       IIF(TotalIncome != 0, (LearningResourcesIctCosts / TotalIncome) * 100, NULL) AS 'LearningResourcesIctCosts',
       IIF(TotalIncome != 0, (TotalGrossCateringCosts / TotalIncome) * 100, NULL) AS 'TotalGrossCateringCosts',
       IIF(TotalIncome != 0, (TotalNetCateringCosts / TotalIncome) * 100, NULL) AS 'TotalNetCateringCosts',
       IIF(TotalIncome != 0, (CateringStaffCosts / TotalIncome) * 100, NULL) AS 'CateringStaffCosts',
       IIF(TotalIncome != 0, (CateringSuppliesCosts / TotalIncome) * 100, NULL) AS 'CateringSuppliesCosts',
       IIF(TotalIncome != 0, (TotalOtherCosts / TotalIncome) * 100, NULL) AS 'TotalOtherCosts',
       IIF(TotalIncome != 0, (GroundsMaintenanceCosts / TotalIncome) * 100, NULL) AS 'GroundsMaintenanceCosts',
       IIF(TotalIncome != 0, (IndirectEmployeeExpenses / TotalIncome) * 100, NULL) AS 'IndirectEmployeeExpenses',
       IIF(TotalIncome != 0, (InterestChargesLoanBank / TotalIncome) * 100, NULL) AS 'InterestChargesLoanBank',
       IIF(TotalIncome != 0, (OtherInsurancePremiumsCosts / TotalIncome) * 100, NULL) AS 'OtherInsurancePremiumsCosts',
       IIF(TotalIncome != 0, (PrivateFinanceInitiativeCharges / TotalIncome) * 100, NULL) AS 'PrivateFinanceInitiativeCharges',
       IIF(TotalIncome != 0, (RentRatesCosts / TotalIncome) * 100, NULL) AS 'RentRatesCosts',
       IIF(TotalIncome != 0, (SpecialFacilitiesCosts / TotalIncome) * 100, NULL) AS 'SpecialFacilitiesCosts',
       IIF(TotalIncome != 0, (StaffDevelopmentTrainingCosts / TotalIncome) * 100, NULL) AS 'StaffDevelopmentTrainingCosts',
       IIF(TotalIncome != 0, (StaffRelatedInsuranceCosts / TotalIncome) * 100, NULL) AS 'StaffRelatedInsuranceCosts',
       IIF(TotalIncome != 0, (SupplyTeacherInsurableCosts / TotalIncome) * 100, NULL) AS 'SupplyTeacherInsurableCosts',
       IIF(TotalIncome != 0, (AdministrativeSuppliesNonEducationalCosts / TotalIncome) * 100, NULL) AS 'AdministrativeSuppliesNonEducationalCosts',
       IIF(TotalIncome != 0, (TotalPremisesStaffServiceCosts / TotalIncome) * 100, NULL) AS 'TotalPremisesStaffServiceCosts',
       IIF(TotalIncome != 0, (CleaningCaretakingCosts / TotalIncome) * 100, NULL) AS 'CleaningCaretakingCosts',
       IIF(TotalIncome != 0, (MaintenancePremisesCosts / TotalIncome) * 100, NULL) AS 'MaintenancePremisesCosts',
       IIF(TotalIncome != 0, (OtherOccupationCosts / TotalIncome) * 100, NULL) AS 'OtherOccupationCosts',
       IIF(TotalIncome != 0, (PremisesStaffCosts / TotalIncome) * 100, NULL) AS 'PremisesStaffCosts',
       IIF(TotalIncome != 0, (TotalUtilitiesCosts / TotalIncome) * 100, NULL) AS 'TotalUtilitiesCosts',
       IIF(TotalIncome != 0, (EnergyCosts / TotalIncome) * 100, NULL) AS 'EnergyCosts',
       IIF(TotalIncome != 0, (WaterSewerageCosts / TotalIncome) * 100, NULL) AS 'WaterSewerageCosts',
       IIF(TotalIncome != 0, (TotalExpenditureCS / TotalIncome) * 100, NULL) AS 'TotalExpenditureCS',
       IIF(TotalIncome != 0, (TotalTeachingSupportStaffCostsCS / TotalIncome) * 100, NULL) AS 'TotalTeachingSupportStaffCostsCS',
       IIF(TotalIncome != 0, (TeachingStaffCostsCS / TotalIncome) * 100, NULL) AS 'TeachingStaffCostsCS',
       IIF(TotalIncome != 0, (SupplyTeachingStaffCostsCS / TotalIncome) * 100, NULL) AS 'SupplyTeachingStaffCostsCS',
       IIF(TotalIncome != 0, (EducationalConsultancyCostsCS / TotalIncome) * 100, NULL) AS 'EducationalConsultancyCostsCS',
       IIF(TotalIncome != 0, (EducationSupportStaffCostsCS / TotalIncome) * 100, NULL) AS 'EducationSupportStaffCostsCS',
       IIF(TotalIncome != 0, (AgencySupplyTeachingStaffCostsCS / TotalIncome) * 100, NULL) AS 'AgencySupplyTeachingStaffCostsCS',
       IIF(TotalIncome != 0, (TotalNonEducationalSupportStaffCostsCS / TotalIncome) * 100, NULL) AS 'TotalNonEducationalSupportStaffCostsCS',
       IIF(TotalIncome != 0, (AdministrativeClericalStaffCostsCS / TotalIncome) * 100, NULL) AS 'AdministrativeClericalStaffCostsCS',
       IIF(TotalIncome != 0, (AuditorsCostsCS / TotalIncome) * 100, NULL) AS 'AuditorsCostsCS',
       IIF(TotalIncome != 0, (OtherStaffCostsCS / TotalIncome) * 100, NULL) AS 'OtherStaffCostsCS',
       IIF(TotalIncome != 0, (ProfessionalServicesNonCurriculumCostsCS / TotalIncome) * 100, NULL) AS 'ProfessionalServicesNonCurriculumCostsCS',
       IIF(TotalIncome != 0, (TotalEducationalSuppliesCostsCS / TotalIncome) * 100, NULL) AS 'TotalEducationalSuppliesCostsCS',
       IIF(TotalIncome != 0, (ExaminationFeesCostsCS / TotalIncome) * 100, NULL) AS 'ExaminationFeesCostsCS',
       IIF(TotalIncome != 0, (LearningResourcesNonIctCostsCS / TotalIncome) * 100, NULL) AS 'LearningResourcesNonIctCostsCS',
       IIF(TotalIncome != 0, (LearningResourcesIctCostsCS / TotalIncome) * 100, NULL) AS 'LearningResourcesIctCostsCS',
       IIF(TotalIncome != 0, (TotalGrossCateringCostsCS / TotalIncome) * 100, NULL) AS 'TotalGrossCateringCostsCS',
       IIF(TotalIncome != 0, (TotalNetCateringCostsCS / TotalIncome) * 100, NULL) AS 'TotalNetCateringCostsCS',
       IIF(TotalIncome != 0, (CateringStaffCostsCS / TotalIncome) * 100, NULL) AS 'CateringStaffCostsCS',
       IIF(TotalIncome != 0, (CateringSuppliesCostsCS / TotalIncome) * 100, NULL) AS 'CateringSuppliesCostsCS',
       IIF(TotalIncome != 0, (TotalOtherCostsCS / TotalIncome) * 100, NULL) AS 'TotalOtherCostsCS',
       IIF(TotalIncome != 0, (GroundsMaintenanceCostsCS / TotalIncome) * 100, NULL) AS 'GroundsMaintenanceCostsCS',
       IIF(TotalIncome != 0, (IndirectEmployeeExpensesCS / TotalIncome) * 100, NULL) AS 'IndirectEmployeeExpensesCS',
       IIF(TotalIncome != 0, (InterestChargesLoanBankCS / TotalIncome) * 100, NULL) AS 'InterestChargesLoanBankCS',
       IIF(TotalIncome != 0, (OtherInsurancePremiumsCostsCS / TotalIncome) * 100, NULL) AS 'OtherInsurancePremiumsCostsCS',
       IIF(TotalIncome != 0, (PrivateFinanceInitiativeChargesCS / TotalIncome) * 100, NULL) AS 'PrivateFinanceInitiativeChargesCS',
       IIF(TotalIncome != 0, (RentRatesCostsCS / TotalIncome) * 100, NULL) AS 'RentRatesCostsCS',
       IIF(TotalIncome != 0, (SpecialFacilitiesCostsCS / TotalIncome) * 100, NULL) AS 'SpecialFacilitiesCostsCS',
       IIF(TotalIncome != 0, (StaffDevelopmentTrainingCostsCS / TotalIncome) * 100, NULL) AS 'StaffDevelopmentTrainingCostsCS',
       IIF(TotalIncome != 0, (StaffRelatedInsuranceCostsCS / TotalIncome) * 100, NULL) AS 'StaffRelatedInsuranceCostsCS',
       IIF(TotalIncome != 0, (SupplyTeacherInsurableCostsCS / TotalIncome) * 100, NULL) AS 'SupplyTeacherInsurableCostsCS',
       IIF(TotalIncome != 0, (AdministrativeSuppliesNonEducationalCostsCS / TotalIncome) * 100, NULL) AS 'AdministrativeSuppliesNonEducationalCostsCS',
       IIF(TotalIncome != 0, (TotalPremisesStaffServiceCostsCS / TotalIncome) * 100, NULL) AS 'TotalPremisesStaffServiceCostsCS',
       IIF(TotalIncome != 0, (CleaningCaretakingCostsCS / TotalIncome) * 100, NULL) AS 'CleaningCaretakingCostsCS',
       IIF(TotalIncome != 0, (MaintenancePremisesCostsCS / TotalIncome) * 100, NULL) AS 'MaintenancePremisesCostsCS',
       IIF(TotalIncome != 0, (OtherOccupationCostsCS / TotalIncome) * 100, NULL) AS 'OtherOccupationCostsCS',
       IIF(TotalIncome != 0, (PremisesStaffCostsCS / TotalIncome) * 100, NULL) AS 'PremisesStaffCostsCS',
       IIF(TotalIncome != 0, (TotalUtilitiesCostsCS / TotalIncome) * 100, NULL) AS 'TotalUtilitiesCostsCS',
       IIF(TotalIncome != 0, (EnergyCostsCS / TotalIncome) * 100, NULL) AS 'EnergyCostsCS',
       IIF(TotalIncome != 0, (WaterSewerageCostsCS / TotalIncome) * 100, NULL) AS 'WaterSewerageCostsCS',
       IIF(TotalIncome != 0, (TotalExpenditureSchool / TotalIncome) * 100, NULL) AS 'TotalExpenditureSchool',
       IIF(TotalIncome != 0, (TotalTeachingSupportStaffCostsSchool / TotalIncome) * 100, NULL) AS 'TotalTeachingSupportStaffCostsSchool',
       IIF(TotalIncome != 0, (TeachingStaffCostsSchool / TotalIncome) * 100, NULL) AS 'TeachingStaffCostsSchool',
       IIF(TotalIncome != 0, (SupplyTeachingStaffCostsSchool / TotalIncome) * 100, NULL) AS 'SupplyTeachingStaffCostsSchool',
       IIF(TotalIncome != 0, (EducationalConsultancyCostsSchool / TotalIncome) * 100, NULL) AS 'EducationalConsultancyCostsSchool',
       IIF(TotalIncome != 0, (EducationSupportStaffCostsSchool / TotalIncome) * 100, NULL) AS 'EducationSupportStaffCostsSchool',
       IIF(TotalIncome != 0, (AgencySupplyTeachingStaffCostsSchool / TotalIncome) * 100, NULL) AS 'AgencySupplyTeachingStaffCostsSchool',
       IIF(TotalIncome != 0, (TotalNonEducationalSupportStaffCostsSchool / TotalIncome) * 100, NULL) AS 'TotalNonEducationalSupportStaffCostsSchool',
       IIF(TotalIncome != 0, (AdministrativeClericalStaffCostsSchool / TotalIncome) * 100, NULL) AS 'AdministrativeClericalStaffCostsSchool',
       IIF(TotalIncome != 0, (AuditorsCostsSchool / TotalIncome) * 100, NULL) AS 'AuditorsCostsSchool',
       IIF(TotalIncome != 0, (OtherStaffCostsSchool / TotalIncome) * 100, NULL) AS 'OtherStaffCostsSchool',
       IIF(TotalIncome != 0, (ProfessionalServicesNonCurriculumCostsSchool / TotalIncome) * 100, NULL) AS 'ProfessionalServicesNonCurriculumCostsSchool',
       IIF(TotalIncome != 0, (TotalEducationalSuppliesCostsSchool / TotalIncome) * 100, NULL) AS 'TotalEducationalSuppliesCostsSchool',
       IIF(TotalIncome != 0, (ExaminationFeesCostsSchool / TotalIncome) * 100, NULL) AS 'ExaminationFeesCostsSchool',
       IIF(TotalIncome != 0, (LearningResourcesNonIctCostsSchool / TotalIncome) * 100, NULL) AS 'LearningResourcesNonIctCostsSchool',
       IIF(TotalIncome != 0, (LearningResourcesIctCostsSchool / TotalIncome) * 100, NULL) AS 'LearningResourcesIctCostsSchool',
       IIF(TotalIncome != 0, (TotalGrossCateringCostsSchool / TotalIncome) * 100, NULL) AS 'TotalGrossCateringCostsSchool',
       IIF(TotalIncome != 0, (TotalNetCateringCostsSchool / TotalIncome) * 100, NULL) AS 'TotalNetCateringCostsSchool',
       IIF(TotalIncome != 0, (CateringStaffCostsSchool / TotalIncome) * 100, NULL) AS 'CateringStaffCostsSchool',
       IIF(TotalIncome != 0, (CateringSuppliesCostsSchool / TotalIncome) * 100, NULL) AS 'CateringSuppliesCostsSchool',
       IIF(TotalIncome != 0, (TotalOtherCostsSchool / TotalIncome) * 100, NULL) AS 'TotalOtherCostsSchool',
       IIF(TotalIncome != 0, (GroundsMaintenanceCostsSchool / TotalIncome) * 100, NULL) AS 'GroundsMaintenanceCostsSchool',
       IIF(TotalIncome != 0, (IndirectEmployeeExpensesSchool / TotalIncome) * 100, NULL) AS 'IndirectEmployeeExpensesSchool',
       IIF(TotalIncome != 0, (InterestChargesLoanBankSchool / TotalIncome) * 100, NULL) AS 'InterestChargesLoanBankSchool',
       IIF(TotalIncome != 0, (OtherInsurancePremiumsCostsSchool / TotalIncome) * 100, NULL) AS 'OtherInsurancePremiumsCostsSchool',
       IIF(TotalIncome != 0, (PrivateFinanceInitiativeChargesSchool / TotalIncome) * 100, NULL) AS 'PrivateFinanceInitiativeChargesSchool',
       IIF(TotalIncome != 0, (RentRatesCostsSchool / TotalIncome) * 100, NULL) AS 'RentRatesCostsSchool',
       IIF(TotalIncome != 0, (SpecialFacilitiesCostsSchool / TotalIncome) * 100, NULL) AS 'SpecialFacilitiesCostsSchool',
       IIF(TotalIncome != 0, (StaffDevelopmentTrainingCostsSchool / TotalIncome) * 100, NULL) AS 'StaffDevelopmentTrainingCostsSchool',
       IIF(TotalIncome != 0, (StaffRelatedInsuranceCostsSchool / TotalIncome) * 100, NULL) AS 'StaffRelatedInsuranceCostsSchool',
       IIF(TotalIncome != 0, (SupplyTeacherInsurableCostsSchool / TotalIncome) * 100, NULL) AS 'SupplyTeacherInsurableCostsSchool',
       IIF(TotalIncome != 0, (AdministrativeSuppliesNonEducationalCostsSchool / TotalIncome) * 100, NULL) AS 'AdministrativeSuppliesNonEducationalCostsSchool',
       IIF(TotalIncome != 0, (TotalPremisesStaffServiceCostsSchool / TotalIncome) * 100, NULL) AS 'TotalPremisesStaffServiceCostsSchool',
       IIF(TotalIncome != 0, (CleaningCaretakingCostsSchool / TotalIncome) * 100, NULL) AS 'CleaningCaretakingCostsSchool',
       IIF(TotalIncome != 0, (MaintenancePremisesCostsSchool / TotalIncome) * 100, NULL) AS 'MaintenancePremisesCostsSchool',
       IIF(TotalIncome != 0, (OtherOccupationCostsSchool / TotalIncome) * 100, NULL) AS 'OtherOccupationCostsSchool',
       IIF(TotalIncome != 0, (PremisesStaffCostsSchool / TotalIncome) * 100, NULL) AS 'PremisesStaffCostsSchool',
       IIF(TotalIncome != 0, (TotalUtilitiesCostsSchool / TotalIncome) * 100, NULL) AS 'TotalUtilitiesCostsSchool',
       IIF(TotalIncome != 0, (EnergyCostsSchool / TotalIncome) * 100, NULL) AS 'EnergyCostsSchool',
       IIF(TotalIncome != 0, (WaterSewerageCostsSchool / TotalIncome) * 100, NULL) AS 'WaterSewerageCostsSchool',
       EMLBand,
       TotalPupils
FROM VW_TrustFinancialDefault
GO

DROP VIEW IF EXISTS VW_ExpenditureTrustDefaultPerUnit
GO

CREATE VIEW VW_ExpenditureTrustDefaultPerUnit AS
SELECT CompanyNumber,
       RunId,
       IIF(TotalPupils != 0, TotalExpenditure / TotalPupils, NULL) AS 'TotalExpenditure',
       IIF(TotalPupils != 0, TotalTeachingSupportStaffCosts / TotalPupils, NULL) AS 'TotalTeachingSupportStaffCosts',
       IIF(TotalPupils != 0, TeachingStaffCosts / TotalPupils, NULL) AS 'TeachingStaffCosts',
       IIF(TotalPupils != 0, SupplyTeachingStaffCosts / TotalPupils, NULL) AS 'SupplyTeachingStaffCosts',
       IIF(TotalPupils != 0, EducationalConsultancyCosts / TotalPupils, NULL) AS 'EducationalConsultancyCosts',
       IIF(TotalPupils != 0, EducationSupportStaffCosts / TotalPupils, NULL) AS 'EducationSupportStaffCosts',
       IIF(TotalPupils != 0, AgencySupplyTeachingStaffCosts / TotalPupils, NULL) AS 'AgencySupplyTeachingStaffCosts',
       IIF(TotalPupils != 0, TotalNonEducationalSupportStaffCosts / TotalPupils, NULL) AS 'TotalNonEducationalSupportStaffCosts',
       IIF(TotalPupils != 0, AdministrativeClericalStaffCosts / TotalPupils, NULL) AS 'AdministrativeClericalStaffCosts',
       IIF(TotalPupils != 0, AuditorsCosts / TotalPupils, NULL) AS 'AuditorsCosts',
       IIF(TotalPupils != 0, OtherStaffCosts / TotalPupils, NULL) AS 'OtherStaffCosts',
       IIF(TotalPupils != 0, ProfessionalServicesNonCurriculumCosts / TotalPupils, NULL) AS 'ProfessionalServicesNonCurriculumCosts',
       IIF(TotalPupils != 0, TotalEducationalSuppliesCosts / TotalPupils, NULL) AS 'TotalEducationalSuppliesCosts',
       IIF(TotalPupils != 0, ExaminationFeesCosts / TotalPupils, NULL) AS 'ExaminationFeesCosts',
       IIF(TotalPupils != 0, LearningResourcesNonIctCosts / TotalPupils, NULL) AS 'LearningResourcesNonIctCosts',
       IIF(TotalPupils != 0, LearningResourcesIctCosts / TotalPupils, NULL) AS 'LearningResourcesIctCosts',
       IIF(TotalPupils != 0, TotalGrossCateringCosts / TotalPupils, NULL) AS 'TotalGrossCateringCosts',
       IIF(TotalPupils != 0, TotalNetCateringCosts / TotalPupils, NULL) AS 'TotalNetCateringCosts',
       IIF(TotalPupils != 0, CateringStaffCosts / TotalPupils, NULL) AS 'CateringStaffCosts',
       IIF(TotalPupils != 0, CateringSuppliesCosts / TotalPupils, NULL) AS 'CateringSuppliesCosts',
       IIF(TotalPupils != 0, TotalOtherCosts / TotalPupils, NULL) AS 'TotalOtherCosts',
       IIF(TotalPupils != 0, GroundsMaintenanceCosts / TotalPupils, NULL) AS 'GroundsMaintenanceCosts',
       IIF(TotalPupils != 0, IndirectEmployeeExpenses / TotalPupils, NULL) AS 'IndirectEmployeeExpenses',
       IIF(TotalPupils != 0, InterestChargesLoanBank / TotalPupils, NULL) AS 'InterestChargesLoanBank',
       IIF(TotalPupils != 0, OtherInsurancePremiumsCosts / TotalPupils, NULL) AS 'OtherInsurancePremiumsCosts',
       IIF(TotalPupils != 0, PrivateFinanceInitiativeCharges / TotalPupils, NULL) AS 'PrivateFinanceInitiativeCharges',
       IIF(TotalPupils != 0, RentRatesCosts / TotalPupils, NULL) AS 'RentRatesCosts',
       IIF(TotalPupils != 0, SpecialFacilitiesCosts / TotalPupils, NULL) AS 'SpecialFacilitiesCosts',
       IIF(TotalPupils != 0, StaffDevelopmentTrainingCosts / TotalPupils, NULL) AS 'StaffDevelopmentTrainingCosts',
       IIF(TotalPupils != 0, StaffRelatedInsuranceCosts / TotalPupils, NULL) AS 'StaffRelatedInsuranceCosts',
       IIF(TotalPupils != 0, SupplyTeacherInsurableCosts / TotalPupils, NULL) AS 'SupplyTeacherInsurableCosts',
       IIF(TotalPupils != 0, AdministrativeSuppliesNonEducationalCosts / TotalPupils, NULL) AS 'AdministrativeSuppliesNonEducationalCosts',
       IIF(TotalInternalFloorArea != 0, TotalPremisesStaffServiceCosts / TotalInternalFloorArea, NULL) AS 'TotalPremisesStaffServiceCosts',
       IIF(TotalInternalFloorArea != 0, CleaningCaretakingCosts / TotalInternalFloorArea, NULL) AS 'CleaningCaretakingCosts',
       IIF(TotalInternalFloorArea != 0, MaintenancePremisesCosts / TotalInternalFloorArea, NULL) AS 'MaintenancePremisesCosts',
       IIF(TotalInternalFloorArea != 0, OtherOccupationCosts / TotalInternalFloorArea, NULL) AS 'OtherOccupationCosts',
       IIF(TotalInternalFloorArea != 0, PremisesStaffCosts / TotalInternalFloorArea, NULL) AS 'PremisesStaffCosts',
       IIF(TotalInternalFloorArea != 0, TotalUtilitiesCosts / TotalInternalFloorArea, NULL) AS 'TotalUtilitiesCosts',
       IIF(TotalInternalFloorArea != 0, EnergyCosts / TotalInternalFloorArea, NULL) AS 'EnergyCosts',
       IIF(TotalInternalFloorArea != 0, WaterSewerageCosts / TotalInternalFloorArea, NULL) AS 'WaterSewerageCosts',
       IIF(TotalPupils != 0, TotalExpenditureCS / TotalPupils, NULL) AS 'TotalExpenditureCS',
       IIF(TotalPupils != 0, TotalTeachingSupportStaffCostsCS / TotalPupils, NULL) AS 'TotalTeachingSupportStaffCostsCS',
       IIF(TotalPupils != 0, TeachingStaffCostsCS / TotalPupils, NULL) AS 'TeachingStaffCostsCS',
       IIF(TotalPupils != 0, SupplyTeachingStaffCostsCS / TotalPupils, NULL) AS 'SupplyTeachingStaffCostsCS',
       IIF(TotalPupils != 0, EducationalConsultancyCostsCS / TotalPupils, NULL) AS 'EducationalConsultancyCostsCS',
       IIF(TotalPupils != 0, EducationSupportStaffCostsCS / TotalPupils, NULL) AS 'EducationSupportStaffCostsCS',
       IIF(TotalPupils != 0, AgencySupplyTeachingStaffCostsCS / TotalPupils, NULL) AS 'AgencySupplyTeachingStaffCostsCS',
       IIF(TotalPupils != 0, TotalNonEducationalSupportStaffCostsCS / TotalPupils, NULL) AS 'TotalNonEducationalSupportStaffCostsCS',
       IIF(TotalPupils != 0, AdministrativeClericalStaffCostsCS / TotalPupils, NULL) AS 'AdministrativeClericalStaffCostsCS',
       IIF(TotalPupils != 0, AuditorsCostsCS / TotalPupils, NULL) AS 'AuditorsCostsCS',
       IIF(TotalPupils != 0, OtherStaffCostsCS / TotalPupils, NULL) AS 'OtherStaffCostsCS',
       IIF(TotalPupils != 0, ProfessionalServicesNonCurriculumCostsCS / TotalPupils, NULL) AS 'ProfessionalServicesNonCurriculumCostsCS',
       IIF(TotalPupils != 0, TotalEducationalSuppliesCostsCS / TotalPupils, NULL) AS 'TotalEducationalSuppliesCostsCS',
       IIF(TotalPupils != 0, ExaminationFeesCostsCS / TotalPupils, NULL) AS 'ExaminationFeesCostsCS',
       IIF(TotalPupils != 0, LearningResourcesNonIctCostsCS / TotalPupils, NULL) AS 'LearningResourcesNonIctCostsCS',
       IIF(TotalPupils != 0, LearningResourcesIctCostsCS / TotalPupils, NULL) AS 'LearningResourcesIctCostsCS',
       IIF(TotalPupils != 0, TotalGrossCateringCostsCS / TotalPupils, NULL) AS 'TotalGrossCateringCostsCS',
       IIF(TotalPupils != 0, TotalNetCateringCostsCS / TotalPupils, NULL) AS 'TotalNetCateringCostsCS',
       IIF(TotalPupils != 0, CateringStaffCostsCS / TotalPupils, NULL) AS 'CateringStaffCostsCS',
       IIF(TotalPupils != 0, CateringSuppliesCostsCS / TotalPupils, NULL) AS 'CateringSuppliesCostsCS',
       IIF(TotalPupils != 0, TotalOtherCostsCS / TotalPupils, NULL) AS 'TotalOtherCostsCS',
       IIF(TotalPupils != 0, GroundsMaintenanceCostsCS / TotalPupils, NULL) AS 'GroundsMaintenanceCostsCS',
       IIF(TotalPupils != 0, IndirectEmployeeExpensesCS / TotalPupils, NULL) AS 'IndirectEmployeeExpensesCS',
       IIF(TotalPupils != 0, InterestChargesLoanBankCS / TotalPupils, NULL) AS 'InterestChargesLoanBankCS',
       IIF(TotalPupils != 0, OtherInsurancePremiumsCostsCS / TotalPupils, NULL) AS 'OtherInsurancePremiumsCostsCS',
       IIF(TotalPupils != 0, PrivateFinanceInitiativeChargesCS / TotalPupils, NULL) AS 'PrivateFinanceInitiativeChargesCS',
       IIF(TotalPupils != 0, RentRatesCostsCS / TotalPupils, NULL) AS 'RentRatesCostsCS',
       IIF(TotalPupils != 0, SpecialFacilitiesCostsCS / TotalPupils, NULL) AS 'SpecialFacilitiesCostsCS',
       IIF(TotalPupils != 0, StaffDevelopmentTrainingCostsCS / TotalPupils, NULL) AS 'StaffDevelopmentTrainingCostsCS',
       IIF(TotalPupils != 0, StaffRelatedInsuranceCostsCS / TotalPupils, NULL) AS 'StaffRelatedInsuranceCostsCS',
       IIF(TotalPupils != 0, SupplyTeacherInsurableCostsCS / TotalPupils, NULL) AS 'SupplyTeacherInsurableCostsCS',
       IIF(TotalPupils != 0, AdministrativeSuppliesNonEducationalCostsCS / TotalPupils, NULL) AS 'AdministrativeSuppliesNonEducationalCostsCS',
       IIF(TotalInternalFloorArea != 0, TotalPremisesStaffServiceCostsCS / TotalInternalFloorArea, NULL) AS 'TotalPremisesStaffServiceCostsCS',
       IIF(TotalInternalFloorArea != 0, CleaningCaretakingCostsCS / TotalInternalFloorArea, NULL) AS 'CleaningCaretakingCostsCS',
       IIF(TotalInternalFloorArea != 0, MaintenancePremisesCostsCS / TotalInternalFloorArea, NULL) AS 'MaintenancePremisesCostsCS',
       IIF(TotalInternalFloorArea != 0, OtherOccupationCostsCS / TotalInternalFloorArea, NULL) AS 'OtherOccupationCostsCS',
       IIF(TotalInternalFloorArea != 0, PremisesStaffCostsCS / TotalInternalFloorArea, NULL) AS 'PremisesStaffCostsCS',
       IIF(TotalInternalFloorArea != 0, TotalUtilitiesCostsCS / TotalInternalFloorArea, NULL) AS 'TotalUtilitiesCostsCS',
       IIF(TotalInternalFloorArea != 0, EnergyCostsCS / TotalInternalFloorArea, NULL) AS 'EnergyCostsCS',
       IIF(TotalInternalFloorArea != 0, WaterSewerageCostsCS / TotalInternalFloorArea, NULL) AS 'WaterSewerageCostsCS',
       IIF(TotalPupils != 0, TotalExpenditureSchool / TotalPupils, NULL) AS 'TotalExpenditureSchool',
       IIF(TotalPupils != 0, TotalTeachingSupportStaffCostsSchool / TotalPupils, NULL) AS 'TotalTeachingSupportStaffCostsSchool',
       IIF(TotalPupils != 0, TeachingStaffCostsSchool / TotalPupils, NULL) AS 'TeachingStaffCostsSchool',
       IIF(TotalPupils != 0, SupplyTeachingStaffCostsSchool / TotalPupils, NULL) AS 'SupplyTeachingStaffCostsSchool',
       IIF(TotalPupils != 0, EducationalConsultancyCostsSchool / TotalPupils, NULL) AS 'EducationalConsultancyCostsSchool',
       IIF(TotalPupils != 0, EducationSupportStaffCostsSchool / TotalPupils, NULL) AS 'EducationSupportStaffCostsSchool',
       IIF(TotalPupils != 0, AgencySupplyTeachingStaffCostsSchool / TotalPupils, NULL) AS 'AgencySupplyTeachingStaffCostsSchool',
       IIF(TotalPupils != 0, TotalNonEducationalSupportStaffCostsSchool / TotalPupils, NULL) AS 'TotalNonEducationalSupportStaffCostsSchool',
       IIF(TotalPupils != 0, AdministrativeClericalStaffCostsSchool / TotalPupils, NULL) AS 'AdministrativeClericalStaffCostsSchool',
       IIF(TotalPupils != 0, AuditorsCostsSchool / TotalPupils, NULL) AS 'AuditorsCostsSchool',
       IIF(TotalPupils != 0, OtherStaffCostsSchool / TotalPupils, NULL) AS 'OtherStaffCostsSchool',
       IIF(TotalPupils != 0, ProfessionalServicesNonCurriculumCostsSchool / TotalPupils, NULL) AS 'ProfessionalServicesNonCurriculumCostsSchool',
       IIF(TotalPupils != 0, TotalEducationalSuppliesCostsSchool / TotalPupils, NULL) AS 'TotalEducationalSuppliesCostsSchool',
       IIF(TotalPupils != 0, ExaminationFeesCostsSchool / TotalPupils, NULL) AS 'ExaminationFeesCostsSchool',
       IIF(TotalPupils != 0, LearningResourcesNonIctCostsSchool / TotalPupils, NULL) AS 'LearningResourcesNonIctCostsSchool',
       IIF(TotalPupils != 0, LearningResourcesIctCostsSchool / TotalPupils, NULL) AS 'LearningResourcesIctCostsSchool',
       IIF(TotalPupils != 0, TotalGrossCateringCostsSchool / TotalPupils, NULL) AS 'TotalGrossCateringCostsSchool',
       IIF(TotalPupils != 0, TotalNetCateringCostsSchool / TotalPupils, NULL) AS 'TotalNetCateringCostsSchool',
       IIF(TotalPupils != 0, CateringStaffCostsSchool / TotalPupils, NULL) AS 'CateringStaffCostsSchool',
       IIF(TotalPupils != 0, CateringSuppliesCostsSchool / TotalPupils, NULL) AS 'CateringSuppliesCostsSchool',
       IIF(TotalPupils != 0, TotalOtherCostsSchool / TotalPupils, NULL) AS 'TotalOtherCostsSchool',
       IIF(TotalPupils != 0, GroundsMaintenanceCostsSchool / TotalPupils, NULL) AS 'GroundsMaintenanceCostsSchool',
       IIF(TotalPupils != 0, IndirectEmployeeExpensesSchool / TotalPupils, NULL) AS 'IndirectEmployeeExpensesSchool',
       IIF(TotalPupils != 0, InterestChargesLoanBankSchool / TotalPupils, NULL) AS 'InterestChargesLoanBankSchool',
       IIF(TotalPupils != 0, OtherInsurancePremiumsCostsSchool / TotalPupils, NULL) AS 'OtherInsurancePremiumsCostsSchool',
       IIF(TotalPupils != 0, PrivateFinanceInitiativeChargesSchool / TotalPupils, NULL) AS 'PrivateFinanceInitiativeChargesSchool',
       IIF(TotalPupils != 0, RentRatesCostsSchool / TotalPupils, NULL) AS 'RentRatesCostsSchool',
       IIF(TotalPupils != 0, SpecialFacilitiesCostsSchool / TotalPupils, NULL) AS 'SpecialFacilitiesCostsSchool',
       IIF(TotalPupils != 0, StaffDevelopmentTrainingCostsSchool / TotalPupils, NULL) AS 'StaffDevelopmentTrainingCostsSchool',
       IIF(TotalPupils != 0, StaffRelatedInsuranceCostsSchool / TotalPupils, NULL) AS 'StaffRelatedInsuranceCostsSchool',
       IIF(TotalPupils != 0, SupplyTeacherInsurableCostsSchool / TotalPupils, NULL) AS 'SupplyTeacherInsurableCostsSchool',
       IIF(TotalPupils != 0, AdministrativeSuppliesNonEducationalCostsSchool / TotalPupils, NULL) AS 'AdministrativeSuppliesNonEducationalCostsSchool',
       IIF(TotalInternalFloorArea != 0, TotalPremisesStaffServiceCostsSchool / TotalInternalFloorArea, NULL) AS 'TotalPremisesStaffServiceCostsSchool',
       IIF(TotalInternalFloorArea != 0, CleaningCaretakingCostsSchool / TotalInternalFloorArea, NULL) AS 'CleaningCaretakingCostsSchool',
       IIF(TotalInternalFloorArea != 0, MaintenancePremisesCostsSchool / TotalInternalFloorArea, NULL) AS 'MaintenancePremisesCostsSchool',
       IIF(TotalInternalFloorArea != 0, OtherOccupationCostsSchool / TotalInternalFloorArea, NULL) AS 'OtherOccupationCostsSchool',
       IIF(TotalInternalFloorArea != 0, PremisesStaffCostsSchool / TotalInternalFloorArea, NULL) AS 'PremisesStaffCostsSchool',
       IIF(TotalInternalFloorArea != 0, TotalUtilitiesCostsSchool / TotalInternalFloorArea, NULL) AS 'TotalUtilitiesCostsSchool',
       IIF(TotalInternalFloorArea != 0, EnergyCostsSchool / TotalInternalFloorArea, NULL) AS 'EnergyCostsSchool',
       IIF(TotalInternalFloorArea != 0, WaterSewerageCostsSchool / TotalInternalFloorArea, NULL) AS 'WaterSewerageCostsSchool',
       EMLBand,
       TotalPupils
FROM VW_TrustFinancialDefault
GO

DROP VIEW IF EXISTS VW_ExpenditureTrustDefaultCurrentActual
GO

CREATE VIEW VW_ExpenditureTrustDefaultCurrentActual AS
SELECT f.*,
       t.TrustName
FROM Trust t
         LEFT JOIN VW_ExpenditureTrustDefaultActual f on f.CompanyNumber = t.CompanyNumber
WHERE f.RunId = (SELECT Value FROM Parameters WHERE Name = 'CurrentYear')
GO

DROP VIEW IF EXISTS VW_ExpenditureTrustDefaultCurrentPercentExpenditure
GO

CREATE VIEW VW_ExpenditureTrustDefaultCurrentPercentExpenditure AS
SELECT f.*,
       t.TrustName
FROM Trust t
         LEFT JOIN VW_ExpenditureTrustDefaultPercentExpenditure f on f.CompanyNumber = t.CompanyNumber
WHERE f.RunId = (SELECT Value FROM Parameters WHERE Name = 'CurrentYear')
GO

DROP VIEW IF EXISTS VW_ExpenditureTrustDefaultCurrentPercentIncome
GO

CREATE VIEW VW_ExpenditureTrustDefaultCurrentPercentIncome AS
SELECT f.*,
       t.TrustName
FROM Trust t
         LEFT JOIN VW_ExpenditureTrustDefaultPercentIncome f on f.CompanyNumber = t.CompanyNumber
WHERE f.RunId = (SELECT Value FROM Parameters WHERE Name = 'CurrentYear')
GO

DROP VIEW IF EXISTS VW_ExpenditureTrustDefaultCurrentPerUnit
GO

CREATE VIEW VW_ExpenditureTrustDefaultCurrentPerUnit AS
SELECT f.*,
       t.TrustName
FROM Trust t
         LEFT JOIN VW_ExpenditureTrustDefaultPerUnit f on f.CompanyNumber = t.CompanyNumber
WHERE f.RunId = (SELECT Value FROM Parameters WHERE Name = 'CurrentYear')
GO
