DROP VIEW IF EXISTS VW_ExpenditureTrustDefaultActual
GO

CREATE VIEW VW_ExpenditureTrustDefaultActual AS
SELECT CompanyNumber,
       RunId,
       TotalExpenditure,
       TotalTeachingSupportStaffCosts,
       TeachingStaffCosts,
       SupplyTeachingStaffCosts,
       EducationalConsultancyCosts,
       EducationSupportStaffCosts,
       AgencySupplyTeachingStaffCosts,
       TotalNonEducationalSupportStaffCosts,
       AdministrativeClericalStaffCosts,
       AuditorsCosts,
       OtherStaffCosts,
       ProfessionalServicesNonCurriculumCosts,
       TotalEducationalSuppliesCosts,
       ExaminationFeesCosts,
       LearningResourcesNonIctCosts,
       LearningResourcesIctCosts,
       TotalGrossCateringCosts,
       TotalNetCateringCosts,
       CateringStaffCosts,
       CateringSuppliesCosts,
       TotalOtherCosts,
       GroundsMaintenanceCosts,
       IndirectEmployeeExpenses,
       InterestChargesLoanBank,
       OtherInsurancePremiumsCosts,
       PrivateFinanceInitiativeCharges,
       RentRatesCosts,
       SpecialFacilitiesCosts,
       StaffDevelopmentTrainingCosts,
       StaffRelatedInsuranceCosts,
       SupplyTeacherInsurableCosts,
       AdministrativeSuppliesNonEducationalCosts,
       TotalPremisesStaffServiceCosts,
       CleaningCaretakingCosts,
       MaintenancePremisesCosts,
       OtherOccupationCosts,
       PremisesStaffCosts,
       TotalUtilitiesCosts,
       EnergyCosts,
       WaterSewerageCosts,
       TotalExpenditureCS,
       TotalTeachingSupportStaffCostsCS,
       TeachingStaffCostsCS,
       SupplyTeachingStaffCostsCS,
       EducationalConsultancyCostsCS,
       EducationSupportStaffCostsCS,
       AgencySupplyTeachingStaffCostsCS,
       TotalNonEducationalSupportStaffCostsCS,
       AdministrativeClericalStaffCostsCS,
       AuditorsCostsCS,
       OtherStaffCostsCS,
       ProfessionalServicesNonCurriculumCostsCS,
       TotalEducationalSuppliesCostsCS,
       ExaminationFeesCostsCS,
       LearningResourcesNonIctCostsCS,
       LearningResourcesIctCostsCS,
       TotalGrossCateringCostsCS,
       TotalNetCateringCostsCS,
       CateringStaffCostsCS,
       CateringSuppliesCostsCS,
       TotalOtherCostsCS,
       GroundsMaintenanceCostsCS,
       IndirectEmployeeExpensesCS,
       InterestChargesLoanBankCS,
       OtherInsurancePremiumsCostsCS,
       PrivateFinanceInitiativeChargesCS,
       RentRatesCostsCS,
       SpecialFacilitiesCostsCS,
       StaffDevelopmentTrainingCostsCS,
       StaffRelatedInsuranceCostsCS,
       SupplyTeacherInsurableCostsCS,
       AdministrativeSuppliesNonEducationalCostsCS,
       TotalPremisesStaffServiceCostsCS,
       CleaningCaretakingCostsCS,
       MaintenancePremisesCostsCS,
       OtherOccupationCostsCS,
       PremisesStaffCostsCS,
       TotalUtilitiesCostsCS,
       EnergyCostsCS,
       WaterSewerageCostsCS,
       TotalExpenditureSchool,
       TotalTeachingSupportStaffCostsSchool,
       TeachingStaffCostsSchool,
       SupplyTeachingStaffCostsSchool,
       EducationalConsultancyCostsSchool,
       EducationSupportStaffCostsSchool,
       AgencySupplyTeachingStaffCostsSchool,
       TotalNonEducationalSupportStaffCostsSchool,
       AdministrativeClericalStaffCostsSchool,
       AuditorsCostsSchool,
       OtherStaffCostsSchool,
       ProfessionalServicesNonCurriculumCostsSchool,
       TotalEducationalSuppliesCostsSchool,
       ExaminationFeesCostsSchool,
       LearningResourcesNonIctCostsSchool,
       LearningResourcesIctCostsSchool,
       TotalGrossCateringCostsSchool,
       TotalNetCateringCostsSchool,
       CateringStaffCostsSchool,
       CateringSuppliesCostsSchool,
       TotalOtherCostsSchool,
       GroundsMaintenanceCostsSchool,
       IndirectEmployeeExpensesSchool,
       InterestChargesLoanBankSchool,
       OtherInsurancePremiumsCostsSchool,
       PrivateFinanceInitiativeChargesSchool,
       RentRatesCostsSchool,
       SpecialFacilitiesCostsSchool,
       StaffDevelopmentTrainingCostsSchool,
       StaffRelatedInsuranceCostsSchool,
       SupplyTeacherInsurableCostsSchool,
       AdministrativeSuppliesNonEducationalCostsSchool,
       TotalPremisesStaffServiceCostsSchool,
       CleaningCaretakingCostsSchool,
       MaintenancePremisesCostsSchool,
       OtherOccupationCostsSchool,
       PremisesStaffCostsSchool,
       TotalUtilitiesCostsSchool,
       EnergyCostsSchool,
       WaterSewerageCostsSchool,
       EMLBand,
       TotalPupils
FROM VW_TrustFinancialDefault
GO

DROP VIEW IF EXISTS VW_ExpenditureTrustDefaultPercentExpenditure
GO

CREATE VIEW VW_ExpenditureTrustDefaultPercentExpenditure AS
SELECT CompanyNumber,
       RunId,
       IIF(TotalExpenditure != 0, (TotalExpenditure / TotalExpenditure) * 100, NULL) AS 'TotalExpenditure',
       IIF(TotalExpenditure != 0, (TotalTeachingSupportStaffCosts / TotalExpenditure) * 100, NULL) AS 'TotalTeachingSupportStaffCosts',
       IIF(TotalExpenditure != 0, (TeachingStaffCosts / TotalExpenditure) * 100, NULL) AS 'TeachingStaffCosts',
       IIF(TotalExpenditure != 0, (SupplyTeachingStaffCosts / TotalExpenditure) * 100, NULL) AS 'SupplyTeachingStaffCosts',
       IIF(TotalExpenditure != 0, (EducationalConsultancyCosts / TotalExpenditure) * 100, NULL) AS 'EducationalConsultancyCosts',
       IIF(TotalExpenditure != 0, (EducationSupportStaffCosts / TotalExpenditure) * 100, NULL) AS 'EducationSupportStaffCosts',
       IIF(TotalExpenditure != 0, (AgencySupplyTeachingStaffCosts / TotalExpenditure) * 100, NULL) AS 'AgencySupplyTeachingStaffCosts',
       IIF(TotalExpenditure != 0, (TotalNonEducationalSupportStaffCosts / TotalExpenditure) * 100, NULL) AS 'TotalNonEducationalSupportStaffCosts',
       IIF(TotalExpenditure != 0, (AdministrativeClericalStaffCosts / TotalExpenditure) * 100, NULL) AS 'AdministrativeClericalStaffCosts',
       IIF(TotalExpenditure != 0, (AuditorsCosts / TotalExpenditure) * 100, NULL) AS 'AuditorsCosts',
       IIF(TotalExpenditure != 0, (OtherStaffCosts / TotalExpenditure) * 100, NULL) AS 'OtherStaffCosts',
       IIF(TotalExpenditure != 0, (ProfessionalServicesNonCurriculumCosts / TotalExpenditure) * 100, NULL) AS 'ProfessionalServicesNonCurriculumCosts',
       IIF(TotalExpenditure != 0, (TotalEducationalSuppliesCosts / TotalExpenditure) * 100, NULL) AS 'TotalEducationalSuppliesCosts',
       IIF(TotalExpenditure != 0, (ExaminationFeesCosts / TotalExpenditure) * 100, NULL) AS 'ExaminationFeesCosts',
       IIF(TotalExpenditure != 0, (LearningResourcesNonIctCosts / TotalExpenditure) * 100, NULL) AS 'LearningResourcesNonIctCosts',
       IIF(TotalExpenditure != 0, (LearningResourcesIctCosts / TotalExpenditure) * 100, NULL) AS 'LearningResourcesIctCosts',
       IIF(TotalExpenditure != 0, (TotalGrossCateringCosts / TotalExpenditure) * 100, NULL) AS 'TotalGrossCateringCosts',
       IIF(TotalExpenditure != 0, (TotalNetCateringCosts / TotalExpenditure) * 100, NULL) AS 'TotalNetCateringCosts',
       IIF(TotalExpenditure != 0, (CateringStaffCosts / TotalExpenditure) * 100, NULL) AS 'CateringStaffCosts',
       IIF(TotalExpenditure != 0, (CateringSuppliesCosts / TotalExpenditure) * 100, NULL) AS 'CateringSuppliesCosts',
       IIF(TotalExpenditure != 0, (TotalOtherCosts / TotalExpenditure) * 100, NULL) AS 'TotalOtherCosts',
       IIF(TotalExpenditure != 0, (GroundsMaintenanceCosts / TotalExpenditure) * 100, NULL) AS 'GroundsMaintenanceCosts',
       IIF(TotalExpenditure != 0, (IndirectEmployeeExpenses / TotalExpenditure) * 100, NULL) AS 'IndirectEmployeeExpenses',
       IIF(TotalExpenditure != 0, (InterestChargesLoanBank / TotalExpenditure) * 100, NULL) AS 'InterestChargesLoanBank',
       IIF(TotalExpenditure != 0, (OtherInsurancePremiumsCosts / TotalExpenditure) * 100, NULL) AS 'OtherInsurancePremiumsCosts',
       IIF(TotalExpenditure != 0, (PrivateFinanceInitiativeCharges / TotalExpenditure) * 100, NULL) AS 'PrivateFinanceInitiativeCharges',
       IIF(TotalExpenditure != 0, (RentRatesCosts / TotalExpenditure) * 100, NULL) AS 'RentRatesCosts',
       IIF(TotalExpenditure != 0, (SpecialFacilitiesCosts / TotalExpenditure) * 100, NULL) AS 'SpecialFacilitiesCosts',
       IIF(TotalExpenditure != 0, (StaffDevelopmentTrainingCosts / TotalExpenditure) * 100, NULL) AS 'StaffDevelopmentTrainingCosts',
       IIF(TotalExpenditure != 0, (StaffRelatedInsuranceCosts / TotalExpenditure) * 100, NULL) AS 'StaffRelatedInsuranceCosts',
       IIF(TotalExpenditure != 0, (SupplyTeacherInsurableCosts / TotalExpenditure) * 100, NULL) AS 'SupplyTeacherInsurableCosts',
       IIF(TotalExpenditure != 0, (AdministrativeSuppliesNonEducationalCosts / TotalExpenditure) * 100, NULL) AS 'AdministrativeSuppliesNonEducationalCosts',
       IIF(TotalExpenditure != 0, (TotalPremisesStaffServiceCosts / TotalExpenditure) * 100, NULL) AS 'TotalPremisesStaffServiceCosts',
       IIF(TotalExpenditure != 0, (CleaningCaretakingCosts / TotalExpenditure) * 100, NULL) AS 'CleaningCaretakingCosts',
       IIF(TotalExpenditure != 0, (MaintenancePremisesCosts / TotalExpenditure) * 100, NULL) AS 'MaintenancePremisesCosts',
       IIF(TotalExpenditure != 0, (OtherOccupationCosts / TotalExpenditure) * 100, NULL) AS 'OtherOccupationCosts',
       IIF(TotalExpenditure != 0, (PremisesStaffCosts / TotalExpenditure) * 100, NULL) AS 'PremisesStaffCosts',
       IIF(TotalExpenditure != 0, (TotalUtilitiesCosts / TotalExpenditure) * 100, NULL) AS 'TotalUtilitiesCosts',
       IIF(TotalExpenditure != 0, (EnergyCosts / TotalExpenditure) * 100, NULL) AS 'EnergyCosts',
       IIF(TotalExpenditure != 0, (WaterSewerageCosts / TotalExpenditure) * 100, NULL) AS 'WaterSewerageCosts',
       IIF(TotalExpenditureCS != 0, (TotalExpenditureCS / TotalExpenditureCS) * 100, NULL) AS 'TotalExpenditureCS',
       IIF(TotalExpenditureCS != 0, (TotalTeachingSupportStaffCostsCS / TotalExpenditureCS) * 100, NULL) AS 'TotalTeachingSupportStaffCostsCS',
       IIF(TotalExpenditureCS != 0, (TeachingStaffCostsCS / TotalExpenditureCS) * 100, NULL) AS 'TeachingStaffCostsCS',
       IIF(TotalExpenditureCS != 0, (SupplyTeachingStaffCostsCS / TotalExpenditureCS) * 100, NULL) AS 'SupplyTeachingStaffCostsCS',
       IIF(TotalExpenditureCS != 0, (EducationalConsultancyCostsCS / TotalExpenditureCS) * 100, NULL) AS 'EducationalConsultancyCostsCS',
       IIF(TotalExpenditureCS != 0, (EducationSupportStaffCostsCS / TotalExpenditureCS) * 100, NULL) AS 'EducationSupportStaffCostsCS',
       IIF(TotalExpenditureCS != 0, (AgencySupplyTeachingStaffCostsCS / TotalExpenditureCS) * 100, NULL) AS 'AgencySupplyTeachingStaffCostsCS',
       IIF(TotalExpenditureCS != 0, (TotalNonEducationalSupportStaffCostsCS / TotalExpenditureCS) * 100, NULL) AS 'TotalNonEducationalSupportStaffCostsCS',
       IIF(TotalExpenditureCS != 0, (AdministrativeClericalStaffCostsCS / TotalExpenditureCS) * 100, NULL) AS 'AdministrativeClericalStaffCostsCS',
       IIF(TotalExpenditureCS != 0, (AuditorsCostsCS / TotalExpenditureCS) * 100, NULL) AS 'AuditorsCostsCS',
       IIF(TotalExpenditureCS != 0, (OtherStaffCostsCS / TotalExpenditureCS) * 100, NULL) AS 'OtherStaffCostsCS',
       IIF(TotalExpenditureCS != 0, (ProfessionalServicesNonCurriculumCostsCS / TotalExpenditureCS) * 100, NULL) AS 'ProfessionalServicesNonCurriculumCostsCS',
       IIF(TotalExpenditureCS != 0, (TotalEducationalSuppliesCostsCS / TotalExpenditureCS) * 100, NULL) AS 'TotalEducationalSuppliesCostsCS',
       IIF(TotalExpenditureCS != 0, (ExaminationFeesCostsCS / TotalExpenditureCS) * 100, NULL) AS 'ExaminationFeesCostsCS',
       IIF(TotalExpenditureCS != 0, (LearningResourcesNonIctCostsCS / TotalExpenditureCS) * 100, NULL) AS 'LearningResourcesNonIctCostsCS',
       IIF(TotalExpenditureCS != 0, (LearningResourcesIctCostsCS / TotalExpenditureCS) * 100, NULL) AS 'LearningResourcesIctCostsCS',
       IIF(TotalExpenditureCS != 0, (TotalGrossCateringCostsCS / TotalExpenditureCS) * 100, NULL) AS 'TotalGrossCateringCostsCS',
       IIF(TotalExpenditureCS != 0, (TotalNetCateringCostsCS / TotalExpenditureCS) * 100, NULL) AS 'TotalNetCateringCostsCS',
       IIF(TotalExpenditureCS != 0, (CateringStaffCostsCS / TotalExpenditureCS) * 100, NULL) AS 'CateringStaffCostsCS',
       IIF(TotalExpenditureCS != 0, (CateringSuppliesCostsCS / TotalExpenditureCS) * 100, NULL) AS 'CateringSuppliesCostsCS',
       IIF(TotalExpenditureCS != 0, (TotalOtherCostsCS / TotalExpenditureCS) * 100, NULL) AS 'TotalOtherCostsCS',
       IIF(TotalExpenditureCS != 0, (GroundsMaintenanceCostsCS / TotalExpenditureCS) * 100, NULL) AS 'GroundsMaintenanceCostsCS',
       IIF(TotalExpenditureCS != 0, (IndirectEmployeeExpensesCS / TotalExpenditureCS) * 100, NULL) AS 'IndirectEmployeeExpensesCS',
       IIF(TotalExpenditureCS != 0, (InterestChargesLoanBankCS / TotalExpenditureCS) * 100, NULL) AS 'InterestChargesLoanBankCS',
       IIF(TotalExpenditureCS != 0, (OtherInsurancePremiumsCostsCS / TotalExpenditureCS) * 100, NULL) AS 'OtherInsurancePremiumsCostsCS',
       IIF(TotalExpenditureCS != 0, (PrivateFinanceInitiativeChargesCS / TotalExpenditureCS) * 100, NULL) AS 'PrivateFinanceInitiativeChargesCS',
       IIF(TotalExpenditureCS != 0, (RentRatesCostsCS / TotalExpenditureCS) * 100, NULL) AS 'RentRatesCostsCS',
       IIF(TotalExpenditureCS != 0, (SpecialFacilitiesCostsCS / TotalExpenditureCS) * 100, NULL) AS 'SpecialFacilitiesCostsCS',
       IIF(TotalExpenditureCS != 0, (StaffDevelopmentTrainingCostsCS / TotalExpenditureCS) * 100, NULL) AS 'StaffDevelopmentTrainingCostsCS',
       IIF(TotalExpenditureCS != 0, (StaffRelatedInsuranceCostsCS / TotalExpenditureCS) * 100, NULL) AS 'StaffRelatedInsuranceCostsCS',
       IIF(TotalExpenditureCS != 0, (SupplyTeacherInsurableCostsCS / TotalExpenditureCS) * 100, NULL) AS 'SupplyTeacherInsurableCostsCS',
       IIF(TotalExpenditureCS != 0, (AdministrativeSuppliesNonEducationalCostsCS / TotalExpenditureCS) * 100, NULL) AS 'AdministrativeSuppliesNonEducationalCostsCS',
       IIF(TotalExpenditureCS != 0, (TotalPremisesStaffServiceCostsCS / TotalExpenditureCS) * 100, NULL) AS 'TotalPremisesStaffServiceCostsCS',
       IIF(TotalExpenditureCS != 0, (CleaningCaretakingCostsCS / TotalExpenditureCS) * 100, NULL) AS 'CleaningCaretakingCostsCS',
       IIF(TotalExpenditureCS != 0, (MaintenancePremisesCostsCS / TotalExpenditureCS) * 100, NULL) AS 'MaintenancePremisesCostsCS',
       IIF(TotalExpenditureCS != 0, (OtherOccupationCostsCS / TotalExpenditureCS) * 100, NULL) AS 'OtherOccupationCostsCS',
       IIF(TotalExpenditureCS != 0, (PremisesStaffCostsCS / TotalExpenditureCS) * 100, NULL) AS 'PremisesStaffCostsCS',
       IIF(TotalExpenditureCS != 0, (TotalUtilitiesCostsCS / TotalExpenditureCS) * 100, NULL) AS 'TotalUtilitiesCostsCS',
       IIF(TotalExpenditureCS != 0, (EnergyCostsCS / TotalExpenditureCS) * 100, NULL) AS 'EnergyCostsCS',
       IIF(TotalExpenditureCS != 0, (WaterSewerageCostsCS / TotalExpenditureCS) * 100, NULL) AS 'WaterSewerageCostsCS',
       IIF(TotalExpenditureSchool != 0, (TotalExpenditureSchool / TotalExpenditureSchool) * 100, NULL) AS 'TotalExpenditureSchool',
       IIF(TotalExpenditureSchool != 0, (TotalTeachingSupportStaffCostsSchool / TotalExpenditureSchool) * 100, NULL) AS 'TotalTeachingSupportStaffCostsSchool',
       IIF(TotalExpenditureSchool != 0, (TeachingStaffCostsSchool / TotalExpenditureSchool) * 100, NULL) AS 'TeachingStaffCostsSchool',
       IIF(TotalExpenditureSchool != 0, (SupplyTeachingStaffCostsSchool / TotalExpenditureSchool) * 100, NULL) AS 'SupplyTeachingStaffCostsSchool',
       IIF(TotalExpenditureSchool != 0, (EducationalConsultancyCostsSchool / TotalExpenditureSchool) * 100, NULL) AS 'EducationalConsultancyCostsSchool',
       IIF(TotalExpenditureSchool != 0, (EducationSupportStaffCostsSchool / TotalExpenditureSchool) * 100, NULL) AS 'EducationSupportStaffCostsSchool',
       IIF(TotalExpenditureSchool != 0, (AgencySupplyTeachingStaffCostsSchool / TotalExpenditureSchool) * 100, NULL) AS 'AgencySupplyTeachingStaffCostsSchool',
       IIF(TotalExpenditureSchool != 0, (TotalNonEducationalSupportStaffCostsSchool / TotalExpenditureSchool) * 100, NULL) AS 'TotalNonEducationalSupportStaffCostsSchool',
       IIF(TotalExpenditureSchool != 0, (AdministrativeClericalStaffCostsSchool / TotalExpenditureSchool) * 100, NULL) AS 'AdministrativeClericalStaffCostsSchool',
       IIF(TotalExpenditureSchool != 0, (AuditorsCostsSchool / TotalExpenditureSchool) * 100, NULL) AS 'AuditorsCostsSchool',
       IIF(TotalExpenditureSchool != 0, (OtherStaffCostsSchool / TotalExpenditureSchool) * 100, NULL) AS 'OtherStaffCostsSchool',
       IIF(TotalExpenditureSchool != 0, (ProfessionalServicesNonCurriculumCostsSchool / TotalExpenditureSchool) * 100, NULL) AS 'ProfessionalServicesNonCurriculumCostsSchool',
       IIF(TotalExpenditureSchool != 0, (TotalEducationalSuppliesCostsSchool / TotalExpenditureSchool) * 100, NULL) AS 'TotalEducationalSuppliesCostsSchool',
       IIF(TotalExpenditureSchool != 0, (ExaminationFeesCostsSchool / TotalExpenditureSchool) * 100, NULL) AS 'ExaminationFeesCostsSchool',
       IIF(TotalExpenditureSchool != 0, (LearningResourcesNonIctCostsSchool / TotalExpenditureSchool) * 100, NULL) AS 'LearningResourcesNonIctCostsSchool',
       IIF(TotalExpenditureSchool != 0, (LearningResourcesIctCostsSchool / TotalExpenditureSchool) * 100, NULL) AS 'LearningResourcesIctCostsSchool',
       IIF(TotalExpenditureSchool != 0, (TotalGrossCateringCostsSchool / TotalExpenditureSchool) * 100, NULL) AS 'TotalGrossCateringCostsSchool',
       IIF(TotalExpenditureSchool != 0, (TotalNetCateringCostsSchool / TotalExpenditureSchool) * 100, NULL) AS 'TotalNetCateringCostsSchool',
       IIF(TotalExpenditureSchool != 0, (CateringStaffCostsSchool / TotalExpenditureSchool) * 100, NULL) AS 'CateringStaffCostsSchool',
       IIF(TotalExpenditureSchool != 0, (CateringSuppliesCostsSchool / TotalExpenditureSchool) * 100, NULL) AS 'CateringSuppliesCostsSchool',
       IIF(TotalExpenditureSchool != 0, (TotalOtherCostsSchool / TotalExpenditureSchool) * 100, NULL) AS 'TotalOtherCostsSchool',
       IIF(TotalExpenditureSchool != 0, (GroundsMaintenanceCostsSchool / TotalExpenditureSchool) * 100, NULL) AS 'GroundsMaintenanceCostsSchool',
       IIF(TotalExpenditureSchool != 0, (IndirectEmployeeExpensesSchool / TotalExpenditureSchool) * 100, NULL) AS 'IndirectEmployeeExpensesSchool',
       IIF(TotalExpenditureSchool != 0, (InterestChargesLoanBankSchool / TotalExpenditureSchool) * 100, NULL) AS 'InterestChargesLoanBankSchool',
       IIF(TotalExpenditureSchool != 0, (OtherInsurancePremiumsCostsSchool / TotalExpenditureSchool) * 100, NULL) AS 'OtherInsurancePremiumsCostsSchool',
       IIF(TotalExpenditureSchool != 0, (PrivateFinanceInitiativeChargesSchool / TotalExpenditureSchool) * 100, NULL) AS 'PrivateFinanceInitiativeChargesSchool',
       IIF(TotalExpenditureSchool != 0, (RentRatesCostsSchool / TotalExpenditureSchool) * 100, NULL) AS 'RentRatesCostsSchool',
       IIF(TotalExpenditureSchool != 0, (SpecialFacilitiesCostsSchool / TotalExpenditureSchool) * 100, NULL) AS 'SpecialFacilitiesCostsSchool',
       IIF(TotalExpenditureSchool != 0, (StaffDevelopmentTrainingCostsSchool / TotalExpenditureSchool) * 100, NULL) AS 'StaffDevelopmentTrainingCostsSchool',
       IIF(TotalExpenditureSchool != 0, (StaffRelatedInsuranceCostsSchool / TotalExpenditureSchool) * 100, NULL) AS 'StaffRelatedInsuranceCostsSchool',
       IIF(TotalExpenditureSchool != 0, (SupplyTeacherInsurableCostsSchool / TotalExpenditureSchool) * 100, NULL) AS 'SupplyTeacherInsurableCostsSchool',
       IIF(TotalExpenditureSchool != 0, (AdministrativeSuppliesNonEducationalCostsSchool / TotalExpenditureSchool) * 100, NULL) AS 'AdministrativeSuppliesNonEducationalCostsSchool',
       IIF(TotalExpenditureSchool != 0, (TotalPremisesStaffServiceCostsSchool / TotalExpenditureSchool) * 100, NULL) AS 'TotalPremisesStaffServiceCostsSchool',
       IIF(TotalExpenditureSchool != 0, (CleaningCaretakingCostsSchool / TotalExpenditureSchool) * 100, NULL) AS 'CleaningCaretakingCostsSchool',
       IIF(TotalExpenditureSchool != 0, (MaintenancePremisesCostsSchool / TotalExpenditureSchool) * 100, NULL) AS 'MaintenancePremisesCostsSchool',
       IIF(TotalExpenditureSchool != 0, (OtherOccupationCostsSchool / TotalExpenditureSchool) * 100, NULL) AS 'OtherOccupationCostsSchool',
       IIF(TotalExpenditureSchool != 0, (PremisesStaffCostsSchool / TotalExpenditureSchool) * 100, NULL) AS 'PremisesStaffCostsSchool',
       IIF(TotalExpenditureSchool != 0, (TotalUtilitiesCostsSchool / TotalExpenditureSchool) * 100, NULL) AS 'TotalUtilitiesCostsSchool',
       IIF(TotalExpenditureSchool != 0, (EnergyCostsSchool / TotalExpenditureSchool) * 100, NULL) AS 'EnergyCostsSchool',
       IIF(TotalExpenditureSchool != 0, (WaterSewerageCostsSchool / TotalExpenditureSchool) * 100, NULL) AS 'WaterSewerageCostsSchool',
       EMLBand,
       TotalPupils
FROM VW_TrustFinancialDefault
GO

DROP VIEW IF EXISTS VW_ExpenditureTrustDefaultPercentIncome
GO

CREATE VIEW VW_ExpenditureTrustDefaultPercentIncome AS
SELECT CompanyNumber,
       RunId,
       IIF(TotalIncome != 0, (TotalExpenditure / TotalIncome) * 100, NULL) AS 'TotalExpenditure',
       IIF(TotalIncome != 0, (TotalTeachingSupportStaffCosts / TotalIncome) * 100, NULL) AS 'TotalTeachingSupportStaffCosts',
       IIF(TotalIncome != 0, (TeachingStaffCosts / TotalIncome) * 100, NULL) AS 'TeachingStaffCosts',
       IIF(TotalIncome != 0, (SupplyTeachingStaffCosts / TotalIncome) * 100, NULL) AS 'SupplyTeachingStaffCosts',
       IIF(TotalIncome != 0, (EducationalConsultancyCosts / TotalIncome) * 100, NULL) AS 'EducationalConsultancyCosts',
       IIF(TotalIncome != 0, (EducationSupportStaffCosts / TotalIncome) * 100, NULL) AS 'EducationSupportStaffCosts',
       IIF(TotalIncome != 0, (AgencySupplyTeachingStaffCosts / TotalIncome) * 100, NULL) AS 'AgencySupplyTeachingStaffCosts',
       IIF(TotalIncome != 0, (TotalNonEducationalSupportStaffCosts / TotalIncome) * 100, NULL) AS 'TotalNonEducationalSupportStaffCosts',
       IIF(TotalIncome != 0, (AdministrativeClericalStaffCosts / TotalIncome) * 100, NULL) AS 'AdministrativeClericalStaffCosts',
       IIF(TotalIncome != 0, (AuditorsCosts / TotalIncome) * 100, NULL) AS 'AuditorsCosts',
       IIF(TotalIncome != 0, (OtherStaffCosts / TotalIncome) * 100, NULL) AS 'OtherStaffCosts',
       IIF(TotalIncome != 0, (ProfessionalServicesNonCurriculumCosts / TotalIncome) * 100, NULL) AS 'ProfessionalServicesNonCurriculumCosts',
       IIF(TotalIncome != 0, (TotalEducationalSuppliesCosts / TotalIncome) * 100, NULL) AS 'TotalEducationalSuppliesCosts',
       IIF(TotalIncome != 0, (ExaminationFeesCosts / TotalIncome) * 100, NULL) AS 'ExaminationFeesCosts',
       IIF(TotalIncome != 0, (LearningResourcesNonIctCosts / TotalIncome) * 100, NULL) AS 'LearningResourcesNonIctCosts',
       IIF(TotalIncome != 0, (LearningResourcesIctCosts / TotalIncome) * 100, NULL) AS 'LearningResourcesIctCosts',
       IIF(TotalIncome != 0, (TotalGrossCateringCosts / TotalIncome) * 100, NULL) AS 'TotalGrossCateringCosts',
       IIF(TotalIncome != 0, (TotalNetCateringCosts / TotalIncome) * 100, NULL) AS 'TotalNetCateringCosts',
       IIF(TotalIncome != 0, (CateringStaffCosts / TotalIncome) * 100, NULL) AS 'CateringStaffCosts',
       IIF(TotalIncome != 0, (CateringSuppliesCosts / TotalIncome) * 100, NULL) AS 'CateringSuppliesCosts',
       IIF(TotalIncome != 0, (TotalOtherCosts / TotalIncome) * 100, NULL) AS 'TotalOtherCosts',
       IIF(TotalIncome != 0, (GroundsMaintenanceCosts / TotalIncome) * 100, NULL) AS 'GroundsMaintenanceCosts',
       IIF(TotalIncome != 0, (IndirectEmployeeExpenses / TotalIncome) * 100, NULL) AS 'IndirectEmployeeExpenses',
       IIF(TotalIncome != 0, (InterestChargesLoanBank / TotalIncome) * 100, NULL) AS 'InterestChargesLoanBank',
       IIF(TotalIncome != 0, (OtherInsurancePremiumsCosts / TotalIncome) * 100, NULL) AS 'OtherInsurancePremiumsCosts',
       IIF(TotalIncome != 0, (PrivateFinanceInitiativeCharges / TotalIncome) * 100, NULL) AS 'PrivateFinanceInitiativeCharges',
       IIF(TotalIncome != 0, (RentRatesCosts / TotalIncome) * 100, NULL) AS 'RentRatesCosts',
       IIF(TotalIncome != 0, (SpecialFacilitiesCosts / TotalIncome) * 100, NULL) AS 'SpecialFacilitiesCosts',
       IIF(TotalIncome != 0, (StaffDevelopmentTrainingCosts / TotalIncome) * 100, NULL) AS 'StaffDevelopmentTrainingCosts',
       IIF(TotalIncome != 0, (StaffRelatedInsuranceCosts / TotalIncome) * 100, NULL) AS 'StaffRelatedInsuranceCosts',
       IIF(TotalIncome != 0, (SupplyTeacherInsurableCosts / TotalIncome) * 100, NULL) AS 'SupplyTeacherInsurableCosts',
       IIF(TotalIncome != 0, (AdministrativeSuppliesNonEducationalCosts / TotalIncome) * 100, NULL) AS 'AdministrativeSuppliesNonEducationalCosts',
       IIF(TotalIncome != 0, (TotalPremisesStaffServiceCosts / TotalIncome) * 100, NULL) AS 'TotalPremisesStaffServiceCosts',
       IIF(TotalIncome != 0, (CleaningCaretakingCosts / TotalIncome) * 100, NULL) AS 'CleaningCaretakingCosts',
       IIF(TotalIncome != 0, (MaintenancePremisesCosts / TotalIncome) * 100, NULL) AS 'MaintenancePremisesCosts',
       IIF(TotalIncome != 0, (OtherOccupationCosts / TotalIncome) * 100, NULL) AS 'OtherOccupationCosts',
       IIF(TotalIncome != 0, (PremisesStaffCosts / TotalIncome) * 100, NULL) AS 'PremisesStaffCosts',
       IIF(TotalIncome != 0, (TotalUtilitiesCosts / TotalIncome) * 100, NULL) AS 'TotalUtilitiesCosts',
       IIF(TotalIncome != 0, (EnergyCosts / TotalIncome) * 100, NULL) AS 'EnergyCosts',
       IIF(TotalIncome != 0, (WaterSewerageCosts / TotalIncome) * 100, NULL) AS 'WaterSewerageCosts',
       IIF(TotalIncomeCS != 0, (TotalExpenditureCS / TotalIncomeCS) * 100, NULL) AS 'TotalExpenditureCS',
       IIF(TotalIncomeCS != 0, (TotalTeachingSupportStaffCostsCS / TotalIncomeCS) * 100, NULL) AS 'TotalTeachingSupportStaffCostsCS',
       IIF(TotalIncomeCS != 0, (TeachingStaffCostsCS / TotalIncomeCS) * 100, NULL) AS 'TeachingStaffCostsCS',
       IIF(TotalIncomeCS != 0, (SupplyTeachingStaffCostsCS / TotalIncomeCS) * 100, NULL) AS 'SupplyTeachingStaffCostsCS',
       IIF(TotalIncomeCS != 0, (EducationalConsultancyCostsCS / TotalIncomeCS) * 100, NULL) AS 'EducationalConsultancyCostsCS',
       IIF(TotalIncomeCS != 0, (EducationSupportStaffCostsCS / TotalIncomeCS) * 100, NULL) AS 'EducationSupportStaffCostsCS',
       IIF(TotalIncomeCS != 0, (AgencySupplyTeachingStaffCostsCS / TotalIncomeCS) * 100, NULL) AS 'AgencySupplyTeachingStaffCostsCS',
       IIF(TotalIncomeCS != 0, (TotalNonEducationalSupportStaffCostsCS / TotalIncomeCS) * 100, NULL) AS 'TotalNonEducationalSupportStaffCostsCS',
       IIF(TotalIncomeCS != 0, (AdministrativeClericalStaffCostsCS / TotalIncomeCS) * 100, NULL) AS 'AdministrativeClericalStaffCostsCS',
       IIF(TotalIncomeCS != 0, (AuditorsCostsCS / TotalIncomeCS) * 100, NULL) AS 'AuditorsCostsCS',
       IIF(TotalIncomeCS != 0, (OtherStaffCostsCS / TotalIncomeCS) * 100, NULL) AS 'OtherStaffCostsCS',
       IIF(TotalIncomeCS != 0, (ProfessionalServicesNonCurriculumCostsCS / TotalIncomeCS) * 100, NULL) AS 'ProfessionalServicesNonCurriculumCostsCS',
       IIF(TotalIncomeCS != 0, (TotalEducationalSuppliesCostsCS / TotalIncomeCS) * 100, NULL) AS 'TotalEducationalSuppliesCostsCS',
       IIF(TotalIncomeCS != 0, (ExaminationFeesCostsCS / TotalIncomeCS) * 100, NULL) AS 'ExaminationFeesCostsCS',
       IIF(TotalIncomeCS != 0, (LearningResourcesNonIctCostsCS / TotalIncomeCS) * 100, NULL) AS 'LearningResourcesNonIctCostsCS',
       IIF(TotalIncomeCS != 0, (LearningResourcesIctCostsCS / TotalIncomeCS) * 100, NULL) AS 'LearningResourcesIctCostsCS',
       IIF(TotalIncomeCS != 0, (TotalGrossCateringCostsCS / TotalIncomeCS) * 100, NULL) AS 'TotalGrossCateringCostsCS',
       IIF(TotalIncomeCS != 0, (TotalNetCateringCostsCS / TotalIncomeCS) * 100, NULL) AS 'TotalNetCateringCostsCS',
       IIF(TotalIncomeCS != 0, (CateringStaffCostsCS / TotalIncomeCS) * 100, NULL) AS 'CateringStaffCostsCS',
       IIF(TotalIncomeCS != 0, (CateringSuppliesCostsCS / TotalIncomeCS) * 100, NULL) AS 'CateringSuppliesCostsCS',
       IIF(TotalIncomeCS != 0, (TotalOtherCostsCS / TotalIncomeCS) * 100, NULL) AS 'TotalOtherCostsCS',
       IIF(TotalIncomeCS != 0, (GroundsMaintenanceCostsCS / TotalIncomeCS) * 100, NULL) AS 'GroundsMaintenanceCostsCS',
       IIF(TotalIncomeCS != 0, (IndirectEmployeeExpensesCS / TotalIncomeCS) * 100, NULL) AS 'IndirectEmployeeExpensesCS',
       IIF(TotalIncomeCS != 0, (InterestChargesLoanBankCS / TotalIncomeCS) * 100, NULL) AS 'InterestChargesLoanBankCS',
       IIF(TotalIncomeCS != 0, (OtherInsurancePremiumsCostsCS / TotalIncomeCS) * 100, NULL) AS 'OtherInsurancePremiumsCostsCS',
       IIF(TotalIncomeCS != 0, (PrivateFinanceInitiativeChargesCS / TotalIncomeCS) * 100, NULL) AS 'PrivateFinanceInitiativeChargesCS',
       IIF(TotalIncomeCS != 0, (RentRatesCostsCS / TotalIncomeCS) * 100, NULL) AS 'RentRatesCostsCS',
       IIF(TotalIncomeCS != 0, (SpecialFacilitiesCostsCS / TotalIncomeCS) * 100, NULL) AS 'SpecialFacilitiesCostsCS',
       IIF(TotalIncomeCS != 0, (StaffDevelopmentTrainingCostsCS / TotalIncomeCS) * 100, NULL) AS 'StaffDevelopmentTrainingCostsCS',
       IIF(TotalIncomeCS != 0, (StaffRelatedInsuranceCostsCS / TotalIncomeCS) * 100, NULL) AS 'StaffRelatedInsuranceCostsCS',
       IIF(TotalIncomeCS != 0, (SupplyTeacherInsurableCostsCS / TotalIncomeCS) * 100, NULL) AS 'SupplyTeacherInsurableCostsCS',
       IIF(TotalIncomeCS != 0, (AdministrativeSuppliesNonEducationalCostsCS / TotalIncomeCS) * 100, NULL) AS 'AdministrativeSuppliesNonEducationalCostsCS',
       IIF(TotalIncomeCS != 0, (TotalPremisesStaffServiceCostsCS / TotalIncomeCS) * 100, NULL) AS 'TotalPremisesStaffServiceCostsCS',
       IIF(TotalIncomeCS != 0, (CleaningCaretakingCostsCS / TotalIncomeCS) * 100, NULL) AS 'CleaningCaretakingCostsCS',
       IIF(TotalIncomeCS != 0, (MaintenancePremisesCostsCS / TotalIncomeCS) * 100, NULL) AS 'MaintenancePremisesCostsCS',
       IIF(TotalIncomeCS != 0, (OtherOccupationCostsCS / TotalIncomeCS) * 100, NULL) AS 'OtherOccupationCostsCS',
       IIF(TotalIncomeCS != 0, (PremisesStaffCostsCS / TotalIncomeCS) * 100, NULL) AS 'PremisesStaffCostsCS',
       IIF(TotalIncomeCS != 0, (TotalUtilitiesCostsCS / TotalIncomeCS) * 100, NULL) AS 'TotalUtilitiesCostsCS',
       IIF(TotalIncomeCS != 0, (EnergyCostsCS / TotalIncomeCS) * 100, NULL) AS 'EnergyCostsCS',
       IIF(TotalIncomeCS != 0, (WaterSewerageCostsCS / TotalIncomeCS) * 100, NULL) AS 'WaterSewerageCostsCS',
       IIF(TotalIncomeSchool != 0, (TotalExpenditureSchool / TotalIncomeSchool) * 100, NULL) AS 'TotalExpenditureSchool',
       IIF(TotalIncomeSchool != 0, (TotalTeachingSupportStaffCostsSchool / TotalIncomeSchool) * 100, NULL) AS 'TotalTeachingSupportStaffCostsSchool',
       IIF(TotalIncomeSchool != 0, (TeachingStaffCostsSchool / TotalIncomeSchool) * 100, NULL) AS 'TeachingStaffCostsSchool',
       IIF(TotalIncomeSchool != 0, (SupplyTeachingStaffCostsSchool / TotalIncomeSchool) * 100, NULL) AS 'SupplyTeachingStaffCostsSchool',
       IIF(TotalIncomeSchool != 0, (EducationalConsultancyCostsSchool / TotalIncomeSchool) * 100, NULL) AS 'EducationalConsultancyCostsSchool',
       IIF(TotalIncomeSchool != 0, (EducationSupportStaffCostsSchool / TotalIncomeSchool) * 100, NULL) AS 'EducationSupportStaffCostsSchool',
       IIF(TotalIncomeSchool != 0, (AgencySupplyTeachingStaffCostsSchool / TotalIncomeSchool) * 100, NULL) AS 'AgencySupplyTeachingStaffCostsSchool',
       IIF(TotalIncomeSchool != 0, (TotalNonEducationalSupportStaffCostsSchool / TotalIncomeSchool) * 100, NULL) AS 'TotalNonEducationalSupportStaffCostsSchool',
       IIF(TotalIncomeSchool != 0, (AdministrativeClericalStaffCostsSchool / TotalIncomeSchool) * 100, NULL) AS 'AdministrativeClericalStaffCostsSchool',
       IIF(TotalIncomeSchool != 0, (AuditorsCostsSchool / TotalIncomeSchool) * 100, NULL) AS 'AuditorsCostsSchool',
       IIF(TotalIncomeSchool != 0, (OtherStaffCostsSchool / TotalIncomeSchool) * 100, NULL) AS 'OtherStaffCostsSchool',
       IIF(TotalIncomeSchool != 0, (ProfessionalServicesNonCurriculumCostsSchool / TotalIncomeSchool) * 100, NULL) AS 'ProfessionalServicesNonCurriculumCostsSchool',
       IIF(TotalIncomeSchool != 0, (TotalEducationalSuppliesCostsSchool / TotalIncomeSchool) * 100, NULL) AS 'TotalEducationalSuppliesCostsSchool',
       IIF(TotalIncomeSchool != 0, (ExaminationFeesCostsSchool / TotalIncomeSchool) * 100, NULL) AS 'ExaminationFeesCostsSchool',
       IIF(TotalIncomeSchool != 0, (LearningResourcesNonIctCostsSchool / TotalIncomeSchool) * 100, NULL) AS 'LearningResourcesNonIctCostsSchool',
       IIF(TotalIncomeSchool != 0, (LearningResourcesIctCostsSchool / TotalIncomeSchool) * 100, NULL) AS 'LearningResourcesIctCostsSchool',
       IIF(TotalIncomeSchool != 0, (TotalGrossCateringCostsSchool / TotalIncomeSchool) * 100, NULL) AS 'TotalGrossCateringCostsSchool',
       IIF(TotalIncomeSchool != 0, (TotalNetCateringCostsSchool / TotalIncomeSchool) * 100, NULL) AS 'TotalNetCateringCostsSchool',
       IIF(TotalIncomeSchool != 0, (CateringStaffCostsSchool / TotalIncomeSchool) * 100, NULL) AS 'CateringStaffCostsSchool',
       IIF(TotalIncomeSchool != 0, (CateringSuppliesCostsSchool / TotalIncomeSchool) * 100, NULL) AS 'CateringSuppliesCostsSchool',
       IIF(TotalIncomeSchool != 0, (TotalOtherCostsSchool / TotalIncomeSchool) * 100, NULL) AS 'TotalOtherCostsSchool',
       IIF(TotalIncomeSchool != 0, (GroundsMaintenanceCostsSchool / TotalIncomeSchool) * 100, NULL) AS 'GroundsMaintenanceCostsSchool',
       IIF(TotalIncomeSchool != 0, (IndirectEmployeeExpensesSchool / TotalIncomeSchool) * 100, NULL) AS 'IndirectEmployeeExpensesSchool',
       IIF(TotalIncomeSchool != 0, (InterestChargesLoanBankSchool / TotalIncomeSchool) * 100, NULL) AS 'InterestChargesLoanBankSchool',
       IIF(TotalIncomeSchool != 0, (OtherInsurancePremiumsCostsSchool / TotalIncomeSchool) * 100, NULL) AS 'OtherInsurancePremiumsCostsSchool',
       IIF(TotalIncomeSchool != 0, (PrivateFinanceInitiativeChargesSchool / TotalIncomeSchool) * 100, NULL) AS 'PrivateFinanceInitiativeChargesSchool',
       IIF(TotalIncomeSchool != 0, (RentRatesCostsSchool / TotalIncomeSchool) * 100, NULL) AS 'RentRatesCostsSchool',
       IIF(TotalIncomeSchool != 0, (SpecialFacilitiesCostsSchool / TotalIncomeSchool) * 100, NULL) AS 'SpecialFacilitiesCostsSchool',
       IIF(TotalIncomeSchool != 0, (StaffDevelopmentTrainingCostsSchool / TotalIncomeSchool) * 100, NULL) AS 'StaffDevelopmentTrainingCostsSchool',
       IIF(TotalIncomeSchool != 0, (StaffRelatedInsuranceCostsSchool / TotalIncomeSchool) * 100, NULL) AS 'StaffRelatedInsuranceCostsSchool',
       IIF(TotalIncomeSchool != 0, (SupplyTeacherInsurableCostsSchool / TotalIncomeSchool) * 100, NULL) AS 'SupplyTeacherInsurableCostsSchool',
       IIF(TotalIncomeSchool != 0, (AdministrativeSuppliesNonEducationalCostsSchool / TotalIncomeSchool) * 100, NULL) AS 'AdministrativeSuppliesNonEducationalCostsSchool',
       IIF(TotalIncomeSchool != 0, (TotalPremisesStaffServiceCostsSchool / TotalIncomeSchool) * 100, NULL) AS 'TotalPremisesStaffServiceCostsSchool',
       IIF(TotalIncomeSchool != 0, (CleaningCaretakingCostsSchool / TotalIncomeSchool) * 100, NULL) AS 'CleaningCaretakingCostsSchool',
       IIF(TotalIncomeSchool != 0, (MaintenancePremisesCostsSchool / TotalIncomeSchool) * 100, NULL) AS 'MaintenancePremisesCostsSchool',
       IIF(TotalIncomeSchool != 0, (OtherOccupationCostsSchool / TotalIncomeSchool) * 100, NULL) AS 'OtherOccupationCostsSchool',
       IIF(TotalIncomeSchool != 0, (PremisesStaffCostsSchool / TotalIncomeSchool) * 100, NULL) AS 'PremisesStaffCostsSchool',
       IIF(TotalIncomeSchool != 0, (TotalUtilitiesCostsSchool / TotalIncomeSchool) * 100, NULL) AS 'TotalUtilitiesCostsSchool',
       IIF(TotalIncomeSchool != 0, (EnergyCostsSchool / TotalIncomeSchool) * 100, NULL) AS 'EnergyCostsSchool',
       IIF(TotalIncomeSchool != 0, (WaterSewerageCostsSchool / TotalIncomeSchool) * 100, NULL) AS 'WaterSewerageCostsSchool',
       EMLBand,
       TotalPupils
FROM VW_TrustFinancialDefault
GO

DROP VIEW IF EXISTS VW_ExpenditureTrustDefaultPerUnit
GO

CREATE VIEW VW_ExpenditureTrustDefaultPerUnit AS
SELECT CompanyNumber,
       RunId,
       IIF(TotalPupils != 0, TotalExpenditure / TotalPupils, NULL) AS 'TotalExpenditure',
       IIF(TotalPupils != 0, TotalTeachingSupportStaffCosts / TotalPupils, NULL) AS 'TotalTeachingSupportStaffCosts',
       IIF(TotalPupils != 0, TeachingStaffCosts / TotalPupils, NULL) AS 'TeachingStaffCosts',
       IIF(TotalPupils != 0, SupplyTeachingStaffCosts / TotalPupils, NULL) AS 'SupplyTeachingStaffCosts',
       IIF(TotalPupils != 0, EducationalConsultancyCosts / TotalPupils, NULL) AS 'EducationalConsultancyCosts',
       IIF(TotalPupils != 0, EducationSupportStaffCosts / TotalPupils, NULL) AS 'EducationSupportStaffCosts',
       IIF(TotalPupils != 0, AgencySupplyTeachingStaffCosts / TotalPupils, NULL) AS 'AgencySupplyTeachingStaffCosts',
       IIF(TotalPupils != 0, TotalNonEducationalSupportStaffCosts / TotalPupils, NULL) AS 'TotalNonEducationalSupportStaffCosts',
       IIF(TotalPupils != 0, AdministrativeClericalStaffCosts / TotalPupils, NULL) AS 'AdministrativeClericalStaffCosts',
       IIF(TotalPupils != 0, AuditorsCosts / TotalPupils, NULL) AS 'AuditorsCosts',
       IIF(TotalPupils != 0, OtherStaffCosts / TotalPupils, NULL) AS 'OtherStaffCosts',
       IIF(TotalPupils != 0, ProfessionalServicesNonCurriculumCosts / TotalPupils, NULL) AS 'ProfessionalServicesNonCurriculumCosts',
       IIF(TotalPupils != 0, TotalEducationalSuppliesCosts / TotalPupils, NULL) AS 'TotalEducationalSuppliesCosts',
       IIF(TotalPupils != 0, ExaminationFeesCosts / TotalPupils, NULL) AS 'ExaminationFeesCosts',
       IIF(TotalPupils != 0, LearningResourcesNonIctCosts / TotalPupils, NULL) AS 'LearningResourcesNonIctCosts',
       IIF(TotalPupils != 0, LearningResourcesIctCosts / TotalPupils, NULL) AS 'LearningResourcesIctCosts',
       IIF(TotalPupils != 0, TotalGrossCateringCosts / TotalPupils, NULL) AS 'TotalGrossCateringCosts',
       IIF(TotalPupils != 0, TotalNetCateringCosts / TotalPupils, NULL) AS 'TotalNetCateringCosts',
       IIF(TotalPupils != 0, CateringStaffCosts / TotalPupils, NULL) AS 'CateringStaffCosts',
       IIF(TotalPupils != 0, CateringSuppliesCosts / TotalPupils, NULL) AS 'CateringSuppliesCosts',
       IIF(TotalPupils != 0, TotalOtherCosts / TotalPupils, NULL) AS 'TotalOtherCosts',
       IIF(TotalPupils != 0, GroundsMaintenanceCosts / TotalPupils, NULL) AS 'GroundsMaintenanceCosts',
       IIF(TotalPupils != 0, IndirectEmployeeExpenses / TotalPupils, NULL) AS 'IndirectEmployeeExpenses',
       IIF(TotalPupils != 0, InterestChargesLoanBank / TotalPupils, NULL) AS 'InterestChargesLoanBank',
       IIF(TotalPupils != 0, OtherInsurancePremiumsCosts / TotalPupils, NULL) AS 'OtherInsurancePremiumsCosts',
       IIF(TotalPupils != 0, PrivateFinanceInitiativeCharges / TotalPupils, NULL) AS 'PrivateFinanceInitiativeCharges',
       IIF(TotalPupils != 0, RentRatesCosts / TotalPupils, NULL) AS 'RentRatesCosts',
       IIF(TotalPupils != 0, SpecialFacilitiesCosts / TotalPupils, NULL) AS 'SpecialFacilitiesCosts',
       IIF(TotalPupils != 0, StaffDevelopmentTrainingCosts / TotalPupils, NULL) AS 'StaffDevelopmentTrainingCosts',
       IIF(TotalPupils != 0, StaffRelatedInsuranceCosts / TotalPupils, NULL) AS 'StaffRelatedInsuranceCosts',
       IIF(TotalPupils != 0, SupplyTeacherInsurableCosts / TotalPupils, NULL) AS 'SupplyTeacherInsurableCosts',
       IIF(TotalPupils != 0, AdministrativeSuppliesNonEducationalCosts / TotalPupils, NULL) AS 'AdministrativeSuppliesNonEducationalCosts',
       IIF(TotalInternalFloorArea != 0, TotalPremisesStaffServiceCosts / TotalInternalFloorArea, NULL) AS 'TotalPremisesStaffServiceCosts',
       IIF(TotalInternalFloorArea != 0, CleaningCaretakingCosts / TotalInternalFloorArea, NULL) AS 'CleaningCaretakingCosts',
       IIF(TotalInternalFloorArea != 0, MaintenancePremisesCosts / TotalInternalFloorArea, NULL) AS 'MaintenancePremisesCosts',
       IIF(TotalInternalFloorArea != 0, OtherOccupationCosts / TotalInternalFloorArea, NULL) AS 'OtherOccupationCosts',
       IIF(TotalInternalFloorArea != 0, PremisesStaffCosts / TotalInternalFloorArea, NULL) AS 'PremisesStaffCosts',
       IIF(TotalInternalFloorArea != 0, TotalUtilitiesCosts / TotalInternalFloorArea, NULL) AS 'TotalUtilitiesCosts',
       IIF(TotalInternalFloorArea != 0, EnergyCosts / TotalInternalFloorArea, NULL) AS 'EnergyCosts',
       IIF(TotalInternalFloorArea != 0, WaterSewerageCosts / TotalInternalFloorArea, NULL) AS 'WaterSewerageCosts',
       IIF(TotalPupils != 0, TotalExpenditureCS / TotalPupils, NULL) AS 'TotalExpenditureCS',
       IIF(TotalPupils != 0, TotalTeachingSupportStaffCostsCS / TotalPupils, NULL) AS 'TotalTeachingSupportStaffCostsCS',
       IIF(TotalPupils != 0, TeachingStaffCostsCS / TotalPupils, NULL) AS 'TeachingStaffCostsCS',
       IIF(TotalPupils != 0, SupplyTeachingStaffCostsCS / TotalPupils, NULL) AS 'SupplyTeachingStaffCostsCS',
       IIF(TotalPupils != 0, EducationalConsultancyCostsCS / TotalPupils, NULL) AS 'EducationalConsultancyCostsCS',
       IIF(TotalPupils != 0, EducationSupportStaffCostsCS / TotalPupils, NULL) AS 'EducationSupportStaffCostsCS',
       IIF(TotalPupils != 0, AgencySupplyTeachingStaffCostsCS / TotalPupils, NULL) AS 'AgencySupplyTeachingStaffCostsCS',
       IIF(TotalPupils != 0, TotalNonEducationalSupportStaffCostsCS / TotalPupils, NULL) AS 'TotalNonEducationalSupportStaffCostsCS',
       IIF(TotalPupils != 0, AdministrativeClericalStaffCostsCS / TotalPupils, NULL) AS 'AdministrativeClericalStaffCostsCS',
       IIF(TotalPupils != 0, AuditorsCostsCS / TotalPupils, NULL) AS 'AuditorsCostsCS',
       IIF(TotalPupils != 0, OtherStaffCostsCS / TotalPupils, NULL) AS 'OtherStaffCostsCS',
       IIF(TotalPupils != 0, ProfessionalServicesNonCurriculumCostsCS / TotalPupils, NULL) AS 'ProfessionalServicesNonCurriculumCostsCS',
       IIF(TotalPupils != 0, TotalEducationalSuppliesCostsCS / TotalPupils, NULL) AS 'TotalEducationalSuppliesCostsCS',
       IIF(TotalPupils != 0, ExaminationFeesCostsCS / TotalPupils, NULL) AS 'ExaminationFeesCostsCS',
       IIF(TotalPupils != 0, LearningResourcesNonIctCostsCS / TotalPupils, NULL) AS 'LearningResourcesNonIctCostsCS',
       IIF(TotalPupils != 0, LearningResourcesIctCostsCS / TotalPupils, NULL) AS 'LearningResourcesIctCostsCS',
       IIF(TotalPupils != 0, TotalGrossCateringCostsCS / TotalPupils, NULL) AS 'TotalGrossCateringCostsCS',
       IIF(TotalPupils != 0, TotalNetCateringCostsCS / TotalPupils, NULL) AS 'TotalNetCateringCostsCS',
       IIF(TotalPupils != 0, CateringStaffCostsCS / TotalPupils, NULL) AS 'CateringStaffCostsCS',
       IIF(TotalPupils != 0, CateringSuppliesCostsCS / TotalPupils, NULL) AS 'CateringSuppliesCostsCS',
       IIF(TotalPupils != 0, TotalOtherCostsCS / TotalPupils, NULL) AS 'TotalOtherCostsCS',
       IIF(TotalPupils != 0, GroundsMaintenanceCostsCS / TotalPupils, NULL) AS 'GroundsMaintenanceCostsCS',
       IIF(TotalPupils != 0, IndirectEmployeeExpensesCS / TotalPupils, NULL) AS 'IndirectEmployeeExpensesCS',
       IIF(TotalPupils != 0, InterestChargesLoanBankCS / TotalPupils, NULL) AS 'InterestChargesLoanBankCS',
       IIF(TotalPupils != 0, OtherInsurancePremiumsCostsCS / TotalPupils, NULL) AS 'OtherInsurancePremiumsCostsCS',
       IIF(TotalPupils != 0, PrivateFinanceInitiativeChargesCS / TotalPupils, NULL) AS 'PrivateFinanceInitiativeChargesCS',
       IIF(TotalPupils != 0, RentRatesCostsCS / TotalPupils, NULL) AS 'RentRatesCostsCS',
       IIF(TotalPupils != 0, SpecialFacilitiesCostsCS / TotalPupils, NULL) AS 'SpecialFacilitiesCostsCS',
       IIF(TotalPupils != 0, StaffDevelopmentTrainingCostsCS / TotalPupils, NULL) AS 'StaffDevelopmentTrainingCostsCS',
       IIF(TotalPupils != 0, StaffRelatedInsuranceCostsCS / TotalPupils, NULL) AS 'StaffRelatedInsuranceCostsCS',
       IIF(TotalPupils != 0, SupplyTeacherInsurableCostsCS / TotalPupils, NULL) AS 'SupplyTeacherInsurableCostsCS',
       IIF(TotalPupils != 0, AdministrativeSuppliesNonEducationalCostsCS / TotalPupils, NULL) AS 'AdministrativeSuppliesNonEducationalCostsCS',
       IIF(TotalInternalFloorArea != 0, TotalPremisesStaffServiceCostsCS / TotalInternalFloorArea, NULL) AS 'TotalPremisesStaffServiceCostsCS',
       IIF(TotalInternalFloorArea != 0, CleaningCaretakingCostsCS / TotalInternalFloorArea, NULL) AS 'CleaningCaretakingCostsCS',
       IIF(TotalInternalFloorArea != 0, MaintenancePremisesCostsCS / TotalInternalFloorArea, NULL) AS 'MaintenancePremisesCostsCS',
       IIF(TotalInternalFloorArea != 0, OtherOccupationCostsCS / TotalInternalFloorArea, NULL) AS 'OtherOccupationCostsCS',
       IIF(TotalInternalFloorArea != 0, PremisesStaffCostsCS / TotalInternalFloorArea, NULL) AS 'PremisesStaffCostsCS',
       IIF(TotalInternalFloorArea != 0, TotalUtilitiesCostsCS / TotalInternalFloorArea, NULL) AS 'TotalUtilitiesCostsCS',
       IIF(TotalInternalFloorArea != 0, EnergyCostsCS / TotalInternalFloorArea, NULL) AS 'EnergyCostsCS',
       IIF(TotalInternalFloorArea != 0, WaterSewerageCostsCS / TotalInternalFloorArea, NULL) AS 'WaterSewerageCostsCS',
       IIF(TotalPupils != 0, TotalExpenditureSchool / TotalPupils, NULL) AS 'TotalExpenditureSchool',
       IIF(TotalPupils != 0, TotalTeachingSupportStaffCostsSchool / TotalPupils, NULL) AS 'TotalTeachingSupportStaffCostsSchool',
       IIF(TotalPupils != 0, TeachingStaffCostsSchool / TotalPupils, NULL) AS 'TeachingStaffCostsSchool',
       IIF(TotalPupils != 0, SupplyTeachingStaffCostsSchool / TotalPupils, NULL) AS 'SupplyTeachingStaffCostsSchool',
       IIF(TotalPupils != 0, EducationalConsultancyCostsSchool / TotalPupils, NULL) AS 'EducationalConsultancyCostsSchool',
       IIF(TotalPupils != 0, EducationSupportStaffCostsSchool / TotalPupils, NULL) AS 'EducationSupportStaffCostsSchool',
       IIF(TotalPupils != 0, AgencySupplyTeachingStaffCostsSchool / TotalPupils, NULL) AS 'AgencySupplyTeachingStaffCostsSchool',
       IIF(TotalPupils != 0, TotalNonEducationalSupportStaffCostsSchool / TotalPupils, NULL) AS 'TotalNonEducationalSupportStaffCostsSchool',
       IIF(TotalPupils != 0, AdministrativeClericalStaffCostsSchool / TotalPupils, NULL) AS 'AdministrativeClericalStaffCostsSchool',
       IIF(TotalPupils != 0, AuditorsCostsSchool / TotalPupils, NULL) AS 'AuditorsCostsSchool',
       IIF(TotalPupils != 0, OtherStaffCostsSchool / TotalPupils, NULL) AS 'OtherStaffCostsSchool',
       IIF(TotalPupils != 0, ProfessionalServicesNonCurriculumCostsSchool / TotalPupils, NULL) AS 'ProfessionalServicesNonCurriculumCostsSchool',
       IIF(TotalPupils != 0, TotalEducationalSuppliesCostsSchool / TotalPupils, NULL) AS 'TotalEducationalSuppliesCostsSchool',
       IIF(TotalPupils != 0, ExaminationFeesCostsSchool / TotalPupils, NULL) AS 'ExaminationFeesCostsSchool',
       IIF(TotalPupils != 0, LearningResourcesNonIctCostsSchool / TotalPupils, NULL) AS 'LearningResourcesNonIctCostsSchool',
       IIF(TotalPupils != 0, LearningResourcesIctCostsSchool / TotalPupils, NULL) AS 'LearningResourcesIctCostsSchool',
       IIF(TotalPupils != 0, TotalGrossCateringCostsSchool / TotalPupils, NULL) AS 'TotalGrossCateringCostsSchool',
       IIF(TotalPupils != 0, TotalNetCateringCostsSchool / TotalPupils, NULL) AS 'TotalNetCateringCostsSchool',
       IIF(TotalPupils != 0, CateringStaffCostsSchool / TotalPupils, NULL) AS 'CateringStaffCostsSchool',
       IIF(TotalPupils != 0, CateringSuppliesCostsSchool / TotalPupils, NULL) AS 'CateringSuppliesCostsSchool',
       IIF(TotalPupils != 0, TotalOtherCostsSchool / TotalPupils, NULL) AS 'TotalOtherCostsSchool',
       IIF(TotalPupils != 0, GroundsMaintenanceCostsSchool / TotalPupils, NULL) AS 'GroundsMaintenanceCostsSchool',
       IIF(TotalPupils != 0, IndirectEmployeeExpensesSchool / TotalPupils, NULL) AS 'IndirectEmployeeExpensesSchool',
       IIF(TotalPupils != 0, InterestChargesLoanBankSchool / TotalPupils, NULL) AS 'InterestChargesLoanBankSchool',
       IIF(TotalPupils != 0, OtherInsurancePremiumsCostsSchool / TotalPupils, NULL) AS 'OtherInsurancePremiumsCostsSchool',
       IIF(TotalPupils != 0, PrivateFinanceInitiativeChargesSchool / TotalPupils, NULL) AS 'PrivateFinanceInitiativeChargesSchool',
       IIF(TotalPupils != 0, RentRatesCostsSchool / TotalPupils, NULL) AS 'RentRatesCostsSchool',
       IIF(TotalPupils != 0, SpecialFacilitiesCostsSchool / TotalPupils, NULL) AS 'SpecialFacilitiesCostsSchool',
       IIF(TotalPupils != 0, StaffDevelopmentTrainingCostsSchool / TotalPupils, NULL) AS 'StaffDevelopmentTrainingCostsSchool',
       IIF(TotalPupils != 0, StaffRelatedInsuranceCostsSchool / TotalPupils, NULL) AS 'StaffRelatedInsuranceCostsSchool',
       IIF(TotalPupils != 0, SupplyTeacherInsurableCostsSchool / TotalPupils, NULL) AS 'SupplyTeacherInsurableCostsSchool',
       IIF(TotalPupils != 0, AdministrativeSuppliesNonEducationalCostsSchool / TotalPupils, NULL) AS 'AdministrativeSuppliesNonEducationalCostsSchool',
       IIF(TotalInternalFloorArea != 0, TotalPremisesStaffServiceCostsSchool / TotalInternalFloorArea, NULL) AS 'TotalPremisesStaffServiceCostsSchool',
       IIF(TotalInternalFloorArea != 0, CleaningCaretakingCostsSchool / TotalInternalFloorArea, NULL) AS 'CleaningCaretakingCostsSchool',
       IIF(TotalInternalFloorArea != 0, MaintenancePremisesCostsSchool / TotalInternalFloorArea, NULL) AS 'MaintenancePremisesCostsSchool',
       IIF(TotalInternalFloorArea != 0, OtherOccupationCostsSchool / TotalInternalFloorArea, NULL) AS 'OtherOccupationCostsSchool',
       IIF(TotalInternalFloorArea != 0, PremisesStaffCostsSchool / TotalInternalFloorArea, NULL) AS 'PremisesStaffCostsSchool',
       IIF(TotalInternalFloorArea != 0, TotalUtilitiesCostsSchool / TotalInternalFloorArea, NULL) AS 'TotalUtilitiesCostsSchool',
       IIF(TotalInternalFloorArea != 0, EnergyCostsSchool / TotalInternalFloorArea, NULL) AS 'EnergyCostsSchool',
       IIF(TotalInternalFloorArea != 0, WaterSewerageCostsSchool / TotalInternalFloorArea, NULL) AS 'WaterSewerageCostsSchool',
       EMLBand,
       TotalPupils
FROM VW_TrustFinancialDefault
GO

DROP VIEW IF EXISTS VW_ExpenditureTrustDefaultCurrentActual
GO

CREATE VIEW VW_ExpenditureTrustDefaultCurrentActual AS
SELECT f.*,
       t.TrustName
FROM Trust t
         LEFT JOIN VW_ExpenditureTrustDefaultActual f on f.CompanyNumber = t.CompanyNumber
WHERE f.RunId = (SELECT Value FROM Parameters WHERE Name = 'CurrentYear')
GO

DROP VIEW IF EXISTS VW_ExpenditureTrustDefaultCurrentPercentExpenditure
GO

CREATE VIEW VW_ExpenditureTrustDefaultCurrentPercentExpenditure AS
SELECT f.*,
       t.TrustName
FROM Trust t
         LEFT JOIN VW_ExpenditureTrustDefaultPercentExpenditure f on f.CompanyNumber = t.CompanyNumber
WHERE f.RunId = (SELECT Value FROM Parameters WHERE Name = 'CurrentYear')
GO

DROP VIEW IF EXISTS VW_ExpenditureTrustDefaultCurrentPercentIncome
GO

CREATE VIEW VW_ExpenditureTrustDefaultCurrentPercentIncome AS
SELECT f.*,
       t.TrustName
FROM Trust t
         LEFT JOIN VW_ExpenditureTrustDefaultPercentIncome f on f.CompanyNumber = t.CompanyNumber
WHERE f.RunId = (SELECT Value FROM Parameters WHERE Name = 'CurrentYear')
GO

DROP VIEW IF EXISTS VW_ExpenditureTrustDefaultCurrentPerUnit
GO

CREATE VIEW VW_ExpenditureTrustDefaultCurrentPerUnit AS
SELECT f.*,
       t.TrustName
FROM Trust t
         LEFT JOIN VW_ExpenditureTrustDefaultPerUnit f on f.CompanyNumber = t.CompanyNumber
WHERE f.RunId = (SELECT Value FROM Parameters WHERE Name = 'CurrentYear')
GO