DROP VIEW IF EXISTS VW_SchoolExpenditureDefaultCurrentActual
GO

CREATE VIEW VW_SchoolExpenditureDefaultCurrentActual AS
SELECT s.URN,
       s.SchoolName,
       s.SchoolType,
       s.OverallPhase,
       s.LACode,
       s.LAName,
       s.TrustCompanyNumber,
       f.PeriodCoveredByReturn,
       f.TotalPupils,
       f.TotalInternalFloorArea,
       f.TotalExpenditure,
       f.TotalTeachingSupportStaffCosts,
       f.TeachingStaffCosts,
       f.SupplyTeachingStaffCosts,
       f.EducationalConsultancyCosts,
       f.EducationSupportStaffCosts,
       f.AgencySupplyTeachingStaffCosts,
       f.TotalNonEducationalSupportStaffCosts,
       f.AdministrativeClericalStaffCosts,
       f.AuditorsCosts,
       f.OtherStaffCosts,
       f.ProfessionalServicesNonCurriculumCosts,
       f.TotalEducationalSuppliesCosts,
       f.ExaminationFeesCosts,
       f.LearningResourcesNonIctCosts,
       f.LearningResourcesIctCosts,
       f.TotalPremisesStaffServiceCosts,
       f.CleaningCaretakingCosts,
       f.MaintenancePremisesCosts,
       f.OtherOccupationCosts,
       f.PremisesStaffCosts,
       f.TotalUtilitiesCosts,
       f.EnergyCosts,
       f.WaterSewerageCosts,
       f.AdministrativeSuppliesNonEducationalCosts,
       f.TotalGrossCateringCosts,
       f.TotalNetCateringCostsCosts AS TotalNetCateringCosts,
       f.CateringStaffCosts,
       f.CateringSuppliesCosts,
       f.TotalOtherCosts,
       f.DirectRevenueFinancingCosts,
       f.GroundsMaintenanceCosts,
       f.IndirectEmployeeExpenses,
       f.InterestChargesLoanBank,
       f.OtherInsurancePremiumsCosts,
       f.PrivateFinanceInitiativeCharges,
       f.RentRatesCosts,
       f.SpecialFacilitiesCosts,
       f.StaffDevelopmentTrainingCosts,
       f.StaffRelatedInsuranceCosts,
       f.SupplyTeacherInsurableCosts,
       f.CommunityFocusedSchoolStaff,
       f.CommunityFocusedSchoolCosts
FROM School s
         LEFT JOIN VW_FinancialDefaultCurrent f ON f.URN = s.URN
GO

DROP VIEW IF EXISTS VW_SchoolExpenditureCustomActual
GO

CREATE VIEW VW_SchoolExpenditureCustomActual AS
SELECT s.URN,
       s.SchoolName,
       s.SchoolType,
       s.LAName,
       s.TrustCompanyNumber,
       f.RunId,
       f.TotalPupils,
       f.TotalInternalFloorArea,
       f.TotalExpenditure,
       f.TotalTeachingSupportStaffCosts,
       f.TeachingStaffCosts,
       f.SupplyTeachingStaffCosts,
       f.EducationalConsultancyCosts,
       f.EducationSupportStaffCosts,
       f.AgencySupplyTeachingStaffCosts,
       f.TotalNonEducationalSupportStaffCosts,
       f.AdministrativeClericalStaffCosts,
       f.AuditorsCosts,
       f.OtherStaffCosts,
       f.ProfessionalServicesNonCurriculumCosts,
       f.TotalEducationalSuppliesCosts,
       f.ExaminationFeesCosts,
       f.LearningResourcesNonIctCosts,
       f.LearningResourcesIctCosts,
       f.TotalPremisesStaffServiceCosts,
       f.CleaningCaretakingCosts,
       f.MaintenancePremisesCosts,
       f.OtherOccupationCosts,
       f.PremisesStaffCosts,
       f.TotalUtilitiesCosts,
       f.EnergyCosts,
       f.WaterSewerageCosts,
       f.AdministrativeSuppliesNonEducationalCosts,
       f.TotalGrossCateringCosts,
       f.TotalNetCateringCostsCosts AS TotalNetCateringCosts,
       f.CateringStaffCosts,
       f.CateringSuppliesCosts,
       f.TotalOtherCosts,
       f.DirectRevenueFinancingCosts,
       f.GroundsMaintenanceCosts,
       f.IndirectEmployeeExpenses,
       f.InterestChargesLoanBank,
       f.OtherInsurancePremiumsCosts,
       f.PrivateFinanceInitiativeCharges,
       f.RentRatesCosts,
       f.SpecialFacilitiesCosts,
       f.StaffDevelopmentTrainingCosts,
       f.StaffRelatedInsuranceCosts,
       f.SupplyTeacherInsurableCosts,
       f.CommunityFocusedSchoolStaff,
       f.CommunityFocusedSchoolCosts
FROM School s
         LEFT JOIN Financial f ON f.URN = s.URN
WHERE f.RunType = 'custom'
GO

DROP VIEW IF EXISTS VW_SchoolExpenditureDefaultActual
GO

CREATE VIEW VW_SchoolExpenditureDefaultActual AS
SELECT RunId,
       URN,
       TotalPupils,
       TotalInternalFloorArea,
       TotalExpenditure,
       TotalTeachingSupportStaffCosts,
       TeachingStaffCosts,
       SupplyTeachingStaffCosts,
       EducationalConsultancyCosts,
       EducationSupportStaffCosts,
       AgencySupplyTeachingStaffCosts,
       TotalNonEducationalSupportStaffCosts,
       AdministrativeClericalStaffCosts,
       AuditorsCosts,
       OtherStaffCosts,
       ProfessionalServicesNonCurriculumCosts,
       TotalEducationalSuppliesCosts,
       ExaminationFeesCosts,
       LearningResourcesNonIctCosts,
       LearningResourcesIctCosts,
       TotalPremisesStaffServiceCosts,
       CleaningCaretakingCosts,
       MaintenancePremisesCosts,
       OtherOccupationCosts,
       PremisesStaffCosts,
       TotalUtilitiesCosts,
       EnergyCosts,
       WaterSewerageCosts,
       AdministrativeSuppliesNonEducationalCosts,
       TotalGrossCateringCosts,
       TotalNetCateringCostsCosts AS TotalNetCateringCosts,
       CateringStaffCosts,
       CateringSuppliesCosts,
       TotalOtherCosts,
       DirectRevenueFinancingCosts,
       GroundsMaintenanceCosts,
       IndirectEmployeeExpenses,
       InterestChargesLoanBank,
       OtherInsurancePremiumsCosts,
       PrivateFinanceInitiativeCharges,
       RentRatesCosts,
       SpecialFacilitiesCosts,
       StaffDevelopmentTrainingCosts,
       StaffRelatedInsuranceCosts,
       SupplyTeacherInsurableCosts,
       CommunityFocusedSchoolStaff,
       CommunityFocusedSchoolCosts
FROM Financial
WHERE RunType = 'default'
GO


