displayName: Average_API_Benchmark - Comparator Set
testPlan: url-test.json
description: Average load test for GET /comparator-set/school/{identifier}/default
engineInstances: 1
testId: 49627d01-559a-4e73-9313-649e2602906e
testType: URL
subnetId: /subscriptions/a5c0a8d7-a54d-4a6d-ab79-4ca64a3b750f/resourceGroups/s198t01-ebis-core/providers/Microsoft.Network/virtualNetworks/s198t01-app-service-network/subnets/s198t01-load-test-subnet
publicIPDisabled: true
splitAllCSVs: False
configurationFiles:
- schools.csv
failureCriteria:
- p50(response_time_ms) > 100
- p95(response_time_ms) > 150
- p99(response_time_ms) > 500
- percentage(error) > 0.1
secrets:
- name: benchmark-host-key
  value: https://s198t01-ebis-keyvault.vault.azure.net/secrets/benchmark-host-key
autoStop:
  errorPercentage: 90
  timeWindow: 60
