parameters:
  subscription: ''
  environmentPrefix: ''
  environment: ''
  cipEnvironment: ''

steps:
  - template: ..\common\run-terraform.yaml
    parameters:
      subscription: ${{ parameters.subscription }}
      environmentPrefix: ${{ parameters.environmentPrefix }}
      environment: ${{ parameters.environment }}
      cipEnvironment: ${{ parameters.cipEnvironment }}
      module: 'core'