pool:
  vmImage: 'windows-2022'

trigger:
  batch: true
  branches:
    include:
      - main
  paths:
    include:
      - prototype

pr: none

stages:
  - stage: Build
    displayName: 'Build artifacts'
    jobs:
      - job: Zip_static_artifacts
        displayName: 'Zip static artifacts'
        steps:
          - task: ArchiveFiles@2
            displayName: 'Zip terraform files'
            inputs:
              rootFolderOrFile: 'prototype/terraform'
              includeRootFolder: false
              archiveFile: '$(Build.ArtifactStagingDirectory)/terraform.zip'

          - publish: $(Build.ArtifactStagingDirectory)/terraform.zip
            artifact: terraform

      - job: Build
        displayName: Build
        pool:
          vmImage: ubuntu-latest
        steps:
          - script: |
              npm install
              npm run build --if-present
              npm run test --if-present
            displayName: 'npm install, build and test'
            workingDirectory: 'prototype/src'

          - task: ArchiveFiles@2
            displayName: 'Archive files'
            inputs:
              rootFolderOrFile: 'prototype/src'
              includeRootFolder: false
              archiveFile: $(Build.ArtifactStagingDirectory)/prototype.zip
              replaceExistingArchive: true

          - publish: $(Build.ArtifactStagingDirectory)/prototype.zip
            artifact: prototype

  - stage: DeployDevelopment
    dependsOn: [Build]
    displayName: 'Deploy to prototype'
    jobs:
      - template: jobs-prototype.yaml
        parameters:
          subscription: 's198d.azdo-deployment'
          environmentPrefix: 's198d99'
          environment: 'prototype'
          cipEnvironment: 'Dev'