pool:
  vmImage: 'ubuntu-latest'

trigger:
  batch: true
  branches:
    include:
      - main
  paths:
    include:
      - shared
      - prototype

pr: none

variables:
  TerraformFolder: 'prototype/terraform'
  TerraformDirectory: '$(System.DefaultWorkingDirectory)/$(TerraformFolder)'
  ShouldDeploy: and(eq(variables['Build.SourceBranch'], 'refs/heads/main'), ne(variables['Build.Reason'], 'PullRequest'))

stages:
  - stage: Build
    displayName: 'Build artifacts'
    jobs:
      - job: FmtValidateTf
        displayName: "Lint and validate terraform"
        steps:
          - template: ..\..\shared\steps-fmt-validate-terraform.yaml
            parameters:
              TerraformDirectory: $(TerraformDirectory)

      - job: RunCheckOv
        displayName: "Static analysis terraform"
        steps:
          - template: ..\..\shared\steps-scan-terraform.yaml
            parameters:
              TerraformDirectory: $(TerraformDirectory)

      - job: ZipStaticArtifacts
        displayName: 'Zip static artifacts'
        steps:
          - template: ..\..\shared\steps-publish-terraform-artifacts.yaml
            parameters:
              TerraformFolder: $(TerraformFolder)

      - job: Build
        displayName: Build
        pool:
          vmImage: ubuntu-latest
        steps:
          - template: steps-prototype-build.yaml

  - stage: DeployDevelopment
    dependsOn: [Build]
    condition: and(succeeded(), $(ShouldDeploy))
    displayName: 'Deploy to prototype'
    variables:
      - group: 'prototype'
    jobs:
      - template: jobs-prototype.yaml
        parameters:
          subscription: 's198d.azdo-deployment'
          environmentPrefix: 's198d99'
          environment: 'prototype'
          cipEnvironment: 'Dev'