pool:
  vmImage: 'ubuntu-latest'

trigger:
  batch: true
  branches:
    include:
      - main
  paths:
    include:
      - prototype

pr: none

stages:
  - stage: Build
    displayName: 'Build artifacts'
    jobs:
      - job: RunCheckov
        displayName: "Checkov scan terraform"
        steps:
          - template: steps-prototype-scan-terraform.yaml
            parameters:
              TerraformDirectory: $(System.DefaultWorkingDirectory)/prototype/terraform

      - job: Zip_static_artifacts
        displayName: 'Zip static artifacts'
        steps:
          - template: steps-prototype-publish-static-artifacts.yaml

      - job: Build
        displayName: Build
        pool:
          vmImage: ubuntu-latest
        steps:
          - template: steps-prototype-build.yaml

  - stage: DeployDevelopment
    dependsOn: [Build]
    displayName: 'Deploy to prototype'
    jobs:
      - template: jobs-prototype.yaml
        parameters:
          subscription: 's198d.azdo-deployment'
          environmentPrefix: 's198d99'
          environment: 'prototype'
          cipEnvironment: 'Dev'