  version: 2
  registries:
    npm-azure-artifacts:
      type: npm-registry
      url: https://dfe-ssp.pkgs.visualstudio.com/s198-DfE-Benchmarking-service/_packaging/education-benchmarking/npm/registry/
      username: ${{ secrets.AZURE_DEVOPS_USER }}
      password: ${{ secrets.AZURE_DEVOPS_PAT }}

  updates:
    - package-ecosystem: "terraform"
      directory: "/core-infrastructure/terraform"
      schedule:
        interval: "monthly"
      commit-message:
        prefix: "[terraform] "

    - package-ecosystem: "npm"
      directory: "/front-end-components"
      schedule:
        interval: "monthly"
      commit-message:
        prefix: "[npm] "
      open-pull-requests-limit: 10

    - package-ecosystem: "terraform"
      directory: "/platform/terraform"
      schedule:
        interval: "monthly"
      commit-message:
        prefix: "[terraform] "

    - package-ecosystem: "nuget"
      directory: "/platform/src/abstractions/Platform.Functions"
      schedule:
        interval: "monthly"
      commit-message:
        prefix: "[nuget] "

    - package-ecosystem: "nuget"
      directory: "/platform/src/abstractions/Platform.Infrastructure"
      schedule:
        interval: "monthly"
      commit-message:
        prefix: "[nuget] "

    - package-ecosystem: "nuget"
      directory: "/platform/src/apis/Platform.Api.Benchmark"
      schedule:
        interval: "monthly"
      commit-message:
        prefix: "[nuget] "

    - package-ecosystem: "nuget"
      directory: "/platform/src/apis/Platform.Api.Establishment"
      schedule:
        interval: "monthly"
      commit-message:
        prefix: "[nuget] "

    - package-ecosystem: "nuget"
      directory: "/platform/src/apis/Platform.Api.Insight"
      schedule:
        interval: "monthly"
      commit-message:
        prefix: "[nuget] "

    - package-ecosystem: "nuget"
      directory: "/platform/src/search/Platform.Search"
      schedule:
        interval: "monthly"
      commit-message:
        prefix: "[nuget] "

    - package-ecosystem: "nuget"
      directory: "/platform/src/search/Platform.Search.App"
      schedule:
        interval: "monthly"
      commit-message:
        prefix: "[nuget] "

    - package-ecosystem: "nuget"
      directory: "/platform/src/search/Platform.Search.Processor"
      schedule:
        interval: "monthly"
      commit-message:
        prefix: "[nuget] "

    - package-ecosystem: "nuget"
      directory: "/platform/tests/Platform.ApiTests"
      schedule:
        interval: "monthly"
      commit-message:
        prefix: "[nuget] "
      # License changes impact v8, so stick to v7 major version instead
      ignore:
        - dependency-name: "FluentAssertions"
          versions: ["8.*"]

    - package-ecosystem: "nuget"
      directory: "/platform/tests/Platform.Tests"
      schedule:
        interval: "monthly"
      commit-message:
        prefix: "[nuget] "
          
    - package-ecosystem: "npm"
      directory: "/prototype/src"
      schedule:
        interval: "monthly"
      commit-message:
        prefix: "[npm] "

    - package-ecosystem: "terraform"
      directory: "/prototype/terraform"
      schedule:
        interval: "monthly"
      commit-message:
        prefix: "[terraform] "

    - package-ecosystem: "npm"
      directory: "/web/src/Web.App"
      registries:
        - npm-azure-artifacts
      schedule:
        interval: "monthly"
      commit-message:
        prefix: "[npm] "

    - package-ecosystem: "terraform"
      directory: "/web/terraform"
      schedule:
        interval: "monthly"
      commit-message:
        prefix: "[terraform] "

    - package-ecosystem: "nuget"
      directory: "/web/src/Web.App"
      schedule:
        interval: "monthly"
      commit-message:
        prefix: "[nuget] "

    - package-ecosystem: "nuget"
      directory: "/web/tests/Web.A11yTests"
      schedule:
        interval: "monthly"
      commit-message:
        prefix: "[nuget] "

    - package-ecosystem: "nuget"
      directory: "/web/tests/Web.E2ETests"
      schedule:
        interval: "monthly"
      commit-message:
        prefix: "[nuget] "

    - package-ecosystem: "nuget"
      directory: "/web/tests/Web.Integration.Tests"
      schedule:
        interval: "monthly"
      commit-message:
        prefix: "[nuget] "

    - package-ecosystem: "nuget"
      directory: "/web/tests/Web.Tests"
      schedule:
        interval: "monthly"
      commit-message:
        prefix: "[nuget] "