  version: 2
  registries:
    npm-azure-artifacts:
      type: npm-registry
      url: https://dfe-ssp.pkgs.visualstudio.com/s198-DfE-Benchmarking-service/_packaging/education-benchmarking/npm/registry/
      username: ${{ secrets.AZURE_DEVOPS_USER }}
      password: ${{ secrets.AZURE_DEVOPS_PAT }}

  updates:
    - package-ecosystem: "terraform"
      directory: "/core-infrastructure/terraform"
      schedule:
        interval: "weekly"
      commit-message:
        prefix: "[terraform] "

    - package-ecosystem: "npm"
      directory: "/front-end-components"
      schedule:
        interval: "weekly"
      commit-message:
        prefix: "[npm] "

    - package-ecosystem: "terraform"
      directory: "/platform/terraform"
      schedule:
        interval: "weekly"
      commit-message:
        prefix: "[terraform] "

    - package-ecosystem: "nuget"
      directory: "/platform/src/abstractions/Platform.Domain"
      schedule:
        interval: "weekly"
      commit-message:
        prefix: "[nuget] "
      ignore:
        - dependency-name: "Microsoft.Extensions.Configuration.Binder"
          versions: ["7.*", "8.*"]
        - dependency-name: "Microsoft.Extensions.Logging.Abstractions"
          versions: ["7.*", "8.*"]
        - dependency-name: "Microsoft.Extensions.Options"
          versions: ["7.*", "8.*"]
        - dependency-name: "Microsoft.Extensions.Options.ConfigurationExtensions"
          versions: ["7.*", "8.*"]
        - dependency-name: "Microsoft.Extensions.Configuration"
          versions: ["7.*", "8.*"]
        - dependency-name: "Microsoft.Extensions.Logging.Console"
          versions: [ "7.*", "8.*" ]
        - dependency-name: "Microsoft.Extensions.Diagnostics.HealthChecks"
          versions: [ "7.*", "8.*" ]
        - dependency-name: "Serilog.AspNetCore"
          versions: [ "7.*", "8.*" ]
        - dependency-name: "Microsoft.Extensions.Logging"
          versions: [ "7.*", "8.*" ]
        - dependency-name: "Microsoft.Extensions.Configuration.Json"
          versions: [ "7.*", "8.*" ]

    - package-ecosystem: "nuget"
      directory: "/platform/src/abstractions/Platform.Functions"
      schedule:
        interval: "weekly"
      commit-message:
        prefix: "[nuget] "
      ignore:
        - dependency-name: "Microsoft.Extensions.Configuration.Binder"
          versions: ["7.*", "8.*"]
        - dependency-name: "Microsoft.Extensions.Logging.Abstractions"
          versions: ["7.*", "8.*"]
        - dependency-name: "Microsoft.Extensions.Options"
          versions: ["7.*", "8.*"]
        - dependency-name: "Microsoft.Extensions.Options.ConfigurationExtensions"
          versions: ["7.*", "8.*"]
        - dependency-name: "Microsoft.Extensions.Configuration"
          versions: ["7.*", "8.*"]
        - dependency-name: "Microsoft.Extensions.Logging.Console"
          versions: [ "7.*", "8.*" ]
        - dependency-name: "Microsoft.Extensions.Diagnostics.HealthChecks"
          versions: [ "7.*", "8.*" ]
        - dependency-name: "Serilog.AspNetCore"
          versions: [ "7.*", "8.*" ]
        - dependency-name: "Microsoft.Extensions.Logging"
          versions: [ "7.*", "8.*" ]
        - dependency-name: "Microsoft.Extensions.Configuration.Json"
          versions: [ "7.*", "8.*" ]

    - package-ecosystem: "nuget"
      directory: "/platform/src/abstractions/Platform.Infrastructure"
      schedule:
        interval: "weekly"
      commit-message:
        prefix: "[nuget] "
      ignore:
        - dependency-name: "Microsoft.Extensions.Configuration.Binder"
          versions: ["7.*", "8.*"]
        - dependency-name: "Microsoft.Extensions.Logging.Abstractions"
          versions: ["7.*", "8.*"]
        - dependency-name: "Microsoft.Extensions.Options"
          versions: ["7.*", "8.*"]
        - dependency-name: "Microsoft.Extensions.Options.ConfigurationExtensions"
          versions: ["7.*", "8.*"]
        - dependency-name: "Microsoft.Extensions.Configuration"
          versions: ["7.*", "8.*"]
        - dependency-name: "Microsoft.Extensions.Logging.Console"
          versions: [ "7.*", "8.*" ]
        - dependency-name: "Microsoft.Extensions.Diagnostics.HealthChecks"
          versions: [ "7.*", "8.*" ]
        - dependency-name: "Serilog.AspNetCore"
          versions: [ "7.*", "8.*" ]
        - dependency-name: "Microsoft.Extensions.Logging"
          versions: [ "7.*", "8.*" ]
        - dependency-name: "Microsoft.Extensions.Configuration.Json"
          versions: [ "7.*", "8.*" ]

    - package-ecosystem: "nuget"
      directory: "/platform/src/apis/Platform.Api.Benchmark"
      schedule:
        interval: "weekly"
      commit-message:
        prefix: "[nuget] "
      ignore:
        - dependency-name: "Microsoft.Extensions.Configuration.Binder"
          versions: ["7.*", "8.*"]
        - dependency-name: "Microsoft.Extensions.Logging.Abstractions"
          versions: ["7.*", "8.*"]
        - dependency-name: "Microsoft.Extensions.Options"
          versions: ["7.*", "8.*"]
        - dependency-name: "Microsoft.Extensions.Options.ConfigurationExtensions"
          versions: ["7.*", "8.*"]
        - dependency-name: "Microsoft.Extensions.Configuration"
          versions: ["7.*", "8.*"]
        - dependency-name: "Microsoft.Extensions.Logging.Console"
          versions: [ "7.*", "8.*" ]
        - dependency-name: "Microsoft.Extensions.Diagnostics.HealthChecks"
          versions: [ "7.*", "8.*" ]
        - dependency-name: "Serilog.AspNetCore"
          versions: [ "7.*", "8.*" ]
        - dependency-name: "Microsoft.Extensions.Logging"
          versions: [ "7.*", "8.*" ]
        - dependency-name: "Microsoft.Extensions.Configuration.Json"
          versions: [ "7.*", "8.*" ]

    - package-ecosystem: "nuget"
      directory: "/platform/src/api/Platform.Api.Establishment"
      schedule:
        interval: "weekly"
      commit-message:
        prefix: "[nuget] "
      ignore:
        - dependency-name: "Microsoft.Extensions.Configuration.Binder"
          versions: ["7.*", "8.*"]
        - dependency-name: "Microsoft.Extensions.Logging.Abstractions"
          versions: ["7.*", "8.*"]
        - dependency-name: "Microsoft.Extensions.Options"
          versions: ["7.*", "8.*"]
        - dependency-name: "Microsoft.Extensions.Options.ConfigurationExtensions"
          versions: ["7.*", "8.*"]
        - dependency-name: "Microsoft.Extensions.Configuration"
          versions: ["7.*", "8.*"]
        - dependency-name: "Microsoft.Extensions.Logging.Console"
          versions: [ "7.*", "8.*" ]
        - dependency-name: "Microsoft.Extensions.Diagnostics.HealthChecks"
          versions: [ "7.*", "8.*" ]
        - dependency-name: "Serilog.AspNetCore"
          versions: [ "7.*", "8.*" ]
        - dependency-name: "Microsoft.Extensions.Logging"
          versions: [ "7.*", "8.*" ]
        - dependency-name: "Microsoft.Extensions.Configuration.Json"
          versions: [ "7.*", "8.*" ]

    - package-ecosystem: "nuget"
      directory: "/platform/src/api/Platform.Api.Insight"
      schedule:
        interval: "weekly"
      commit-message:
        prefix: "[nuget] "
      ignore:
        - dependency-name: "Microsoft.Extensions.Configuration.Binder"
          versions: ["7.*", "8.*"]
        - dependency-name: "Microsoft.Extensions.Logging.Abstractions"
          versions: ["7.*", "8.*"]
        - dependency-name: "Microsoft.Extensions.Options"
          versions: ["7.*", "8.*"]
        - dependency-name: "Microsoft.Extensions.Options.ConfigurationExtensions"
          versions: ["7.*", "8.*"]
        - dependency-name: "Microsoft.Extensions.Configuration"
          versions: ["7.*", "8.*"]
        - dependency-name: "Microsoft.Extensions.Logging.Console"
          versions: [ "7.*", "8.*" ]
        - dependency-name: "Microsoft.Extensions.Diagnostics.HealthChecks"
          versions: [ "7.*", "8.*" ]
        - dependency-name: "Serilog.AspNetCore"
          versions: [ "7.*", "8.*" ]
        - dependency-name: "Microsoft.Extensions.Logging"
          versions: [ "7.*", "8.*" ]
        - dependency-name: "Microsoft.Extensions.Configuration.Json"
          versions: [ "7.*", "8.*" ]

    - package-ecosystem: "nuget"
      directory: "/platform/src/search/Platform.Search"
      schedule:
        interval: "weekly"
      commit-message:
        prefix: "[nuget] "
      ignore:
        - dependency-name: "Microsoft.Extensions.Configuration.Binder"
          versions: ["7.*", "8.*"]
        - dependency-name: "Microsoft.Extensions.Logging.Abstractions"
          versions: ["7.*", "8.*"]
        - dependency-name: "Microsoft.Extensions.Options"
          versions: ["7.*", "8.*"]
        - dependency-name: "Microsoft.Extensions.Options.ConfigurationExtensions"
          versions: ["7.*", "8.*"]
        - dependency-name: "Microsoft.Extensions.Configuration"
          versions: ["7.*", "8.*"]
        - dependency-name: "Microsoft.Extensions.Logging.Console"
          versions: [ "7.*", "8.*" ]
        - dependency-name: "Microsoft.Extensions.Diagnostics.HealthChecks"
          versions: [ "7.*", "8.*" ]
        - dependency-name: "Serilog.AspNetCore"
          versions: [ "7.*", "8.*" ]
        - dependency-name: "Microsoft.Extensions.Logging"
          versions: [ "7.*", "8.*" ]
        - dependency-name: "Microsoft.Extensions.Configuration.Json"
          versions: [ "7.*", "8.*" ]

    - package-ecosystem: "nuget"
      directory: "/platform/src/search/Platform.Search.App"
      schedule:
        interval: "weekly"
      commit-message:
        prefix: "[nuget] "
      ignore:
        - dependency-name: "Microsoft.Extensions.Configuration.Binder"
          versions: ["7.*", "8.*"]
        - dependency-name: "Microsoft.Extensions.Logging.Abstractions"
          versions: ["7.*", "8.*"]
        - dependency-name: "Microsoft.Extensions.Options"
          versions: ["7.*", "8.*"]
        - dependency-name: "Microsoft.Extensions.Options.ConfigurationExtensions"
          versions: ["7.*", "8.*"]
        - dependency-name: "Microsoft.Extensions.Configuration"
          versions: ["7.*", "8.*"]
        - dependency-name: "Microsoft.Extensions.Logging.Console"
          versions: [ "7.*", "8.*" ]
        - dependency-name: "Microsoft.Extensions.Diagnostics.HealthChecks"
          versions: [ "7.*", "8.*" ]
        - dependency-name: "Serilog.AspNetCore"
          versions: [ "7.*", "8.*" ]
        - dependency-name: "Microsoft.Extensions.Logging"
          versions: [ "7.*", "8.*" ]
        - dependency-name: "Microsoft.Extensions.Configuration.Json"
          versions: [ "7.*", "8.*" ]

    - package-ecosystem: "nuget"
      directory: "/platform/src/search/Platform.Search.Processor"
      schedule:
        interval: "weekly"
      commit-message:
        prefix: "[nuget] "
      ignore:
        - dependency-name: "Microsoft.Extensions.Configuration.Binder"
          versions: ["7.*", "8.*"]
        - dependency-name: "Microsoft.Extensions.Logging.Abstractions"
          versions: ["7.*", "8.*"]
        - dependency-name: "Microsoft.Extensions.Options"
          versions: ["7.*", "8.*"]
        - dependency-name: "Microsoft.Extensions.Options.ConfigurationExtensions"
          versions: ["7.*", "8.*"]
        - dependency-name: "Microsoft.Extensions.Configuration"
          versions: ["7.*", "8.*"]
        - dependency-name: "Microsoft.Extensions.Logging.Console"
          versions: [ "7.*", "8.*" ]
        - dependency-name: "Microsoft.Extensions.Diagnostics.HealthChecks"
          versions: [ "7.*", "8.*" ]
        - dependency-name: "Serilog.AspNetCore"
          versions: [ "7.*", "8.*" ]
        - dependency-name: "Microsoft.Extensions.Logging"
          versions: [ "7.*", "8.*" ]
        - dependency-name: "Microsoft.Extensions.Configuration.Json"
          versions: [ "7.*", "8.*" ]

    - package-ecosystem: "nuget"
      directory: "/platform/tests/Platform.ApiTests"
      schedule:
        interval: "weekly"
      commit-message:
        prefix: "[nuget] "
      ignore:
        - dependency-name: "Microsoft.Extensions.Logging.Console"
          versions: [ "7.*", "8.*" ]
        - dependency-name: "Microsoft.Extensions.Configuration.Binder"
          versions: ["7.*", "8.*"]
        - dependency-name: "Microsoft.Extensions.Logging.Abstractions"
          versions: ["7.*", "8.*"]
        - dependency-name: "Microsoft.Extensions.Options"
          versions: ["7.*", "8.*"]
        - dependency-name: "Microsoft.Extensions.Options.ConfigurationExtensions"
          versions: ["7.*", "8.*"]
        - dependency-name: "Microsoft.Extensions.Configuration"
          versions: ["7.*", "8.*"]
        - dependency-name: "Microsoft.Extensions.Diagnostics.HealthChecks"
          versions: [ "7.*", "8.*" ]
        - dependency-name: "Serilog.AspNetCore"
          versions: [ "7.*", "8.*" ]
        - dependency-name: "Microsoft.Extensions.Logging"
          versions: [ "7.*", "8.*" ]
        - dependency-name: "Microsoft.Extensions.Configuration.Json"
          versions: [ "7.*", "8.*" ]

    - package-ecosystem: "nuget"
      directory: "/platform/tests/Platform.Tests"
      schedule:
        interval: "weekly"
      commit-message:
        prefix: "[nuget] "
      ignore:
        - dependency-name: "Microsoft.Extensions.Logging.Console"
          versions: [ "7.*", "8.*" ]
        - dependency-name: "Microsoft.Extensions.Configuration.Binder"
          versions: ["7.*", "8.*"]
        - dependency-name: "Microsoft.Extensions.Logging.Abstractions"
          versions: ["7.*", "8.*"]
        - dependency-name: "Microsoft.Extensions.Options"
          versions: ["7.*", "8.*"]
        - dependency-name: "Microsoft.Extensions.Options.ConfigurationExtensions"
          versions: ["7.*", "8.*"]
        - dependency-name: "Microsoft.Extensions.Configuration"
          versions: ["7.*", "8.*"]
        - dependency-name: "Microsoft.Extensions.Diagnostics.HealthChecks"
          versions: [ "7.*", "8.*" ]
        - dependency-name: "Serilog.AspNetCore"
          versions: [ "7.*", "8.*" ]
        - dependency-name: "Microsoft.Extensions.Logging"
          versions: [ "7.*", "8.*" ]
        - dependency-name: "Microsoft.Extensions.Configuration.Json"
          versions: [ "7.*", "8.*" ]
          
    - package-ecosystem: "npm"
      directory: "/prototype/src"
      schedule:
        interval: "weekly"
      commit-message:
        prefix: "[npm] "

    - package-ecosystem: "terraform"
      directory: "/prototype/terraform"
      schedule:
        interval: "weekly"
      commit-message:
        prefix: "[terraform] "

    - package-ecosystem: "npm"
      directory: "/web/src/Web.App"
      registries:
        - npm-azure-artifacts
      schedule:
        interval: "weekly"
      commit-message:
        prefix: "[npm] "

    - package-ecosystem: "terraform"
      directory: "/web/terraform"
      schedule:
        interval: "weekly"
      commit-message:
        prefix: "[terraform] "

    - package-ecosystem: "nuget"
      directory: "/web/src/Web.App"
      schedule:
        interval: "weekly"
      commit-message:
        prefix: "[nuget] "

    - package-ecosystem: "nuget"
      directory: "/web/src/Web.Identity"
      schedule:
        interval: "weekly"
      commit-message:
        prefix: "[nuget] "

    - package-ecosystem: "nuget"
      directory: "/web/tests/Web.A11yTests"
      schedule:
        interval: "weekly"
      commit-message:
        prefix: "[nuget] "

    - package-ecosystem: "nuget"
      directory: "/web/tests/Web.E2ETests"
      schedule:
        interval: "weekly"
      commit-message:
        prefix: "[nuget] "

    - package-ecosystem: "nuget"
      directory: "/web/tests/Web.Integration.Tests"
      schedule:
        interval: "weekly"
      commit-message:
        prefix: "[nuget] "

    - package-ecosystem: "nuget"
      directory: "/web/tests/Web.Tests"
      schedule:
        interval: "weekly"
      commit-message:
        prefix: "[nuget] "