  version: 2
  registries:
    npm-azure-artifacts:
      type: npm-registry
      url: https://dfe-ssp.pkgs.visualstudio.com/s198-DfE-Benchmarking-service/_packaging/education-benchmarking/npm/registry/
      username: ${{ secrets.AZURE_DEVOPS_USER }}
      password: ${{ secrets.AZURE_DEVOPS_PAT }}

  updates:
    - package-ecosystem: "terraform"
      directory: "/core-infrastructure/terraform"
      schedule:
        interval: "monthly"
      commit-message:
        prefix: "[terraform] "

    - package-ecosystem: "npm"
      directory: "/front-end-components"
      schedule:
        interval: "monthly"
      commit-message:
        prefix: "[npm] "
      open-pull-requests-limit: 10
      # React v18 to v19 major version upgrade affects other packages as at
      # Feb 2025 due to broken peer dependencies. Ignore for the time being.
      # Feb 2025 html-to-image versions after 1.11.11 cause issues for
      # the styling of front-end-components charts in images.
      # Ignore until resolved.
      ignore:
        - dependency-name: "react"
          versions: [">=19.0.0"]
        - dependency-name: "react-dom"
          versions: [">=19.0.0"]
        - dependency-name: "@types/react"
          versions: [">=19.0.0"]
        - dependency-name: "@types/react-dom"
          versions: [">=19.0.0"]
        - dependency-name: "html-to-image"
        - dependency-name: "recharts"
          versions: [">=3.0.0"]

    - package-ecosystem: "terraform"
      directory: "/platform/terraform"
      schedule:
        interval: "monthly"
      commit-message:
        prefix: "[terraform] "

    - package-ecosystem: "nuget"
      directory: "/platform/src/abstractions/Platform.Functions"
      schedule:
        interval: "monthly"
      commit-message:
        prefix: "[nuget] "

    - package-ecosystem: "nuget"
      directory: "/platform/src/abstractions/Platform.Infrastructure"
      schedule:
        interval: "monthly"
      commit-message:
        prefix: "[nuget] "

    - package-ecosystem: "nuget"
      directory: "/platform/src/apis/Platform.Api.Benchmark"
      schedule:
        interval: "monthly"
      commit-message:
        prefix: "[nuget] "

    - package-ecosystem: "npm"
      directory: "/platform/src/apis/Platform.Api.ChartRendering"
      schedule:
        interval: "monthly"
      commit-message:
        prefix: "[npm] "

    - package-ecosystem: "nuget"
      directory: "/platform/src/apis/Platform.Api.Establishment"
      schedule:
        interval: "monthly"
      commit-message:
        prefix: "[nuget] "

    - package-ecosystem: "nuget"
      directory: "/platform/src/apis/Platform.Api.Insight"
      schedule:
        interval: "monthly"
      commit-message:
        prefix: "[nuget] "

    - package-ecosystem: "nuget"
      directory: "/platform/src/apis/Platform.Api.LocalAuthorityFinances"
      schedule:
        interval: "monthly"
      commit-message:
        prefix: "[nuget] "

    - package-ecosystem: "nuget"
      directory: "/platform/src/apis/Platform.Api.NonFinancial"
      schedule:
        interval: "monthly"
      commit-message:
        prefix: "[nuget] "

    - package-ecosystem: "nuget"
      directory: "/platform/src/apis/Platform.Api.Content"
      schedule:
        interval: "monthly"
      commit-message:
        prefix: "[nuget] "

    - package-ecosystem: "nuget"
      directory: "/platform/src/search/Platform.Search"
      schedule:
        interval: "monthly"
      commit-message:
        prefix: "[nuget] "

    - package-ecosystem: "nuget"
      directory: "/platform/src/search/Platform.Search.App"
      schedule:
        interval: "monthly"
      commit-message:
        prefix: "[nuget] "

    - package-ecosystem: "nuget"
      directory: "/platform/src/search/Platform.Search.Processor"
      schedule:
        interval: "monthly"
      commit-message:
        prefix: "[nuget] "

    - package-ecosystem: "nuget"
      directory: "/platform/tests/Platform.ApiTests"
      schedule:
        interval: "monthly"
      commit-message:
        prefix: "[nuget] "

    - package-ecosystem: "nuget"
      directory: "/platform/tests/Platform.Tests"
      schedule:
        interval: "monthly"
      commit-message:
        prefix: "[nuget] "

    - package-ecosystem: "npm"
      directory: "/prototype/src"
      schedule:
        interval: "monthly"
      commit-message:
        prefix: "[npm] "

    - package-ecosystem: "terraform"
      directory: "/prototype/terraform"
      schedule:
        interval: "monthly"
      commit-message:
        prefix: "[terraform] "

    - package-ecosystem: "npm"
      directory: "/web/src/Web.App"
      registries:
        - npm-azure-artifacts
      schedule:
        interval: "hourly"
      commit-message:
        prefix: "[npm] "
      allow:
        - dependency-name: "front-end"

    - package-ecosystem: "npm"
      directory: "/web/src/Web.App"
      registries:
        - npm-azure-artifacts
      schedule:
        interval: "monthly"
      commit-message:
        prefix: "[npm] "

    - package-ecosystem: "terraform"
      directory: "/web/terraform"
      schedule:
        interval: "monthly"
      commit-message:
        prefix: "[terraform] "

    - package-ecosystem: "nuget"
      directory: "/web/src/Web.App"
      schedule:
        interval: "monthly"
      commit-message:
        prefix: "[nuget] "

    - package-ecosystem: "npm"
      directory: "/web/src/Web.Shutter"
      registries:
        - npm-azure-artifacts
      schedule:
        interval: "monthly"
      commit-message:
        prefix: "[npm] "

    - package-ecosystem: "nuget"
      directory: "/web/tests/Web.A11yTests"
      schedule:
        interval: "monthly"
      commit-message:
        prefix: "[nuget] "

    - package-ecosystem: "nuget"
      directory: "/web/tests/Web.E2ETests"
      schedule:
        interval: "monthly"
      commit-message:
        prefix: "[nuget] "

    - package-ecosystem: "nuget"
      directory: "/web/tests/Web.Integration.Tests"
      schedule:
        interval: "monthly"
      commit-message:
        prefix: "[nuget] "

    - package-ecosystem: "nuget"
      directory: "/web/tests/Web.Tests"
      schedule:
        interval: "monthly"
      commit-message:
        prefix: "[nuget] "
