# yaml-language-server: $schema=https://json.schemastore.org/pre-commit-config.json
repos:
  # built-in hooks run repo-wide
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: end-of-file-fixer
      - id: no-commit-to-branch
        args: [
            "-p",
            # regex negates that defined in ./pipelines/common/validate-branch.yaml
            "^(?!(refs\/heads\/)?main$|(refs\/heads\/)?(feature|bugfix|hotfix|exp|tech-debt|doc|prototype|dependabot|chore)\/(\\d+\/){0,1}[a-z0-9-]+).*$",
          ]
      - id: trailing-whitespace

  # hooks-per-project in monorepo using sub-re-commit
  - repo: https://github.com/ddanier/sub-pre-commit.git
    rev: v4.2.0 # MUST match your pre-commit version
    hooks:
      - id: sub-pre-commit
        alias: core-infrastructure
        name: "pre-commit for core-infrastructure"
        args: ["-p", "core-infrastructure"]
        files: "^core-infrastructure/.*"
        stages: ["pre-commit"]

      - id: sub-pre-commit
        alias: data-pipeline
        name: "pre-commit for data-pipeline"
        args: ["-p", "data-pipeline"]
        files: "^data-pipeline/.*"
        stages: ["pre-commit"]

      - id: sub-pre-commit
        alias: documentation
        name: "pre-commit for documentation"
        args: ["-p", "documentation"]
        files: "^documentation/.*"
        stages: ["pre-commit"]

      - id: sub-pre-commit
        alias: front-end-components
        name: "pre-commit for front-end-components"
        args: ["-p", "front-end-components"]
        files: "^front-end-components/.*"
        stages: ["pre-commit"]

      - id: sub-pre-commit
        alias: pipelines
        name: "pre-commit for pipelines"
        args: ["-p", "pipelines"]
        files: "^pipelines/.*"
        stages: ["pre-commit"]

      - id: sub-pre-commit
        alias: platform
        name: "pre-commit for platform"
        args: ["-p", "platform"]
        files: "^platform/.*"
        stages: ["pre-commit"]

      - id: sub-pre-commit
        alias: prototype
        name: "pre-commit for prototype"
        args: ["-p", "prototype"]
        files: "^prototype/.*"
        stages: ["pre-commit"]

      - id: sub-pre-commit
        alias: support-analytics
        name: "pre-commit for support-analytics"
        args: ["-p", "support-analytics"]
        files: "^support-analytics/.*"
        stages: ["pre-commit"]

      - id: sub-pre-commit
        alias: web
        name: "pre-commit for web"
        args: ["-p", "web"]
        files: "^web/(?!src/Web.App).*"
        stages: ["pre-commit"]
      - id: sub-pre-commit
        alias: web-app
        name: "pre-commit for web/src/Web.App"
        args: ["-p", "web/src/Web.App"]
        files: "^web/src/Web.App.*"
        stages: ["pre-commit"]
