version: '3.7'

services:
  azurite:
    container_name: "azurite-platform"
    image: "mcr.microsoft.com/azure-storage/azurite"
    ports: 
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    volumes:
      - "./azurite/data:/data"
  sqldata:
    container_name: "sqldata-platform"
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - "./sql/data:/var/opt/mssql/data"
      