version: '3.7'

services:
  azurite:
    container_name: "azurite"
    hostname: "azurite"
    image: "mcr.microsoft.com/azure-storage/azurite"
    ports: 
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    volumes:
      - "./azurite/data:/data"