version: '3.7'

services:
  azurite:
    container_name: "azurite-platform"
    image: "mcr.microsoft.com/azure-storage/azurite:3.31.0"
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    volumes:
      - "./azurite/data:/data"
  sqldata:
    container_name: "sqldata-platform"
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - "./sql/data:/var/opt/mssql/data"
  cache:
    container_name: "redis-platform"
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
    command:
      - /bin/sh
      - -c
      - redis-server --save 20 1 --loglevel warning --requirepass "$${REDIS_PASSWORD:?REDIS_PASSWORD variable is not set}"
    env_file:
      - redis.env
    volumes:
      - "./redis/data:/data"
