from .local_authority import (
    la_db_financial_projections,
    la_db_non_financial_projections,
    la_statistical_neighbours_projections,
)

nonaggregated_income_category_map = {
    "academies": {
        "BNCH11142 (Other Revenue)": "Income_Other DFE grants",
        "BNCH11151 (Other Government Revenue Grants)": "Income_Other grants",
        "BNCH11162 (Academies)": "Income_Academies",
        "BNCH11161 (Government source (non-grant))": "Income_Government source",
        "BNCH11202 (Income from catering)": "Income_Catering services",
        "BNCH11203 (Receipts from supply teacher insurance claims)": "Income_Receipts supply teacher insurance",
        "BNCH11300T (Voluntary income)": "Income_Donations and voluntary funds",
        "BNCH11204 (Other income - revenue)": "Income_Other self-generated income",
        "BNCH11400T (Investment income)": "Income_Investment income",
        "BNCH11141 (SEN)": "Income_Targeted grants",
        "BNCH44001 (Closing Balance (Restricted and Unrestricted Funds))": "Revenue reserve",
        "BNCH21707 (Direct revenue financing (Revenue contributions to capital))": "Income_Direct revenue finance",
    },
    "central_services": {
        "BNCH11142 (Other Revenue)": "Income_Other DFE grants",
        "BNCH11151 (Other Government Revenue Grants)": "Income_Other grants",
        "BNCH11162 (Academies)": "Income_Academies",
        "BNCH11161 (Government source (non-grant))": "Income_Government source",
        "BNCH11202 (Income from catering)": "Income_Catering services",
        "BNCH11203 (Receipts from supply teacher insurance claims)": "Income_Receipts supply teacher insurance",
        "BNCH11300T (Voluntary income)": "Income_Donations and voluntary funds",
        "BNCH11204 (Other income - revenue)": "Income_Other self-generated income",
        "BNCH11400T (Investment income)": "Income_Investment income",
        "BNCH11141 (SEN)": "Income_Targeted grants",
        "BNCH44001CS (Closing Balance (Restricted and Unrestricted Funds))": "Revenue reserve",
        "BNCH21707 (Direct revenue financing (Revenue contributions to capital))": "Income_Direct revenue finance",
    },
    "maintained_schools": {
        "I06  Other government grants": "Income_Other DFE grants",
        "I07  Other grants and payments": "Income_Other grants",
        "I08  Income from facilities and services": "Income_Facilities and services",
        "I09  Income from catering": "Income_Catering services",
        "I10  Receipts from supply teacher insurance claims": "Income_Receipts supply teacher insurance",
        "I13  Donations and or private funds": "Income_Donations and voluntary funds",
        "Total Income   I01 to I18": "Total Income",
        "Revenue Reserve   B01 plus B02 plus B06": "Revenue reserve",
        "Direct Grant": "Income_Direct grants",
        "Targeted Grants": "Income_Targeted grants",
        "Self Generated Funding": "Income_Total self generated funding",
        "Community Grants": "Income_Other Revenue Income",
        "CI04 Direct revenue financing": "Income_Direct revenue finance",
    },
}

nonaggregated_cost_category_map = {
    "academies": {
        "BNCH21101 (Teaching staff)": "Teaching and Teaching support staff_Teaching staff",
        "BNCH21102 (Supply teaching staff - extra note in guidance)": "Teaching and Teaching support staff_Supply teaching staff",
        "BNCH21103 (Education support staff)": "Teaching and Teaching support staff_Education support staff",
        "BNCH21104 (Administrative and clerical staff)": "Non-educational support staff and services_Administrative and clerical staff",
        "BNCH21105 (Premises staff)": "Premises staff and services_Premises staff",
        "BNCH21106 (Catering staff)": "Catering staff and supplies_Catering staff",
        "BNCH21107 (Other staff)": "Non-educational support staff and services_Other staff",
        "BNCH21201 (Indirect employee expenses)": "Other costs_Indirect employee expenses",
        "BNCH21202 (Staff development and training)": "Other costs_Staff development and training",
        "BNCH21203 (Staff-related insurance)": "Other costs_Staff-related insurance",
        "BNCH21204 (Supply teacher insurance)": "Other costs_Supply teacher insurance",
        "BNCH21301 (Maintenance of premises)": "Premises staff and services_Maintenance of premises",
        "BNCH21405 (Grounds maintenance)": "Other costs_Grounds maintenance",
        "BNCH21401 (Cleaning and caretaking)": "Premises staff and services_Cleaning and caretaking",
        "BNCH21402 (Water and sewerage)": "Utilities_Water and sewerage",
        "BNCH21403 (Energy)": "Utilities_Energy",
        "BNCH21404 (Rent and rates)": "Other costs_Rent and rates",
        "BNCH21406 (Other occupation costs)": "Premises staff and services_Other occupation costs",
        "BNCH21501 (Special facilities)": "Other costs_Special facilities",
        "BNCH21601 (Learning resources (not ICT equipment))": "Educational supplies_Learning resources (not ICT equipment)",
        "BNCH21602 (ICT learning resources)": "Educational ICT_ICT learning resources",
        "BNCH21603 (Examination fees)": "Educational supplies_Examination fees",
        "BNCH21604 (Educational Consultancy)": "Teaching and Teaching support staff_Educational consultancy",
        "BNCH21706 (Administrative supplies - non educational)": "Administrative supplies_Administrative supplies (non educational)",
        "BNCH21606 (Agency supply teaching staff)": "Teaching and Teaching support staff_Agency supply teaching staff",
        "BNCH21701 (Catering supplies)": "Catering staff and supplies_Catering supplies",
        "BNCH21705 (Other insurance premiums)": "Other costs_Other insurance premiums",
        "BNCH21702 (Professional Services - non-curriculum)": "Non-educational support staff and services_Professional services (non-curriculum)",
        "BNCH21703 (Auditor costs)": "Non-educational support staff and services_Audit cost",
        "BNCH21801 (Interest charges for Loan and bank)": "Other costs_Interest charges for loan and bank",
        "BNCH21802 (PFI Charges)": "Other costs_PFI charges"
    },
    "central_services": {
        "BNCH21101 (Teaching staff)": "Teaching and Teaching support staff_Teaching staff",
        "BNCH21102 (Supply teaching staff - extra note in guidance)": "Teaching and Teaching support staff_Supply teaching staff",
        "BNCH21103 (Education support staff)": "Teaching and Teaching support staff_Education support staff",
        "BNCH21104 (Administrative and clerical staff)": "Non-educational support staff and services_Administrative and clerical staff",
        "BNCH21105 (Premises staff)": "Premises staff and services_Premises staff",
        "BNCH21106 (Catering staff)": "Catering staff and supplies_Catering staff",
        "BNCH21107 (Other staff)": "Non-educational support staff and services_Other staff",
        "BNCH21201 (Indirect employee expenses)": "Other costs_Indirect employee expenses",
        "BNCH21202 (Staff development and training)": "Other costs_Staff development and training",
        "BNCH21203 (Staff-related insurance)": "Other costs_Staff-related insurance",
        "BNCH21204 (Supply teacher insurance)": "Other costs_Supply teacher insurance",
        "BNCH21301 (Maintenance of premises)": "Premises staff and services_Maintenance of premises",
        "BNCH21405 (Grounds maintenance)": "Other costs_Grounds maintenance",
        "BNCH21401 (Cleaning and caretaking)": "Premises staff and services_Cleaning and caretaking",
        "BNCH21402 (Water and sewerage)": "Utilities_Water and sewerage",
        "BNCH21403 (Energy)": "Utilities_Energy",
        "BNCH21404 (Rent and rates)": "Other costs_Rent and rates",
        "BNCH21406 (Other occupation costs)": "Premises staff and services_Other occupation costs",
        "BNCH21501 (Special facilities)": "Other costs_Special facilities",
        "BNCH21601 (Learning resources (not ICT equipment))": "Educational supplies_Learning resources (not ICT equipment)",
        "BNCH21602 (ICT learning resources)": "Educational ICT_ICT learning resources",
        "BNCH21603 (Examination fees)": "Educational supplies_Examination fees",
        "BNCH21604 (Educational Consultancy)": "Teaching and Teaching support staff_Educational consultancy",
        "BNCH21706 (Administrative supplies - non educational)": "Administrative supplies_Administrative supplies (non educational)",
        "BNCH21606 (Agency supply teaching staff)": "Teaching and Teaching support staff_Agency supply teaching staff",
        "BNCH21701 (Catering supplies)": "Catering staff and supplies_Catering supplies",
        "BNCH21705 (Other insurance premiums)": "Other costs_Other insurance premiums",
        "BNCH21702 (Professional Services - non-curriculum)": "Non-educational support staff and services_Professional services (non-curriculum)",
        "BNCH21703 (Auditor costs)": "Non-educational support staff and services_Audit cost",
        "BNCH21801 (Interest charges for Loan and bank)": "Other costs_Interest charges for loan and bank",
        "BNCH21802 (PFI Charges)": "Other costs_PFI charges",
    },
    "maintained_schools": {
        "LA (code)": "LA Code",
        "LA (name)": "LA Name",
        "E06 Catering staff": "Catering staff and supplies_Catering staff",
        "E25  Catering supplies": "Catering staff and supplies_Catering supplies",
        "E21  Exam fees": "Educational supplies_Examination fees",
        "E19  Learning resources (not ICT equipment)": "Educational supplies_Learning resources (not ICT equipment)",
        "E05 Administrative and clerical staff": "Non-educational support staff and services_Administrative and clerical staff",
        "E07  Cost of other staff": "Non-educational support staff and services_Other staff",
        "E28a  Bought in professional services - other (except PFI)": "Non-educational support staff and services_Professional services (non-curriculum)",
        "E13  Grounds maintenance and improvement": "Other costs_Grounds maintenance",
        "E08  Indirect employee expenses": "Other costs_Indirect employee expenses",
        "E29  Loan interest": "Other costs_Interest charges for loan and bank",
        "E23  Other insurance premiums": "Other costs_Other insurance premiums",
        "E28b Bought in professional services - other (PFI)": "Other costs_PFI charges",
        "E17  Rates": "Other costs_Rent and rates",
        "E24  Special facilities ": "Other costs_Special facilities",
        "E09  Development and training": "Other costs_Staff development and training",
        "E11  Staff related insurance": "Other costs_Staff-related insurance",
        "E10  Supply teacher insurance": "Other costs_Supply teacher insurance",
        "E14  Cleaning and caretaking": "Premises staff and services_Cleaning and caretaking",
        "E12  Building maintenance and improvement": "Premises staff and services_Maintenance of premises",
        "E18  Other occupation costs": "Premises staff and services_Other occupation costs",
        "E04  Premises staff": "Premises staff and services_Premises staff",
        "E26 Agency supply teaching staff": "Teaching and Teaching support staff_Agency supply teaching staff",
        "E03 Education support staff": "Teaching and Teaching support staff_Education support staff",
        "E27  Bought in professional services - curriculum": "Teaching and Teaching support staff_Educational consultancy",
        "E02  Supply teaching staff": "Teaching and Teaching support staff_Supply teaching staff",
        "E01  Teaching Staff": "Teaching and Teaching support staff_Teaching staff",
        "E16  Energy": "Utilities_Energy",
        "E15  Water and sewerage": "Utilities_Water and sewerage",
        "PFI": "Is PFI School",
        "Total Expenditure  E01 to E32": "Total Expenditure",
        "E31  Community focused school staff": "Other costs_School staff",
        "E32 Community focused school costs": "Other costs_School costs",
    },
}

census_column_map = {
    "headcount of pupils": "Number of pupils (headcount)",
    "fte pupils": "Number of pupils",
    "Total Number of Non-Classroom-based School Support Staff, (Other school support staff plus Administrative staff plus Technicians and excluding Auxiliary staff (Full-Time Equivalent)": "NonClassroomSupportStaffFTE",
    "Total Number of Non Classroom-based School Support Staff, Excluding Auxiliary Staff (Headcount)": "NonClassroomSupportStaffHeadcount",
    "% of pupils known to be eligible for free school meals": "Percentage Free school meals",
}

rag_category_settings = {
    "Teaching and Teaching support staff": {
        "type": "Pupil",
        "outstanding_10": [
            "amber",
            "amber",
            "amber",
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "red",
            "red",
        ],
        "outstanding": [
            "amber",
            "amber",
            "amber",
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "amber",
            "red",
        ],
        "other_10": [
            "red",
            "red",
            "amber",
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "red",
            "red",
        ],
        "other": [
            "red",
            "amber",
            "amber",
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "amber",
            "red",
        ],
    },
    "Non-educational support staff and services": {
        "type": "Pupil",
        "outstanding_10": [
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "amber",
            "amber",
            "amber",
            "red",
            "red",
        ],
        "outstanding": [
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "amber",
            "amber",
            "amber",
            "red",
            "red",
        ],
        "other_10": [
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "amber",
            "amber",
            "amber",
            "red",
            "red",
        ],
        "other": [
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "amber",
            "amber",
            "amber",
            "red",
            "red",
        ],
    },
    "Educational supplies": {
        "type": "Pupil",
        "outstanding_10": [
            "amber",
            "amber",
            "amber",
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "red",
            "red",
        ],
        "outstanding": [
            "amber",
            "amber",
            "amber",
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "amber",
            "red",
        ],
        "other_10": [
            "red",
            "red",
            "amber",
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "red",
            "red",
        ],
        "other": [
            "red",
            "amber",
            "amber",
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "amber",
            "red",
        ],
    },
    "Educational ICT": {
        "type": "Pupil",
        "outstanding_10": [
            "amber",
            "amber",
            "amber",
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "red",
            "red",
        ],
        "outstanding": [
            "amber",
            "amber",
            "amber",
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "amber",
            "red",
        ],
        "other_10": [
            "red",
            "red",
            "amber",
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "red",
            "red",
        ],
        "other": [
            "red",
            "amber",
            "amber",
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "amber",
            "red",
        ],
    },
    "Premises staff and services": {
        "type": "Building",
        "outstanding_10": [
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "amber",
            "amber",
            "amber",
            "red",
            "red",
        ],
        "outstanding": [
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "amber",
            "amber",
            "amber",
            "red",
            "red",
        ],
        "other_10": [
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "amber",
            "amber",
            "amber",
            "red",
            "red",
        ],
        "other": [
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "amber",
            "amber",
            "amber",
            "red",
            "red",
        ],
    },
    "Utilities": {
        "type": "Building",
        "outstanding_10": [
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "amber",
            "amber",
            "amber",
            "red",
            "red",
        ],
        "outstanding": [
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "amber",
            "amber",
            "amber",
            "red",
            "red",
        ],
        "other_10": [
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "amber",
            "amber",
            "amber",
            "red",
            "red",
        ],
        "other": [
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "amber",
            "amber",
            "amber",
            "red",
            "red",
        ],
    },
    "Administrative supplies": {
        "sub_categories": {"Energy", "Water and sewerage"},
        "type": "Pupil",
        "outstanding_10": [
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "amber",
            "amber",
            "amber",
            "red",
            "red",
        ],
        "outstanding": [
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "amber",
            "amber",
            "amber",
            "red",
            "red",
        ],
        "other_10": [
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "amber",
            "amber",
            "amber",
            "red",
            "red",
        ],
        "other": [
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "amber",
            "amber",
            "amber",
            "red",
            "red",
        ],
    },
    "Catering staff and supplies": {
        "sub_categories": {"Energy", "Water and sewerage"},
        "type": "Pupil",
        "outstanding_10": [
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "amber",
            "amber",
            "amber",
            "red",
            "red",
        ],
        "outstanding": [
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "amber",
            "amber",
            "amber",
            "red",
            "red",
        ],
        "other_10": [
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "amber",
            "amber",
            "amber",
            "red",
            "red",
        ],
        "other": [
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "amber",
            "amber",
            "amber",
            "red",
            "red",
        ],
    },
    "Other costs": {
        "type": "Pupil",
        "outstanding_10": [
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "amber",
            "amber",
            "amber",
            "red",
            "red",
        ],
        "outstanding": [
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "amber",
            "amber",
            "amber",
            "red",
            "red",
        ],
        "other_10": [
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "amber",
            "amber",
            "amber",
            "red",
            "red",
        ],
        "other": [
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "amber",
            "amber",
            "amber",
            "red",
            "red",
        ],
    },
}

cdc_generated_columns = [
    "Total Internal Floor Area",
    "Age Average Score",
    "Building Age",
]

sen_generated_columns = [
    "EHC plan",
    "SEN support",
    "Percentage SEN",
    "Percentage with EHC",
    "Percentage without EHC",
    "Percentage Primary Need SPLD",
    "Percentage Primary Need MLD",
    "Percentage Primary Need SLD",
    "Percentage Primary Need PMLD",
    "Percentage Primary Need SEMH",
    "Percentage Primary Need SLCN",
    "Percentage Primary Need HI",
    "Percentage Primary Need VI",
    "Percentage Primary Need MSI",
    "Percentage Primary Need PD",
    "Percentage Primary Need ASD",
    "Percentage Primary Need OTH",
]

trust_db_projections = {
    "Company Registration Number": "CompanyNumber",
    "Trust Financial Position": "TrustPosition",
    "Total Income": "TotalIncome",
    "Total Expenditure": "TotalExpenditure",
    "Total Internal Floor Area": "TotalInternalFloorArea",
    "Number of pupils": "TotalPupils",
    "In year balance": "InYearBalance",
    "Revenue reserve": "RevenueReserve",
    "Income_Total grant funding": "TotalGrantFunding",
    "Income_Total self generated funding": "TotalSelfGeneratedFunding",
    "Income_Direct grants": "DirectGrants",
    "Income_Targeted grants": "TargetedGrants",
    "Income_Other DFE grants": "OtherDfeGrants",
    "Income_Other grants": "OtherIncomeGrants",
    "Income_Government source": "GovernmentSource",
    "Income_Other Revenue Income": "CommunityGrants",
    "Income_Academies": "Academies",
    "Income_Facilities and services": "IncomeFacilitiesServices",
    "Income_Catering services": "IncomeCateringServices",
    "Income_Donations and voluntary funds": "DonationsVoluntaryFunds",
    "Income_Receipts supply teacher insurance": "ReceiptsSupplyTeacherInsuranceClaims",
    "Income_Investment income": "InvestmentIncome",
    "Income_Other self-generated income": "OtherSelfGeneratedIncome",
    "Teaching and Teaching support staff_Total": "TotalTeachingSupportStaffCosts",
    "Teaching and Teaching support staff_Teaching staff": "TeachingStaffCosts",
    "Teaching and Teaching support staff_Supply teaching staff": "SupplyTeachingStaffCosts",
    "Teaching and Teaching support staff_Educational consultancy": "EducationalConsultancyCosts",
    "Teaching and Teaching support staff_Education support staff": "EducationSupportStaffCosts",
    "Teaching and Teaching support staff_Agency supply teaching staff": "AgencySupplyTeachingStaffCosts",
    "Non-educational support staff and services_Total": "TotalNonEducationalSupportStaffCosts",
    "Non-educational support staff and services_Administrative and clerical staff": "AdministrativeClericalStaffCosts",
    "Non-educational support staff and services_Audit cost": "AuditorsCosts",
    "Non-educational support staff and services_Other staff": "OtherStaffCosts",
    "Non-educational support staff and services_Professional services (non-curriculum)": "ProfessionalServicesNonCurriculumCosts",
    "Educational supplies_Total": "TotalEducationalSuppliesCosts",
    "Educational supplies_Examination fees": "ExaminationFeesCosts",
    "Educational supplies_Learning resources (not ICT equipment)": "LearningResourcesNonIctCosts",
    "Educational ICT_ICT learning resources": "LearningResourcesIctCosts",
    "Premises staff and services_Total": "TotalPremisesStaffServiceCosts",
    "Premises staff and services_Cleaning and caretaking": "CleaningCaretakingCosts",
    "Premises staff and services_Maintenance of premises": "MaintenancePremisesCosts",
    "Premises staff and services_Other occupation costs": "OtherOccupationCosts",
    "Premises staff and services_Premises staff": "PremisesStaffCosts",
    "Utilities_Total": "TotalUtilitiesCosts",
    "Utilities_Energy": "EnergyCosts",
    "Utilities_Water and sewerage": "WaterSewerageCosts",
    "Administrative supplies_Administrative supplies (non educational)": "AdministrativeSuppliesNonEducationalCosts",
    "Catering staff and supplies_Total": "TotalGrossCateringCosts",
    "Catering staff and supplies_Net Costs": "TotalNetCateringCostsCosts",
    "Catering staff and supplies_Catering staff": "CateringStaffCosts",
    "Catering staff and supplies_Catering supplies": "CateringSuppliesCosts",
    "Other costs_Total": "TotalOtherCosts",
    "Other costs_Grounds maintenance": "GroundsMaintenanceCosts",
    "Other costs_Indirect employee expenses": "IndirectEmployeeExpenses",
    "Other costs_Interest charges for loan and bank": "InterestChargesLoanBank",
    "Other costs_Other insurance premiums": "OtherInsurancePremiumsCosts",
    "Other costs_PFI charges": "PrivateFinanceInitiativeCharges",
    "Other costs_Rent and rates": "RentRatesCosts",
    "Other costs_Special facilities": "SpecialFacilitiesCosts",
    "Other costs_Staff development and training": "StaffDevelopmentTrainingCosts",
    "Other costs_Staff-related insurance": "StaffRelatedInsuranceCosts",
    "Other costs_Supply teacher insurance": "SupplyTeacherInsurableCosts",
    "Total Income_CS": "TotalIncomeCS",
    "Total Expenditure_CS": "TotalExpenditureCS",
    "In year balance_CS": "InYearBalanceCS",
    "Income_Total grant funding_CS": "TotalGrantFundingCS",
    "Income_Total self generated funding_CS": "TotalSelfGeneratedFundingCS",
    "Income_Direct grants_CS": "DirectGrantsCS",
    "Income_Other DFE grants_CS": "OtherDfeGrantsCS",
    "Income_Other grants_CS": "OtherIncomeGrantsCS",
    "Income_Government source_CS": "GovernmentSourceCS",
    "Income_Other Revenue Income_CS": "CommunityGrantsCS",
    "Income_Academies_CS": "AcademiesCS",
    "Income_Facilities and services_CS": "IncomeFacilitiesServicesCS",
    "Income_Catering services_CS": "IncomeCateringServicesCS",
    "Income_Donations and voluntary funds_CS": "DonationsVoluntaryFundsCS",
    "Income_Receipts supply teacher insurance_CS": "ReceiptsSupplyTeacherInsuranceClaimsCS",
    "Income_Investment income_CS": "InvestmentIncomeCS",
    "Income_Other self-generated income_CS": "OtherSelfGeneratedIncomeCS",
    "Teaching and Teaching support staff_Total_CS": "TotalTeachingSupportStaffCostsCS",
    "Teaching and Teaching support staff_Teaching staff_CS": "TeachingStaffCostsCS",
    "Teaching and Teaching support staff_Supply teaching staff_CS": "SupplyTeachingStaffCostsCS",
    "Teaching and Teaching support staff_Educational consultancy_CS": "EducationalConsultancyCostsCS",
    "Teaching and Teaching support staff_Education support staff_CS": "EducationSupportStaffCostsCS",
    "Teaching and Teaching support staff_Agency supply teaching staff_CS": "AgencySupplyTeachingStaffCostsCS",
    "Non-educational support staff and services_Total_CS": "TotalNonEducationalSupportStaffCostsCS",
    "Non-educational support staff and services_Administrative and clerical staff_CS": "AdministrativeClericalStaffCostsCS",
    "Non-educational support staff and services_Audit cost_CS": "AuditorsCostsCS",
    "Non-educational support staff and services_Other staff_CS": "OtherStaffCostsCS",
    "Non-educational support staff and services_Professional services (non-curriculum)_CS": "ProfessionalServicesNonCurriculumCostsCS",
    "Educational supplies_Total_CS": "TotalEducationalSuppliesCostsCS",
    "Educational supplies_Examination fees_CS": "ExaminationFeesCostsCS",
    "Educational supplies_Learning resources (not ICT equipment)_CS": "LearningResourcesNonIctCostsCS",
    "Educational ICT_ICT learning resources_CS": "LearningResourcesIctCostsCS",
    "Premises staff and services_Total_CS": "TotalPremisesStaffServiceCostsCS",
    "Premises staff and services_Cleaning and caretaking_CS": "CleaningCaretakingCostsCS",
    "Premises staff and services_Maintenance of premises_CS": "MaintenancePremisesCostsCS",
    "Premises staff and services_Other occupation costs_CS": "OtherOccupationCostsCS",
    "Premises staff and services_Premises staff_CS": "PremisesStaffCostsCS",
    "Utilities_Total_CS": "TotalUtilitiesCostsCS",
    "Utilities_Energy_CS": "EnergyCostsCS",
    "Utilities_Water and sewerage_CS": "WaterSewerageCostsCS",
    "Administrative supplies_Administrative supplies (non educational)_CS": "AdministrativeSuppliesNonEducationalCostsCS",
    "Catering staff and supplies_Total_CS": "TotalGrossCateringCostsCS",
    "Catering staff and supplies_Net Costs_CS": "TotalNetCateringCostsCostsCS",
    "Catering staff and supplies_Catering staff_CS": "CateringStaffCostsCS",
    "Catering staff and supplies_Catering supplies_CS": "CateringSuppliesCostsCS",
    "Other costs_Total_CS": "TotalOtherCostsCS",
    "Other costs_Indirect employee expenses_CS": "IndirectEmployeeExpensesCS",
    "Other costs_Interest charges for loan and bank_CS": "InterestChargesLoanBankCS",
    "Other costs_Other insurance premiums_CS": "OtherInsurancePremiumsCostsCS",
    "Other costs_PFI charges_CS": "PrivateFinanceInitiativeChargesCS",
    "Other costs_Rent and rates_CS": "RentRatesCostsCS",
    "Other costs_Special facilities_CS": "SpecialFacilitiesCostsCS",
    "Other costs_Staff development and training_CS": "StaffDevelopmentTrainingCostsCS",
    "Other costs_Staff-related insurance_CS": "StaffRelatedInsuranceCostsCS",
    "Other costs_Supply teacher insurance_CS": "SupplyTeacherInsurableCostsCS",
    "Income_Pre Post 16_CS": "PrePost16FundingCS",
    "Income_Pre Post 16": "PrePost16Funding",
    "Other costs_Grounds maintenance_CS": "GroundsMaintenanceCostsCS",
    "EMLBand": "EMLBand",
}
