la_db_financial_projections = {
    "RunType": "RunType",
    "RunId": "RunId",
    "old_la_code": "LaCode",
    "Population2To18": "Population2To18",
    "Number of pupils": "TotalPupils",
    "OutturnTotalHighNeeds": "OutturnTotalHighNeeds",
    "OutturnTotalPlaceFunding": "OutturnTotalPlaceFunding",
    "OutturnTotalTopUpFundingMaintained": "OutturnTotalTopUpFundingMaintained",
    "OutturnTotalTopUpFundingNonMaintained": "OutturnTotalTopUpFundingNonMaintained",
    "OutturnTotalSenServices": "OutturnTotalSenServices",
    "OutturnTotalAlternativeProvisionServices": "OutturnTotalAlternativeProvisionServices",
    "OutturnTotalHospitalServices": "OutturnTotalHospitalServices",
    "OutturnTotalOtherHealthServices": "OutturnTotalOtherHealthServices",
    "OutturnTopFundingMaintainedEarlyYears": "OutturnTopFundingMaintainedEarlyYears",
    "OutturnTopFundingMaintainedPrimary": "OutturnTopFundingMaintainedPrimary",
    "OutturnTopFundingMaintainedSecondary": "OutturnTopFundingMaintainedSecondary",
    "OutturnTopFundingMaintainedSpecial": "OutturnTopFundingMaintainedSpecial",
    "OutturnTopFundingMaintainedAlternativeProvision": "OutturnTopFundingMaintainedAlternativeProvision",
    "OutturnTopFundingMaintainedPostSchool": "OutturnTopFundingMaintainedPostSchool",
    "OutturnTopFundingMaintainedIncome": "OutturnTopFundingMaintainedIncome",
    "OutturnTopFundingNonMaintainedEarlyYears": "OutturnTopFundingNonMaintainedEarlyYears",
    "OutturnTopFundingNonMaintainedPrimary": "OutturnTopFundingNonMaintainedPrimary",
    "OutturnTopFundingNonMaintainedSecondary": "OutturnTopFundingNonMaintainedSecondary",
    "OutturnTopFundingNonMaintainedSpecial": "OutturnTopFundingNonMaintainedSpecial",
    "OutturnTopFundingNonMaintainedAlternativeProvision": "OutturnTopFundingNonMaintainedAlternativeProvision",
    "OutturnTopFundingNonMaintainedPostSchool": "OutturnTopFundingNonMaintainedPostSchool",
    "OutturnTopFundingNonMaintainedIncome": "OutturnTopFundingNonMaintainedIncome",
    "OutturnPlaceFundingPrimary": "OutturnPlaceFundingPrimary",
    "OutturnPlaceFundingSecondary": "OutturnPlaceFundingSecondary",
    "OutturnPlaceFundingSpecial": "OutturnPlaceFundingSpecial",
    "OutturnPlaceFundingAlternativeProvision": "OutturnPlaceFundingAlternativeProvision",
    "OutturnDSGCarriedForward": "OutturnDSGCarriedForward",
    "OutturnSENTransportDSG": "OutturnSENTransportDSG", 
    "OutturnHometoSchoolTransportPre16": "OutturnHometoSchoolTransportPre16", 
    "OutturnHometoSchoolTransport1618": "OutturnHometoSchoolTransport1618",
    "OutturnHometoSchoolTransport1925": "OutturnHometoSchoolTransport1925",
    "OutturnEdPsychologyService": "OutturnEdPsychologyService", 
    "OutturnSENAdmin": "OutturnSENAdmin", 
    "DSGRecoupmentServiceTotal": "DSGRecoupmentServiceTotal",
    "DSGPrimaryAcademyPlaceFunding": "DSGPrimaryAcademyPlaceFunding",
    "DSGSecondaryAcademyPlaceFunding": "DSGSecondaryAcademyPlaceFunding",
    "DSGSENAcademyPlaceFunding": "DSGSENAcademyPlaceFunding",
    "DSGAPAcademyPlaceFunding": "DSGAPAcademyPlaceFunding",
    "DSGHospitalPlaceFunding": "DSGHospitalPlaceFunding",
    "DSGNurseryPlaceFunding": "DSGNurseryPlaceFunding",
    "DSGHighNeedsAllocation": "DSGHighNeedsAllocation",
    "PrimaryPlaces6000": "PrimaryPlaces6000",
    "PrimaryPlaces10000": "PrimaryPlaces10000",
    "SecondaryPlaces6000": "SecondaryPlaces6000",
    "SecondaryPlaces10000": "SecondaryPlaces10000",
    "BudgetTotalHighNeeds": "BudgetTotalHighNeeds",
    "BudgetTotalPlaceFunding": "BudgetTotalPlaceFunding",
    "BudgetTotalTopUpFundingMaintained": "BudgetTotalTopUpFundingMaintained",
    "BudgetTotalTopUpFundingNonMaintained": "BudgetTotalTopUpFundingNonMaintained",
    "BudgetTotalSenServices": "BudgetTotalSenServices",
    "BudgetTotalAlternativeProvisionServices": "BudgetTotalAlternativeProvisionServices",
    "BudgetTotalHospitalServices": "BudgetTotalHospitalServices",
    "BudgetTotalOtherHealthServices": "BudgetTotalOtherHealthServices",
    "BudgetTopFundingMaintainedEarlyYears": "BudgetTopFundingMaintainedEarlyYears",
    "BudgetTopFundingMaintainedPrimary": "BudgetTopFundingMaintainedPrimary",
    "BudgetTopFundingMaintainedSecondary": "BudgetTopFundingMaintainedSecondary",
    "BudgetTopFundingMaintainedSpecial": "BudgetTopFundingMaintainedSpecial",
    "BudgetTopFundingMaintainedAlternativeProvision": "BudgetTopFundingMaintainedAlternativeProvision",
    "BudgetTopFundingMaintainedPostSchool": "BudgetTopFundingMaintainedPostSchool",
    "BudgetTopFundingMaintainedIncome": "BudgetTopFundingMaintainedIncome",
    "BudgetTopFundingNonMaintainedEarlyYears": "BudgetTopFundingNonMaintainedEarlyYears",
    "BudgetTopFundingNonMaintainedPrimary": "BudgetTopFundingNonMaintainedPrimary",
    "BudgetTopFundingNonMaintainedSecondary": "BudgetTopFundingNonMaintainedSecondary",
    "BudgetTopFundingNonMaintainedSpecial": "BudgetTopFundingNonMaintainedSpecial",
    "BudgetTopFundingNonMaintainedAlternativeProvision": "BudgetTopFundingNonMaintainedAlternativeProvision",
    "BudgetTopFundingNonMaintainedPostSchool": "BudgetTopFundingNonMaintainedPostSchool",
    "BudgetTopFundingNonMaintainedIncome": "BudgetTopFundingNonMaintainedIncome",
    "BudgetPlaceFundingPrimary": "BudgetPlaceFundingPrimary",
    "BudgetPlaceFundingSecondary": "BudgetPlaceFundingSecondary",
    "BudgetPlaceFundingSpecial": "BudgetPlaceFundingSpecial",
    "BudgetPlaceFundingAlternativeProvision": "BudgetPlaceFundingAlternativeProvision",
    "BudgetSENTransportDSG": "BudgetSENTransportDSG",
    "BudgetHometoSchoolTransportPre16": "BudgetHometoSchoolTransportPre16",
    "BudgetHometoSchoolTransport1618": "BudgetHometoSchoolTransport1618",
    "BudgetHometoSchoolTransport1925": "BudgetHometoSchoolTransport1925",
    "BudgetEdPsychologyService": "BudgetEdPsychologyService",
    "BudgetSENAdmin": "BudgetSENAdmin",
}

la_db_non_financial_projections = {
    "RunType": "RunType",
    "RunId": "RunId",
    "old_la_code": "LaCode",
    "Population2To18": "Population2To18",
    "Number of pupils": "TotalPupils",
    "SEN support": "SENSupport",
    "EHCPTotal": "EHCPTotal",
    "EHCPMainstream": "EHCPMainstream",
    "EHCPResourced": "EHCPResourced",
    "EHCPSpecial": "EHCPSpecial",
    "EHCPIndependent": "EHCPIndependent",
    "EHCPHospital": "EHCPHospital",
    "EHCPPost16": "EHCPPost16",
    "EHCPOther": "EHCPOther",
}

la_statistical_neighbours_projections = {
    "RunType": "RunType",
    "RunId": "RunId",
    "old_la_code": "LaCode",
    "NeighbourPosition": "NeighbourPosition",
    "NeighbourLaCode": "NeighbourLaCode",
    "NeighbourDescription": "NeighbourDescription",
}
