la_db_financial_projections = {
    "RunType": "RunType",
    "RunId": "RunId",
    "old_la_code": "LaCode",
    "Population2To18": "Population2To18",
    "Number of pupils": "TotalPupils",
    "OutturnTotalHighNeeds": "OutturnTotalHighNeeds",
    "OutturnTotalPlaceFunding": "OutturnTotalPlaceFunding",
    "OutturnTotalTopUpFundingMaintained": "OutturnTotalTopUpFundingMaintained",
    "OutturnTotalTopUpFundingNonMaintained": "OutturnTotalTopUpFundingNonMaintained",
    "OutturnTotalSenServices": "OutturnTotalSenServices",
    "OutturnTotalAlternativeProvisionServices": "OutturnTotalAlternativeProvisionServices",
    "OutturnTotalHospitalServices": "OutturnTotalHospitalServices",
    "OutturnTotalOtherHealthServices": "OutturnTotalOtherHealthServices",
    "OutturnTopFundingMaintainedEarlyYears": "OutturnTopFundingMaintainedEarlyYears",
    "OutturnTopFundingMaintainedPrimary": "OutturnTopFundingMaintainedPrimary",
    "OutturnTopFundingMaintainedSecondary": "OutturnTopFundingMaintainedSecondary",
    "OutturnTopFundingMaintainedSpecial": "OutturnTopFundingMaintainedSpecial",
    "OutturnTopFundingMaintainedAlternativeProvision": "OutturnTopFundingMaintainedAlternativeProvision",
    "OutturnTopFundingMaintainedPostSchool": "OutturnTopFundingMaintainedPostSchool",
    "OutturnTopFundingMaintainedIncome": "OutturnTopFundingMaintainedIncome",
    "OutturnTopFundingNonMaintainedEarlyYears": "OutturnTopFundingNonMaintainedEarlyYears",
    "OutturnTopFundingNonMaintainedPrimary": "OutturnTopFundingNonMaintainedPrimary",
    "OutturnTopFundingNonMaintainedSecondary": "OutturnTopFundingNonMaintainedSecondary",
    "OutturnTopFundingNonMaintainedSpecial": "OutturnTopFundingNonMaintainedSpecial",
    "OutturnTopFundingNonMaintainedAlternativeProvision": "OutturnTopFundingNonMaintainedAlternativeProvision",
    "OutturnTopFundingNonMaintainedPostSchool": "OutturnTopFundingNonMaintainedPostSchool",
    "OutturnTopFundingNonMaintainedIncome": "OutturnTopFundingNonMaintainedIncome",
    "OutturnPlaceFundingPrimary": "OutturnPlaceFundingPrimary",
    "OutturnPlaceFundingSecondary": "OutturnPlaceFundingSecondary",
    "OutturnPlaceFundingSpecial": "OutturnPlaceFundingSpecial",
    "OutturnPlaceFundingAlternativeProvision": "OutturnPlaceFundingAlternativeProvision",
    "OutturnPlaceFundingPost16": "OutturnPlaceFundingPost16",
    "DSGPrimaryAcademyPlaceFunding": "DSGPrimaryAcademyPlaceFunding",
    "DSGSecondaryAcademyPlaceFunding": "DSGSecondaryAcademyPlaceFunding",
    "DSGSENAcademyPlaceFunding": "DSGSENAcademyPlaceFunding",
    "DSGAPAcademyPlaceFunding": "DSGAPAcademyPlaceFunding",
    "DSGPost16PlaceFunding": "DSGPost16PlaceFunding",
    "DSGHospitalPlaceFunding": "DSGHospitalPlaceFunding",
    "DSGNurseryPlaceFunding": "DSGNurseryPlaceFunding",
    "PrimaryPlaces6000": "PrimaryPlaces6000",
    "PrimaryPlaces10000": "PrimaryPlaces10000",
    "SecondaryPlaces6000": "SecondaryPlaces6000",
    "SecondaryPlaces10000": "SecondaryPlaces10000",
    "BudgetTotalHighNeeds": "BudgetTotalHighNeeds",
    "BudgetTotalPlaceFunding": "BudgetTotalPlaceFunding",
    "BudgetTotalTopUpFundingMaintained": "BudgetTotalTopUpFundingMaintained",
    "BudgetTotalTopUpFundingNonMaintained": "BudgetTotalTopUpFundingNonMaintained",
    "BudgetTotalSenServices": "BudgetTotalSenServices",
    "BudgetTotalAlternativeProvisionServices": "BudgetTotalAlternativeProvisionServices",
    "BudgetTotalHospitalServices": "BudgetTotalHospitalServices",
    "BudgetTotalOtherHealthServices": "BudgetTotalOtherHealthServices",
    "BudgetTopFundingMaintainedEarlyYears": "BudgetTopFundingMaintainedEarlyYears",
    "BudgetTopFundingMaintainedPrimary": "BudgetTopFundingMaintainedPrimary",
    "BudgetTopFundingMaintainedSecondary": "BudgetTopFundingMaintainedSecondary",
    "BudgetTopFundingMaintainedSpecial": "BudgetTopFundingMaintainedSpecial",
    "BudgetTopFundingMaintainedAlternativeProvision": "BudgetTopFundingMaintainedAlternativeProvision",
    "BudgetTopFundingMaintainedPostSchool": "BudgetTopFundingMaintainedPostSchool",
    "BudgetTopFundingMaintainedIncome": "BudgetTopFundingMaintainedIncome",
    "BudgetTopFundingNonMaintainedEarlyYears": "BudgetTopFundingNonMaintainedEarlyYears",
    "BudgetTopFundingNonMaintainedPrimary": "BudgetTopFundingNonMaintainedPrimary",
    "BudgetTopFundingNonMaintainedSecondary": "BudgetTopFundingNonMaintainedSecondary",
    "BudgetTopFundingNonMaintainedSpecial": "BudgetTopFundingNonMaintainedSpecial",
    "BudgetTopFundingNonMaintainedAlternativeProvision": "BudgetTopFundingNonMaintainedAlternativeProvision",
    "BudgetTopFundingNonMaintainedPostSchool": "BudgetTopFundingNonMaintainedPostSchool",
    "BudgetTopFundingNonMaintainedIncome": "BudgetTopFundingNonMaintainedIncome",
    "BudgetPlaceFundingPrimary": "BudgetPlaceFundingPrimary",
    "BudgetPlaceFundingSecondary": "BudgetPlaceFundingSecondary",
    "BudgetPlaceFundingSpecial": "BudgetPlaceFundingSpecial",
    "BudgetPlaceFundingAlternativeProvision": "BudgetPlaceFundingAlternativeProvision",
    "BudgetPlaceFundingPost16": "BudgetPlaceFundingPost16",
}

la_db_non_financial_projections = {
    "RunType": "RunType",
    "RunId": "RunId",
    "old_la_code": "LaCode",
    "Population2To18": "Population2To18",
    "Number of pupils": "TotalPupils",
    "EHCPTotal": "EHCPTotal",
    "EHCPMainstream": "EHCPMainstream",
    "EHCPResourced": "EHCPResourced",
    "EHCPSpecial": "EHCPSpecial",
    "EHCPIndependent": "EHCPIndependent",
    "EHCPHospital": "EHCPHospital",
    "EHCPPost16": "EHCPPost16",
    "EHCPOther": "EHCPOther",
}

la_statistical_neighbours_projections = {
    "RunType": "RunType",
    "RunId": "RunId",
    "old_la_code": "LaCode",
    "NeighbourPosition": "NeighbourPosition",
    "NeighbourLaCode": "NeighbourLaCode",
    "NeighbourDescription": "NeighbourDescription",
}
