from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, List, Optional, Sequence, Tuple, Union

import numpy as np
import pandas as pd


class RiskGroup(Enum):
    FINANCIAL = "Financial"
    EDUCATIONAL_PERFORMANCE = "Educational Performance"
    SCHOOL_CHARACTERISTICS = "School Characteristics"


class RiskFlag(str, Enum):
    NO_FLAG = "No flag"
    MINOR = "Minor"
    MAJOR = "Major"


class RiskIndicatorValueFormatting(str, Enum):
    PERCENTAGE = "Percentage"
    BOOLEAN = "Boolean"
    DECIMAL = "Decimal"
    STRING = "String"


@dataclass
class GradeThreshold:
    grade: str
    max_score: float
    max_risks: int
    max_major_risks: int
    min_parental_pref: Optional[float] = None
    min_attainment: Optional[float] = None


@dataclass
class MetricRule:
    lower: float
    upper: float
    score: float
    risk: str
    inclusive: str = "both"


class ApplicabilityRule(ABC):
    """Abstract base rule to determine if a metric applies to a school."""

    @abstractmethod
    def is_applicable(self, df: pd.DataFrame) -> pd.Series:
        """Returns a boolean Series: True if the metric applies, False if N/A."""
        pass


@dataclass
class ExcludePhases(ApplicabilityRule):
    """Marks specified educational phases as N/A."""

    phases: Sequence[str]
    column: str = "Overall Phase"

    def is_applicable(self, df: pd.DataFrame) -> pd.Series:
        if self.column not in df.columns:
            return pd.Series(True, index=df.index)
        return ~df[self.column].isin(self.phases)


@dataclass
class BaseRiskMetric:
    name: str
    risk_group: RiskGroup
    risk_score_maximum: float
    risk_flag_maximum: str = field(default=RiskFlag.MAJOR.value, kw_only=True)
    value_formatting: RiskIndicatorValueFormatting = field(
        default=RiskIndicatorValueFormatting.DECIMAL, kw_only=True
    )
    applicability: Optional[Union[ApplicabilityRule, List[ApplicabilityRule]]] = field(
        default=None, kw_only=True
    )

    @property
    def value_column(self) -> str:
        return self.name

    @property
    def score_column(self) -> str:
        return f"{self.name}_Score"

    @property
    def flag_column(self) -> str:
        return f"{self.name}_Risk"

    def get_all_cols(self) -> List[str]:
        """Returns the list of columns generated by this metric."""
        return [self.value_column, self.score_column, self.flag_column]

    def is_applicable(self, df: pd.DataFrame) -> pd.Series:
        """Evaluates whether each school in the DataFrame is applicable for this metric."""
        if not self.applicability:
            return pd.Series(True, index=df.index)
        if (
            hasattr(df, "attrs")
            and "applicability" in df.attrs
            and self.name in df.attrs["applicability"]
        ):
            return df.attrs["applicability"][self.name]

        rules = (
            self.applicability
            if isinstance(self.applicability, list)
            else [self.applicability]
        )
        mask = pd.Series(True, index=df.index)
        for rule in rules:
            mask = mask & rule.is_applicable(df)

        if hasattr(df, "attrs"):
            df.attrs.setdefault("applicability", {})[self.name] = mask
        return mask

    def derive_value(self, df: pd.DataFrame) -> pd.Series:
        """Derives the raw value of the metric from the input DataFrame.
        Override in subclasses for custom derivations.
        """
        return df[self.value_column]

    def derive_risk_score(
        self, df: pd.DataFrame, value_series: pd.Series
    ) -> Tuple[pd.Series, pd.Series]:
        """Derives the risk score and risk flag (string) from the derived value.
        Override in subclasses to implement specific scoring logic.
        """
        raise NotImplementedError

    def _format_single_value(self, val: Any) -> Optional[str]:
        """Formats an individual scalar value based on value_formatting."""
        if pd.isna(val) or val is None:
            return None
        formatting = self.value_formatting
        if formatting == RiskIndicatorValueFormatting.BOOLEAN:
            if isinstance(val, (bool, np.bool_)):
                return "Yes" if val else "No"
            if isinstance(val, (int, np.integer)):
                return "Yes" if val != 0 else "No"
            if isinstance(val, str):
                return "Yes" if val.strip().lower() in ("true", "1", "yes") else "No"
            return "Yes" if bool(val) else "No"

        if formatting == RiskIndicatorValueFormatting.STRING:
            return str(val)

        if isinstance(val, (int, np.integer)):
            return str(val)

        if isinstance(val, (float, np.floating)):
            if np.isinf(val):
                return None
            rounded = round(float(val), 6)
            if (
                formatting == RiskIndicatorValueFormatting.DECIMAL
                and rounded.is_integer()
            ):
                return str(int(rounded))
            return str(rounded)

        return str(val)

    def format_value(
        self, values: pd.Series, df: Optional[pd.DataFrame] = None
    ) -> pd.Series:
        """Serialises metric values to clean string representations and masks non-applicable rows to 'N/A'."""
        formatted = values.apply(self._format_single_value)
        if df is not None:
            is_na = ~self.is_applicable(df)
            if is_na.any():
                formatted = formatted.mask(is_na, "N/A")
        return formatted

    def execute(self, df: pd.DataFrame) -> None:
        """Orchestrates the metric lifecycle: derives the value, score, and flag,
        and saves them onto the DataFrame.
        """
        values = self.derive_value(df)
        if not isinstance(values, pd.Series):
            values = pd.Series(values, index=df.index)
        values = values.replace([np.inf, -np.inf], np.nan)
        df[self.value_column] = values

        is_applicable = self.is_applicable(df)
        scores, flags = self.derive_risk_score(df, values)

        # Missing value penalty applies ONLY to applicable schools
        is_missing = values.isna() & is_applicable
        if is_missing.any():
            scores = scores.mask(is_missing, self.risk_score_maximum)
            flags = flags.mask(is_missing, self.risk_flag_maximum)

        # Non-applicable schools receive score 0.0 and No flag
        is_na = ~is_applicable
        if is_na.any():
            scores = scores.mask(is_na, 0.0)
            flags = flags.mask(is_na, RiskFlag.NO_FLAG.value)
            

        df[self.score_column] = scores
        df[self.flag_column] = flags


def _evaluate_metric_rules(
    value_series: pd.Series,
    rules: Sequence[MetricRule],
    default_score: float = 0.0,
    default_risk: str = RiskFlag.NO_FLAG.value,
) -> Tuple[np.ndarray, np.ndarray]:
    """Evaluates a sequence of MetricRule against a value Series."""
    conditions = [
        value_series.between(r.lower, r.upper, inclusive=r.inclusive) for r in rules
    ]
    scores = np.select(conditions, [r.score for r in rules], default=default_score)
    risks = np.select(conditions, [r.risk for r in rules], default=default_risk)
    return scores, risks


@dataclass
class RangeRiskMetric(BaseRiskMetric):
    default_score: Optional[float] = None
    default_risk: Optional[str] = None
    rules: List[MetricRule] = field(default_factory=list)

    def __post_init__(self):
        if self.default_score is None:
            self.default_score = self.risk_score_maximum
        if self.default_risk is None:
            self.default_risk = self.risk_flag_maximum

    def derive_risk_score(
        self, df: pd.DataFrame, value_series: pd.Series
    ) -> Tuple[pd.Series, pd.Series]:
        scores, flags = _evaluate_metric_rules(
            value_series, self.rules, self.default_score, self.default_risk
        )
        return pd.Series(scores, index=df.index), pd.Series(flags, index=df.index)


@dataclass
class CurrentYearRevenueReserveMetric(RangeRiskMetric):
    value_formatting: RiskIndicatorValueFormatting = field(
        default=RiskIndicatorValueFormatting.PERCENTAGE, kw_only=True
    )

    def derive_value(self, df: pd.DataFrame) -> pd.Series:
        return df["Revenue reserve"] / df["Total Income"]


@dataclass
class PreviousYearRevenueReserveMetric(RangeRiskMetric):
    value_formatting: RiskIndicatorValueFormatting = field(
        default=RiskIndicatorValueFormatting.PERCENTAGE, kw_only=True
    )

    def derive_value(self, df: pd.DataFrame) -> pd.Series:
        return df["Revenue reserve_y_minus_one"] / df["Total Income_y_minus_one"]


EndYearBalanceMetric = CurrentYearRevenueReserveMetric


@dataclass
class BinaryRiskMetric(BaseRiskMetric):
    score_when_1: float
    risk_when_1: str
    value_formatting: RiskIndicatorValueFormatting = field(
        default=RiskIndicatorValueFormatting.BOOLEAN, kw_only=True
    )

    def derive_risk_score(
        self, df: pd.DataFrame, value_series: pd.Series
    ) -> Tuple[pd.Series, pd.Series]:
        score_series = pd.Series(
            np.where(value_series, float(self.score_when_1), 0.0), index=df.index
        )
        flag_series = pd.Series(
            np.where(value_series, self.risk_when_1, RiskFlag.NO_FLAG.value),
            index=df.index,
        )
        return score_series, flag_series


@dataclass
class ConditionalRiskMetric(BaseRiskMetric):
    condition_column: str
    special_values: List[int]
    standard_rules: List[MetricRule]
    special_rules: List[MetricRule]

    def derive_risk_score(
        self, df: pd.DataFrame, value_series: pd.Series
    ) -> Tuple[pd.Series, pd.Series]:
        is_special = df[self.condition_column].isin(self.special_values)
        score_std, risk_std = _evaluate_metric_rules(value_series, self.standard_rules)
        score_spec, risk_spec = _evaluate_metric_rules(value_series, self.special_rules)

        score_series = pd.Series(
            np.where(is_special, score_spec, score_std), index=df.index
        )
        flag_series = pd.Series(
            np.where(is_special, risk_spec, risk_std), index=df.index
        )
        return score_series, flag_series


@dataclass
class InterestOnLoanFlagMetric(BinaryRiskMetric):
    def derive_value(self, df: pd.DataFrame) -> pd.Series:
        return df["Other costs_Interest charges for loan and bank"] > 0


@dataclass
class PercentExpenditureOnPremisesMetric(RangeRiskMetric):
    value_formatting: RiskIndicatorValueFormatting = field(
        default=RiskIndicatorValueFormatting.PERCENTAGE, kw_only=True
    )

    def derive_value(self, df: pd.DataFrame) -> pd.Series:
        return df["LAAPremisesExpenditureRollup"] / df["NetExpenditure"]


@dataclass
class PercentExpenditureOnStaffMetric(RangeRiskMetric):
    value_formatting: RiskIndicatorValueFormatting = field(
        default=RiskIndicatorValueFormatting.PERCENTAGE, kw_only=True
    )

    def derive_value(self, df: pd.DataFrame) -> pd.Series:
        return df["LAAStaffExpenditureRollup"] / df["NetExpenditure"]


@dataclass
class ChangeInExpenditureOver4YearsMetric(RangeRiskMetric):
    value_formatting: RiskIndicatorValueFormatting = field(
        default=RiskIndicatorValueFormatting.PERCENTAGE, kw_only=True
    )

    def derive_value(self, df: pd.DataFrame) -> pd.Series:
        return (df["Total Expenditure"] - df["Total Expenditure_y_minus_four"]) / df[
            "Total Income"
        ]


@dataclass
class DeficitInLast4YearsFlagMetric(BinaryRiskMetric):
    def derive_value(self, df: pd.DataFrame) -> pd.Series:
        return (
            df[
                [
                    "Revenue reserve",
                    "Revenue reserve_y_minus_one",
                    "Revenue reserve_y_minus_two",
                    "Revenue reserve_y_minus_three",
                    "Revenue reserve_y_minus_four",
                ]
            ]
            < 0
        ).any(axis=1)


@dataclass
class CurrentLongTermSurplusABoveThresholdFor5YearsMetric(BinaryRiskMetric):
    threshold: float = 0.15

    def derive_value(self, df: pd.DataFrame) -> pd.Series:
        t = self.threshold
        return (
            ((df["Revenue reserve"] / df["Total Income"]) >= t)
            & (
                (df["Revenue reserve_y_minus_one"] / df["Total Income_y_minus_one"])
                >= t
            )
            & (
                (df["Revenue reserve_y_minus_two"] / df["Total Income_y_minus_two"])
                >= t
            )
            & (
                (df["Revenue reserve_y_minus_three"] / df["Total Income_y_minus_three"])
                >= t
            )
            & (
                (df["Revenue reserve_y_minus_four"] / df["Total Income_y_minus_four"])
                >= t
            )
        )


@dataclass
class PreviousLongTermBalanceDeficitMetric(BinaryRiskMetric):
    threshold: float

    def derive_value(self, df: pd.DataFrame) -> pd.Series:
        return (df["Revenue reserve"] / df["Total Income"]) >= self.threshold


@dataclass
class OverspendMetric(RangeRiskMetric):
    value_formatting: RiskIndicatorValueFormatting = field(
        default=RiskIndicatorValueFormatting.PERCENTAGE, kw_only=True
    )

    def derive_value(self, df: pd.DataFrame) -> pd.Series:
        return (df["Total Income"] - df["Total Expenditure"]) / df["Total Income"]


@dataclass
class LargeDecreaseInBalanceMetric(BinaryRiskMetric):
    def derive_value(self, df: pd.DataFrame) -> pd.Series:
        op1 = df["Revenue reserve"] / df["Total Income"]
        op1_prev = df["Revenue reserve_y_minus_one"] / df["Total Income_y_minus_one"]
        op2 = op1 - op1_prev
        return (op1 < 0.15) & (op2 <= -0.1)


@dataclass
class PupilNumberVarianceFromCapacityMetric(RangeRiskMetric):
    value_formatting: RiskIndicatorValueFormatting = field(
        default=RiskIndicatorValueFormatting.PERCENTAGE, kw_only=True
    )

    def derive_value(self, df: pd.DataFrame) -> pd.Series:
        return df["Number of pupils"] / df["school_places"]


@dataclass
class PupilChangeOver1YearMetric(RangeRiskMetric):
    value_formatting: RiskIndicatorValueFormatting = field(
        default=RiskIndicatorValueFormatting.PERCENTAGE, kw_only=True
    )

    def derive_value(self, df: pd.DataFrame) -> pd.Series:
        return (df["Number of pupils"] - df["Number of pupils_y_minus_one"]) / df[
            "Number of pupils_y_minus_one"
        ]


@dataclass
class PupilChangeOver4YearsMetric(RangeRiskMetric):
    value_formatting: RiskIndicatorValueFormatting = field(
        default=RiskIndicatorValueFormatting.PERCENTAGE, kw_only=True
    )

    def derive_value(self, df: pd.DataFrame) -> pd.Series:
        return (df["Number of pupils"] - df["Number of pupils_y_minus_four"]) / df[
            "Number of pupils_y_minus_four"
        ]


@dataclass
class PupilsSixthFormMetric(RangeRiskMetric):
    value_formatting: RiskIndicatorValueFormatting = field(
        default=RiskIndicatorValueFormatting.DECIMAL, kw_only=True
    )

    def derive_value(self, df: pd.DataFrame) -> pd.Series:
        return df["TotalPupilsSixthForm"]


@dataclass
class PupilAbsenceMetric(ConditionalRiskMetric):
    value_formatting: RiskIndicatorValueFormatting = field(
        default=RiskIndicatorValueFormatting.PERCENTAGE, kw_only=True
    )

    def derive_value(self, df: pd.DataFrame) -> pd.Series:
        return df["sess_overall_percent"]


@dataclass
class ParentalPreferenceMetric(RangeRiskMetric):
    rating_low_threshold: float = np.nan
    rating_high_threshold: float = np.nan
    value_formatting: RiskIndicatorValueFormatting = field(
        default=RiskIndicatorValueFormatting.STRING, kw_only=True
    )

    def derive_value(self, df: pd.DataFrame) -> pd.Series:
        return df["proportion_1stprefs_v_totaloffers"]

    def _format_single_value(self, val: Any) -> Optional[str]:
        if pd.isna(val) or val is None:
            return "N/A"
        if val <= self.rating_low_threshold:
            return "Low"
        if val > self.rating_high_threshold:
            return "High"
        return "Medium"


@dataclass
class PerformanceTablesProgressScoreMetric(RangeRiskMetric):
    value_formatting: RiskIndicatorValueFormatting = field(
        default=RiskIndicatorValueFormatting.DECIMAL, kw_only=True
    )

    def derive_value(self, df: pd.DataFrame) -> pd.Series:
        primary_secondary_condition = [
            df["Overall Phase"] == "Primary",
            df["Overall Phase"] == "Secondary",
        ]
        progress_score_choices = [(df["Ks2Progress"] / 3), df["Progress8Measure"]]
        result = np.select(
            primary_secondary_condition, progress_score_choices, default=np.nan
        )
        return pd.Series(result, index=df.index)


@dataclass
class PerformanceTablesAchievementScoreMetric(RangeRiskMetric):
    value_formatting: RiskIndicatorValueFormatting = field(
        default=RiskIndicatorValueFormatting.DECIMAL, kw_only=True
    )

    def derive_value(self, df: pd.DataFrame) -> pd.Series:
        primary_secondary_condition = [
            df["Overall Phase"] == "Primary",
            df["Overall Phase"] == "Secondary",
        ]
        achievement_score_choices = [df["PTRWM_EXP"], df["AverageAttainment"]]
        result = np.select(
            primary_secondary_condition, achievement_score_choices, default=np.nan
        )
        return pd.Series(result, index=df.index)
