trigger:
- main
- feature/*

pr:
- main
- feature/*

pool:
  vmImage: ''  

steps:
- checkout: self
  fetchDepth: 1 

- task: Npm@1
  displayName: 'Install dependencies'
  inputs:
    command: 'install'

- task: Npm@1
  displayName: 'Run tests'
  inputs:
    command: 'custom'
    customCommand: 'test'

- task: Npm@1
  displayName: 'Build project'
  inputs:
    command: 'custom'
    customCommand: 'run build'
