parameters:
  subscription: ''
  environmentPrefix: ''
  environment: ''
  pipelineEnvironment: ''
  cipEnvironment: ''
  buildNumber: ''
  dependsOn: []

jobs:
  - template: ../core-infrastructure/sync.yaml
    parameters:
      dependsOn: ${{ parameters.dependsOn }}
      subscription: ${{ parameters.subscription }}
      environmentPrefix: ${{ parameters.environmentPrefix }}
      environment: ${{ parameters.environment }}
      pipelineEnvironment: ${{ parameters.pipelineEnvironment }}
      cipEnvironment: ${{ parameters.cipEnvironment }}
      disablePurgeProtection: 'true'

  - template: ../data-pipeline/sync.yaml
    parameters:
      dependsOn: [ CoreSync ]
      subscription: ${{ parameters.subscription }}
      environmentPrefix: ${{ parameters.environmentPrefix }}
      environment: ${{ parameters.environment }}
      pipelineEnvironment: ${{ parameters.pipelineEnvironment }}
      cipEnvironment: ${{ parameters.cipEnvironment }}

  - template: ../platform/sync.yaml
    parameters:
      dependsOn: [ DataPipelineSync ]
      subscription: ${{ parameters.subscription }}
      environmentPrefix: ${{ parameters.environmentPrefix }}
      environment: ${{ parameters.environment }}
      pipelineEnvironment: ${{ parameters.pipelineEnvironment }}
      cipEnvironment: ${{ parameters.cipEnvironment }}

  - template: ../web/sync.yaml
    parameters:
      dependsOn: [ PlatformSync ]
      subscription: ${{ parameters.subscription }}
      environmentPrefix: ${{ parameters.environmentPrefix }}
      environment: ${{ parameters.environment }}
      pipelineEnvironment: ${{ parameters.pipelineEnvironment }}
      cipEnvironment: ${{ parameters.cipEnvironment }}

  - template: ../support-analytics/sync.yaml
    parameters:
      dependsOn: [ WebSync ]
      subscription: ${{ parameters.subscription }}
      environmentPrefix: ${{ parameters.environmentPrefix }}
      environment: ${{ parameters.environment }}
      pipelineEnvironment: ${{ parameters.pipelineEnvironment }}
      cipEnvironment: ${{ parameters.cipEnvironment }}

  - template: ../support-analytics/destroy.yaml
    parameters:
      dependsOn: [ SupportAnalyticsSync ]
      subscription: ${{ parameters.subscription }}
      environmentPrefix: ${{ parameters.environmentPrefix }}
      environment: ${{ parameters.environment }}
      pipelineEnvironment: ${{ parameters.pipelineEnvironment }}
      cipEnvironment: ${{ parameters.cipEnvironment }}

  - template: ../web/destroy.yaml
    parameters:
      dependsOn: [ SupportAnalyticsDestroy ]
      subscription: ${{ parameters.subscription }}
      environmentPrefix: ${{ parameters.environmentPrefix }}
      environment: ${{ parameters.environment }}
      pipelineEnvironment: ${{ parameters.pipelineEnvironment }}
      cipEnvironment: ${{ parameters.cipEnvironment }}

  - template: ../platform/destroy.yaml
    parameters:
      dependsOn: [ WebDestroy ]
      subscription: ${{ parameters.subscription }}
      environmentPrefix: ${{ parameters.environmentPrefix }}
      environment: ${{ parameters.environment }}
      pipelineEnvironment: ${{ parameters.pipelineEnvironment }}
      cipEnvironment: ${{ parameters.cipEnvironment }}

  - template: ../data-pipeline/destroy.yaml
    parameters:
      dependsOn: [ PlatformDestroy ]
      subscription: ${{ parameters.subscription }}
      environmentPrefix: ${{ parameters.environmentPrefix }}
      environment: ${{ parameters.environment }}
      pipelineEnvironment: ${{ parameters.pipelineEnvironment }}
      cipEnvironment: ${{ parameters.cipEnvironment }}
      buildNumber: ${{ parameters.buildNumber }}

  - template: ../core-infrastructure/destroy.yaml
    parameters:
      dependsOn: [ DataPipelineDestroy ]
      subscription: ${{ parameters.subscription }}
      environmentPrefix: ${{ parameters.environmentPrefix }}
      environment: ${{ parameters.environment }}
      pipelineEnvironment: ${{ parameters.pipelineEnvironment }}
      cipEnvironment: ${{ parameters.cipEnvironment }}
