pool:
  vmImage: 'ubuntu-latest'

trigger: none

pr: none

parameters:
  - name: environment
    displayName: 'Environment associated with original deployment'
    type: string
    default: feature
    values:
      - automated-test
      - development
      - feature
      - pre-production
      - test
  - name: environmentPrefix
    displayName: 'Environment prefix to destroy (e.g. s198d01-feature-name)'
    type: string
    default: ''
  - name: areYouSure
    displayName: 'Are you sure you wish to destroy this environment?'
    type: string
    default: No
    values:
      - Yes
      - No

variables:
  Environment: ${{ parameters.environment }}
  EnvironmentPrefix: ${{ parameters.environmentPrefix }}
  ShouldDestroy: $[and(eq('${{ parameters.areYouSure }}', 'Yes'), ne('${{ parameters.environmentPrefix }}', ''))]

stages:
  - stage: Destroy
    condition: eq(variables['ShouldDestroy'], 'true')
    displayName: 'Destroy Environment'
    jobs:
      - template: destroy.yaml
        parameters:
          subscription: 's198d.azdo-deployment'
          environmentPrefix: $(EnvironmentPrefix)
          environment: $(Environment)
          pipelineEnvironment: 'destroy'
          cipEnvironment: 'Dev'
          module: 'web'