locals {

  function-app-settings = merge(var.app-settings, {
    "AzureWebJobsSecretStorageType" = "keyvault"
    "AzureWebJobsSecretStorageKeyVaultUri" = azurerm_key_vault.func_app_kv.vault_uri
    "AzureWebJobsSecretStorageKeyVaultClientId" = azurerm_user_assigned_identity.func-identity.client_id
  })

  function-app-name = "${var.core.environment_prefix}-ebis-${var.core.name}-fa"
  storage-account-name = "${var.core.environment_prefix}ebis${var.core.short_name}sa"
  key-vault-name = "${var.core.environment_prefix}-ebis-${var.core.short_name}-kv"
  identity_name = "${var.core.environment_prefix}-ebis-${var.core.name}-identity"

  storage_account_tier = "Standard"
  storage_account_replication_type = "LRS"

  key      = "generated by resource"
  host     = "https://${azurerm_function_app_flex_consumption.func-app.default_hostname}"

  ip_default_action = var.networking.enable_restrictions ? "Deny" : "Allow"
  ip_restrictions   = var.networking.enable_restrictions ? var.networking.subnet_ids : []

  redis_contributor_count = var.redis_cache.contributor ? 1 : 0
  redis_owner_count       = var.redis_cache.owner ? 1 : 0

}
