gias_index_col = "URN"
gias = {
    "default": {
        "URN": "Int64",
        "UKPRN": "Int64",
        "LA (code)": "Int64",
        "LA (name)": "string",
        "EstablishmentNumber": "Int64",
        "EstablishmentName": "string",
        "TypeOfEstablishment (code)": "Int64",
        "TypeOfEstablishment (name)": "string",
        "OpenDate": "string",
        "CloseDate": "string",
        "PhaseOfEducation (code)": "Int64",
        "PhaseOfEducation (name)": "string",
        "Boarders (code)": "Int64",
        "Boarders (name)": "string",
        "NurseryProvision (name)": "string",
        "OfficialSixthForm (code)": "Int64",
        "OfficialSixthForm (name)": "string",
        "AdmissionsPolicy (code)": "Int64",
        "AdmissionsPolicy (name)": "string",
        "OfstedLastInsp": "string",
        "Postcode": "string",
        "SchoolWebsite": "string",
        "TelephoneNum": "string",
        "GOR (name)": "string",
        "OfstedRating (name)": "string",
        "MSOA (code)": "string",
        "LSOA (code)": "string",
        "StatutoryLowAge": "Int64",
        "StatutoryHighAge": "Int64",
        "Street": "string",
        "Locality": "string",
        "Address3": "string",
        "Town": "string",
        "County (name)": "string",
    },
    2024: {
        "URN": "Int64",
        "UKPRN": "Int64",
        "LA (code)": "Int64",
        "LA (name)": "string",
        "EstablishmentNumber": "Int64",
        "EstablishmentName": "string",
        "TypeOfEstablishment (code)": "Int64",
        "TypeOfEstablishment (name)": "string",
        "OpenDate": "string",
        "CloseDate": "string",
        "PhaseOfEducation (code)": "Int64",
        "PhaseOfEducation (name)": "string",
        "Boarders (code)": "Int64",
        "Boarders (name)": "string",
        "NurseryProvision (name)": "string",
        "OfficialSixthForm (code)": "Int64",
        "OfficialSixthForm (name)": "string",
        "AdmissionsPolicy (code)": "Int64",
        "AdmissionsPolicy (name)": "string",
        "Postcode": "string",
        "SchoolWebsite": "string",
        "TelephoneNum": "string",
        "GOR (name)": "string",
        "MSOA (code)": "string",
        "LSOA (code)": "string",
        "StatutoryLowAge": "Int64",
        "StatutoryHighAge": "Int64",
        "Street": "string",
        "Locality": "string",
        "Address3": "string",
        "Town": "string",
        "County (name)": "string",
    },
}
