maintained_schools_master_list_index_col = "URN"

_maintained_default = {
    "URN": "Int64",
    "School Name": "string",
    "LAEstab": "string",
    "Phase": "string",
    "Overall Phase": "string",
    "Type": "string",
    "Period covered by return (months)": "Int64",
    "Did Not Supply flag": "string",
    "Lead school in federation": "string",
    "London Weighting": "string",
    "PFI": "string",
    "I01  Funds delegated by the LA": "float",
    "I02  Funding for 6th form students": "float",
    "I06  Other government grants": "float",
    "I07  Other grants and payments": "float",
    "I08  Income from facilities and services": "float",
    "I09  Income from catering": "float",
    "I10  Receipts from supply teacher insurance claims": "float",
    "I13  Donations and or private funds": "float",
    "Total Income   I01 to I18": "float",
    "CI04 Direct revenue financing": "float",
    "E01  Teaching Staff": "float",
    "E02  Supply teaching staff": "float",
    "E03 Education support staff": "float",
    "E04  Premises staff": "float",
    "E05 Administrative and clerical staff": "float",
    "E06 Catering staff": "float",
    "E07  Cost of other staff": "float",
    "E08  Indirect employee expenses": "float",
    "E09  Development and training": "float",
    "E10  Supply teacher insurance": "float",
    "E11  Staff related insurance": "float",
    "E12  Building maintenance and improvement": "float",
    "E13  Grounds maintenance and improvement": "float",
    "E14  Cleaning and caretaking": "float",
    "E15  Water and sewerage": "float",
    "E16  Energy": "float",
    "E17  Rates": "float",
    "E18  Other occupation costs": "float",
    "E19  Learning resources (not ICT equipment)": "float",
    "E20  ICT learning resources": "float",
    "E21  Exam fees": "float",
    "E22 Administrative supplies": "float",
    "E23  Other insurance premiums": "float",
    "E24  Special facilities ": "float",
    "E25  Catering supplies": "float",
    "E26 Agency supply teaching staff": "float",
    "E27  Bought in professional services - curriculum": "float",
    "E28a  Bought in professional services - other (except PFI)": "float",
    "E28b Bought in professional services - other (PFI)": "float",
    "E29  Loan interest": "float",
    "E30 Direct revenue financing (revenue contributions to capital)": "float",
    "E31  Community focused school staff": "float",
    "E32 Community focused school costs": "float",
    "Total Expenditure  E01 to E32": "float",
    "Revenue Reserve   B01 plus B02 plus B06": "float",
    "Direct Grant": "float",
    "Targeted Grants": "float",
    "Community Grants": "float",
    "Self Generated Funding": "float",
}

# Starting in 2025, E20 (ICT learning resources) was split into multiple subcategories (E20A-E20G)
_maintained_split_ict = _maintained_default.copy()
_maintained_split_ict.pop("E20  ICT learning resources", None)
_maintained_split_ict.update(
    {
        "E20A  Connectivity": "float",
        "E20B  Onsite servers": "float",
        "E20C  IT learning resources": "float",
        "E20D  Administration software and systems": "float",
        "E20E  Laptops, desktops and tablets": "float",
        "E20F  Other hardware": "float",
        "E20G  IT support": "float",
    }
)

maintained_schools_master_list_cols = {
    "default": _maintained_default,
    2025: _maintained_split_ict,
    2026: _maintained_split_ict,
}

_eval_split_ict = {
    "Educational ICT_ICT learning resources": (
        "`E20A  Connectivity`.fillna(0.0) + "
        "`E20B  Onsite servers`.fillna(0.0) + "
        "`E20C  IT learning resources`.fillna(0.0) + "
        "`E20E  Laptops, desktops and tablets`.fillna(0.0) + "
        "`E20F  Other hardware`.fillna(0.0) + "
        "`E20G  IT support`.fillna(0.0)"
    ),
    "Administrative supplies_Administrative supplies (non educational)": (
        "`E20D  Administration software and systems`.fillna(0.0) + "
        "`E22 Administrative supplies`.fillna(0.0)"
    ),
}

maintained_schools_master_list_column_eval = {
    "default": {
        "Educational ICT_ICT learning resources": "`E20  ICT learning resources`.fillna(0.0)",
        "Administrative supplies_Administrative supplies (non educational)": (
            "`E22 Administrative supplies`.fillna(0.0)"
        ),
    },
    2025: _eval_split_ict,
    2026: _eval_split_ict,
}

# Year-on-year Master List Mapping Configurations
_master_list_base_mappings = {
    "I01  Funds delegated by the LA": "I01 Pre-16 Funding",
    "I02  Funding for 6th form students": "I02 Post-16 Funding",
    "I03  SEN funding": "I03 SEN",
    "I04  Funding for minority ethnic pupils": "I04 Funding for minority ethnic pupils",
    "I05  Pupil Premium": "I05 Pupil Premium",
    "I06  Other government grants": "I06 Other DfE/EFA Revenue Grants",
    "I07  Other grants and payments": "I07 Other income (LA & other Government grants)",
    "I08  Income from facilities and services": "I08a/b Income from facilities and services",
    "I09  Income from catering": "I09 Income from catering",
    "I10  Receipts from supply teacher insurance claims": "I10 Receipts from supply teacher insurance claims",
    "I11  Receipts from other insurance claims": "I11 Receipts from other insurance claims",
    "I12  Income from contributions to visits etc ": "I12 Income from contributions to visits etc",
    "I13  Donations and or private funds": "I13 Donations and/or voluntary funds",
    "I15  Pupil focussed extended school funding and   or grants": "I15 Pupil focussed extended school funding and/or grants",
    "I16  Community focussed school funding and   or grants": "I16 Community focussed school funding and/or grants",
    "I17  Community focused school facilities income": "I17 Community focused school facilities income",
    "I18  Additional grant for schools": "I18 Total additional grant for schools",
    "Total Income   I01 to I08, I11 to I15, I18": "Total Income: I01 to I08, I11 to I15, I18 minus E30",
    "Total Income   I01 to I18": "Total Income: I01 to I18 minus E30",
    "E01  Teaching Staff": "E01 Teaching staff",
    "E02  Supply teaching staff": "E02 Supply teaching staff",
    "E03 Education support staff": "E03 Education support staff",
    "E04  Premises staff": "E04 Premises staff",
    "E05 Administrative and clerical staff": "E05 Administrative and clerical staff",
    "E06 Catering staff": "E06 Catering staff",
    "E07  Cost of other staff": "E07 Other staff",
    "E08  Indirect employee expenses": "E08 Indirect employee expenses",
    "E09  Development and training": "E09 Staff development and training",
    "E10  Supply teacher insurance": "E10 Supply teacher insurance",
    "E11  Staff related insurance": "E11 Staff-related insurance",
    "E12  Building maintenance and improvement": "E12 Building maintenance and improvement",
    "E13  Grounds maintenance and improvement": "E13 Grounds maintenance and improvement",
    "E14  Cleaning and caretaking": "E14 Cleaning and caretaking",
    "E15  Water and sewerage": "E15 Water and sewerage",
    "E16  Energy": "E16 Energy",
    "E17  Rates": "E17 Rates",
    "E18  Other occupation costs": "E18 Other occupation costs",
    "E19  Learning resources (not ICT equipment)": "E19 Learning resources (not ICT equipment)",
    "E20A  Connectivity": "E20A Connectivity",
    "E20B  Onsite servers": "E20B Onsite servers",
    "E20C  IT learning resources": "E20C IT learning resources",
    "E20D  Administration software and systems": "E20D Administration software and systems",
    "E20E  Laptops, desktops and tablets": "E20E Laptops, desktops and tablets",
    "E20F  Other hardware": "E20F Other hardware",
    "E20G  IT support": "E20G IT support",
    "E21  Exam fees": "E21 Examination fees",
    "E22 Administrative supplies": "E22 Administrative supplies - non educational",
    "E23  Other insurance premiums": "E23 Other insurance premiums",
    "E24  Special facilities ": "E24 Special facilities",
    "E25  Catering supplies": "E25 Catering supplies",
    "E26 Agency supply teaching staff": "E26 Agency supply teaching staff",
    "E27  Bought in professional services - curriculum": "E27 Educational Consultancy",
    "E28a  Bought in professional services - other (except PFI)": "E28a Bought in professional services, other, not PFI",
    "E28b Bought in professional services - other (PFI)": "E28b Bought in professional services, other, PFI",
    "E29  Loan interest": "E29 Interest charges for Loan and Bank",
    "E30 Direct revenue financing (revenue contributions to capital)": "E30 Direct revenue financing (Revenue contributions to capital)",
    "E31  Community focused school staff": "E31 Community focused school staff",
    "E32 Community focused school costs": "E32 Community focused school costs",
    "Total Expenditure  E01 to E29 and E31 to E32 minus I9, I10, I16 and I17": "Total Expenditure:E01 to E29 and E31 to E32 minus I9, I10, I16 and I17",
    "Total Expenditure  E01 to E32": "Total Expenditure:E01 to E29 and E31 to E32",
    "OB01  Opening pupil-focused revenue balance": "OB01 Opening pupil-focused revenue balance",
    "OB02 Opening community-focused revenue balance": "OB02 Opening community-focused revenue balance",
    "OB03 Opening capital balance": "OB03 Opening capital balance",
    "CI01 Capital income": "CI01 Capital income",
    "CI03 Voluntary or private income": "CI03 Voluntary or private income",
    "CI04 Direct revenue financing": "CI04 Direct revenue financing",
    "CE01 Acquisition of land and existing buildings": "CE01 Acquisition of land and existing buildings",
    "CE02 New construction, conversion and renovation": "CE02 New construction, conversion and renovation",
    "CE03 Vehicles, plant, equipment and machinery": "CE03 Vehicles, plant, equipment and machinery",
    "CE04 Information and communication technology": "CE04 Information and communication technology",
    "B01 Committed revenue balances": "B01 Committed revenue balances",
    "B02 Uncommitted revenue balances": "B02 Uncommitted revenue balances",
    "B03 Devolved formula capital balance": "B03 Devolved formula capital balance",
    "B05 Other capital balances": "B05 Other capital balances",
    "B06 Community-focused school revenue balances": "B06 Community-focused school revenue balances",
    "Revenue Reserve   B01 plus B02 plus B06": "Revenue Reserve: B01 + B02 + B06",
    "In-year Balance   Total Income (I01 to I18) minus Total Expenditure (E01 to E32)": "In-year Balance",
    "Grant Funding": "Grant Funding: (I01:I07) + I15 + I16 + I18a/b/c/d",
    "Direct Grant": "Direct Grants: I01:I02 + I06:I07",
    "Community Grants": "Community Grants: I16+I18",
    "Targeted Grants": "Targetted Grants: I03:I05 + I15",
    "Self Generated Funding": "Self Generated Funding: (I08a/b:I13) + I17",
    "Total Income ": "Total income",
    "Supply Staff": "Supply Staff: E02 + E10 + E26",
    "Other Staff Costs": "Other Staff Costs: (E07:E09) + E11",
    "Staff Total ": "Staff Total: (E01:E03) + E05 + (E07: E11) + E26",
    "Maintenance & Improvement": "Maintenance & Improvement: E12 + E13",
    "Premises": "Premises: (E12:E14) + E04 + E28b",
    "Catering Exp": "Catering Expenses: E06 + E25",
    "Occupation": "Occupation: E06 + (E15:E18) + E23 + E25",
    "Supplies and Services": "Supplies and Services: (E19:E22) + (E27:E28b)",
    "Educational Supplies": "Educational Supplies: (E19:E21)",
    "Brought in Professional Sevices": "Brought in Professional Sevices: (E27 + E28a)",
    "Cost of Finance": None,
    "Community Exp": "Community Exp: E31 + E32",
    "Total Expenditure": "Total Expenditure excluding E30",
}

_master_list_2026_mappings = _master_list_base_mappings.copy()
_master_list_2026_mappings.pop("I18  Additional grant for schools", None)
_master_list_2026_mappings.pop("Total Income   I01 to I08, I11 to I15, I18", None)

master_list_mappings = {
    "default": _master_list_base_mappings,
    2026: _master_list_2026_mappings,
}

# Year-on-year Download File Mapping Configurations
_download_file_base_mappings = {
    "I01 Funds delegated by the LA": "I01 Pre-16 Funding",
    "I02 Funding for 6th form students": "I02 Post-16 Funding",
    "I01/2 Total pre and Post-16 Funding": "I01/2 Pre and Post-16 Funding",
    "I03 SEN funding": "I03 SEN",
    "I04 Funding for minority ethnic pupils": "I04 Funding for minority ethnic pupils",
    "I05 Pupil premium": "I05 Pupil Premium",
    "I06 Other government grants": "I06 Other DfE/EFA Revenue Grants",
    "I07 Other grants and payments": "I07 Other income (LA & other Government grants)",
    "I08a Income from lettings": "I08a Income from lettings",
    "I08b Income from facilities and services": "I08b Income from facilities and services",
    "I08a/b Total income from facilities and services": "I08a/b Income from facilities and services",
    "I09 Income from catering": "I09 Income from catering",
    "I10 Receipts from supply teacher insurance claims": "I10 Receipts from supply teacher insurance claims",
    "I11 Receipts from other insurance claims": "I11 Receipts from other insurance claims",
    "I12 Income from contributions to visits etc.": "I12 Income from contributions to visits etc",
    "I13 Donations and/or private funds": "I13 Donations and/or voluntary funds",
    "I15 Pupil focussed extended school funding and / or grants": "I15 Pupil focussed extended school funding and/or grants",
    "I16 Community focussed school funding and / or grants": "I16 Community focussed school funding and/or grants",
    "I17 Community focused school facilities income": "I17 Community focused school facilities income",
    "I18c Income from the £1bn COVID-19 catch-up package announced on 20 July 2020": "I18c Income from the £1bn COVID-19 catch-up package announced on 20 July 2020",
    "I18d Income from other additional grants": "I18d Income from other additional grants",
    "I18 Total additional grant for schools": "I18 Total additional grant for schools",
    "E01 Teaching staff": "E01 Teaching staff",
    "E02 Supply teaching staff": "E02 Supply teaching staff",
    "E03 Education support staff": "E03 Education support staff",
    "E04 Premises staff": "E04 Premises staff",
    "E05 Administrative and clerical staff": "E05 Administrative and clerical staff",
    "E06 Catering staff": "E06 Catering staff",
    "E07 Cost of other staff": "E07 Other staff",
    "E08 Indirect employee expenses": "E08 Indirect employee expenses",
    "E09 Development and training": "E09 Staff development and training",
    "E10 Supply teacher insurance": "E10 Supply teacher insurance",
    "E11 Staff related insurance": "E11 Staff-related insurance",
    "E12 Building maintenance and improvement": "E12 Building maintenance and improvement",
    "E13 Grounds maintenance and improvement": "E13 Grounds maintenance and improvement",
    "E14 Cleaning and caretaking": "E14 Cleaning and caretaking",
    "E15 Water and sewerage": "E15 Water and sewerage",
    "E16 Energy": "E16 Energy",
    "E17 Rates": "E17 Rates",
    "E18 Other occupation costs": "E18 Other occupation costs",
    "E19 Learning resources (not ICT equipment)": "E19 Learning resources (not ICT equipment)",
    "E20A Connectivity": "E20A Connectivity",
    "E20B Onsite servers": "E20B Onsite servers",
    "E20C IT learning resources": "E20C IT learning resources",
    "E20D Administration software and systems": "E20D Administration software and systems",
    "E20E Laptops, desktops and tablets": "E20E Laptops, desktops and tablets",
    "E20F Other hardware": "E20F Other hardware",
    "E20G IT support": "E20G IT support",
    "E21 Exam fees": "E21 Examination fees",
    "E22 Administrative supplies": "E22 Administrative supplies - non educational",
    "E23 Other insurance premiums": "E23 Other insurance premiums",
    "E24 Special facilities": "E24 Special facilities",
    "E25 Catering supplies": "E25 Catering supplies",
    "E26 Agency supply teaching staff": "E26 Agency supply teaching staff",
    "E27 Bought in professional services – curriculum": "E27 Educational Consultancy",
    "E28a Bought in professional services, other, not PFI": "E28a Bought in professional services, other, not PFI",
    "E28b Bought in professional services, other, PFI": "E28b Bought in professional services, other, PFI",
    "E28a/b Total bought in professional services": "E28a/b Bought in professional services",
    "E29 Loan interest": "E29 Interest charges for Loan and Bank",
    "E30 Direct revenue financing (Revenue contributions to capital)": "E30 Direct revenue financing (Revenue contributions to capital)",
    "E31 Community focused school staff": "E31 Community focused school staff",
    "E32 Community focused school costs": "E32 Community focused school costs",
    "OB01 Opening pupil-focused revenue balance": "OB01 Opening pupil-focused revenue balance",
    "OB02 Opening community-focused revenue balance": "OB02 Opening community-focused revenue balance",
    "OB03 Opening capital balance": "OB03 Opening capital balance",
    "CI01 Capital income": "CI01 Capital income",
    "CI03 Voluntary or private income": "CI03 Voluntary or private income",
    "CI04 Direct revenue financing": "CI04 Direct revenue financing",
    "CE01 Acquisition of land and existing buildings": "CE01 Acquisition of land and existing buildings",
    "CE02 New construction, conversion and renovation": "CE02 New construction, conversion and renovation",
    "CE03 Vehicles, plant, equipment and machinery": "CE03 Vehicles, plant, equipment and machinery",
    "CE04A Connectivity": "CE04A Connectivity",
    "CE04B Onsite servers": "CE04B Onsite servers",
    "CE04C Administration software and systems": "CE04C Administration software and systems",
    "CE04D Laptops desktops and tablets": "CE04D Laptops desktops and tablets",
    "CE04E Other hardware": "CE04E Other hardware",
    "B01 Committed revenue balances": "B01 Committed revenue balances",
    "B02 Uncommitted revenue balances": "B02 Uncommitted revenue balances",
    "B03 Devolved formula capital balance": "B03 Devolved formula capital balance",
    "B05 Other capital balances": "B05 Other capital balances",
    "B06 Community-focused school revenue balances": "B06 Community-focused school revenue balances",
    "B07 Outstanding balance on capital loans to school": "B07 Outstanding balance on capital loans to school",
    "Revenue Reserve: B01 + B02 + B06": "Revenue Reserve: B01 + B02 + B06",
    "In-year Balance: Total Income (I01:I18 - E30) - Total Expenditure (E01:E29 + E31 + E32)": "In-year Balance",
    "Grant Funding: (I01:I07) + I15 + I16 + I18a/b/c/d": "Grant Funding: (I01:I07) + I15 + I16 + I18a/b/c/d",
    "Direct Grants: I01:I02 + I06:I07": "Direct Grants: I01:I02 + I06:I07",
    "Community Grants: I16+I18": "Community Grants: I16+I18",
    "Targetted Grants: I03:I05 + I15": "Targetted Grants: I03:I05 + I15",
    "Self Generated Funding: (I08a/b:I13) + I17": "Self Generated Funding: (I08a/b:I13) + I17",
    "Total Income: I01:I18 - E30": "Total income",
    "Teaching Staff E01": "Teaching Staff: E01",
    "Supply Staff: E02 + E10 + E26": "Supply Staff: E02 + E10 + E26",
    "Education support staff: E03": "Education support staff: E03",
    "Other Staff Costs: (E07:E09) + E11": "Other Staff Costs: (E07:E09) + E11",
    "Staff Total: (E01:E03) + E05 + (E07: E11) + E26": "Staff Total: (E01:E03) + E05 + (E07: E11) + E26",
    "Maintenance & Improvement: E12 + E13": "Maintenance & Improvement: E12 + E13",
    "Premises: (E12:E14) + E04 + E28b": "Premises: (E12:E14) + E04 + E28b",
    "Catering Expenses: E06 + E25": "Catering Expenses: E06 + E25",
    "Occupation: E06 + (E15:E18) + E23 + E25": "Occupation: E06 + (E15:E18) + E23 + E25",
    "Supplies and Services: (E19:E22) + (E27:E28b)": "Supplies and Services: (E19:E22) + (E27:E28b)",
    "Educational Supplies: (E19:E21)": "Educational Supplies: (E19:E21)",
    "Brought in Professional Services: (E27 + E28a)": "Brought in Professional Sevices: (E27 + E28a)",
    "Community Exp: E31 + E32": "Community Exp: E31 + E32",
    "Total Expenditure: (E01:E29 + E31 + E32)": "Total Expenditure excluding E30",
}

_download_file_2026_mappings = _download_file_base_mappings.copy()
_download_file_2026_mappings.pop(
    "I18c Income from the £1bn COVID-19 catch-up package announced on 20 July 2020",
    None,
)
_download_file_2026_mappings.pop("I18d Income from other additional grants", None)
_download_file_2026_mappings.pop("I18 Total additional grant for schools", None)

download_file_mappings = {
    "default": _download_file_base_mappings,
    2026: _download_file_2026_mappings,
}
