environment-prefix       = "__environmentPrefix__"
environment              = "__environment__"
location                 = "__location__"
cip-environment          = "__cipEnvironment__"
disable-purge-protection = "__disablePurgeProtection__"
support-alert-email      = "__supportAlertEmail__"
