pool:
  vmImage: 'windows-2022'

trigger: none

stages:
  - stage: Build
    displayName: 'Build artifacts'
    jobs:
      - job: Zip_static_artifacts
        displayName: 'Zip static artifacts'
        steps:
          - task: ArchiveFiles@2
            displayName: 'Zip terraform files'
            inputs:
              rootFolderOrFile: 'core-infrastructure/terraform'
              includeRootFolder: false
              archiveFile: '$(Build.ArtifactStagingDirectory)/terraform.zip'

          - publish: $(Build.ArtifactStagingDirectory)/terraform.zip
            artifact: terraform

  - stage: DeployDevelopment
    dependsOn: [Build]
    displayName: 'Deploy to development'
    jobs:
      - template: jobs-core-deployment.yaml
        parameters:
          subscription: 's198d.azdo-deployment'
          environmentPrefix: 's198d01'
          environment: 'development'
          cipEnvironment: 'Dev'
          devopsPrincipal: '5018b284-3fee-449b-9e73-936e7efb1e78'