pool:
  vmImage: 'ubuntu-latest'

trigger:
  batch: true
  branches:
    include:
      - main
  paths:
    include:
      - core-infrastructure

pr: none

stages:
  - stage: Build
    displayName: 'Build artifacts'
    jobs:
      - job: RunCheckov
        displayName: "Checkov scan terraform"
        steps:
          - template: steps-core-scan-terraform.yaml
            parameters:
              TerraformDirectory: $(System.DefaultWorkingDirectory)/core-infrastructure/terraform

      - job: Zip_static_artifacts
        displayName: 'Zip static artifacts'
        steps:
          - template: steps-core-publish-static-artifacts.yaml

  - stage: DeployDevelopment
    dependsOn: [Build]
    displayName: 'Deploy to development'
    jobs:
      - template: jobs-core-deployment.yaml
        parameters:
          subscription: 's198d.azdo-deployment'
          environmentPrefix: 's198d01'
          environment: 'development'
          cipEnvironment: 'Dev'