pool:
  vmImage: 'ubuntu-latest'

trigger:
  batch: true
  branches:
    include:
      - main
  paths:
    include:
      - core-infrastructure

pr: none

stages:
  - stage: Build
    displayName: 'Build artifacts'
    jobs:
      - job: "runCheckov"
        displayName: "Checkov > Pull, run and publish results of Checkov scan"
        variables:
          directory: 'front-end-components'
        steps:
          - bash: docker pull bridgecrew/checkov
            workingDirectory: $(directory)
            displayName: "Pull > bridgecrew/checkov"
          - bash: |
              docker run --volume /terraform:/terraform --workdir /terraform bridgecrew/checkov --directory /terraform --output junitxml > CheckovReport.xml --soft-fail
            workingDirectory: $(directory)
            displayName: "Run > checkov"
          - task: PublishTestResults@2
            inputs:
              testRunTitle: "Checkov Results"
              failTaskOnFailedTests: true
              testResultsFormat: "JUnit"
              testResultsFiles: "CheckovReport.xml"
              searchFolder: "$(directory)"
            displayName: "Publish > Checkov scan results"

      - job: Zip_static_artifacts
        displayName: 'Zip static artifacts'
        steps:
          - template: steps-core-publish-static-artifacts.yaml

  - stage: DeployDevelopment
    dependsOn: [Build]
    displayName: 'Deploy to development'
    jobs:
      - template: jobs-core-deployment.yaml
        parameters:
          subscription: 's198d.azdo-deployment'
          environmentPrefix: 's198d01'
          environment: 'development'
          cipEnvironment: 'Dev'