export * from "src/views/compare-your-workforce/partials/types";
export * from "src/views/compare-your-workforce/partials/auxiliary-staff";
export * from "src/views/compare-your-workforce/partials/headcount";
export * from "src/views/compare-your-workforce/partials/non-classroom-support";
export * from "src/views/compare-your-workforce/partials/school-workforce";
export * from "src/views/compare-your-workforce/partials/senior-leadership";
export * from "src/views/compare-your-workforce/partials/teaching-assistants";
export * from "src/views/compare-your-workforce/partials/total-teachers";
export * from "src/views/compare-your-workforce/partials/total-teachers-qualified";
