name: "debug-data-pipeline"

services:
  pipeline:
    container_name: "pipeline-debug"
    build:
      context: ../data-pipeline
      dockerfile: ../data-pipeline/pipeline-worker/Dockerfile

    environment:
      STORAGE_CONNECTION_STRING: ${AZURITE_CONNECTION_STRING}
      WORKER_QUEUE_NAME: data-pipeline-job-default-start
      COMPLETE_QUEUE_NAME: data-pipeline-job-finished
      RAW_DATA_CONTAINER: raw
      DB_PORT: 1433
      DB_ARGS: Encrypt=no;TrustServerCertificate=no;Connection Timeout=30
      DB_HOST: mssql
      DB_NAME: ${DB_NAME}
      DB_USER: ${MSSQL_USER}
      DB_PWD: ${SA_PASSWORD}
      ENV: dev
      PYTHONUNBUFFERED: "1"

    depends_on:
      azurite:
        condition: service_healthy
      mssql:
        condition: service_healthy
      redis:
        condition: service_healthy
      azurite-init:
        condition: service_completed_successfully
      mssql-init:
        condition: service_completed_successfully
      db-migrate:
        condition: service_completed_successfully

    volumes:
      - ../data-pipeline/src/pipeline:/pipeline

    ports:
      - "5678:5678"

    command:
      - python
      - -m
      - debugpy
      - --listen
      - 0.0.0.0:5678
      - --wait-for-client
      - -m
      - pipeline.main
