displayName: Peak_API_Benchmark - User Data
testPlan: url-test.json
description: Peak load test for GET /user-data
engineInstances: 1
testId: b2169cfc-f186-4452-8717-d64aed36246a
testType: URL
subnetId: /subscriptions/a5c0a8d7-a54d-4a6d-ab79-4ca64a3b750f/resourceGroups/s198t01-ebis-core/providers/Microsoft.Network/virtualNetworks/s198t01-app-service-network/subnets/s198t01-load-test-subnet
publicIPDisabled: true
splitAllCSVs: False
failureCriteria:
- p75(response_time_ms) > 200
- p95(response_time_ms) > 300
- p99(response_time_ms) > 500
- percentage(error) > 1
secrets:
- name: benchmark-host-key
  value: https://s198t01-ebis-keyvault.vault.azure.net/secrets/benchmark-host-key
env:
- name: user-id
  value: 0b39be11-6c9f-4f43-882a-a14fce1db545
autoStop:
  errorPercentage: 90
  timeWindow: 60
