parameters:
  subscription: ''
  environmentPrefix: ''
  environment: ''
  cipEnvironment: ''
  workspaceDir: '$(Pipeline.Workspace)'
  dependsOn: []

jobs:
  - deployment: ChartRendererDeployment
    displayName: 'ChartRenderer deployment'
    dependsOn: ${{ parameters.dependsOn }}
    pool:
      vmImage: ubuntu-latest
    environment: ${{ parameters.environment }}
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: none

            - download: current

            - task: AzureCLI@2
              displayName: 'Whitelist Agent IP'
              inputs:
                azureSubscription: ${{ parameters.subscription }}
                scriptType: 'bash'
                scriptLocation: 'inlineScript'
                inlineScript: |
                  agentIP=$(curl -s https://api.ipify.org)
                  echo "Agent IP: $agentIP"
                  
                  storageName=$(az storage account list -g ${{ parameters.environmentPrefix }}-ebis-chart-renderer --query "[0].name" -o tsv)
                  rgName="${{ parameters.environmentPrefix }}-ebis-chart-renderer"
                  
                  echo "Whitelisting $agentIP on Storage: $storageName"
                  az storage account network-rule add --account-name $storageName --resource-group $rgName --ip-address $agentIP
                  
                  # Small delay to allow DNS/Firewall propagation
                  sleep 30

            - template: ..\common\run-terraform.yaml
              parameters:
                subscription: ${{ parameters.subscription }}
                environmentPrefix: ${{ parameters.environmentPrefix }}
                environment: ${{ parameters.environment }}
                cipEnvironment: ${{ parameters.cipEnvironment }}
                module: 'chart-renderer'
                packagePath: '${{ parameters.workspaceDir }}/chart-renderer-apis/ChartRenderer.Api.zip'

            - task: AzureCLI@2
              displayName: 'Remove Whitelist'
              condition: always()
              inputs:
                azureSubscription: ${{ parameters.subscription }}
                scriptType: 'bash'
                scriptLocation: 'inlineScript'
                inlineScript: |
                  storageName=$(az storage account list -g ${{ parameters.environmentPrefix }}-ebis-chart-renderer --query "[0].name" -o tsv)
                  rgName="${{ parameters.environmentPrefix }}-ebis-chart-renderer"
                  
                  echo "Removing agent IP from Storage: $storageName"
                  az storage account network-rule remove --account-name $storageName --resource-group $rgName --ip-address $(curl -s https://api.ipify.org)
