pool:
  vmImage: 'ubuntu-latest'

trigger:
  batch: true
  branches:
    include:
      - main
  paths:
    include:
      - data-pipeline
      - pipelines/data-pipeline
      - pipelines/common

pr:
  paths:
    include:
      - data-pipeline

variables:
  - template: ..\common\vars.yaml
  - name: TerraformFolder
    value: 'data-pipeline/terraform'
  - name: TerraformDirectory
    value: '$(System.DefaultWorkingDirectory)/$(TerraformFolder)'

name: $(Version)$(Version.Revision.Separator)$(Version.Revision).$(Rev:r)

stages:
  - stage: Build
    displayName: 'Build'
    jobs:
      - job: BranchValidate
        displayName: "Validate branch name"
        steps:
          - checkout: none
          - template: ..\common\validate-branch.yaml
            parameters:
              branchName: $(SourceBranch)

      - job: SetBuildNumber
        displayName: 'Set build number'
        steps:
          - checkout: none
          - bash: |
              echo "##vso[task.setvariable variable=Version.BuildNumber]$(Version.BuildNumber)"
              echo "##vso[task.setvariable variable=Version.BuildVersion]$(Version.BuildNumber)"
              echo "##vso[build.updatebuildnumber]$(Version.BuildNumber)"
              echo "##vso[build.addbuildtag]$(Version.BuildNumber)"
            displayName: 'Set release build number'
            condition: and(succeeded(), eq(variables['ShouldDeploy'],'true'))

          - bash: |
              if [[ "$(Build.Reason)" == "PullRequest" ]]; then
                echo "##vso[build.addbuildtag]PR$(System.PullRequest.PullRequestId)"
              fi
              echo "##vso[build.addbuildtag]Data pipeline"
            displayName: 'Set build tags'

      - job: FmtValidateTf
        displayName: "Lint and validate terraform"
        steps:
          - template: ..\common\fmt-validate-terraform.yaml
            parameters:
              TerraformDirectory: $(TerraformDirectory)

      - job: RunCheckOv
        displayName: "Static analysis terraform"
        steps:
          - template: ..\common\scan-terraform.yaml
            parameters:
              TerraformDirectory: $(TerraformDirectory)

      - job: MarkdownLint
        displayName: 'Markdown lint'
        steps:
          - template: ..\common\markdown-lint.yaml
            parameters:
              DocumentsDirectory: '$(System.DefaultWorkingDirectory)/data-pipeline'

      - job: ZipStaticArtifacts
        displayName: 'Zip static artifacts'
        condition: and(succeeded(), eq(variables['ShouldDeploy'],'true'))
        steps:
          - template: ..\common\publish-terraform-artifacts.yaml
            parameters:
              TerraformFolder: $(TerraformFolder)
              Module: 'data-pipeline'

      - job: RunTests
        displayName: 'Run unit tests'
        steps:
          - template: steps\run-unit-tests.yaml

      - job: BuildAndPush
        dependsOn: [ BranchValidate, SetBuildNumber, RunTests ]
        displayName: 'Build and push image'
        condition: and(succeeded(), eq(variables['ShouldDeploy'],'true'))
        steps: 
          - template: steps/build-push-image.yaml
            parameters:
              buildNumber: $(Version.BuildNumber)
              environmentPrefix: 's198d01'
              subscription: 's198d.azdo-deployment'

  - stage: DeployDevelopment
    dependsOn: [ Build ]
    displayName: 'Development'
    condition: and(succeeded(), eq(variables['ShouldDeploy'],'true'))
    jobs:
      - template: deployment.yaml
        parameters:
          subscription: 's198d.azdo-deployment'
          environmentPrefix: 's198d01'
          environment: 'development'
          cipEnvironment: 'Dev'
          importImage: false
          buildNumber: $(Version.BuildNumber)

  - stage: DeployAutomatedTest
    dependsOn: [ Build ]
    displayName: 'Automated test'
    condition: and(succeeded(), eq(variables['ShouldDeploy'],'true'))
    jobs:
      - template: deployment.yaml
        parameters:
          subscription: 's198d.azdo-deployment'
          sourceServicePrincipal: 's198d.azdo-deployment'
          sourceSubscription: 's198-dfebenchmarkingservice-development'
          environmentPrefix: 's198d02'
          environment: 'automated-test'
          cipEnvironment: 'Dev'
          importImage: true
          sourceEnvironmentPrefix: 's198d01'
          buildNumber: $(Version.BuildNumber)

      - job: RunE2ETests
        dependsOn: [ DataPipelineProvision ]
        displayName: 'Run E2E tests'
        steps:
          - template: steps\run-e2e-tests.yaml
            parameters:
              workspaceDir: '$(Pipeline.Workspace)'
              subscription: 's198d.azdo-deployment'
              environmentPrefix: 's198d02'

  - stage: DeployTest
    dependsOn: [ DeployAutomatedTest ]
    displayName: 'Test'
    condition: and(succeeded(), eq(variables['ShouldDeploy'],'true'))
    jobs:
      - template: deployment.yaml
        parameters:
          subscription: 's198t.azdo-deployment'
          sourceServicePrincipal: 's198d.azdo-deployment'
          sourceSubscription: 's198-dfebenchmarkingservice-development'
          environmentPrefix: 's198t01'
          environment: 'test'
          cipEnvironment: 'Test'
          importImage: true
          sourceEnvironmentPrefix: 's198d02'
          buildNumber: $(Version.BuildNumber)