trigger:
  branches:
    include:
      - main
      - feature/databricks-notebooks

pr:
  - main

variables:
  - group: databricks-vars
  - name: PYTHON_VERSION
    value: '3.12'

stages:
  - stage: Test
    displayName: 'Test and Validate'
    jobs:
      - job: unit_tests
        displayName: 'Unit Tests'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '$(PYTHON_VERSION)'
            displayName: 'Use Python $(PYTHON_VERSION)'

          - script: |
              sudo apt-get update
              sudo apt-get install temurin-17-jdk
            displayName: 'Install Java 17'

          - script: |
              curl -LsSf https://astral.sh/uv/install.sh | sh
              echo "##vso[task.prependpath]$HOME/.cargo/bin"
            displayName: 'Install uv'

          - script: |
              uv sync --group unit-test
            workingDirectory: $(System.DefaultWorkingDirectory)/databricks/education_benchmarking_and_insights
            displayName: 'Install Dependencies with uv'

          - script: |
              uv run pytest -v
            workingDirectory: $(System.DefaultWorkingDirectory)/databricks/education_benchmarking_and_insights
            displayName: 'Run unit tests'
            continueOnError: false

      - job: prepare_artifacts
        dependsOn: unit_tests
        displayName: 'Prepare artifacts for the restricted windows deployment runner'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: CopyFiles@2
            displayName: 'Copy source files to staging'
            inputs:
              SourceFolder: '$(Build.SourcesDirectory)'
              Contents: |
                databricks/**
                !databricks/**/.pytest_cache/**
                !databricks/**/__pycache__/**
                !databricks/**/.venv/**
                !databricks/tf_binaries.zip
              TargetFolder: '$(Build.ArtifactStagingDirectory)'
              CleanTargetFolder: true

          - task: ExtractFiles@1
            inputs:
              archiveFilePatterns: '**/*.zip'
              destinationFolder: $(Build.ArtifactStagingDirectory)
              cleanDestinationFolder: false
            displayName: 'Unzip terraform provider binaries'

          - script: |
              curl -fsSL https://releases.hashicorp.com/terraform/1.8.5/terraform_1.8.5_windows_amd64.zip \
               -o $(Build.ArtifactStagingDirectory)\tf_binaries\tf_binaries\terraform.zip
              unzip $(Build.ArtifactStagingDirectory)\tf_binaries\tf_binaries\terraform.zip -d $(Build.ArtifactStagingDirectory)\tf_binaries\tf_binaries
              rm $(Build.ArtifactStagingDirectory)\tf_binaries\tf_binaries\terraform.zip
            displayName: 'Download Windows terraform binary'

          - script: |
              curl -fsSL https://github.com/databricks/cli/releases/download/v0.276.0/databricks_cli_0.276.0_windows_amd64.zip -o $(Build.ArtifactStagingDirectory)/databricks-cli.zip
              unzip $(Build.ArtifactStagingDirectory)/databricks-cli.zip -d $(Build.ArtifactStagingDirectory)/databricks-cli
              rm $(Build.ArtifactStagingDirectory)/databricks-cli.zip
            displayName: 'Download Windows Databricks CLI binary'

          - script: |
              curl -LsSf https://github.com/astral-sh/uv/releases/latest/download/uv-x86_64-pc-windows-msvc.zip -o $(Build.ArtifactStagingDirectory)/uv.zip
              unzip $(Build.ArtifactStagingDirectory)/uv.zip -d $(Build.ArtifactStagingDirectory)/uv
              rm $(Build.ArtifactStagingDirectory)/uv.zip
            displayName: 'Download uv for Windows'

          - task: PublishBuildArtifacts@1
            displayName: 'Publish Artifact'
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: '$(artifactName)'
              publishLocation: 'Container'

      - job: bundle_validate
        dependsOn: prepare_artifacts
        displayName: 'Validate Databricks bundle'
        pool:
          name: DD-Hosted-Prod
        steps:
          - checkout: none
            displayName: 'Skip checkout (using artifact)'

          - task: DownloadBuildArtifacts@1
            displayName: 'Download source code artifact'
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: '$(artifactName)'
              downloadPath: '$(System.ArtifactsDirectory)'

          - script: |
              databricks bundle validate
            workingDirectory: $(System.ArtifactsDirectory)\$(artifactName)\databricks\education_benchmarking_and_insights
            displayName: 'Validate Bundle Configuration'
            env:
              PATH: $(System.ArtifactsDirectory)\$(artifactName)\databricks-cli;$(PATH)
              DATABRICKS_HOST: $(DATABRICKS_HOST)
              DATABRICKS_TOKEN: $(DATABRICKS_TOKEN)

  - stage: DeployDev
    displayName: 'Deploy to Dev'
    dependsOn: Test
    condition: and(succeeded())
    trigger: manual
    jobs:
      - deployment: DeployDevBundle
        displayName: 'Deploy to Dev Environment'
        environment: 'development'
        pool:
          name: DD-Hosted-Prod
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: none
                  displayName: 'Skip checkout (using artifact)'

                - task: DownloadBuildArtifacts@1
                  displayName: 'Download source code artifact'
                  inputs:
                    buildType: 'current'
                    downloadType: 'single'
                    artifactName: '$(artifactName)'
                    downloadPath: '$(System.ArtifactsDirectory)'

                - script: |
                    copy $(System.ArtifactsDirectory)\$(artifactName)\tf_binaries\tf_binaries\registry.terraform.io\databricks\databricks\terraform-provider-databricks_1.96.0_windows_amd64.zip C:\temp\tf_binaries\registry.terraform.io\databricks\databricks\terraform-provider-databricks_1.96.0_windows_amd64.zip
                    databricks bundle deploy --target dev --var="git_commit=%GIT_COMMIT%"
                  displayName: 'Deploy Bundle'
                  workingDirectory: $(System.ArtifactsDirectory)\$(artifactName)\databricks\education_benchmarking_and_insights
                  env:
                    PATH: $(System.ArtifactsDirectory)\$(artifactName)\uv;$(System.ArtifactsDirectory)\$(artifactName)\databricks-cli;$(PATH)
                    DATABRICKS_HOST: $(DATABRICKS_HOST)
                    DATABRICKS_TOKEN: $(DATABRICKS_TOKEN)
                    DATABRICKS_TF_VERSION: 1.8.5
                    DATABRICKS_TF_EXEC_PATH: $(System.ArtifactsDirectory)\$(artifactName)\tf_binaries\tf_binaries\terraform.exe
                    DATABRICKS_TF_PROVIDER_VERSION: 1.96.0
                    DATABRICKS_TF_CLI_CONFIG_FILE: $(System.ArtifactsDirectory)\$(artifactName)\databricks\terraform.rc
                    GIT_COMMIT: $(Build.SourceVersion)

  - stage: DeployProd
    displayName: 'Deploy to Production'
    dependsOn: DeployDev
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    jobs:
      - deployment: DeployProdBundle
        displayName: 'Deploy to Production Environment'
        pool:
          name: DD-Hosted-Prod
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: none
                  displayName: 'Skip checkout (using artifact)'

                - task: DownloadBuildArtifacts@1
                  displayName: 'Download source code artifact'
                  inputs:
                    buildType: 'current'
                    downloadType: 'single'
                    artifactName: '$(artifactName)'
                    downloadPath: '$(System.ArtifactsDirectory)'

                - script: |
                    copy $(System.ArtifactsDirectory)\$(artifactName)\tf_binaries\tf_binaries\registry.terraform.io\databricks\databricks\terraform-provider-databricks_1.96.0_windows_amd64.zip \C:\temp\tf_binaries\registry.terraform.io\databricks\databricks\terraform-provider-databricks_1.96.0_windows_amd64.zip
                    databricks bundle deploy --target dev --var="git_commit=%GIT_COMMIT%"
                  displayName: 'Deploy Bundle'
                  workingDirectory: $(System.ArtifactsDirectory)\$(artifactName)\databricks\education_benchmarking_and_insights
                  env:
                    PATH: $(System.ArtifactsDirectory)\$(artifactName)\uv;$(System.ArtifactsDirectory)\$(artifactName)\databricks-cli;$(PATH)
                    DATABRICKS_HOST: $(DATABRICKS_HOST)
                    DATABRICKS_TOKEN: $(DATABRICKS_TOKEN)
                    DATABRICKS_TF_VERSION: 1.8.5
                    DATABRICKS_TF_EXEC_PATH: $(System.ArtifactsDirectory)\$(artifactName)\tf_binaries\tf_binaries\terraform.exe
                    DATABRICKS_TF_PROVIDER_VERSION: 1.96.0
                    DATABRICKS_TF_CLI_CONFIG_FILE: $(System.ArtifactsDirectory)\$(artifactName)\databricks\terraform.rc
                    GIT_COMMIT: $(Build.SourceVersion)
