trigger:
  branches:
    include:
      - main
      - feature/296817/databricks-landing-zone

variables:
  azureServiceConnection: 's198d.azdo-deployment'
  resourceGroupName: 's198d01-databricks-landing-zone'
  location: 'westeurope'
  storageAccountName: 's198d01-databricks-landing-zone'  # Must be globally unique, 3-24 chars, lowercase alphanumeric
  containerName: 'landing'
  
pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Validate
    displayName: 'Validate Configuration'
    jobs:
      - job: ValidateJob
        displayName: 'Validate Parameters'
        steps:
          - task: AzureCLI@2
            displayName: 'Validate Azure CLI Version'
            inputs:
              azureSubscription: $(azureServiceConnection)
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                echo "Azure CLI Version:"
                az version
                echo "Logged in as:"
                az account show --query user.name -o tsv

  - stage: Deploy
    displayName: 'Deploy Storage Infrastructure'
    dependsOn: Validate
    jobs:
      - job: CreateResources
        displayName: 'Create Storage Resources'
        steps:
          - task: AzureCLI@2
            displayName: 'Create Resource Group'
            inputs:
              azureSubscription: $(azureServiceConnection)
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                echo "Creating resource group: $(resourceGroupName)"
                az group create \
                  --name $(resourceGroupName) \
                  --location $(location) \
                  --tags Environment=Production Purpose=DatabricksExternalVolume
                
                echo "Resource group created successfully"

          - task: AzureCLI@2
            displayName: 'Create Storage Account'
            inputs:
              azureSubscription: $(azureServiceConnection)
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                echo "Creating storage account: $(storageAccountName)"
                az storage account create \
                  --name $(storageAccountName) \
                  --resource-group $(resourceGroupName) \
                  --location $(location) \
                  --sku Standard_LRS \
                  --kind StorageV2 \
                  --hns \
                  --enable-large-file-share \
                  --tags Environment=Production Purpose=DatabricksExternalVolume
                
                echo "Storage account created with hierarchical namespace enabled"

          - task: AzureCLI@2
            displayName: 'Create Storage Container'
            inputs:
              azureSubscription: $(azureServiceConnection)
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                echo "Creating container: $(containerName)"
                az storage container create \
                  --name $(containerName) \
                  --account-name $(storageAccountName) \
                  --auth-mode login
                
                echo "Container created successfully"