parameters:
  subscription: ''
  sourceServicePrincipal: ''
  sourceSubscription: ''
  environmentPrefix: ''
  environment: ''
  cipEnvironment: ''
  buildNumber: ''
  workspaceDir: '$(Pipeline.Workspace)'
  importImage: true
  sourceEnvironmentPrefix: ''
  dependsOn: []

jobs:

  - deployment: DataPipelinePushImage
    displayName: 'Data Pipeline : Import Image'
    dependsOn: ${{ parameters.dependsOn }}
    condition: ${{ parameters.importImage }}
    pool:
      vmImage: ubuntu-latest
    environment: ${{ parameters.environment }}
    strategy:
      runOnce:
        deploy:
          steps:
            - task: AzureCLI@2
              displayName: Get source subscription ID
              inputs:
                azureSubscription: ${{ parameters.sourceServicePrincipal }}
                scriptType: 'bash'
                scriptLocation: 'inlineScript'
                inlineScript: |
                  ID=$(az account show --name ${{ parameters.sourceSubscription }} --output tsv --query "id")
                  echo "##vso[task.setvariable variable=sourceSubscriptionID]${ID}"

            - task: AzureCLI@2
              displayName: 'Import image from ${{ parameters.sourceEnvironmentPrefix }}acr.azurecr.io/fbit-data-pipeline:${{ parameters.buildNumber }}'
              inputs:
                azureSubscription: ${{ parameters.subscription }}
                scriptType: 'bash'
                scriptLocation: 'inlineScript'
                inlineScript: |
                    REGISTRY=/subscriptions/$(sourceSubscriptionID)/resourceGroups/${{ parameters.sourceEnvironmentPrefix }}-ebis-core/providers/Microsoft.ContainerRegistry/registries/${{ parameters.sourceEnvironmentPrefix }}acr
                    echo ${REGISTRY}
                    az acr import --name ${{ parameters.environmentPrefix }}acr --source fbit-data-pipeline:${{ parameters.buildNumber }} --image fbit-data-pipeline:${{ parameters.buildNumber }} --registry ${REGISTRY}

  - deployment: DataPipelineProvision
    displayName: 'Data Pipeline : Provision'
    dependsOn: ${{ parameters.dependsOn }}
    pool:
      vmImage: ubuntu-latest
    environment: ${{ parameters.environment }}
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: none

            - download: current

            - template: ..\common\run-terraform.yaml
              parameters:
                subscription: ${{ parameters.subscription }}
                environmentPrefix: ${{ parameters.environmentPrefix }}
                environment: ${{ parameters.environment }}
                cipEnvironment: ${{ parameters.cipEnvironment }}
                module: 'data-pipeline'
                imageName: 'fbit-data-pipeline:${{ parameters.buildNumber }}'


  