parameters:
  subscription: ''
  environmentPrefix: ''
  environment: ''
  cipEnvironment: ''
  buildVersion: ''
  buildNumber: ''
  workspaceDir: '$(Pipeline.Workspace)'
  dependsOn: []

jobs:

  - deployment: DataPipelinePushImage
    displayName: 'Data Pipeline : Push Image'
    dependsOn: ${{ parameters.dependsOn }}
    pool:
      vmImage: ubuntu-latest
    environment: ${{ parameters.environment }}
    strategy:
      runOnce:
        deploy:
          steps:
            - template: steps/build-push-image.yaml
              parameters:
                environmentPrefix: ${{ parameters.environmentPrefix }}
                environment: ${{ parameters.environment }}
                buildVersion: ${{ parameters.buildVersion }}
                buildNumber: ${{ parameters.buildNumber }}

  - deployment: DataPipelineProvision
    displayName: 'Data Pipeline : Provision'
    dependsOn: ${{ parameters.dependsOn }}
    pool:
      vmImage: ubuntu-latest
    environment: ${{ parameters.environment }}
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: none

            - download: current

            - template: ..\common\run-terraform.yaml
              parameters:
                subscription: ${{ parameters.subscription }}
                environmentPrefix: ${{ parameters.environmentPrefix }}
                environment: ${{ parameters.environment }}
                cipEnvironment: ${{ parameters.cipEnvironment }}
                module: 'data-pipeline'
                imageName: ''


  