parameters:
  subscription: ''
  environmentPrefix: ''
  environment: ''
  pipelineEnvironment: ''
  cipEnvironment: ''
  workspaceDir: '$(Pipeline.Workspace)'
  buildNumber: ''
  dependsOn: []

jobs:
  - job: DataPipelineDestroyManualValidation
    displayName: 'Validate destruction of Data Pipeline resources'
    dependsOn: ${{ parameters.dependsOn }}
    pool: server
    steps:
    - task: ManualValidation@0
      displayName: 'Validation'
      inputs:
        instructions: 'Approve this step to destroy all Data Pipeline resources in ${{ parameters.environmentPrefix }}'

  - deployment: DataPipelineDestroy
    displayName: 'Data Pipeline : Destroy'
    dependsOn: [ DataPipelineDestroyManualValidation ]
    pool:
      vmImage: ubuntu-latest
    environment: ${{ parameters.pipelineEnvironment }}
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self

            - template: ..\common\destroy-terraform.yaml
              parameters:
                workspaceDir: '$(System.DefaultWorkingDirectory)/data-pipeline/terraform'
                subscription: ${{ parameters.subscription }}
                environmentPrefix: ${{ parameters.environmentPrefix }}
                environment: ${{ parameters.environment }}
                cipEnvironment: ${{ parameters.cipEnvironment }}
                module: 'data-pipeline'
                imageName: 'fbit-data-pipeline:${{ parameters.buildNumber }}'
