parameters:
  subscription: ''
  environmentPrefix: ''
  environment: ''
  pipelineEnvironment: ''
  cipEnvironment: ''
  workspaceDir: '$(Pipeline.Workspace)'
  dependsOn: []

jobs:
  - deployment: DataPipelineSync
    displayName: 'Data Pipeline : Sync'
    dependsOn: ${{ parameters.dependsOn }}
    pool:
      vmImage: ubuntu-latest
    environment: ${{ parameters.pipelineEnvironment }}
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self

            - template: ..\common\sync-terraform.yaml
              parameters:
                workspaceDir: '$(System.DefaultWorkingDirectory)/data-pipeline/terraform'
                subscription: ${{ parameters.subscription }}
                environmentPrefix: ${{ parameters.environmentPrefix }}
                environment: ${{ parameters.environment }}
                cipEnvironment: ${{ parameters.cipEnvironment }}
                module: 'data-pipeline'