import pandas as pd


def test_central_services_data_has_correct_output_columns(
    prepared_central_services_data: pd.DataFrame,
):
    assert list(prepared_central_services_data.columns) == [
        "Trust UPIN",
        "In year balance",
        "Income_DFE revenue grants",
        "Income_SEN funding",
        "Income_Other DFE grants",
        "Income_Other grants",
        "Income_Government source",
        "Income_Academies",
        "Income_Non government",
        "Income_Facilities and services",
        "Income_Catering services",
        "Income_Receipts supply teacher insurance",
        "Income_Donations and voluntary funds",
        "Income_Other self-generated income",
        "Income_Investment income",
        "Teaching and Teaching support staff_Teaching staff",
        "Teaching and Teaching support staff_Supply teaching staff",
        "Teaching and Teaching support staff_Education support staff",
        "Non-educational support staff and services_Administrative and clerical staff",
        "Premises staff and services_Premises staff",
        "Catering staff and supplies_Catering staff",
        "Non-educational support staff and services_Other staff",
        "Other costs_Indirect employee expenses",
        "Other costs_Staff development and training",
        "Other costs_Staff-related insurance",
        "Other costs_Supply teacher insurance",
        "Premises staff and services_Maintenance of premises",
        "Premises staff and services_Cleaning and caretaking",
        "Utilities_Water and sewerage",
        "Utilities_Energy",
        "Other costs_Rent and rates",
        "Premises staff and services_Other occupation costs",
        "Other costs_Special facilities",
        "Educational supplies_Learning resources (not ICT equipment)",
        "Educational ICT_ICT learning resources",
        "Educational supplies_Examination fees",
        "Teaching and Teaching support staff_Educational consultancy",
        "Administrative supplies_Administrative supplies (non educational)",
        "Teaching and Teaching support staff_Agency supply teaching staff",
        "Catering staff and supplies_Catering supplies",
        "Other costs_Other insurance premiums",
        "Non-educational support staff and services_Professional services "
        "(non-curriculum)",
        "Non-educational support staff and services_Audit cost",
        "Other costs_Interest charges for loan and bank",
        "Other costs_Direct revenue financing",
        "Other costs_PFI charges",
        "Revenue reserve",
        "Income_Total grant funding",
        "Income_Direct grants",
        "Income_Community grants",
        "Targeted Grants",
        "Income_Total self generated funding",
        "Income_Total",
        "Supply Staff",
        "Other Staff Costs",
        "Staff Total ",
        "Maintenance & Improvement",
        "Premises",
        "Catering Exp",
        "Occupation",
        "Supplies and Services",
        "Educational Supplies",
        "Brought in Professional Services",
        "Total Expenditure",
        "Financial Position",
    ]
