import pandas as pd


def test_central_services_data_has_correct_output_columns(
    prepared_central_services_data: pd.DataFrame,
):
    assert list(prepared_central_services_data.columns) == [
        "BNCH11110T (EFA Revenue Grants)",
        "BNCH11131 (DfE Family Revenue Grants)",
        "Income_Targeted grants",
        "Income_Pre Post 16",
        "Income_Other grants",
        "Income_Government source",
        "Income_Academies",
        "Income_Non government",
        "BNCH11123-BTI011-A (MAT Central services - Income)",
        "BNCH11201 (Income from facilities and services)",
        "Income_Catering services",
        "Income_Receipts supply teacher insurance",
        "Income_Donations and voluntary funds",
        "Income_Other self-generated income",
        "BNCH11205 (Other Income from facilities and services)",
        "Income_Investment income",
        "Administrative supplies_Administrative supplies (non educational)",
        "Catering staff and supplies_Catering staff",
        "Catering staff and supplies_Catering supplies",
        "Other costs_Direct revenue financing",
        "Educational ICT_ICT learning resources",
        "Educational supplies_Examination fees",
        "Educational supplies_Learning resources (not ICT equipment)",
        "BNCH11000T (Revenue Income)",
        "BNCH20000T (Total Costs)",
        "Non-educational support staff and services_Administrative and clerical staff",
        "Non-educational support staff and services_Audit cost",
        "Non-educational support staff and services_Other staff",
        "Revenue reserve",
        "Non-educational support staff and services_Professional services "
        "(non-curriculum)",
        "Premises staff and services_Maintenance of premises",
        "Other costs_Grounds maintenance",
        "Other costs_Indirect employee expenses",
        "Other costs_Interest charges for loan and bank",
        "Other costs_Other insurance premiums",
        "Other costs_PFI charges",
        "Other costs_Rent and rates",
        "Other costs_Special facilities",
        "Other costs_Staff development and training",
        "Other costs_Staff-related insurance",
        "Other costs_Supply teacher insurance",
        "Premises staff and services_Cleaning and caretaking",
        "Premises staff and services_Other occupation costs",
        "Premises staff and services_Premises staff",
        "Teaching and Teaching support staff_Teaching staff",
        "Teaching and Teaching support staff_Supply teaching staff",
        "Teaching and Teaching support staff_Education support staff",
        "Teaching and Teaching support staff_Educational consultancy",
        "Teaching and Teaching support staff_Agency supply teaching staff",
        "Utilities_Energy",
        "Utilities_Water and sewerage",
        "In year balance",
        "Income_Total grant funding",
        "Income_Total self generated funding",
        "Income_Direct grants",
        "Income_Other DFE grants",
        "Income_Other Revenue Income",
        "Income_Facilities and services",
        "Total Expenditure",
        "Total Income",
        "Financial Position",
    ]
