IF EXISTS(SELECT *
              FROM INFORMATION_SCHEMA.TABLES
              WHERE table_name = 'School')
BEGIN    
    ALTER TABLE dbo.School ALTER COLUMN TrustUKPRN NVARCHAR(50) NULL    
    ALTER TABLE dbo.School ALTER COLUMN TrustName NVARCHAR(255) NULL
    ALTER TABLE dbo.School ALTER COLUMN FederationLeadUKPRN NVARCHAR(50) NULL
    ALTER TABLE dbo.School ALTER COLUMN FederationLeadName NVARCHAR(255) NULL
    ALTER TABLE dbo.School ALTER COLUMN HeadteacherEmail NVARCHAR(255) NULL
    ALTER TABLE dbo.School ALTER COLUMN HeadteacherName NVARCHAR(255) NULL
    ALTER TABLE dbo.School ALTER COLUMN OverallPhase NVARCHAR(50) NOT NULL
    ALTER TABLE dbo.School ALTER COLUMN SchoolType NVARCHAR(50) NOT NULL

END