IF EXISTS(SELECT *
          FROM INFORMATION_SCHEMA.TABLES
          WHERE table_name = 'Trust')
    BEGIN
        ALTER TABLE dbo.Trust ALTER COLUMN CFOName NVARCHAR(255) NULL
        ALTER TABLE dbo.Trust ALTER COLUMN CFOEmail NVARCHAR(255) NULL
    END