IF EXISTS(SELECT *
          FROM INFORMATION_SCHEMA.TABLES
          WHERE table_name = 'Financial')
    BEGIN
        DROP TABLE dbo.Financial
    END;

GO;

IF NOT EXISTS(SELECT *
              FROM INFORMATION_SCHEMA.TABLES
              WHERE table_name = 'Financial')
    BEGIN
        CREATE TABLE dbo.Financial
        (
            RunType                                                  nvarchar(50) NOT NULL,
            RunId                                                    nvarchar(50) NOT NULL,
            URN                                                      nvarchar(6)  NOT NULL,
            PeriodCoveredByReturn                                    smallint     NOT NULL,
            FinancialPosition                                        nvarchar(10) NOT NULL,
            TrustPosition                                            nvarchar(10) NULL,
            EstablishmentType                                        nvarchar(50) NULL,
            TotalPupils                                              decimal      NULL,
            TotalInternalFloorArea                                   decimal      NULL,
            TotalIncome                                              decimal      NULL,
            TotalExpenditure                                         decimal      NULL,
            InYearBalance                                            decimal      NULL,
            RevenueReserve                                           decimal      NULL,
            TotalGrantFunding                                        decimal      NULL,
            TotalSelfGeneratedFunding                                decimal      NULL,
            DirectRevenueFinancing                                   decimal      NULL,
            DirectGrants                                             decimal      NULL,
            PrePost16Funding                                         decimal      NULL,
            OtherDfeGrants                                           decimal      NULL,
            OtherIncomeGrants                                        decimal      NULL,
            GovernmentSource                                         decimal      NULL,
            CommunityGrants                                          decimal      NULL,
            Academies                                                decimal      NULL,
            IncomeFacilitiesServices                                 decimal      NULL,
            IncomeCateringServices                                   decimal      NULL,
            DonationsVoluntaryFunds                                  decimal      NULL,
            ReceiptsSupplyTeacherInsuranceClaims                     decimal      NULL,
            InvestmentIncome                                         decimal      NULL,
            OtherSelfGeneratedIncome                                 decimal      NULL,
            TotalTeachingSupportStaffCosts                           decimal      NULL,
            TeachingStaffCosts                                       decimal      NULL,
            SupplyTeachingStaffCosts                                 decimal      NULL,
            EducationalConsultancyCosts                              decimal      NULL,
            EducationSupportStaffCosts                               decimal      NULL,
            AgencySupplyTeachingStaffCosts                           decimal      NULL,
            TotalNonEducationalSupportStaffCosts                     decimal      NULL,
            AdministrativeClericalStaffCosts                         decimal      NULL,
            AuditorsCosts                                            decimal      NULL,
            OtherStaffCosts                                          decimal      NULL,
            ProfessionalServicesNonCurriculumCosts                   decimal      NULL,
            TotalEducationalSuppliesCosts                            decimal      NULL,
            ExaminationFeesCosts                                     decimal      NULL,
            BreakdownEducationalSuppliesCosts                        decimal      NULL,
            LearningResourcesNonIctCosts                             decimal      NULL,
            LearningResourcesIctCosts                                decimal      NULL,
            TotalPremisesStaffServiceCosts                           decimal      NULL,
            CleaningCaretakingCosts                                  decimal      NULL,
            MaintenancePremisesCosts                                 decimal      NULL,
            OtherOccupationCosts                                     decimal      NULL,
            PremisesStaffCosts                                       decimal      NULL,
            TotalUtilitiesCosts                                      decimal      NULL,
            EnergyCosts                                              decimal      NULL,
            WaterSewerageCosts                                       decimal      NULL,
            AdministrativeSuppliesNonEducationalCosts                decimal      NULL,
            TotalGrossCateringCosts                                  decimal      NULL,
            TotalNetCateringCostsCosts                               decimal      NULL,
            CateringStaffCosts                                       decimal      NULL,
            CateringSuppliesCosts                                    decimal      NULL,
            TotalOtherCosts                                          decimal      NULL,
            DirectRevenueFinancingCosts                              decimal      NULL,
            GroundsMaintenanceCosts                                  decimal      NULL,
            IndirectEmployeeExpenses                                 decimal      NULL,
            InterestChargesLoanBank                                  decimal      NULL,
            OtherInsurancePremiumsCosts                              decimal      NULL,
            PrivateFinanceInitiativeCharges                          decimal      NULL,
            RentRatesCosts                                           decimal      NULL,
            SpecialFacilitiesCosts                                   decimal      NULL,
            StaffDevelopmentTrainingCosts                            decimal      NULL,
            StaffRelatedInsuranceCosts                               decimal      NULL,
            SupplyTeacherInsurableCosts                              decimal      NULL,
            CommunityFocusedSchoolStaff                              decimal      NULL,
            CommunityFocusedSchoolCosts                              decimal      NULL,
            TotalIncomeCS                               decimal      NULL,
            TotalExpenditureCS                          decimal      NULL,
            InYearBalanceCS                             decimal      NULL,
            RevenueReserveCS                            decimal      NULL,
            TotalGrantFundingCS                         decimal      NULL,
            TotalSelfGeneratedFundingCS                 decimal      NULL,
            DirectRevenueFinancingCS                    decimal      NULL,
            DirectGrantsCS                              decimal      NULL,
            PrePost16FundingCS                          decimal      NULL,
            OtherDfeGrantsCS                            decimal      NULL,
            OtherIncomeGrantsCS                         decimal      NULL,
            GovernmentSourceCS                          decimal      NULL,
            CommunityGrantsCS                           decimal      NULL,
            AcademiesCS                                 decimal      NULL,
            IncomeFacilitiesServicesCS                  decimal      NULL,
            IncomeCateringServicesCS                    decimal      NULL,
            DonationsVoluntaryFundsCS                   decimal      NULL,
            ReceiptsSupplyTeacherInsuranceClaimsCS      decimal      NULL,
            InvestmentIncomeCS                          decimal      NULL,
            OtherSelfGeneratedIncomeCS                  decimal      NULL,
            TotalTeachingSupportStaffCostsCS            decimal      NULL,
            TeachingStaffCostsCS                        decimal      NULL,
            SupplyTeachingStaffCostsCS                  decimal      NULL,
            EducationalConsultancyCostsCS               decimal      NULL,
            EducationSupportStaffCostsCS                decimal      NULL,
            AgencySupplyTeachingStaffCostsCS            decimal      NULL,
            TotalNonEducationalSupportStaffCostsCS      decimal      NULL,
            AdministrativeClericalStaffCostsCS          decimal      NULL,
            AuditorsCostsCS                             decimal      NULL,
            OtherStaffCostsCS                           decimal      NULL,
            ProfessionalServicesNonCurriculumCostsCS    decimal      NULL,
            TotalEducationalSuppliesCostsCS             decimal      NULL,
            ExaminationFeesCostsCS                      decimal      NULL,
            BreakdownEducationalSuppliesCostsCS         decimal      NULL,
            LearningResourcesNonIctCostsCS              decimal      NULL,
            LearningResourcesIctCostsCS                 decimal      NULL,
            TotalPremisesStaffServiceCostsCS            decimal      NULL,
            CleaningCaretakingCostsCS                   decimal      NULL,
            MaintenancePremisesCostsCS                  decimal      NULL,
            OtherOccupationCostsCS                      decimal      NULL,
            PremisesStaffCostsCS                        decimal      NULL,
            TotalUtilitiesCostsCS                       decimal      NULL,
            EnergyCostsCS                               decimal      NULL,
            WaterSewerageCostsCS                        decimal      NULL,
            AdministrativeSuppliesNonEducationalCostsCS decimal      NULL,
            TotalGrossCateringCostsCS                   decimal      NULL,
            TotalNetCateringCostsCostsCS                decimal      NULL,
            CateringStaffCostsCS                        decimal      NULL,
            CateringSuppliesCostsCS                     decimal      NULL,
            TotalOtherCostsCS                           decimal      NULL,
            DirectRevenueFinancingCostsCS               decimal      NULL,
            GroundsMaintenanceCostsCS                   decimal      NULL,
            IndirectEmployeeExpensesCS                  decimal      NULL,
            InterestChargesLoanBankCS                   decimal      NULL,
            OtherInsurancePremiumsCostsCS               decimal      NULL,
            PrivateFinanceInitiativeChargesCS           decimal      NULL,
            RentRatesCostsCS                            decimal      NULL,
            SpecialFacilitiesCostsCS                    decimal      NULL,
            StaffDevelopmentTrainingCostsCS             decimal      NULL,
            StaffRelatedInsuranceCostsCS                decimal      NULL,
            SupplyTeacherInsurableCostsCS               decimal      NULL,
            CommunityFocusedSchoolStaffCS               decimal      NULL,
            CommunityFocusedSchoolCostsCS               decimal      NULL,

            CONSTRAINT PK_Financial PRIMARY KEY (RunType, RunId, URN)
        );
    END;