ALTER VIEW [dbo].[SchoolExpenditure] AS
SELECT
    s.URN,
    s.SchoolName,
    s.SchoolType,
    s.LAName,
    s.TrustCompanyNumber,
    f.TotalPupils,
    f.TotalInternalFloorArea,
    f.TotalIncome,
    f.TotalExpenditure,
    f.TotalTeachingSupportStaffCosts,
    f.TeachingStaffCosts,
    f.SupplyTeachingStaffCosts,
    f.EducationalConsultancyCosts,
    f.EducationSupportStaffCosts,
    f.AgencySupplyTeachingStaffCosts,
    f.TotalNonEducationalSupportStaffCosts,
    f.AdministrativeClericalStaffCosts,
    f.AuditorsCosts,
    f.OtherStaffCosts,
    f.ProfessionalServicesNonCurriculumCosts,
    f.TotalEducationalSuppliesCosts,
    f.ExaminationFeesCosts,
    f.LearningResourcesNonIctCosts,
    f.LearningResourcesIctCosts,
    f.TotalPremisesStaffServiceCosts,
    f.CleaningCaretakingCosts,
    f.MaintenancePremisesCosts,
    f.OtherOccupationCosts,
    f.PremisesStaffCosts,
    f.TotalUtilitiesCosts,
    f.EnergyCosts,
    f.WaterSewerageCosts,
    f.AdministrativeSuppliesNonEducationalCosts,
    f.TotalGrossCateringCosts,
    f.TotalNetCateringCostsCosts AS TotalNetCateringCosts,
    f.CateringStaffCosts,
    f.CateringSuppliesCosts,
    f.TotalOtherCosts,
    f.DirectRevenueFinancingCosts,
    f.GroundsMaintenanceCosts,
    f.IndirectEmployeeExpenses,
    f.InterestChargesLoanBank,
    f.OtherInsurancePremiumsCosts,
    f.PrivateFinanceInitiativeCharges,
    f.RentRatesCosts,
    f.SpecialFacilitiesCosts,
    f.StaffDevelopmentTrainingCosts,
    f.StaffRelatedInsuranceCosts,
    f.SupplyTeacherInsurableCosts,
    f.CommunityFocusedSchoolStaff,
    f.CommunityFocusedSchoolCosts,
    f.TotalIncomeCS,
    f.TotalExpenditureCS,
    f.TotalTeachingSupportStaffCostsCS,
    f.TeachingStaffCostsCS,
    f.SupplyTeachingStaffCostsCS,
    f.EducationalConsultancyCostsCS,
    f.EducationSupportStaffCostsCS,
    f.AgencySupplyTeachingStaffCostsCS,
    f.TotalNonEducationalSupportStaffCostsCS,
    f.AdministrativeClericalStaffCostsCS,
    f.AuditorsCostsCS,
    f.OtherStaffCostsCS,
    f.ProfessionalServicesNonCurriculumCostsCS,
    f.TotalEducationalSuppliesCostsCS,
    f.ExaminationFeesCostsCS,
    f.LearningResourcesNonIctCostsCS,
    f.LearningResourcesIctCostsCS,
    f.TotalPremisesStaffServiceCostsCS,
    f.CleaningCaretakingCostsCS,
    f.MaintenancePremisesCostsCS,
    f.OtherOccupationCostsCS,
    f.PremisesStaffCostsCS,
    f.TotalUtilitiesCostsCS,
    f.EnergyCostsCS,
    f.WaterSewerageCostsCS,
    f.AdministrativeSuppliesNonEducationalCostsCS,
    f.TotalGrossCateringCostsCS,
    f.TotalNetCateringCostsCostsCS AS TotalNetCateringCostsCS,
    f.CateringStaffCostsCS,
    f.CateringSuppliesCostsCS,
    f.TotalOtherCostsCS,
    f.DirectRevenueFinancingCostsCS,
    f.GroundsMaintenanceCostsCS,
    f.IndirectEmployeeExpensesCS,
    f.InterestChargesLoanBankCS,
    f.OtherInsurancePremiumsCostsCS,
    f.PrivateFinanceInitiativeChargesCS,
    f.RentRatesCostsCS,
    f.SpecialFacilitiesCostsCS,
    f.StaffDevelopmentTrainingCostsCS,
    f.StaffRelatedInsuranceCostsCS,
    f.SupplyTeacherInsurableCostsCS
FROM
    School s
    LEFT JOIN CurrentDefaultFinancial f ON f.URN = s.URN
GO
    ALTER VIEW SchoolExpenditureCustom AS
SELECT
    s.URN,
    s.SchoolName,
    s.SchoolType,
    s.LAName,
    s.TrustCompanyNumber,
    f.RunId,
    f.TotalPupils,
    f.TotalInternalFloorArea,
    f.TotalIncome,
    f.TotalExpenditure,
    f.TotalTeachingSupportStaffCosts,
    f.TeachingStaffCosts,
    f.SupplyTeachingStaffCosts,
    f.EducationalConsultancyCosts,
    f.EducationSupportStaffCosts,
    f.AgencySupplyTeachingStaffCosts,
    f.TotalNonEducationalSupportStaffCosts,
    f.AdministrativeClericalStaffCosts,
    f.AuditorsCosts,
    f.OtherStaffCosts,
    f.ProfessionalServicesNonCurriculumCosts,
    f.TotalEducationalSuppliesCosts,
    f.ExaminationFeesCosts,
    f.LearningResourcesNonIctCosts,
    f.LearningResourcesIctCosts,
    f.TotalPremisesStaffServiceCosts,
    f.CleaningCaretakingCosts,
    f.MaintenancePremisesCosts,
    f.OtherOccupationCosts,
    f.PremisesStaffCosts,
    f.TotalUtilitiesCosts,
    f.EnergyCosts,
    f.WaterSewerageCosts,
    f.AdministrativeSuppliesNonEducationalCosts,
    f.TotalGrossCateringCosts,
    f.TotalNetCateringCostsCosts AS TotalNetCateringCosts,
    f.CateringStaffCosts,
    f.CateringSuppliesCosts,
    f.TotalOtherCosts,
    f.DirectRevenueFinancingCosts,
    f.GroundsMaintenanceCosts,
    f.IndirectEmployeeExpenses,
    f.InterestChargesLoanBank,
    f.OtherInsurancePremiumsCosts,
    f.PrivateFinanceInitiativeCharges,
    f.RentRatesCosts,
    f.SpecialFacilitiesCosts,
    f.StaffDevelopmentTrainingCosts,
    f.StaffRelatedInsuranceCosts,
    f.SupplyTeacherInsurableCosts,
    f.CommunityFocusedSchoolStaff,
    f.CommunityFocusedSchoolCosts,
    f.TotalIncomeCS,
    f.TotalExpenditureCS,
    f.TotalTeachingSupportStaffCostsCS,
    f.TeachingStaffCostsCS,
    f.SupplyTeachingStaffCostsCS,
    f.EducationalConsultancyCostsCS,
    f.EducationSupportStaffCostsCS,
    f.AgencySupplyTeachingStaffCostsCS,
    f.TotalNonEducationalSupportStaffCostsCS,
    f.AdministrativeClericalStaffCostsCS,
    f.AuditorsCostsCS,
    f.OtherStaffCostsCS,
    f.ProfessionalServicesNonCurriculumCostsCS,
    f.TotalEducationalSuppliesCostsCS,
    f.ExaminationFeesCostsCS,
    f.LearningResourcesNonIctCostsCS,
    f.LearningResourcesIctCostsCS,
    f.TotalPremisesStaffServiceCostsCS,
    f.CleaningCaretakingCostsCS,
    f.MaintenancePremisesCostsCS,
    f.OtherOccupationCostsCS,
    f.PremisesStaffCostsCS,
    f.TotalUtilitiesCostsCS,
    f.EnergyCostsCS,
    f.WaterSewerageCostsCS,
    f.AdministrativeSuppliesNonEducationalCostsCS,
    f.TotalGrossCateringCostsCS,
    f.TotalNetCateringCostsCostsCS AS TotalNetCateringCostsCS,
    f.CateringStaffCostsCS,
    f.CateringSuppliesCostsCS,
    f.TotalOtherCostsCS,
    f.DirectRevenueFinancingCostsCS,
    f.GroundsMaintenanceCostsCS,
    f.IndirectEmployeeExpensesCS,
    f.InterestChargesLoanBankCS,
    f.OtherInsurancePremiumsCostsCS,
    f.PrivateFinanceInitiativeChargesCS,
    f.RentRatesCostsCS,
    f.SpecialFacilitiesCostsCS,
    f.StaffDevelopmentTrainingCostsCS,
    f.StaffRelatedInsuranceCostsCS,
    f.SupplyTeacherInsurableCostsCS
FROM
    School s
    LEFT JOIN Financial f ON f.URN = s.URN
WHERE
    f.RunType = 'custom'
GO
    ALTER VIEW [dbo].[SchoolExpenditureHistoric] AS
SELECT
    s.URN,
    s.Year,
    s.TrustCompanyNumber,
    f.TotalPupils,
    f.TotalInternalFloorArea,
    f.TotalIncome,
    f.TotalExpenditure,
    f.TotalTeachingSupportStaffCosts,
    f.TeachingStaffCosts,
    f.SupplyTeachingStaffCosts,
    f.EducationalConsultancyCosts,
    f.EducationSupportStaffCosts,
    f.AgencySupplyTeachingStaffCosts,
    f.TotalNonEducationalSupportStaffCosts,
    f.AdministrativeClericalStaffCosts,
    f.AuditorsCosts,
    f.OtherStaffCosts,
    f.ProfessionalServicesNonCurriculumCosts,
    f.TotalEducationalSuppliesCosts,
    f.ExaminationFeesCosts,
    f.LearningResourcesNonIctCosts,
    f.LearningResourcesIctCosts,
    f.TotalPremisesStaffServiceCosts,
    f.CleaningCaretakingCosts,
    f.MaintenancePremisesCosts,
    f.OtherOccupationCosts,
    f.PremisesStaffCosts,
    f.TotalUtilitiesCosts,
    f.EnergyCosts,
    f.WaterSewerageCosts,
    f.AdministrativeSuppliesNonEducationalCosts,
    f.TotalGrossCateringCosts,
    f.TotalNetCateringCostsCosts AS TotalNetCateringCosts,
    f.CateringStaffCosts,
    f.CateringSuppliesCosts,
    f.TotalOtherCosts,
    f.DirectRevenueFinancingCosts,
    f.GroundsMaintenanceCosts,
    f.IndirectEmployeeExpenses,
    f.InterestChargesLoanBank,
    f.OtherInsurancePremiumsCosts,
    f.PrivateFinanceInitiativeCharges,
    f.RentRatesCosts,
    f.SpecialFacilitiesCosts,
    f.StaffDevelopmentTrainingCosts,
    f.StaffRelatedInsuranceCosts,
    f.SupplyTeacherInsurableCosts,
    f.CommunityFocusedSchoolStaff,
    f.CommunityFocusedSchoolCosts,
    f.TotalIncomeCS,
    f.TotalExpenditureCS,
    f.TotalTeachingSupportStaffCostsCS,
    f.TeachingStaffCostsCS,
    f.SupplyTeachingStaffCostsCS,
    f.EducationalConsultancyCostsCS,
    f.EducationSupportStaffCostsCS,
    f.AgencySupplyTeachingStaffCostsCS,
    f.TotalNonEducationalSupportStaffCostsCS,
    f.AdministrativeClericalStaffCostsCS,
    f.AuditorsCostsCS,
    f.OtherStaffCostsCS,
    f.ProfessionalServicesNonCurriculumCostsCS,
    f.TotalEducationalSuppliesCostsCS,
    f.ExaminationFeesCostsCS,
    f.LearningResourcesNonIctCostsCS,
    f.LearningResourcesIctCostsCS,
    f.TotalPremisesStaffServiceCostsCS,
    f.CleaningCaretakingCostsCS,
    f.MaintenancePremisesCostsCS,
    f.OtherOccupationCostsCS,
    f.PremisesStaffCostsCS,
    f.TotalUtilitiesCostsCS,
    f.EnergyCostsCS,
    f.WaterSewerageCostsCS,
    f.AdministrativeSuppliesNonEducationalCostsCS,
    f.TotalGrossCateringCostsCS,
    f.TotalNetCateringCostsCostsCS AS TotalNetCateringCostsCS,
    f.CateringStaffCostsCS,
    f.CateringSuppliesCostsCS,
    f.TotalOtherCostsCS,
    f.DirectRevenueFinancingCostsCS,
    f.GroundsMaintenanceCostsCS,
    f.IndirectEmployeeExpensesCS,
    f.InterestChargesLoanBankCS,
    f.OtherInsurancePremiumsCostsCS,
    f.PrivateFinanceInitiativeChargesCS,
    f.RentRatesCostsCS,
    f.SpecialFacilitiesCostsCS,
    f.StaffDevelopmentTrainingCostsCS,
    f.StaffRelatedInsuranceCostsCS,
    f.SupplyTeacherInsurableCostsCS
FROM
    (
        SELECT
            *
        FROM
            School,
            AARHistoryYears
    ) s
    LEFT OUTER JOIN Financial f ON s.Year = f.RunId
    AND f.URN = s.URN
    AND f.RunType = 'default'
WHERE
    s.FinanceType = 'Academy'
UNION
SELECT
    s.URN,
    s.Year,
    s.TrustCompanyNumber,
    f.TotalPupils,
    f.TotalInternalFloorArea,
    f.TotalIncome,
    f.TotalExpenditure,
    f.TotalTeachingSupportStaffCosts,
    f.TeachingStaffCosts,
    f.SupplyTeachingStaffCosts,
    f.EducationalConsultancyCosts,
    f.EducationSupportStaffCosts,
    f.AgencySupplyTeachingStaffCosts,
    f.TotalNonEducationalSupportStaffCosts,
    f.AdministrativeClericalStaffCosts,
    f.AuditorsCosts,
    f.OtherStaffCosts,
    f.ProfessionalServicesNonCurriculumCosts,
    f.TotalEducationalSuppliesCosts,
    f.ExaminationFeesCosts,
    f.LearningResourcesNonIctCosts,
    f.LearningResourcesIctCosts,
    f.TotalPremisesStaffServiceCosts,
    f.CleaningCaretakingCosts,
    f.MaintenancePremisesCosts,
    f.OtherOccupationCosts,
    f.PremisesStaffCosts,
    f.TotalUtilitiesCosts,
    f.EnergyCosts,
    f.WaterSewerageCosts,
    f.AdministrativeSuppliesNonEducationalCosts,
    f.TotalGrossCateringCosts,
    f.TotalNetCateringCostsCosts AS TotalNetCateringCosts,
    f.CateringStaffCosts,
    f.CateringSuppliesCosts,
    f.TotalOtherCosts,
    f.DirectRevenueFinancingCosts,
    f.GroundsMaintenanceCosts,
    f.IndirectEmployeeExpenses,
    f.InterestChargesLoanBank,
    f.OtherInsurancePremiumsCosts,
    f.PrivateFinanceInitiativeCharges,
    f.RentRatesCosts,
    f.SpecialFacilitiesCosts,
    f.StaffDevelopmentTrainingCosts,
    f.StaffRelatedInsuranceCosts,
    f.SupplyTeacherInsurableCosts,
    f.CommunityFocusedSchoolStaff,
    f.CommunityFocusedSchoolCosts,
    f.TotalIncomeCS,
    f.TotalExpenditureCS,
    f.TotalTeachingSupportStaffCostsCS,
    f.TeachingStaffCostsCS,
    f.SupplyTeachingStaffCostsCS,
    f.EducationalConsultancyCostsCS,
    f.EducationSupportStaffCostsCS,
    f.AgencySupplyTeachingStaffCostsCS,
    f.TotalNonEducationalSupportStaffCostsCS,
    f.AdministrativeClericalStaffCostsCS,
    f.AuditorsCostsCS,
    f.OtherStaffCostsCS,
    f.ProfessionalServicesNonCurriculumCostsCS,
    f.TotalEducationalSuppliesCostsCS,
    f.ExaminationFeesCostsCS,
    f.LearningResourcesNonIctCostsCS,
    f.LearningResourcesIctCostsCS,
    f.TotalPremisesStaffServiceCostsCS,
    f.CleaningCaretakingCostsCS,
    f.MaintenancePremisesCostsCS,
    f.OtherOccupationCostsCS,
    f.PremisesStaffCostsCS,
    f.TotalUtilitiesCostsCS,
    f.EnergyCostsCS,
    f.WaterSewerageCostsCS,
    f.AdministrativeSuppliesNonEducationalCostsCS,
    f.TotalGrossCateringCostsCS,
    f.TotalNetCateringCostsCostsCS AS TotalNetCateringCostsCS,
    f.CateringStaffCostsCS,
    f.CateringSuppliesCostsCS,
    f.TotalOtherCostsCS,
    f.DirectRevenueFinancingCostsCS,
    f.GroundsMaintenanceCostsCS,
    f.IndirectEmployeeExpensesCS,
    f.InterestChargesLoanBankCS,
    f.OtherInsurancePremiumsCostsCS,
    f.PrivateFinanceInitiativeChargesCS,
    f.RentRatesCostsCS,
    f.SpecialFacilitiesCostsCS,
    f.StaffDevelopmentTrainingCostsCS,
    f.StaffRelatedInsuranceCostsCS,
    f.SupplyTeacherInsurableCostsCS
FROM
    (
        SELECT
            *
        FROM
            School,
            CFRHistoryYears
    ) s
    LEFT OUTER JOIN Financial f ON s.Year = f.RunId
    AND f.URN = s.URN
    AND f.RunType = 'default'
WHERE
    s.FinanceType = 'Maintained'
GO
    ALTER VIEW [dbo].[TrustExpenditure] AS
SELECT
    t.CompanyNumber,
    t.TrustName,
    f.TotalPupils,
    f.TotalInternalFloorArea,
    f.TotalIncome,
    f.TotalExpenditure,
    f.TotalTeachingSupportStaffCosts,
    f.TeachingStaffCosts,
    f.SupplyTeachingStaffCosts,
    f.EducationalConsultancyCosts,
    f.EducationSupportStaffCosts,
    f.AgencySupplyTeachingStaffCosts,
    f.TotalNonEducationalSupportStaffCosts,
    f.AdministrativeClericalStaffCosts,
    f.AuditorsCosts,
    f.OtherStaffCosts,
    f.ProfessionalServicesNonCurriculumCosts,
    f.TotalEducationalSuppliesCosts,
    f.ExaminationFeesCosts,
    f.LearningResourcesNonIctCosts,
    f.LearningResourcesIctCosts,
    f.TotalPremisesStaffServiceCosts,
    f.CleaningCaretakingCosts,
    f.MaintenancePremisesCosts,
    f.OtherOccupationCosts,
    f.PremisesStaffCosts,
    f.TotalUtilitiesCosts,
    f.EnergyCosts,
    f.WaterSewerageCosts,
    f.AdministrativeSuppliesNonEducationalCosts,
    f.TotalGrossCateringCosts,
    f.TotalNetCateringCosts,
    f.CateringStaffCosts,
    f.CateringSuppliesCosts,
    f.TotalOtherCosts,
    f.DirectRevenueFinancingCosts,
    f.GroundsMaintenanceCosts,
    f.IndirectEmployeeExpenses,
    f.InterestChargesLoanBank,
    f.OtherInsurancePremiumsCosts,
    f.PrivateFinanceInitiativeCharges,
    f.RentRatesCosts,
    f.SpecialFacilitiesCosts,
    f.StaffDevelopmentTrainingCosts,
    f.StaffRelatedInsuranceCosts,
    f.SupplyTeacherInsurableCosts,
    f.CommunityFocusedSchoolStaff,
    f.CommunityFocusedSchoolCosts,
    f.TotalIncomeCS,
    f.TotalExpenditureCS,
    f.TotalTeachingSupportStaffCostsCS,
    f.TeachingStaffCostsCS,
    f.SupplyTeachingStaffCostsCS,
    f.EducationalConsultancyCostsCS,
    f.EducationSupportStaffCostsCS,
    f.AgencySupplyTeachingStaffCostsCS,
    f.TotalNonEducationalSupportStaffCostsCS,
    f.AdministrativeClericalStaffCostsCS,
    f.AuditorsCostsCS,
    f.OtherStaffCostsCS,
    f.ProfessionalServicesNonCurriculumCostsCS,
    f.TotalEducationalSuppliesCostsCS,
    f.ExaminationFeesCostsCS,
    f.LearningResourcesNonIctCostsCS,
    f.LearningResourcesIctCostsCS,
    f.TotalPremisesStaffServiceCostsCS,
    f.CleaningCaretakingCostsCS,
    f.MaintenancePremisesCostsCS,
    f.OtherOccupationCostsCS,
    f.PremisesStaffCostsCS,
    f.TotalUtilitiesCostsCS,
    f.EnergyCostsCS,
    f.WaterSewerageCostsCS,
    f.AdministrativeSuppliesNonEducationalCostsCS,
    f.TotalGrossCateringCostsCS,
    f.TotalNetCateringCostsCS,
    f.CateringStaffCostsCS,
    f.CateringSuppliesCostsCS,
    f.TotalOtherCostsCS,
    f.DirectRevenueFinancingCostsCS,
    f.GroundsMaintenanceCostsCS,
    f.IndirectEmployeeExpensesCS,
    f.InterestChargesLoanBankCS,
    f.OtherInsurancePremiumsCostsCS,
    f.PrivateFinanceInitiativeChargesCS,
    f.RentRatesCostsCS,
    f.SpecialFacilitiesCostsCS,
    f.StaffDevelopmentTrainingCostsCS,
    f.StaffRelatedInsuranceCostsCS,
    f.SupplyTeacherInsurableCostsCS
FROM
    Trust t
    LEFT JOIN (
        SELECT
            TrustCompanyNumber 'CompanyNumber',
            SUM(TotalPupils) 'TotalPupils',
            SUM(TotalInternalFloorArea) 'TotalInternalFloorArea',
            SUM(TotalIncome) 'TotalIncome',
            SUM(TotalExpenditure) 'TotalExpenditure',
            SUM(TotalTeachingSupportStaffCosts) 'TotalTeachingSupportStaffCosts',
            SUM(TeachingStaffCosts) 'TeachingStaffCosts',
            SUM(SupplyTeachingStaffCosts) 'SupplyTeachingStaffCosts',
            SUM(EducationalConsultancyCosts) 'EducationalConsultancyCosts',
            SUM(EducationSupportStaffCosts) 'EducationSupportStaffCosts',
            SUM(AgencySupplyTeachingStaffCosts) 'AgencySupplyTeachingStaffCosts',
            SUM(TotalNonEducationalSupportStaffCosts) 'TotalNonEducationalSupportStaffCosts',
            SUM(AdministrativeClericalStaffCosts) 'AdministrativeClericalStaffCosts',
            SUM(AuditorsCosts) 'AuditorsCosts',
            SUM(OtherStaffCosts) 'OtherStaffCosts',
            SUM(ProfessionalServicesNonCurriculumCosts) 'ProfessionalServicesNonCurriculumCosts',
            SUM(TotalEducationalSuppliesCosts) 'TotalEducationalSuppliesCosts',
            SUM(ExaminationFeesCosts) 'ExaminationFeesCosts',
            SUM(LearningResourcesNonIctCosts) 'LearningResourcesNonIctCosts',
            SUM(LearningResourcesIctCosts) 'LearningResourcesIctCosts',
            SUM(TotalPremisesStaffServiceCosts) 'TotalPremisesStaffServiceCosts',
            SUM(CleaningCaretakingCosts) 'CleaningCaretakingCosts',
            SUM(MaintenancePremisesCosts) 'MaintenancePremisesCosts',
            SUM(OtherOccupationCosts) 'OtherOccupationCosts',
            SUM(PremisesStaffCosts) 'PremisesStaffCosts',
            SUM(TotalUtilitiesCosts) 'TotalUtilitiesCosts',
            SUM(EnergyCosts) 'EnergyCosts',
            SUM(WaterSewerageCosts) 'WaterSewerageCosts',
            SUM(AdministrativeSuppliesNonEducationalCosts) 'AdministrativeSuppliesNonEducationalCosts',
            SUM(TotalGrossCateringCosts) 'TotalGrossCateringCosts',
            SUM(TotalNetCateringCosts) 'TotalNetCateringCosts',
            SUM(CateringStaffCosts) 'CateringStaffCosts',
            SUM(CateringSuppliesCosts) 'CateringSuppliesCosts',
            SUM(TotalOtherCosts) 'TotalOtherCosts',
            SUM(DirectRevenueFinancingCosts) 'DirectRevenueFinancingCosts',
            SUM(GroundsMaintenanceCosts) 'GroundsMaintenanceCosts',
            SUM(IndirectEmployeeExpenses) 'IndirectEmployeeExpenses',
            SUM(InterestChargesLoanBank) 'InterestChargesLoanBank',
            SUM(OtherInsurancePremiumsCosts) 'OtherInsurancePremiumsCosts',
            SUM(PrivateFinanceInitiativeCharges) 'PrivateFinanceInitiativeCharges',
            SUM(RentRatesCosts) 'RentRatesCosts',
            SUM(SpecialFacilitiesCosts) 'SpecialFacilitiesCosts',
            SUM(StaffDevelopmentTrainingCosts) 'StaffDevelopmentTrainingCosts',
            SUM(StaffRelatedInsuranceCosts) 'StaffRelatedInsuranceCosts',
            SUM(SupplyTeacherInsurableCosts) 'SupplyTeacherInsurableCosts',
            SUM(CommunityFocusedSchoolStaff) 'CommunityFocusedSchoolStaff',
            SUM(CommunityFocusedSchoolCosts) 'CommunityFocusedSchoolCosts',
            SUM(TotalIncomeCS) 'TotalIncomeCS',
            SUM(TotalExpenditureCS) 'TotalExpenditureCS',
            SUM(TotalTeachingSupportStaffCostsCS) 'TotalTeachingSupportStaffCostsCS',
            SUM(TeachingStaffCostsCS) 'TeachingStaffCostsCS',
            SUM(SupplyTeachingStaffCostsCS) 'SupplyTeachingStaffCostsCS',
            SUM(EducationalConsultancyCostsCS) 'EducationalConsultancyCostsCS',
            SUM(EducationSupportStaffCostsCS) 'EducationSupportStaffCostsCS',
            SUM(AgencySupplyTeachingStaffCostsCS) 'AgencySupplyTeachingStaffCostsCS',
            SUM(TotalNonEducationalSupportStaffCostsCS) 'TotalNonEducationalSupportStaffCostsCS',
            SUM(AdministrativeClericalStaffCostsCS) 'AdministrativeClericalStaffCostsCS',
            SUM(AuditorsCostsCS) 'AuditorsCostsCS',
            SUM(OtherStaffCostsCS) 'OtherStaffCostsCS',
            SUM(ProfessionalServicesNonCurriculumCostsCS) 'ProfessionalServicesNonCurriculumCostsCS',
            SUM(TotalEducationalSuppliesCostsCS) 'TotalEducationalSuppliesCostsCS',
            SUM(ExaminationFeesCostsCS) 'ExaminationFeesCostsCS',
            SUM(LearningResourcesNonIctCostsCS) 'LearningResourcesNonIctCostsCS',
            SUM(LearningResourcesIctCostsCS) 'LearningResourcesIctCostsCS',
            SUM(TotalPremisesStaffServiceCostsCS) 'TotalPremisesStaffServiceCostsCS',
            SUM(CleaningCaretakingCostsCS) 'CleaningCaretakingCostsCS',
            SUM(MaintenancePremisesCostsCS) 'MaintenancePremisesCostsCS',
            SUM(OtherOccupationCostsCS) 'OtherOccupationCostsCS',
            SUM(PremisesStaffCostsCS) 'PremisesStaffCostsCS',
            SUM(TotalUtilitiesCostsCS) 'TotalUtilitiesCostsCS',
            SUM(EnergyCostsCS) 'EnergyCostsCS',
            SUM(WaterSewerageCostsCS) 'WaterSewerageCostsCS',
            SUM(AdministrativeSuppliesNonEducationalCostsCS) 'AdministrativeSuppliesNonEducationalCostsCS',
            SUM(TotalGrossCateringCostsCS) 'TotalGrossCateringCostsCS',
            SUM(TotalNetCateringCostsCS) 'TotalNetCateringCostsCS',
            SUM(CateringStaffCostsCS) 'CateringStaffCostsCS',
            SUM(CateringSuppliesCostsCS) 'CateringSuppliesCostsCS',
            SUM(TotalOtherCostsCS) 'TotalOtherCostsCS',
            SUM(DirectRevenueFinancingCostsCS) 'DirectRevenueFinancingCostsCS',
            SUM(GroundsMaintenanceCostsCS) 'GroundsMaintenanceCostsCS',
            SUM(IndirectEmployeeExpensesCS) 'IndirectEmployeeExpensesCS',
            SUM(InterestChargesLoanBankCS) 'InterestChargesLoanBankCS',
            SUM(OtherInsurancePremiumsCostsCS) 'OtherInsurancePremiumsCostsCS',
            SUM(PrivateFinanceInitiativeChargesCS) 'PrivateFinanceInitiativeChargesCS',
            SUM(RentRatesCostsCS) 'RentRatesCostsCS',
            SUM(SpecialFacilitiesCostsCS) 'SpecialFacilitiesCostsCS',
            SUM(StaffDevelopmentTrainingCostsCS) 'StaffDevelopmentTrainingCostsCS',
            SUM(StaffRelatedInsuranceCostsCS) 'StaffRelatedInsuranceCostsCS',
            SUM(SupplyTeacherInsurableCostsCS) 'SupplyTeacherInsurableCostsCS'
        FROM
            SchoolExpenditure
        WHERE
            TrustCompanyNumber IS NOT NULL
        GROUP BY
            TrustCompanyNumber
    ) f ON f.CompanyNumber = t.CompanyNumber
GO
    ALTER VIEW [dbo].[TrustExpenditureHistoric] AS
SELECT
    t.CompanyNumber,
    t.TrustName,
    f.Year,
    f.TotalPupils,
    f.TotalInternalFloorArea,
    f.TotalIncome,
    f.TotalExpenditure,
    f.TotalTeachingSupportStaffCosts,
    f.TeachingStaffCosts,
    f.SupplyTeachingStaffCosts,
    f.EducationalConsultancyCosts,
    f.EducationSupportStaffCosts,
    f.AgencySupplyTeachingStaffCosts,
    f.TotalNonEducationalSupportStaffCosts,
    f.AdministrativeClericalStaffCosts,
    f.AuditorsCosts,
    f.OtherStaffCosts,
    f.ProfessionalServicesNonCurriculumCosts,
    f.TotalEducationalSuppliesCosts,
    f.ExaminationFeesCosts,
    f.LearningResourcesNonIctCosts,
    f.LearningResourcesIctCosts,
    f.TotalPremisesStaffServiceCosts,
    f.CleaningCaretakingCosts,
    f.MaintenancePremisesCosts,
    f.OtherOccupationCosts,
    f.PremisesStaffCosts,
    f.TotalUtilitiesCosts,
    f.EnergyCosts,
    f.WaterSewerageCosts,
    f.AdministrativeSuppliesNonEducationalCosts,
    f.TotalGrossCateringCosts,
    f.TotalNetCateringCosts,
    f.CateringStaffCosts,
    f.CateringSuppliesCosts,
    f.TotalOtherCosts,
    f.DirectRevenueFinancingCosts,
    f.GroundsMaintenanceCosts,
    f.IndirectEmployeeExpenses,
    f.InterestChargesLoanBank,
    f.OtherInsurancePremiumsCosts,
    f.PrivateFinanceInitiativeCharges,
    f.RentRatesCosts,
    f.SpecialFacilitiesCosts,
    f.StaffDevelopmentTrainingCosts,
    f.StaffRelatedInsuranceCosts,
    f.SupplyTeacherInsurableCosts,
    f.CommunityFocusedSchoolStaff,
    f.CommunityFocusedSchoolCosts,
    f.TotalIncomeCS,
    f.TotalExpenditureCS,
    f.TotalTeachingSupportStaffCostsCS,
    f.TeachingStaffCostsCS,
    f.SupplyTeachingStaffCostsCS,
    f.EducationalConsultancyCostsCS,
    f.EducationSupportStaffCostsCS,
    f.AgencySupplyTeachingStaffCostsCS,
    f.TotalNonEducationalSupportStaffCostsCS,
    f.AdministrativeClericalStaffCostsCS,
    f.AuditorsCostsCS,
    f.OtherStaffCostsCS,
    f.ProfessionalServicesNonCurriculumCostsCS,
    f.TotalEducationalSuppliesCostsCS,
    f.ExaminationFeesCostsCS,
    f.LearningResourcesNonIctCostsCS,
    f.LearningResourcesIctCostsCS,
    f.TotalPremisesStaffServiceCostsCS,
    f.CleaningCaretakingCostsCS,
    f.MaintenancePremisesCostsCS,
    f.OtherOccupationCostsCS,
    f.PremisesStaffCostsCS,
    f.TotalUtilitiesCostsCS,
    f.EnergyCostsCS,
    f.WaterSewerageCostsCS,
    f.AdministrativeSuppliesNonEducationalCostsCS,
    f.TotalGrossCateringCostsCS,
    f.TotalNetCateringCostsCS,
    f.CateringStaffCostsCS,
    f.CateringSuppliesCostsCS,
    f.TotalOtherCostsCS,
    f.DirectRevenueFinancingCostsCS,
    f.GroundsMaintenanceCostsCS,
    f.IndirectEmployeeExpensesCS,
    f.InterestChargesLoanBankCS,
    f.OtherInsurancePremiumsCostsCS,
    f.PrivateFinanceInitiativeChargesCS,
    f.RentRatesCostsCS,
    f.SpecialFacilitiesCostsCS,
    f.StaffDevelopmentTrainingCostsCS,
    f.StaffRelatedInsuranceCostsCS,
    f.SupplyTeacherInsurableCostsCS
FROM
    Trust t
    LEFT JOIN (
        SELECT
            TrustCompanyNumber 'CompanyNumber',
            Year,
            SUM(TotalPupils) 'TotalPupils',
            SUM(TotalInternalFloorArea) 'TotalInternalFloorArea',
            SUM(TotalIncome) 'TotalIncome',
            SUM(TotalExpenditure) 'TotalExpenditure',
            SUM(TotalTeachingSupportStaffCosts) 'TotalTeachingSupportStaffCosts',
            SUM(TeachingStaffCosts) 'TeachingStaffCosts',
            SUM(SupplyTeachingStaffCosts) 'SupplyTeachingStaffCosts',
            SUM(EducationalConsultancyCosts) 'EducationalConsultancyCosts',
            SUM(EducationSupportStaffCosts) 'EducationSupportStaffCosts',
            SUM(AgencySupplyTeachingStaffCosts) 'AgencySupplyTeachingStaffCosts',
            SUM(TotalNonEducationalSupportStaffCosts) 'TotalNonEducationalSupportStaffCosts',
            SUM(AdministrativeClericalStaffCosts) 'AdministrativeClericalStaffCosts',
            SUM(AuditorsCosts) 'AuditorsCosts',
            SUM(OtherStaffCosts) 'OtherStaffCosts',
            SUM(ProfessionalServicesNonCurriculumCosts) 'ProfessionalServicesNonCurriculumCosts',
            SUM(TotalEducationalSuppliesCosts) 'TotalEducationalSuppliesCosts',
            SUM(ExaminationFeesCosts) 'ExaminationFeesCosts',
            SUM(LearningResourcesNonIctCosts) 'LearningResourcesNonIctCosts',
            SUM(LearningResourcesIctCosts) 'LearningResourcesIctCosts',
            SUM(TotalPremisesStaffServiceCosts) 'TotalPremisesStaffServiceCosts',
            SUM(CleaningCaretakingCosts) 'CleaningCaretakingCosts',
            SUM(MaintenancePremisesCosts) 'MaintenancePremisesCosts',
            SUM(OtherOccupationCosts) 'OtherOccupationCosts',
            SUM(PremisesStaffCosts) 'PremisesStaffCosts',
            SUM(TotalUtilitiesCosts) 'TotalUtilitiesCosts',
            SUM(EnergyCosts) 'EnergyCosts',
            SUM(WaterSewerageCosts) 'WaterSewerageCosts',
            SUM(AdministrativeSuppliesNonEducationalCosts) 'AdministrativeSuppliesNonEducationalCosts',
            SUM(TotalGrossCateringCosts) 'TotalGrossCateringCosts',
            SUM(TotalNetCateringCosts) 'TotalNetCateringCosts',
            SUM(CateringStaffCosts) 'CateringStaffCosts',
            SUM(CateringSuppliesCosts) 'CateringSuppliesCosts',
            SUM(TotalOtherCosts) 'TotalOtherCosts',
            SUM(DirectRevenueFinancingCosts) 'DirectRevenueFinancingCosts',
            SUM(GroundsMaintenanceCosts) 'GroundsMaintenanceCosts',
            SUM(IndirectEmployeeExpenses) 'IndirectEmployeeExpenses',
            SUM(InterestChargesLoanBank) 'InterestChargesLoanBank',
            SUM(OtherInsurancePremiumsCosts) 'OtherInsurancePremiumsCosts',
            SUM(PrivateFinanceInitiativeCharges) 'PrivateFinanceInitiativeCharges',
            SUM(RentRatesCosts) 'RentRatesCosts',
            SUM(SpecialFacilitiesCosts) 'SpecialFacilitiesCosts',
            SUM(StaffDevelopmentTrainingCosts) 'StaffDevelopmentTrainingCosts',
            SUM(StaffRelatedInsuranceCosts) 'StaffRelatedInsuranceCosts',
            SUM(SupplyTeacherInsurableCosts) 'SupplyTeacherInsurableCosts',
            SUM(CommunityFocusedSchoolStaff) 'CommunityFocusedSchoolStaff',
            SUM(CommunityFocusedSchoolCosts) 'CommunityFocusedSchoolCosts',
            SUM(TotalIncomeCS) 'TotalIncomeCS',
            SUM(TotalExpenditureCS) 'TotalExpenditureCS',
            SUM(TotalTeachingSupportStaffCostsCS) 'TotalTeachingSupportStaffCostsCS',
            SUM(TeachingStaffCostsCS) 'TeachingStaffCostsCS',
            SUM(SupplyTeachingStaffCostsCS) 'SupplyTeachingStaffCostsCS',
            SUM(EducationalConsultancyCostsCS) 'EducationalConsultancyCostsCS',
            SUM(EducationSupportStaffCostsCS) 'EducationSupportStaffCostsCS',
            SUM(AgencySupplyTeachingStaffCostsCS) 'AgencySupplyTeachingStaffCostsCS',
            SUM(TotalNonEducationalSupportStaffCostsCS) 'TotalNonEducationalSupportStaffCostsCS',
            SUM(AdministrativeClericalStaffCostsCS) 'AdministrativeClericalStaffCostsCS',
            SUM(AuditorsCostsCS) 'AuditorsCostsCS',
            SUM(OtherStaffCostsCS) 'OtherStaffCostsCS',
            SUM(ProfessionalServicesNonCurriculumCostsCS) 'ProfessionalServicesNonCurriculumCostsCS',
            SUM(TotalEducationalSuppliesCostsCS) 'TotalEducationalSuppliesCostsCS',
            SUM(ExaminationFeesCostsCS) 'ExaminationFeesCostsCS',
            SUM(LearningResourcesNonIctCostsCS) 'LearningResourcesNonIctCostsCS',
            SUM(LearningResourcesIctCostsCS) 'LearningResourcesIctCostsCS',
            SUM(TotalPremisesStaffServiceCostsCS) 'TotalPremisesStaffServiceCostsCS',
            SUM(CleaningCaretakingCostsCS) 'CleaningCaretakingCostsCS',
            SUM(MaintenancePremisesCostsCS) 'MaintenancePremisesCostsCS',
            SUM(OtherOccupationCostsCS) 'OtherOccupationCostsCS',
            SUM(PremisesStaffCostsCS) 'PremisesStaffCostsCS',
            SUM(TotalUtilitiesCostsCS) 'TotalUtilitiesCostsCS',
            SUM(EnergyCostsCS) 'EnergyCostsCS',
            SUM(WaterSewerageCostsCS) 'WaterSewerageCostsCS',
            SUM(AdministrativeSuppliesNonEducationalCostsCS) 'AdministrativeSuppliesNonEducationalCostsCS',
            SUM(TotalGrossCateringCostsCS) 'TotalGrossCateringCostsCS',
            SUM(TotalNetCateringCostsCS) 'TotalNetCateringCostsCS',
            SUM(CateringStaffCostsCS) 'CateringStaffCostsCS',
            SUM(CateringSuppliesCostsCS) 'CateringSuppliesCostsCS',
            SUM(TotalOtherCostsCS) 'TotalOtherCostsCS',
            SUM(DirectRevenueFinancingCostsCS) 'DirectRevenueFinancingCostsCS',
            SUM(GroundsMaintenanceCostsCS) 'GroundsMaintenanceCostsCS',
            SUM(IndirectEmployeeExpensesCS) 'IndirectEmployeeExpensesCS',
            SUM(InterestChargesLoanBankCS) 'InterestChargesLoanBankCS',
            SUM(OtherInsurancePremiumsCostsCS) 'OtherInsurancePremiumsCostsCS',
            SUM(PrivateFinanceInitiativeChargesCS) 'PrivateFinanceInitiativeChargesCS',
            SUM(RentRatesCostsCS) 'RentRatesCostsCS',
            SUM(SpecialFacilitiesCostsCS) 'SpecialFacilitiesCostsCS',
            SUM(StaffDevelopmentTrainingCostsCS) 'StaffDevelopmentTrainingCostsCS',
            SUM(StaffRelatedInsuranceCostsCS) 'StaffRelatedInsuranceCostsCS',
            SUM(SupplyTeacherInsurableCostsCS) 'SupplyTeacherInsurableCostsCS'
        FROM
            SchoolExpenditureHistoric
        WHERE
            TrustCompanyNumber IS NOT NULL
        GROUP BY
            TrustCompanyNumber,
            Year
    ) f ON f.CompanyNumber = t.CompanyNumber
GO