alter view SchoolBalance as
    SELECT s.URN,
           s.SchoolName,
           s.SchoolType,
           s.LAName,
           s.TrustCompanyNumber,
           f.PeriodCoveredByReturn,
           f.TotalPupils,
           f.TotalIncome,
           f.TotalExpenditure,
           f.InYearBalance,
           f.RevenueReserve,
           f.TotalIncomeCS,
           f.TotalExpenditureCS,
           f.InYearBalanceCS,
           f.RevenueReserveCS
    FROM School s
             LEFT JOIN CurrentDefaultFinancial f on f.URN = s.URN
go

alter view SchoolCharacteristic as
    SELECT s.URN,
           s.SchoolName,
           s.AddressTown,
           s.AddressPostcode,
           s.FinanceType,
           s.OverallPhase,
           s.LAName,
           f.PeriodCoveredByReturn,
           CONVERT(float, nf.TotalPupils)                  'TotalPupils',
           CONVERT(float, nf.PercentFreeSchoolMeals)       'PercentFreeSchoolMeals',
           CONVERT(float, nf.PercentSpecialEducationNeeds) 'PercentSpecialEducationNeeds',
           s.LondonWeighting,
           CONVERT(float, nf.BuildingAverageAge)           'BuildingAverageAge',
           CONVERT(float, nf.TotalInternalFloorArea)       'TotalInternalFloorArea',
           s.OfstedDescription,
           st.SchoolsInTrust,
           s.IsPFISchool,
           CONVERT(float, nf.TotalPupilsSixthForm)         'TotalPupilsSixthForm',
           CONVERT(float, nf.KS2Progress)                  'KS2Progress',
           CONVERT(float, nf.KS4Progress)                  'KS4Progress',
           CONVERT(float, nf.PercentWithVI)                'PercentWithVI',
           CONVERT(float, nf.PercentWithSPLD)              'PercentWithSPLD',
           CONVERT(float, nf.PercentWithSLD)               'PercentWithSLD',
           CONVERT(float, nf.PercentWithSLCN)              'PercentWithSLCN',
           CONVERT(float, nf.PercentWithSEMH)              'PercentWithSEMH',
           CONVERT(float, nf.PercentWithPMLD)              'PercentWithPMLD',
           CONVERT(float, nf.PercentWithPD)                'PercentWithPD',
           CONVERT(float, nf.PercentWithOTH)               'PercentWithOTH',
           CONVERT(float, nf.PercentWithMSI)               'PercentWithMSI',
           CONVERT(float, nf.PercentWithMLD)               'PercentWithMLD',
           CONVERT(float, nf.PercentWithHI)                'PercentWithHI',
           CONVERT(float, nf.PercentWithASD)               'PercentWithASD',
           f.FinancialPosition                             'SchoolPosition'
    FROM School s
             LEFT JOIN SchoolsInTrust st on st.CompanyNumber = s.TrustCompanyNumber
             LEFT JOIN CurrentDefaultNonFinancial nf on nf.URN = s.URN
             LEFT JOIN CurrentDefaultFinancial f on f.URN = s.URN
go

alter view SchoolExpenditure as
    SELECT s.URN,
           s.SchoolName,
           s.SchoolType,
           s.LAName,
           s.TrustCompanyNumber,
           f.PeriodCoveredByReturn,
           f.TotalPupils,
           f.TotalInternalFloorArea,
           f.TotalIncome,
           f.TotalExpenditure,
           f.TotalTeachingSupportStaffCosts,
           f.TeachingStaffCosts,
           f.SupplyTeachingStaffCosts,
           f.EducationalConsultancyCosts,
           f.EducationSupportStaffCosts,
           f.AgencySupplyTeachingStaffCosts,
           f.TotalNonEducationalSupportStaffCosts,
           f.AdministrativeClericalStaffCosts,
           f.AuditorsCosts,
           f.OtherStaffCosts,
           f.ProfessionalServicesNonCurriculumCosts,
           f.TotalEducationalSuppliesCosts,
           f.ExaminationFeesCosts,
           f.LearningResourcesNonIctCosts,
           f.LearningResourcesIctCosts,
           f.TotalPremisesStaffServiceCosts,
           f.CleaningCaretakingCosts,
           f.MaintenancePremisesCosts,
           f.OtherOccupationCosts,
           f.PremisesStaffCosts,
           f.TotalUtilitiesCosts,
           f.EnergyCosts,
           f.WaterSewerageCosts,
           f.AdministrativeSuppliesNonEducationalCosts,
           f.TotalGrossCateringCosts,
           f.TotalNetCateringCostsCosts   AS TotalNetCateringCosts,
           f.CateringStaffCosts,
           f.CateringSuppliesCosts,
           f.TotalOtherCosts,
           f.DirectRevenueFinancingCosts,
           f.GroundsMaintenanceCosts,
           f.IndirectEmployeeExpenses,
           f.InterestChargesLoanBank,
           f.OtherInsurancePremiumsCosts,
           f.PrivateFinanceInitiativeCharges,
           f.RentRatesCosts,
           f.SpecialFacilitiesCosts,
           f.StaffDevelopmentTrainingCosts,
           f.StaffRelatedInsuranceCosts,
           f.SupplyTeacherInsurableCosts,
           f.CommunityFocusedSchoolStaff,
           f.CommunityFocusedSchoolCosts,
           f.TotalIncomeCS,
           f.TotalExpenditureCS,
           f.TotalTeachingSupportStaffCostsCS,
           f.TeachingStaffCostsCS,
           f.SupplyTeachingStaffCostsCS,
           f.EducationalConsultancyCostsCS,
           f.EducationSupportStaffCostsCS,
           f.AgencySupplyTeachingStaffCostsCS,
           f.TotalNonEducationalSupportStaffCostsCS,
           f.AdministrativeClericalStaffCostsCS,
           f.AuditorsCostsCS,
           f.OtherStaffCostsCS,
           f.ProfessionalServicesNonCurriculumCostsCS,
           f.TotalEducationalSuppliesCostsCS,
           f.ExaminationFeesCostsCS,
           f.LearningResourcesNonIctCostsCS,
           f.LearningResourcesIctCostsCS,
           f.TotalPremisesStaffServiceCostsCS,
           f.CleaningCaretakingCostsCS,
           f.MaintenancePremisesCostsCS,
           f.OtherOccupationCostsCS,
           f.PremisesStaffCostsCS,
           f.TotalUtilitiesCostsCS,
           f.EnergyCostsCS,
           f.WaterSewerageCostsCS,
           f.AdministrativeSuppliesNonEducationalCostsCS,
           f.TotalGrossCateringCostsCS,
           f.TotalNetCateringCostsCostsCS AS TotalNetCateringCostsCS,
           f.CateringStaffCostsCS,
           f.CateringSuppliesCostsCS,
           f.TotalOtherCostsCS,
           f.DirectRevenueFinancingCostsCS,
           f.GroundsMaintenanceCostsCS,
           f.IndirectEmployeeExpensesCS,
           f.InterestChargesLoanBankCS,
           f.OtherInsurancePremiumsCostsCS,
           f.PrivateFinanceInitiativeChargesCS,
           f.RentRatesCostsCS,
           f.SpecialFacilitiesCostsCS,
           f.StaffDevelopmentTrainingCostsCS,
           f.StaffRelatedInsuranceCostsCS,
           f.SupplyTeacherInsurableCostsCS
    FROM School s
             LEFT JOIN CurrentDefaultFinancial f ON f.URN = s.URN
go

alter view SchoolIncome as
    SELECT s.URN,
           s.SchoolName,
           s.SchoolType,
           s.LAName,
           s.TrustCompanyNumber,
           f.PeriodCoveredByReturn,
           f.TotalPupils,
           f.TotalIncome,
           f.TotalExpenditure,
           f.TotalGrantFunding,
           f.TotalSelfGeneratedFunding,
           f.DirectRevenueFinancing,
           f.DirectGrants,
           f.PrePost16Funding,
           f.OtherDfeGrants,
           f.OtherIncomeGrants,
           f.GovernmentSource,
           f.CommunityGrants,
           f.Academies,
           f.IncomeFacilitiesServices,
           f.IncomeCateringServices,
           f.DonationsVoluntaryFunds,
           f.ReceiptsSupplyTeacherInsuranceClaims,
           f.InvestmentIncome,
           f.OtherSelfGeneratedIncome,
           f.TotalIncomeCS,
           f.TotalExpenditureCS,
           f.TotalGrantFundingCS,
           f.TotalSelfGeneratedFundingCS,
           f.DirectRevenueFinancingCS,
           f.DirectGrantsCS,
           f.PrePost16FundingCS,
           f.OtherDfeGrantsCS,
           f.OtherIncomeGrantsCS,
           f.GovernmentSourceCS,
           f.CommunityGrantsCS,
           f.AcademiesCS,
           f.IncomeFacilitiesServicesCS,
           f.IncomeCateringServicesCS,
           f.DonationsVoluntaryFundsCS,
           f.ReceiptsSupplyTeacherInsuranceClaimsCS,
           f.InvestmentIncomeCS,
           f.OtherSelfGeneratedIncomeCS
    FROM School s
             LEFT JOIN CurrentDefaultFinancial f on f.URN = s.URN
go

