IF EXISTS(SELECT 1
          FROM sys.views
          WHERE name = 'TrustExpenditureHistoric')
    BEGIN
        DROP VIEW TrustExpenditureHistoric
    END
GO

CREATE VIEW TrustExpenditureHistoric
AS
SELECT t.CompanyNumber,
       t.TrustName,
       f.RunId 'Year',
       f.TotalPupils,
       f.TotalInternalFloorArea,
       f.TotalIncome,
       f.TotalExpenditure,
       f.TotalTeachingSupportStaffCosts,
       f.TeachingStaffCosts,
       f.SupplyTeachingStaffCosts,
       f.EducationalConsultancyCosts,
       f.EducationSupportStaffCosts,
       f.AgencySupplyTeachingStaffCosts,
       f.TotalNonEducationalSupportStaffCosts,
       f.AdministrativeClericalStaffCosts,
       f.AuditorsCosts,
       f.OtherStaffCosts,
       f.ProfessionalServicesNonCurriculumCosts,
       f.TotalEducationalSuppliesCosts,
       f.ExaminationFeesCosts,
       f.LearningResourcesNonIctCosts,
       f.LearningResourcesIctCosts,
       f.TotalPremisesStaffServiceCosts,
       f.CleaningCaretakingCosts,
       f.MaintenancePremisesCosts,
       f.OtherOccupationCosts,
       f.PremisesStaffCosts,
       f.TotalUtilitiesCosts,
       f.EnergyCosts,
       f.WaterSewerageCosts,
       f.AdministrativeSuppliesNonEducationalCosts,
       f.TotalGrossCateringCosts,
       f.CateringStaffCosts,
       f.CateringSuppliesCosts,
       f.TotalOtherCosts,
       f.DirectRevenueFinancingCosts,
       f.GroundsMaintenanceCosts,
       f.IndirectEmployeeExpenses,
       f.InterestChargesLoanBank,
       f.OtherInsurancePremiumsCosts,
       f.PrivateFinanceInitiativeCharges,
       f.RentRatesCosts,
       f.SpecialFacilitiesCosts,
       f.StaffDevelopmentTrainingCosts,
       f.StaffRelatedInsuranceCosts,
       f.SupplyTeacherInsurableCosts,
       f.TotalIncomeCS,
       f.TotalExpenditureCS,
       f.TotalTeachingSupportStaffCostsCS,
       f.TeachingStaffCostsCS,
       f.SupplyTeachingStaffCostsCS,
       f.EducationalConsultancyCostsCS,
       f.EducationSupportStaffCostsCS,
       f.AgencySupplyTeachingStaffCostsCS,
       f.TotalNonEducationalSupportStaffCostsCS,
       f.AdministrativeClericalStaffCostsCS,
       f.AuditorsCostsCS,
       f.OtherStaffCostsCS,
       f.ProfessionalServicesNonCurriculumCostsCS,
       f.TotalEducationalSuppliesCostsCS,
       f.ExaminationFeesCostsCS,
       f.LearningResourcesNonIctCostsCS,
       f.LearningResourcesIctCostsCS,
       f.TotalPremisesStaffServiceCostsCS,
       f.CleaningCaretakingCostsCS,
       f.MaintenancePremisesCostsCS,
       f.OtherOccupationCostsCS,
       f.PremisesStaffCostsCS,
       f.TotalUtilitiesCostsCS,
       f.EnergyCostsCS,
       f.WaterSewerageCostsCS,
       f.AdministrativeSuppliesNonEducationalCostsCS,
       f.TotalGrossCateringCostsCS,
       f.CateringStaffCostsCS,
       f.CateringSuppliesCostsCS,
       f.TotalOtherCostsCS,
       f.DirectRevenueFinancingCostsCS,
       f.GroundsMaintenanceCostsCS,
       f.IndirectEmployeeExpensesCS,
       f.InterestChargesLoanBankCS,
       f.OtherInsurancePremiumsCostsCS,
       f.PrivateFinanceInitiativeChargesCS,
       f.RentRatesCostsCS,
       f.SpecialFacilitiesCostsCS,
       f.StaffDevelopmentTrainingCostsCS,
       f.StaffRelatedInsuranceCostsCS,
       f.SupplyTeacherInsurableCostsCS
  FROM Trust t
  LEFT JOIN TrustFinancial f
    ON t.CompanyNumber = f.CompanyNumber
 CROSS JOIN (SELECT Value FROM Parameters p WHERE p.Name = 'LatestAARYear') y
 WHERE f.RunType = 'default'
   AND f.RunId BETWEEN y.Value - 5 AND y.Value

GO


IF EXISTS(SELECT 1
          FROM sys.views
          WHERE name = 'TrustExpenditure')
    BEGIN
        DROP VIEW TrustExpenditure
    END
GO

CREATE VIEW TrustExpenditure
AS
SELECT t.CompanyNumber,
       t.TrustName,
       f.TotalPupils,
       f.TotalInternalFloorArea,
       f.TotalIncome,
       f.TotalExpenditure,
       f.TotalTeachingSupportStaffCosts,
       f.TeachingStaffCosts,
       f.SupplyTeachingStaffCosts,
       f.EducationalConsultancyCosts,
       f.EducationSupportStaffCosts,
       f.AgencySupplyTeachingStaffCosts,
       f.TotalNonEducationalSupportStaffCosts,
       f.AdministrativeClericalStaffCosts,
       f.AuditorsCosts,
       f.OtherStaffCosts,
       f.ProfessionalServicesNonCurriculumCosts,
       f.TotalEducationalSuppliesCosts,
       f.ExaminationFeesCosts,
       f.LearningResourcesNonIctCosts,
       f.LearningResourcesIctCosts,
       f.TotalPremisesStaffServiceCosts,
       f.CleaningCaretakingCosts,
       f.MaintenancePremisesCosts,
       f.OtherOccupationCosts,
       f.PremisesStaffCosts,
       f.TotalUtilitiesCosts,
       f.EnergyCosts,
       f.WaterSewerageCosts,
       f.AdministrativeSuppliesNonEducationalCosts,
       f.TotalGrossCateringCosts,
       f.CateringStaffCosts,
       f.CateringSuppliesCosts,
       f.TotalOtherCosts,
       f.DirectRevenueFinancingCosts,
       f.GroundsMaintenanceCosts,
       f.IndirectEmployeeExpenses,
       f.InterestChargesLoanBank,
       f.OtherInsurancePremiumsCosts,
       f.PrivateFinanceInitiativeCharges,
       f.RentRatesCosts,
       f.SpecialFacilitiesCosts,
       f.StaffDevelopmentTrainingCosts,
       f.StaffRelatedInsuranceCosts,
       f.SupplyTeacherInsurableCosts,
       f.TotalIncomeCS,
       f.TotalExpenditureCS,
       f.TotalTeachingSupportStaffCostsCS,
       f.TeachingStaffCostsCS,
       f.SupplyTeachingStaffCostsCS,
       f.EducationalConsultancyCostsCS,
       f.EducationSupportStaffCostsCS,
       f.AgencySupplyTeachingStaffCostsCS,
       f.TotalNonEducationalSupportStaffCostsCS,
       f.AdministrativeClericalStaffCostsCS,
       f.AuditorsCostsCS,
       f.OtherStaffCostsCS,
       f.ProfessionalServicesNonCurriculumCostsCS,
       f.TotalEducationalSuppliesCostsCS,
       f.ExaminationFeesCostsCS,
       f.LearningResourcesNonIctCostsCS,
       f.LearningResourcesIctCostsCS,
       f.TotalPremisesStaffServiceCostsCS,
       f.CleaningCaretakingCostsCS,
       f.MaintenancePremisesCostsCS,
       f.OtherOccupationCostsCS,
       f.PremisesStaffCostsCS,
       f.TotalUtilitiesCostsCS,
       f.EnergyCostsCS,
       f.WaterSewerageCostsCS,
       f.AdministrativeSuppliesNonEducationalCostsCS,
       f.TotalGrossCateringCostsCS,
       f.CateringStaffCostsCS,
       f.CateringSuppliesCostsCS,
       f.TotalOtherCostsCS,
       f.DirectRevenueFinancingCostsCS,
       f.GroundsMaintenanceCostsCS,
       f.IndirectEmployeeExpensesCS,
       f.InterestChargesLoanBankCS,
       f.OtherInsurancePremiumsCostsCS,
       f.PrivateFinanceInitiativeChargesCS,
       f.RentRatesCostsCS,
       f.SpecialFacilitiesCostsCS,
       f.StaffDevelopmentTrainingCostsCS,
       f.StaffRelatedInsuranceCostsCS,
       f.SupplyTeacherInsurableCostsCS
 FROM Trust t
 LEFT JOIN TrustFinancial f
   ON t.CompanyNumber = f.CompanyNumber
WHERE f.RunType = 'default'
  AND f.RunId = (SELECT Value FROM Parameters WHERE Name = 'CurrentYear')

GO
