IF NOT EXISTS(SELECT *
              FROM INFORMATION_SCHEMA.TABLES
              WHERE table_name = 'LocalAuthorityFinancial')
    BEGIN
        CREATE TABLE dbo.LocalAuthorityFinancial
        (
            RunType                                            nvarchar(50) NOT NULL,
            RunId                                              nvarchar(50) NOT NULL,
            LaCode                                             nvarchar(3)  NOT NULL,
            Population2To18                                    decimal      NULL,
            OutturnTotalHighNeeds                              decimal      NULL,
            OutturnTotalPlaceFunding                           decimal      NULL,
            OutturnTotalTopUpFundingMaintained                 decimal      NULL,
            OutturnTotalTopUpFundingNonMaintained              decimal      NULL,
            OutturnTotalSenServices                            decimal      NULL,
            OutturnTotalAlternativeProvisionServices           decimal      NULL,
            OutturnTotalHospitalServices                       decimal      NULL,
            OutturnTotalOtherHealthServices                    decimal      NULL,
            OutturnTopFundingMaintainedEarlyYears              decimal      NULL,
            OutturnTopFundingMaintainedPrimary                 decimal      NULL,
            OutturnTopFundingMaintainedSecondary               decimal      NULL,
            OutturnTopFundingMaintainedSpecial                 decimal      NULL,
            OutturnTopFundingMaintainedAlternativeProvision    decimal      NULL,
            OutturnTopFundingMaintainedPostSchool              decimal      NULL,
            OutturnTopFundingMaintainedIncome                  decimal      NULL,
            OutturnTopFundingNonMaintainedEarlyYears           decimal      NULL,
            OutturnTopFundingNonMaintainedPrimary              decimal      NULL,
            OutturnTopFundingNonMaintainedSecondary            decimal      NULL,
            OutturnTopFundingNonMaintainedSpecial              decimal      NULL,
            OutturnTopFundingNonMaintainedAlternativeProvision decimal      NULL,
            OutturnTopFundingNonMaintainedPostSchool           decimal      NULL,
            OutturnTopFundingNonMaintainedIncome               decimal      NULL,
            OutturnPlaceFundingPrimary                         decimal      NULL,
            OutturnPlaceFundingSecondary                       decimal      NULL,
            OutturnPlaceFundingSpecial                         decimal      NULL,
            OutturnPlaceFundingAlternativeProvision            decimal      NULL,
            BudgetTotalHighNeeds                               decimal      NULL,
            BudgetTotalPlaceFunding                            decimal      NULL,
            BudgetTotalTopUpFundingMaintained                  decimal      NULL,
            BudgetTotalTopUpFundingNonMaintained               decimal      NULL,
            BudgetTotalSenServices                             decimal      NULL,
            BudgetTotalAlternativeProvisionServices            decimal      NULL,
            BudgetTotalHospitalServices                        decimal      NULL,
            BudgetTotalOtherHealthServices                     decimal      NULL,
            BudgetTopFundingMaintainedEarlyYears               decimal      NULL,
            BudgetTopFundingMaintainedPrimary                  decimal      NULL,
            BudgetTopFundingMaintainedSecondary                decimal      NULL,
            BudgetTopFundingMaintainedSpecial                  decimal      NULL,
            BudgetTopFundingMaintainedAlternativeProvision     decimal      NULL,
            BudgetTopFundingMaintainedPostSchool               decimal      NULL,
            BudgetTopFundingMaintainedIncome                   decimal      NULL,
            BudgetTopFundingNonMaintainedEarlyYears            decimal      NULL,
            BudgetTopFundingNonMaintainedPrimary               decimal      NULL,
            BudgetTopFundingNonMaintainedSecondary             decimal      NULL,
            BudgetTopFundingNonMaintainedSpecial               decimal      NULL,
            BudgetTopFundingNonMaintainedAlternativeProvision  decimal      NULL,
            BudgetTopFundingNonMaintainedPostSchool            decimal      NULL,
            BudgetTopFundingNonMaintainedIncome                decimal      NULL,
            BudgetPlaceFundingPrimary                          decimal      NULL,
            BudgetPlaceFundingSecondary                        decimal      NULL,
            BudgetPlaceFundingSpecial                          decimal      NULL,
            BudgetPlaceFundingAlternativeProvision             decimal      NULL,

            CONSTRAINT PK_LocalAuthorityFinancial PRIMARY KEY (RunType, RunId, LaCode)
        );
    END;
