IF NOT EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME = 'Financial' AND COLUMN_NAME = 'Connectivity'
)
BEGIN
ALTER TABLE Financial
    ADD Connectivity DECIMAL(16,2) NULL;
END;

IF NOT EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME = 'Financial' AND COLUMN_NAME = 'OnsiteServers'
)
BEGIN
ALTER TABLE Financial
    ADD OnsiteServers DECIMAL(16,2) NULL;
END;

IF NOT EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME = 'Financial' AND COLUMN_NAME = 'ItLearningResources'
)
BEGIN
ALTER TABLE Financial
    ADD ItLearningResources DECIMAL(16,2) NULL;
END;

IF NOT EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME = 'Financial' AND COLUMN_NAME = 'AdministrationSoftwareAndSystems'
)
BEGIN
ALTER TABLE Financial
    ADD AdministrationSoftwareAndSystems DECIMAL(16,2) NULL;
END;

IF NOT EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME = 'Financial' AND COLUMN_NAME = 'LaptopsDesktopsAndTablets'
)
BEGIN
ALTER TABLE Financial
    ADD LaptopsDesktopsAndTablets DECIMAL(16,2) NULL;
END;

IF NOT EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME = 'Financial' AND COLUMN_NAME = 'OtherHardware'
)
BEGIN
ALTER TABLE Financial
    ADD OtherHardware DECIMAL(16,2) NULL;
END;

IF NOT EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME = 'Financial' AND COLUMN_NAME = 'ItSupport'
)
BEGIN
ALTER TABLE Financial
    ADD ItSupport DECIMAL(16,2) NULL;
END;
