using System;
using System.Collections.Generic;

namespace EducationBenchmarking.Platform.Domain;

public class SchoolTrustFinance
{
    public long? URN { get; set; }
    public string SchoolName { get; set; }
    public string FinanceType { get; set; }
    public int? CompanyNumber { get; set; }
    public int? UID { get; set; }
    public string TrustOrCompanyName { get; set; }
    public decimal? OtherIncome { get; set; }
    public decimal? SEN { get; set; }
    public decimal? OtherDfeGrants { get; set; }
    public decimal? OtherIncomeGrants { get; set; }
    public decimal? GovernmentSource { get; set; }
    public decimal? Academies { get; set; }
    public decimal? NonGoverntment { get; set; }
    public decimal? IncomeFromFacilities { get; set; }
    public decimal? IncomeFromCatering { get; set; }
    public decimal? ReceiptsFromSupply { get; set; }
    public decimal? ReceiptsFromOther { get; set; }
    public decimal? Donations { get; set; }
    public decimal? OtherSelfGenerated { get; set; }
    public decimal? Investmentincome { get; set; }
    public decimal? TeachingStaff { get; set; }
    public decimal? SupplyTeachingStaff { get; set; }
    public decimal? EducationSupportStaff { get; set; }
    public decimal? AdministrativeClericalStaff { get; set; }
    public decimal? PremisesStaff { get; set; }
    public decimal? CateringStaff { get; set; }
    public decimal? OtherStaff { get; set; }
    public decimal? IndirectEmployeeExpenses { get; set; }
    public decimal? StaffDevelopment { get; set; }
    public decimal? StaffInsurance { get; set; }
    public decimal? SupplyTeacherInsurance { get; set; }
    public decimal? BuildingGroundsMaintenance { get; set; }
    public decimal? CleaningCaretaking { get; set; }
    public decimal? WaterSewerage { get; set; }
    public decimal? Energy { get; set; }
    public decimal? Rates { get; set; }
    public decimal? RentRates { get; set; }
    public decimal? OtherOccupationCosts { get; set; }
    public decimal? Specialfacilities { get; set; }
    public decimal? LearningResources { get; set; }
    public decimal? ICTLearningResources { get; set; }
    public decimal? ExaminationFees { get; set; }
    public decimal? EducationalConsultancy { get; set; }
    public decimal? AdministrativeSupplies { get; set; }
    public decimal? AgencyTeachingStaff { get; set; }
    public decimal? CateringSupplies { get; set; }
    public decimal? OtherInsurancePremiums { get; set; }
    public decimal? LegalProfessional { get; set; }
    public decimal? AuditorCosts { get; set; }
    public decimal? InterestCharges { get; set; }
    public decimal? DirectRevenue { get; set; }
    public decimal? PFICharges { get; set; }
    public decimal? InYearBalance { get; set; }
    public decimal? GrantFunding { get; set; }
    public decimal? DirectGrant { get; set; }
    public decimal? CommunityGrants { get; set; }
    public decimal? TargetedGrants { get; set; }
    public decimal? SelfGeneratedFunding { get; set; }
    public decimal? TotalIncome { get; set; }
    public decimal? SupplyStaff { get; set; }
    public decimal? OtherStaffCosts { get; set; }
    public decimal? StaffTotal { get; set; }
    public decimal? MaintenanceImprovement { get; set; }
    public decimal? GroundsMaintenanceImprovement { get; set; }
    public decimal? BuildingMaintenanceImprovement { get; set; }
    public decimal? Premises { get; set; }
    public decimal? CateringExp { get; set; }
    public decimal? Occupation { get; set; }
    public decimal? SuppliesServices { get; set; }
    public decimal? EducationalSupplies { get; set; }
    public decimal? BroughtProfessionalServices { get; set; }
    public decimal? BoughtInOther { get; set; }
    public decimal? BoughtInNotPFI { get; set; }
    public decimal? CommunityFocusedStaff { get; set; }
    public decimal? CommunityFocusedSchoolCosts { get; set; }
    public decimal? PrePost16Funding { get; set; }
    public decimal? CommunityFocusedFunding { get; set; }
    public decimal? AdditionalGrant { get; set; }
    public decimal? PupilFocusedFunding { get; set; }
    public decimal? PupilPremium { get; set; }
    public decimal? ESG { get; set; }
    public decimal? CostOfFinance { get; set; }
    public decimal? FundingMinority { get; set; }
    public decimal? CommunityExpenditure { get; set; }
    public decimal? CommFocusedSchoolFacilities { get; set; }
    public decimal? ContributionsToVisits { get; set; }
    public decimal? TotalExpenditure { get; set; }
    public decimal? RevenueReserve { get; set; }
    public decimal? NoPupils { get; set; }
    public decimal? NoTeachers { get; set; }
    public int? SchoolCount { get; set; }
    public int? PeriodCoveredByReturn { get; set; }
    public bool? PartialYearsPresent { get; set; }
    public string OverallPhase { get; set; }
    public string Phase { get; set; }
    public Dictionary<string, int> OverallPhaseBreakdown { get; set; }
    public bool DidNotSubmit { get; set; }
    public string MATSATCentralServices { get; set; }
    public bool WorkforcePresent { get; set; }
    public string AdmissionPolicy { get; set; }
    public string Gender { get; set; }
    public string Type { get; set; }
    public string UrbanRural { get; set; }
    public string Region { get; set; }
    public string LondonBorough { get; set; }
    public string LondonWeight { get; set; }
    public decimal? PercentageFSM { get; set; }
    public decimal? PercentagePupilsWSEN { get; set; }
    public decimal? PercentagePupilsWOSEN { get; set; }
    public decimal? PercentagePupilsWEAL { get; set; }
    public decimal? PercentageBoarders { get; set; }
    public string PFI { get; set; }
    public string Has6Form { get; set; }
    public decimal? NumberIn6Form { get; set; }
    public int? HighestAgePupils { get; set; }
    public decimal? AdminStaff { get; set; }
    public decimal? FullTimeOther { get; set; }
    public decimal? FullTimeOtherHeadCount { get; set; }
    public decimal? PercentageQualifiedTeachers { get; set; }
    public int? LowestAgePupils { get; set; }
    public decimal? FullTimeTA { get; set; }
    public decimal? FullTimeTAHeadcount { get; set; }
    public decimal? WorkforceTotal { get; set; }
    public decimal? TeachersTotal { get; set; }
    public decimal? NumberTeachersHeadcount { get; set; }
    public decimal? NumberTeachersInLeadershipHeadcount { get; set; }
    public decimal? TeachersLeader { get; set; }
    public decimal? AuxStaff { get; set; }
    public decimal? AuxStaffHeadcount { get; set; }
    public decimal? WorkforceHeadcount { get; set; }
    public decimal? Ks2Actual { get; set; }
    public decimal? Ks2Progress { get; set; }
    public decimal? AverageAttainment { get; set; }
    public decimal? Progress8Measure { get; set; }
    public decimal? Progress8Banding { get; set; }
    public string OfstedRatingName { get; set; }
    public decimal? SpecificLearningDiff { get; set; }
    public decimal? ModerateLearningDiff { get; set; }
    public decimal? SevereLearningDiff { get; set; }
    public decimal? ProfLearningDiff { get; set; }
    public decimal? SocialHealth { get; set; }
    public decimal? SpeechNeeds { get; set; }
    public decimal? HearingImpairment { get; set; }
    public decimal? VisualImpairment { get; set; }
    public decimal? MultiSensoryImpairment { get; set; }
    public decimal? PhysicalDisability { get; set; }
    public decimal? AutisticDisorder { get; set; }
    public decimal? OtherLearningDiff { get; set; }
    public int? LA { get; set; }
    public decimal? OfstedRating { get; set; }
    public bool IsPlaceholder { get; set; }
    public decimal? RRPerIncomePercentage { get; set; }
    public decimal? PerPupilGrantFunding { get; set; }
    public decimal? PerPupilTotalExpenditure { get; set; }
    public decimal? PerTeachersOnMainPay { get; set; }
    public decimal? PerTeachersOnUpperOrLeadingPay { get; set; }
    public decimal? PerTeachersOnLeadershipPay { get; set; }
    public bool IsFederation { get; set; }
    public bool IsPartOfFederation { get; set; }
    public long? FederationUid { get; set; }
    public string FederationName { get; set; }
    public decimal? InterestLoansAndBanking { get; set; }
    public decimal? DirectRevenueFinancing { get; set; }
    
    
}