pool:
  vmImage: 'ubuntu-latest'

trigger:
  batch: true
  branches:
    include:
      - main
  paths:
    include:
      - front-end-components

pr:
  paths:
    include:
      - front-end-components

variables:
  Version.Revision: $[counter(variables['Build.SourceBranchName'], 0)]
  Version.BuildNumber: 0.1.$(Version.Revision)
  Version.BuildVersion: $(Version.BuildNumber)
  WorkingDir: 'front-end-components'

steps:
  - bash: |
      echo "##vso[build.updatebuildnumber]$(Version.BuildNumber)"
      echo "##vso[build.addbuildtag]$(Version.BuildNumber)"
      echo "##vso[build.addbuildtag]Front-end components"
      if [[ "$(Build.Reason)" == "PullRequest" ]]; then
        preRelease="pr$(System.PullRequest.PullRequestId)"
        echo "##vso[build.addbuildtag]PR #$(System.PullRequest.PullRequestId)"
      fi
      echo "##vso[task.setvariable variable=Version.PreRelease]$preRelease"
    displayName: 'Set release build and version number'

  - task: Npm@1
    displayName: 'Update version number'
    continueOnError: false
    inputs:
      command: 'custom'
      customCommand: 'version $(Version.BuildNumber)'
      workingDir: $(WorkingDir)
      verbose: false

  - task: Npm@1
    displayName: 'Update pre-release version number'
    condition: ne(variables['Version.PreRelease'], '')
    continueOnError: false
    inputs:
      command: 'custom'
      customCommand: 'version prerelease -preid=$(Version.PreRelease)'
      workingDir: $(WorkingDir)
      verbose: false

  - task: Npm@1
    displayName: 'Install dependencies'
    inputs:
      command: 'install'
      workingDir: $(WorkingDir)

  - task: Npm@1
    displayName: 'Run tests'
    inputs:
      command: 'custom'
      customCommand: 'test'
      workingDir: $(WorkingDir)

  - task: Npm@1
    displayName: 'Run lint'
    inputs:
      command: 'custom'
      customCommand: 'run lint'
      workingDir: $(WorkingDir)

  - task: Npm@1
    displayName: 'Build project'
    inputs:
      command: 'custom'
      customCommand: 'run build'
      workingDir: $(WorkingDir)

  - task: Npm@1
    displayName: 'Publish'
    continueOnError: false
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    inputs:
      command: 'publish'
      publishRegistry: useFeed
      publishFeed: 'S198-DfE-Benchmarking-service/education-benchmarking'
      workingDir: $(WorkingDir)
      verbose: false
