pool:
  vmImage: 'ubuntu-latest'

variables:
  Version.Revision: $[counter(variables['Build.SourceBranchName'], 0)]
  Version.BuildNumber: 0.0.$(Version.Revision)
  Version.BuildVersion: $(Version.BuildNumber)
  WorkingDir: 'front-end-components'

trigger:
  batch: true
  branches:
    include:
      - main
  paths:
    include:
      - front-end-components

pr:
  paths:
    include:
      - front-end-components

steps:
  - task: Npm@1
    displayName: 'Update version number'
    continueOnError: false
    inputs:
      command: 'custom'
      ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:
        customCommand: 'version $(Version.BuildNumber)'
      ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
        customCommand: 'version $(Version.BuildNumber)-alpha.0'
      workingDir: $(WorkingDir)
      verbose: false

  - task: Npm@1
    displayName: 'Install dependencies'
    inputs:
      command: 'install'
      workingDir: $(WorkingDir)

  - task: Npm@1
    displayName: 'Run tests'
    inputs:
      command: 'custom'
      customCommand: 'test'
      workingDir: $(WorkingDir)

  - task: Npm@1
    displayName: 'Run lint'
    inputs:
      command: 'custom'
      customCommand: 'run lint'
      workingDir: $(WorkingDir)

  - task: Npm@1
    displayName: 'Build project'
    inputs:
      command: 'custom'
      customCommand: 'run build'
      workingDir: $(WorkingDir)

  - task: Npm@1
    displayName: 'Publish'
    continueOnError: false
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    inputs:
      command: 'publish'
      publishRegistry: useFeed
      publishFeed: 'S198-DfE-Benchmarking-service/education-benchmarking'
      workingDir: $(WorkingDir)
      verbose: false
