pool:
  vmImage: 'ubuntu-latest'

trigger:
  batch: true
  branches:
    include:
      - main
  paths:
    include:
      - shared
      - web

pr:
  paths:
    include:
      - web

variables:
  Version.Revision: $[counter(variables['Build.SourceBranchName'], 0)]
  Version.BuildNumber: 0.0.$(Version.Revision)
  Version.BuildVersion: $(Version.BuildNumber)
  NUGET_PLUGIN_HANDSHAKE_TIMEOUT_IN_SECONDS: 30
  NUGET_PLUGIN_REQUEST_TIMEOUT_IN_SECONDS: 30
  TerraformFolder: 'web/terraform'
  TerraformDirectory: '$(System.DefaultWorkingDirectory)/$(TerraformFolder)'
  ShouldDeploy: $[and(eq(variables['Build.SourceBranch'], 'refs/heads/main'), ne(variables['Build.Reason'], 'PullRequest'))]

stages:
  - stage: Build
    displayName: 'Build'
    jobs:
      - job: SetBuildNumber
        displayName: 'Set build number'
        steps:
          - checkout: none

          - bash: |
              echo "##vso[task.setvariable variable=Version.BuildNumber]$(Version.BuildNumber)-prerelease"
              echo "##vso[task.setvariable variable=Version.BuildVersion]$(Version.BuildNumber)"
              echo "##vso[build.updatebuildnumber]$(Version.BuildNumber)-prerelease"
            condition: or(eq(variables['Build.SourceBranch'], 'refs/heads/main'), eq(variables['Build.Reason'], 'PullRequest'))
            displayName: 'Set pre-release build number'

      - job: FmtValidateTf
        displayName: "Lint and validate terraform"
        steps:
          - template: ..\..\shared\steps-fmt-validate-terraform.yaml
            parameters:
              TerraformDirectory: $(TerraformDirectory)

      - job: RunCheckOv
        displayName: "Static analysis terraform"
        steps:
          - template: ..\..\shared\steps-scan-terraform.yaml
            parameters:
              TerraformDirectory: $(TerraformDirectory)

      - job: ZipStaticArtifacts
        displayName: 'Zip static artifacts'
        condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
        steps:
          - template: ..\..\shared\steps-publish-terraform-artifacts.yaml
            parameters:
              TerraformFolder: $(TerraformFolder)

      - job: RunFormat
        displayName: 'Format solution'
        steps:
          - template: ..\..\shared\steps-dotnet-format.yaml
            parameters:
              SolutionDirectory: '$(System.DefaultWorkingDirectory)/web'

      - job: RunTests
        displayName: 'Run unit tests'
        steps:
          - template: steps-web-run-unit-tests.yaml

      - job: BuildE2eA11yTests
        displayName: 'Build web e2e & a11y tests'
        steps:
          - template: steps-web-build-tests.yaml

      - job: BuildWeb
        dependsOn: [ SetBuildNumber ]
        displayName: 'Build web'
        steps:
          - template: steps-web-build.yaml
            parameters:
              BuildVersion: $(Version.BuildVersion)
              BuildNumber: $(Version.BuildNumber)

  - stage: DeployDevelopment
    dependsOn: [ Build ]
    displayName: 'Development'
    condition: and(succeeded(), eq(variables['ShouldDeploy'],'true'))
    variables:
      - group: 'dsi pre-prod'
    jobs:
      - template: jobs-web-deployment.yaml
        parameters:
          subscription: 's198d.azdo-deployment'
          environmentPrefix: 's198d01'
          environment: 'development'
          cipEnvironment: 'Dev'

  - stage: DeployAutomatedTest
    dependsOn: [ Build ]
    displayName: 'Automated test'
    condition: and(succeeded(), eq(variables['ShouldDeploy'],'true'))
    variables:
      - group: 'dsi pre-prod'
    jobs:
      - template: jobs-web-deployment.yaml
        parameters:
          subscription: 's198d.azdo-deployment'
          environmentPrefix: 's198d02'
          environment: 'automated-test'
          cipEnvironment: 'Dev'

      - job: RunE2ETests
        displayName: 'Run automated e2e tests'
        steps:
          - template: steps-web-run-e2e-tests.yaml
            parameters:
              workspaceDir: '$(Pipeline.Workspace)'
    
      - job: RunA11YTests
        displayName: 'Run automated a11y tests'
        steps:
          - template: steps-web-run-a11y-tests.yaml
            parameters:
              workspaceDir: '$(Pipeline.Workspace)'
  

  - stage: DeployTest
    dependsOn: [ Build, DeployAutomatedTest ]
    displayName: 'Test'
    condition: and(succeeded(), eq(variables['ShouldDeploy'],'true'))
    variables:
      - group: 'dsi pre-prod'
    jobs:
      - template: jobs-web-deployment.yaml
        parameters:
          subscription: 's198t.azdo-deployment'
          environmentPrefix: 's198t01'
          environment: 'test'
          cipEnvironment: 'Test'