parameters:
  subscription: ''
  environmentPrefix: ''
  environment: ''
  cipEnvironment: ''
  workspaceDir: '$(Pipeline.Workspace)'

jobs:
  - deployment: RunTerraform
    displayName: 'Run terraform'
    pool:
      vmImage: ubuntu-latest
    environment: ${{ parameters.environment }}
    strategy:
      runOnce:
        deploy:
          steps:
            - template: ..\..\shared\steps-run-terraform.yaml
              parameters:
                subscription: ${{ parameters.subscription }}
                environmentPrefix: ${{ parameters.environmentPrefix }}
                environment: ${{ parameters.environment }}
                cipEnvironment: ${{ parameters.cipEnvironment }}
                module: 'web'
                
  - deployment: Deploy
    dependsOn: [RunTerraform]
    displayName: 'Deploy web'
    pool:
      vmImage: ubuntu-latest
    environment: ${{ parameters.environment }}
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: none
            - download: current
            - task: AzureRmWebAppDeployment@4
              displayName: 'Deploy website'
              inputs:
                azureSubscription: ${{ parameters.subscription }}
                WebAppName: '${{ parameters.environmentPrefix }}-education-benchmarking'
                deployToSlotOrASE: true
                ResourceGroupName: '${{ parameters.environmentPrefix }}-ebis-web'
                packageForLinux: '${{ parameters.workspaceDir }}/web/EducationBenchmarking.Web.zip'
                enableCustomDeployment: true
                DeploymentType: 'zipDeploy' 