pool:
  vmImage: 'windows-2022'

trigger:
  batch: true
  branches:
    include:
    - main
  paths:
    include:
    - platform

pr:
  paths: 
    include:
    - platform
  drafts: false

variables:
  Version.Revision: $[counter(variables['Build.SourceBranchName'], 0)]  
  Version.BuildNumber: 0.0.$(Version.Revision)
  Version.BuildVersion: $(Version.BuildNumber)
  NUGET_PACKAGES: $(Pipeline.Workspace)/.nuget/test/packages
  CACHE_RESTORED: 'false'
  NUGET_PLUGIN_HANDSHAKE_TIMEOUT_IN_SECONDS: 30
  NUGET_PLUGIN_REQUEST_TIMEOUT_IN_SECONDS: 30

stages:
  - stage: Build
    jobs:
      - job: Set_Build_Number
        displayName: 'Set build number'
        steps:
          - checkout: none          
                    
          - bash: |
              echo "##vso[task.setvariable variable=Version.BuildNumber]$(Version.BuildNumber)-prerelease"
              echo "##vso[task.setvariable variable=Version.BuildVersion]$(Version.BuildNumber)"
              echo "##vso[build.updatebuildnumber]$(Version.BuildNumber)-prerelease"
            condition: or(eq(variables['Build.SourceBranch'], 'refs/heads/main'), eq(variables['Build.Reason'], 'PullRequest'))
            displayName: 'Set pre-release build number'

      - job: Zip_Static_artifacts
        displayName: 'Zip static artifacts'
        condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
        steps: 
          - task: ArchiveFiles@2
            displayName: 'Zip terraform files'
            inputs:
              rootFolderOrFile: 'platform/terraform'
              includeRootFolder: false
              archiveFile: '$(Build.ArtifactStagingDirectory)/terraform.zip'

          - publish: $(Build.ArtifactStagingDirectory)/terraform.zip
            artifact: terraform

      - job: RunTests
        dependsOn: [Set_Build_Number]
        displayName: 'Run unit tests'
        steps:
          - task: NuGetAuthenticate@0
          
          - task: Cache@2
            displayName: 'Cache nuget packages'
            inputs:
              key: 'nuget | "$(Agent.OS)-tests" | platform/**/*.Tests*/packages.lock.json,!**/bin/**,!**/obj/**'
              restoreKeys: |
                nuget | "$(Agent.OS)-tests"
              path: $(NUGET_PACKAGES)
              cacheHitVar: CACHE_RESTORED

          - task: DotNetCoreCLI@2
            displayName: 'Restore nuget packages'
            condition: ne(variables.CACHE_RESTORED, 'true')
            inputs:
              command: restore
              projects: 'platform/**/*.Tests.csproj'
              packagesDirectory: $(NUGET_PACKAGES)
              feedsToUse: 'config'
              nugetConfigPath: 'platform/nuget.config'
                              
          - task: DotNetCoreCLI@2
            displayName: 'Run unit tests'
            inputs:
              command: test
              packagesDirectory: $(NUGET_PACKAGES)
              arguments: '--configuration Release --collect "Code coverage"'
              projects: 'platform/**/*.Tests.csproj'

      - job: BuildPlatform
        dependsOn: [Set_Build_Number]
        displayName: 'Build platform'
        steps:
          - template: steps-platform-build.yaml
            parameters:
              BuildVersion: $(Version.BuildVersion)
              BuildNumber: $(Version.BuildNumber)
      
  - stage: DeployDevelopment
    dependsOn: [Build]
    displayName: 'Deploy to development'
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    jobs:
      - template: jobs-platform-deployment.yaml
        parameters:
          subscription: 's198d.azdo-deployment'
          environmentPrefix: 's198d01'
          environment: 'development'
          cipEnvironment: 'Dev'