pool:
  vmImage: 'ubuntu-latest'

trigger:
  batch: true
  branches:
    include:
    - main
  paths:
    include:
    - platform

pr:
  paths: 
    include:
    - platform
  drafts: false

variables:
  Version.Revision: $[counter(variables['Build.SourceBranchName'], 0)]  
  Version.BuildNumber: 0.0.$(Version.Revision)
  Version.BuildVersion: $(Version.BuildNumber)
  NUGET_PLUGIN_HANDSHAKE_TIMEOUT_IN_SECONDS: 30
  NUGET_PLUGIN_REQUEST_TIMEOUT_IN_SECONDS: 30

stages:
  - stage: Build
    jobs:
      - job: Set_Build_Number
        displayName: 'Set build number'
        steps:
          - checkout: none          
                    
          - bash: |
              echo "##vso[task.setvariable variable=Version.BuildNumber]$(Version.BuildNumber)-prerelease"
              echo "##vso[task.setvariable variable=Version.BuildVersion]$(Version.BuildNumber)"
              echo "##vso[build.updatebuildnumber]$(Version.BuildNumber)-prerelease"
            condition: or(eq(variables['Build.SourceBranch'], 'refs/heads/main'), eq(variables['Build.Reason'], 'PullRequest'))
            displayName: 'Set pre-release build number'

      - job: RunCheckov
        displayName: "Checkov scan terraform"
        steps:
          - template: steps-platform-scan-terraform.yaml
            parameters:
              TerraformDirectory: $(System.DefaultWorkingDirectory)/platform/terraform

      - job: Zip_Static_artifacts
        displayName: 'Zip static artifacts'
        condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
        steps:
          - template: steps-platform-publish-static-artifacts.yaml

      - job: RunTests
        displayName: 'Run unit tests'
        steps:
          - template: steps-platform-run-unit-tests.yaml

      - job: BuildPlatform
        dependsOn: [Set_Build_Number]
        displayName: 'Build platform'
        steps:
          - template: steps-platform-build.yaml
            parameters:
              BuildVersion: $(Version.BuildVersion)
              BuildNumber: $(Version.BuildNumber)
      
  - stage: DeployDevelopment
    dependsOn: [Build]
    displayName: 'Deploy to development'
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    jobs:
      - template: jobs-platform-deployment.yaml
        parameters:
          subscription: 's198d.azdo-deployment'
          environmentPrefix: 's198d01'
          environment: 'development'
          cipEnvironment: 'Dev'