environment-prefix  = "__environmentPrefix__"
environment         = "__environment__"
location            = "__location__"
cip-environment     = "__cipEnvironment__"
pipeline-image-name = "__pipelineImageName__"
api-image-name      = "__apiImageName__"