environment-prefix     = "__environmentPrefix__"
environment            = "__environment__"
location               = "__location__"
secondary-location     = "__secondaryLocation__"
cip-environment        = "__cipEnvironment__"
image-name             = "__imageName__"
use-secondary-location = "__useSecondaryLocation__"
