parameters:
  subscription: ''
  environmentPrefix: ''
  environment: ''
  cipEnvironment: ''
  workspaceDir: '$(Pipeline.Workspace)'
  dependsOn: []

jobs:
  - deployment: WebDeployment
    displayName: 'Web : Deployment'
    dependsOn: ${{ parameters.dependsOn }}
    pool:
      vmImage: ubuntu-latest
    environment: ${{ parameters.environment }}
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: none

            - download: current

            - template: ..\common\run-terraform.yaml
              parameters:
                subscription: ${{ parameters.subscription }}
                environmentPrefix: ${{ parameters.environmentPrefix }}
                environment: ${{ parameters.environment }}
                cipEnvironment: ${{ parameters.cipEnvironment }}
                module: 'web'

            - task: AzureRmWebAppDeployment@4
              displayName: 'Deploy website'
              inputs:
                azureSubscription: ${{ parameters.subscription }}
                WebAppName: '${{ parameters.environmentPrefix }}-education-benchmarking'
                deployToSlotOrASE: true
                ResourceGroupName: '${{ parameters.environmentPrefix }}-ebis-web'
                packageForLinux: '${{ parameters.workspaceDir }}/web/Web.App.zip'
                enableCustomDeployment: true
                DeploymentType: 'zipDeploy' 
                appType: 'webAppLinux'
                ScriptType: 'Inline Script'
                # source: https://nodejs.org/en/download/package-manager
                InlineScript: |
                  # installs NVM (Node Version Manager)
                  curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
                  # This loads nvm
                  export NVM_DIR="$HOME/.nvm"
                  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  
                  # download and install Node.js
                  nvm install 20.12.2
                  # verifies the right Node.js version is in the environment
                  node -v # should print `v20.12.2`
                  # verifies the right NPM version is in the environment
                  npm -v # should print `10.5.0`