environment-prefix       = "__environmentPrefix__"
environment              = "__environment__"
location                 = "__location__"
cip-environment          = "__cipEnvironment__"
package_path           = "__packagePath__"