export const CompareCostsElementId = "compare-your-costs";
export const CompareTrustElementId = "compare-your-trust";
export const CompareCensusElementId = "compare-your-census";
export const DeploymentPlanElementId = "deployment-plan";
export const HorizontalBarChart1SeriesElementId = "horizontal-chart-1-series";
export const HorizontalChartTrustFinancialElementId =
  "horizontal-chart-trust-financial";
export const LineChart1SeriesElementId = "line-chart-1-series";
export const LineChart2SeriesElementId = "line-chart-2-series";
export const VerticalBarChart2SeriesElementId = "vertical-chart-2-series";
export const VerticalBarChart3SeriesElementId = "vertical-chart-3-series";
export const HistoricDataElementId = "historic-data";
export const SpendingAndCostsComposedElementId = "spending-and-costs-composed";
export const FindOrganisationElementId = "find-organisation";
export const SchoolEstablishment = "school";
export const TrustEstablishment = "trust";
export const SchoolSuggesterId = "school-suggester";
export const LaSuggesterId = "la-suggester";
export const TrustSuggesterId = "trust-suggester";
