# build/publish stage
FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

COPY core-infrastructure/ core-infrastructure/
RUN dotnet restore core-infrastructure/src/db/Core.Database/Core.Database.csproj
RUN dotnet publish core-infrastructure/src/db/Core.Database/Core.Database.csproj -c Release -o /app/publish

# runtime stage
FROM mcr.microsoft.com/dotnet/runtime:10.0
WORKDIR /app
COPY --from=build /app/publish .

ENTRYPOINT ["dotnet", "Core.Database.dll"]
