displayName: Spike_API_Establishment - School
testPlan: url-test.json
description: Spike load test for GET /school/{identifier}
engineInstances: 1
testId: d9ada663-f552-4793-952e-e757bbeef008
testType: URL
subnetId: /subscriptions/a5c0a8d7-a54d-4a6d-ab79-4ca64a3b750f/resourceGroups/s198t01-ebis-core/providers/Microsoft.Network/virtualNetworks/s198t01-app-service-network/subnets/s198t01-load-test-subnet
publicIPDisabled: true
splitAllCSVs: False
configurationFiles:
- schools.csv
failureCriteria:
- p75(response_time_ms) > 200
- p95(response_time_ms) > 500
- p99(response_time_ms) > 2000
- percentage(error) > 1
secrets:
- name: establishment-host-key
  value: https://s198t01-ebis-keyvault.vault.azure.net/secrets/establishment-host-key
autoStop:
  errorPercentage: 90
  timeWindow: 60
