/* eslint-disable react-refresh/only-export-components */
export * from "src/views/compare-your-costs-2/partials/accordion-sections/utilities";
export * from "src/views/compare-your-costs-2/partials/accordion-sections/teaching-support-staff";
export * from "src/views/compare-your-costs-2/partials/accordion-sections/other-costs";
export * from "src/views/compare-your-costs-2/partials/accordion-sections/premises-staff-services";
export * from "src/views/compare-your-costs-2/partials/accordion-sections/non-educational-support-staff";
export * from "src/views/compare-your-costs-2/partials/accordion-sections/educational-supplies";
export * from "src/views/compare-your-costs-2/partials/accordion-sections/educational-ict";
export * from "src/views/compare-your-costs-2/partials/accordion-sections/catering-staff-services";
export * from "src/views/compare-your-costs-2/partials/accordion-sections/administrative-supplies";
