parameters:
  subscription: ''
  environmentPrefix: ''
  environment: ''
  cipEnvironment: ''

jobs:
  - deployment: RunTerraform
    displayName: 'Run terraform'
    pool:
      vmImage: ubuntu-latest
    environment: ${{ parameters.environment }}
    strategy:
      runOnce:
        deploy:
          steps:
            - template: ..\steps\run-terraform.yaml
              parameters:
                subscription: ${{ parameters.subscription }}
                environmentPrefix: ${{ parameters.environmentPrefix }}
                environment: ${{ parameters.environment }}
                cipEnvironment: ${{ parameters.cipEnvironment }}
                module: 'core'