# Year-on-year Download File Mapping Configurations
_download_file_base_mappings = {
    "I01 Funds delegated by the LA": "I01 Pre-16 Funding",
    "I02 Funding for 6th form students": "I02 Post-16 Funding",
    "I01/2 Total pre and Post-16 Funding": "I01/2 Pre and Post-16 Funding",
    "I03 SEN funding": "I03 SEN",
    "I04 Funding for minority ethnic pupils": "I04 Funding for minority ethnic pupils",
    "I05 Pupil premium": "I05 Pupil Premium",
    "I06 Other government grants": "I06 Other DfE/EFA Revenue Grants",
    "I07 Other grants and payments": "I07 Other income (LA & other Government grants)",
    "I08a Income from lettings": "I08a Income from lettings",
    "I08b Income from facilities and services": "I08b Income from facilities and services",
    "I08a/b Total income from facilities and services": "I08a/b Income from facilities and services",
    "I09 Income from catering": "I09 Income from catering",
    "I10 Receipts from supply teacher insurance claims": "I10 Receipts from supply teacher insurance claims",
    "I11 Receipts from other insurance claims": "I11 Receipts from other insurance claims",
    "I12 Income from contributions to visits etc.": "I12 Income from contributions to visits etc",
    "I13 Donations and/or private funds": "I13 Donations and/or voluntary funds",
    "I15 Pupil focussed extended school funding and / or grants": "I15 Pupil focussed extended school funding and/or grants",
    "I16 Community focussed school funding and / or grants": "I16 Community focussed school funding and/or grants",
    "I17 Community focused school facilities income": "I17 Community focused school facilities income",
    "I18c Income from the £1bn COVID-19 catch-up package announced on 20 July 2020": "I18c Income from the £1bn COVID-19 catch-up package announced on 20 July 2020",
    "I18d Income from other additional grants": "I18d Income from other additional grants",
    "I18 Total additional grant for schools": "I18 Total additional grant for schools",
    "E01 Teaching staff": "E01 Teaching staff",
    "E02 Supply teaching staff": "E02 Supply teaching staff",
    "E03 Education support staff": "E03 Education support staff",
    "E04 Premises staff": "E04 Premises staff",
    "E05 Administrative and clerical staff": "E05 Administrative and clerical staff",
    "E06 Catering staff": "E06 Catering staff",
    "E07 Cost of other staff": "E07 Other staff",
    "E08 Indirect employee expenses": "E08 Indirect employee expenses",
    "E09 Development and training": "E09 Staff development and training",
    "E10 Supply teacher insurance": "E10 Supply teacher insurance",
    "E11 Staff related insurance": "E11 Staff-related insurance",
    "E12 Building maintenance and improvement": "E12 Building maintenance and improvement",
    "E13 Grounds maintenance and improvement": "E13 Grounds maintenance and improvement",
    "E14 Cleaning and caretaking": "E14 Cleaning and caretaking",
    "E15 Water and sewerage": "E15 Water and sewerage",
    "E16 Energy": "E16 Energy",
    "E17 Rates": "E17 Rates",
    "E18 Other occupation costs": "E18 Other occupation costs",
    "E19 Learning resources (not ICT equipment)": "E19 Learning resources (not ICT equipment)",
    "E20A Connectivity": "E20A Connectivity",
    "E20B Onsite servers": "E20B Onsite servers",
    "E20C IT learning resources": "E20C IT learning resources",
    "E20D Administration software and systems": "E20D Administration software and systems",
    "E20E Laptops, desktops and tablets": "E20E Laptops, desktops and tablets",
    "E20F Other hardware": "E20F Other hardware",
    "E20G IT support": "E20G IT support",
    "E21 Exam fees": "E21 Examination fees",
    "E22 Administrative supplies": "E22 Administrative supplies - non educational",
    "E23 Other insurance premiums": "E23 Other insurance premiums",
    "E24 Special facilities": "E24 Special facilities",
    "E25 Catering supplies": "E25 Catering supplies",
    "E26 Agency supply teaching staff": "E26 Agency supply teaching staff",
    "E27 Bought in professional services – curriculum": "E27 Educational Consultancy",
    "E28a Bought in professional services, other, not PFI": "E28a Bought in professional services, other, not PFI",
    "E28b Bought in professional services, other, PFI": "E28b Bought in professional services, other, PFI",
    "E28a/b Total bought in professional services": "E28a/b Bought in professional services",
    "E29 Loan interest": "E29 Interest charges for Loan and Bank",
    "E30 Direct revenue financing (Revenue contributions to capital)": "E30 Direct revenue financing (Revenue contributions to capital)",
    "E31 Community focused school staff": "E31 Community focused school staff",
    "E32 Community focused school costs": "E32 Community focused school costs",
    "OB01 Opening pupil-focused revenue balance": "OB01 Opening pupil-focused revenue balance",
    "OB02 Opening community-focused revenue balance": "OB02 Opening community-focused revenue balance",
    "OB03 Opening capital balance": "OB03 Opening capital balance",
    "CI01 Capital income": "CI01 Capital income",
    "CI03 Voluntary or private income": "CI03 Voluntary or private income",
    "CI04 Direct revenue financing": "CI04 Direct revenue financing",
    "CE01 Acquisition of land and existing buildings": "CE01 Acquisition of land and existing buildings",
    "CE02 New construction, conversion and renovation": "CE02 New construction, conversion and renovation",
    "CE03 Vehicles, plant, equipment and machinery": "CE03 Vehicles, plant, equipment and machinery",
    "CE04A Connectivity": "CE04A Connectivity",
    "CE04B Onsite servers": "CE04B Onsite servers",
    "CE04C Administration software and systems": "CE04C Administration software and systems",
    "CE04D Laptops desktops and tablets": "CE04D Laptops desktops and tablets",
    "CE04E Other hardware": "CE04E Other hardware",
    "B01 Committed revenue balances": "B01 Committed revenue balances",
    "B02 Uncommitted revenue balances": "B02 Uncommitted revenue balances",
    "B03 Devolved formula capital balance": "B03 Devolved formula capital balance",
    "B05 Other capital balances": "B05 Other capital balances",
    "B06 Community-focused school revenue balances": "B06 Community-focused school revenue balances",
    "B07 Outstanding balance on capital loans to school": "B07 Outstanding balance on capital loans to school",
    "Revenue Reserve: B01 + B02 + B06": "Revenue Reserve: B01 + B02 + B06",
    "In-year Balance: Total Income (I01:I18 - E30) - Total Expenditure (E01:E29 + E31 + E32)": "In-year Balance",
    "Grant Funding: (I01:I07) + I15 + I16 + I18a/b/c/d": "Grant Funding: (I01:I07) + I15 + I16 + I18a/b/c/d",
    "Direct Grants: I01:I02 + I06:I07": "Direct Grants: I01:I02 + I06:I07",
    "Community Grants: I16+I18": "Community Grants: I16+I18",
    "Targetted Grants: I03:I05 + I15": "Targetted Grants: I03:I05 + I15",
    "Self Generated Funding: (I08a/b:I13) + I17": "Self Generated Funding: (I08a/b:I13) + I17",
    "Total Income: I01:I18 - E30": "Total income",
    "Teaching Staff E01": "Teaching Staff: E01",
    "Supply Staff: E02 + E10 + E26": "Supply Staff: E02 + E10 + E26",
    "Education support staff: E03": "Education support staff: E03",
    "Other Staff Costs: (E07:E09) + E11": "Other Staff Costs: (E07:E09) + E11",
    "Staff Total: (E01:E03) + E05 + (E07: E11) + E26": "Staff Total: (E01:E03) + E05 + (E07: E11) + E26",
    "Maintenance & Improvement: E12 + E13": "Maintenance & Improvement: E12 + E13",
    "Premises: (E12:E14) + E04 + E28b": "Premises: (E12:E14) + E04 + E28b",
    "Catering Expenses: E06 + E25": "Catering Expenses: E06 + E25",
    "Occupation: E06 + (E15:E18) + E23 + E25": "Occupation: E06 + (E15:E18) + E23 + E25",
    "Supplies and Services: (E19:E22) + (E27:E28b)": "Supplies and Services: (E19:E22) + (E27:E28b)",
    "Educational Supplies: (E19:E21)": "Educational Supplies: (E19:E21)",
    "Brought in Professional Services: (E27 + E28a)": "Brought in Professional Sevices: (E27 + E28a)",
    "Community Exp: E31 + E32": "Community Exp: E31 + E32",
    "Total Expenditure: (E01:E29 + E31 + E32)": "Total Expenditure excluding E30",
}

_download_file_2026_mappings = _download_file_base_mappings.copy()
_download_file_2026_mappings.pop(
    "I18c Income from the £1bn COVID-19 catch-up package announced on 20 July 2020",
    None,
)
_download_file_2026_mappings.pop("I18d Income from other additional grants", None)
_download_file_2026_mappings.pop("I18 Total additional grant for schools", None)

download_file_mappings = {
    "default": _download_file_base_mappings,
    2026: _download_file_2026_mappings,
}
