rag_category_settings = {
    "Teaching and Teaching support staff": {
        "type": "Pupil",
        "outstanding_10": [
            "amber",
            "amber",
            "amber",
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "red",
            "red",
        ],
        "outstanding": [
            "amber",
            "amber",
            "amber",
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "amber",
            "red",
        ],
        "other_10": [
            "red",
            "red",
            "amber",
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "red",
            "red",
        ],
        "other": [
            "red",
            "amber",
            "amber",
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "amber",
            "red",
        ],
    },
    "Non-educational support staff and services": {
        "type": "Pupil",
        "outstanding_10": [
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "amber",
            "amber",
            "amber",
            "red",
            "red",
        ],
        "outstanding": [
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "amber",
            "amber",
            "amber",
            "red",
            "red",
        ],
        "other_10": [
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "amber",
            "amber",
            "amber",
            "red",
            "red",
        ],
        "other": [
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "amber",
            "amber",
            "amber",
            "red",
            "red",
        ],
    },
    "Educational supplies": {
        "type": "Pupil",
        "outstanding_10": [
            "amber",
            "amber",
            "amber",
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "red",
            "red",
        ],
        "outstanding": [
            "amber",
            "amber",
            "amber",
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "amber",
            "red",
        ],
        "other_10": [
            "red",
            "red",
            "amber",
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "red",
            "red",
        ],
        "other": [
            "red",
            "amber",
            "amber",
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "amber",
            "red",
        ],
    },
    "Educational ICT": {
        "type": "Pupil",
        "outstanding_10": [
            "amber",
            "amber",
            "amber",
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "red",
            "red",
        ],
        "outstanding": [
            "amber",
            "amber",
            "amber",
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "amber",
            "red",
        ],
        "other_10": [
            "red",
            "red",
            "amber",
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "red",
            "red",
        ],
        "other": [
            "red",
            "amber",
            "amber",
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "amber",
            "red",
        ],
    },
    "Premises staff and services": {
        "type": "Building",
        "outstanding_10": [
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "amber",
            "amber",
            "amber",
            "red",
            "red",
        ],
        "outstanding": [
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "amber",
            "amber",
            "amber",
            "red",
            "red",
        ],
        "other_10": [
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "amber",
            "amber",
            "amber",
            "red",
            "red",
        ],
        "other": [
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "amber",
            "amber",
            "amber",
            "red",
            "red",
        ],
    },
    "Utilities": {
        "type": "Building",
        "outstanding_10": [
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "amber",
            "amber",
            "amber",
            "red",
            "red",
        ],
        "outstanding": [
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "amber",
            "amber",
            "amber",
            "red",
            "red",
        ],
        "other_10": [
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "amber",
            "amber",
            "amber",
            "red",
            "red",
        ],
        "other": [
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "amber",
            "amber",
            "amber",
            "red",
            "red",
        ],
    },
    "Administrative supplies": {
        "type": "Pupil",
        "outstanding_10": [
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "amber",
            "amber",
            "amber",
            "red",
            "red",
        ],
        "outstanding": [
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "amber",
            "amber",
            "amber",
            "red",
            "red",
        ],
        "other_10": [
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "amber",
            "amber",
            "amber",
            "red",
            "red",
        ],
        "other": [
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "amber",
            "amber",
            "amber",
            "red",
            "red",
        ],
    },
    "Catering staff and supplies": {
        "type": "Pupil",
        "outstanding_10": [
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "amber",
            "amber",
            "amber",
            "red",
            "red",
        ],
        "outstanding": [
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "amber",
            "amber",
            "amber",
            "red",
            "red",
        ],
        "other_10": [
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "amber",
            "amber",
            "amber",
            "red",
            "red",
        ],
        "other": [
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "amber",
            "amber",
            "amber",
            "red",
            "red",
        ],
    },
    "Other costs": {
        "type": "Pupil",
        "outstanding_10": [
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "amber",
            "amber",
            "amber",
            "red",
            "red",
        ],
        "outstanding": [
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "amber",
            "amber",
            "amber",
            "red",
            "red",
        ],
        "other_10": [
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "amber",
            "amber",
            "amber",
            "red",
            "red",
        ],
        "other": [
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "amber",
            "amber",
            "amber",
            "red",
            "red",
        ],
    },
}