income_category_map = {
    "academies": {
        "DFE/EFA Revenue grants (includes Coronavirus Government Funding": "Income_Other DFE grants",
        "SEN funding": "Income_SEN funding",
        "Other DfE/EFA Revenue Grants": "Income_Pre Post 16",
        "Other income - LA & other Government grants": "Income_Other grants",
        "Academies": "Income_Academies",
        "Non-Government": "Income_Non government",
        "Government source, non-grant": "Income_Government source",
        "All income from facilities and services": "Income_Facilities and services",
        "Income from catering": "Income_Catering services",
        "Receipts from supply teacher insurance claims": "Income_Receipts supply teacher insurance",
        "Donations and/or voluntary funds": "Income_Donations and voluntary funds",
        "Other self-generated income": "Income_Other self-generated income",
        "Investment income": "Income_Investment income",
        "Direct Grants": "Income_Direct grants",
        "Community Grants": "Income_Other Revenue Income",
        "Total Grant Funding": "Income_Total grant funding",
        "Total Self Generated Funding": "Income_Total self generated funding",
        "Total Income": "Income_Total",
        "Revenue reserve": "Revenue reserve",
    },
    "central_services": {
        "DFE/EFA Revenue grants (includes Coronavirus Government Funding": "Income_Other DFE grants",
        "SEN": "Income_SEN funding",
        "Other DfE/EFA Revenue Grants": "Income_Pre Post 16",
        "Other income (LA & other Government grants)": "Income_Other grants",
        "Government source (non-grant)": "Income_Government source",
        "Academies": "Income_Academies",
        "Non- Government": "Income_Non government",
        "Income from facilities and services": "Income_Facilities and services",
        "Income from catering": "Income_Catering services",
        "Receipts from supply teacher insurance claims": "Income_Receipts supply teacher insurance",
        "Donations and/or voluntary funds": "Income_Donations and voluntary funds",
        "Other self-generated income": "Income_Other self-generated income",
        "Investment income": "Income_Investment income",
        "Direct Grant": "Income_Direct grants",
        "Community Grants": "Income_Other Revenue Income",
        "Grant Funding": "Income_Total grant funding",
        "Self Generated Funding": "Income_Total self generated funding",
        "Total Income ": "Income_Total",
        "Revenue Reserve": "Revenue reserve",
    },
    "maintained_schools": {
        # "I01  Funds delegated by the LA": "",
        # "I02  Funding for 6th form students": "",
        "I03  SEN funding": "Income_SEN funding",
        # "I04  Funding for minority ethnic pupils": "",
        # "I05  Pupil Premium": "",
        "I06  Other government grants": "Income_Other DFE grants",
        "I07  Other grants and payments": "Income_Other grants",
        "I08  Income from facilities and services": "Income_Facilities and services",
        "I09  Income from catering": "Income_Catering services",
        "I10  Receipts from supply teacher insurance claims": "Income_Receipts supply teacher insurance",
        # "I11  Receipts from other insurance claims": "",
        # "I12  Income from contributions to visits etc ": "",
        "I13  Donations and or private funds": "Income_Donations and voluntary funds",
        # "I16  Community focussed school funding and   or grants": "Income_Community grants",
        # "I17  Community focused school facilities income": "",
        # "I18  Additional grant for schools": "Income_Other grants",
        "Total Income   I01 to I18": "Income_Total",
        "Revenue Reserve   B01 plus B02 plus B06": "Revenue reserve",
        "Direct Grant": "Income_Direct grants",
        "Targeted Grants": "Income_Targeted grants",
        "Self Generated Funding": "Income_Total self generated funding",
        "Community Grants": "Income_Other Revenue Income",
    },
}

cost_category_map = {
    "academies": {
        "Teaching staff": "Teaching and Teaching support staff_Teaching staff",
        "Supply teaching staff": "Teaching and Teaching support staff_Supply teaching staff",
        "Education support staff": "Teaching and Teaching support staff_Education support staff",
        "Administrative and clerical staff": "Non-educational support staff and services_Administrative and clerical staff",
        "Premises staff": "Premises staff and services_Premises staff",
        "Catering staff": "Catering staff and supplies_Catering staff",
        "Other staff": "Non-educational support staff and services_Other staff",
        "Indirect employee expenses": "Other costs_Indirect employee expenses",
        "Staff development and training": "Other costs_Staff development and training",
        "Staff-related insurance": "Other costs_Staff-related insurance",
        "Supply teacher insurance": "Other costs_Supply teacher insurance",
        "Building and Grounds maintenance and improvement": "Premises staff and services_Maintenance of premises",
        "Cleaning and caretaking": "Premises staff and services_Cleaning and caretaking",
        "Water and sewerage": "Utilities_Water and sewerage",
        "Energy": "Utilities_Energy",
        "Rent and Rates": "Other costs_Rent and rates",
        "Other occupation costs": "Premises staff and services_Other occupation costs",
        "Special facilities": "Other costs_Special facilities",
        "Learning resources (not ICT equipment)": "Educational supplies_Learning resources (not ICT equipment)",
        "ICT learning resources": "Educational ICT_ICT learning resources",
        "Examination fees": "Educational supplies_Examination fees",
        "Educational Consultancy": "Teaching and Teaching support staff_Educational consultancy",
        "Administrative supplies - non educational": "Administrative supplies_Administrative supplies (non educational)",
        "Agency supply teaching staff": "Teaching and Teaching support staff_Agency supply teaching staff",
        "Catering supplies": "Catering staff and supplies_Catering supplies",
        "Other insurance premiums": "Other costs_Other insurance premiums",
        "Legal & Professionalservices": "Non-educational support staff and services_Professional services (non-curriculum)",
        "Auditor costs": "Non-educational support staff and services_Audit cost",
        "Interest charges for Loan and Bank": "Other costs_Interest charges for loan and bank",
        "Direct revenue financing - Revenue contributions to capital": "Other costs_Direct revenue financing",
        "PFI Charges": "Other costs_PFI charges",
    },
    "central_services": {
        "Teaching staff": "Teaching and Teaching support staff_Teaching staff",
        "Supply teaching staff": "Teaching and Teaching support staff_Supply teaching staff",
        "Education support staff": "Teaching and Teaching support staff_Education support staff",
        "Administrative and clerical staff": "Non-educational support staff and services_Administrative and clerical staff",
        "Premises staff": "Premises staff and services_Premises staff",
        "Catering staff": "Catering staff and supplies_Catering staff",
        "Other staff": "Non-educational support staff and services_Other staff",
        "Indirect employee expenses": "Other costs_Indirect employee expenses",
        "Staff development and training": "Other costs_Staff development and training",
        "Staff-related insurance": "Other costs_Staff-related insurance",
        "Supply teacher insurance": "Other costs_Supply teacher insurance",
        "Building and Grounds maintenance and improvement": "Premises staff and services_Maintenance of premises",
        "Cleaning and caretaking": "Premises staff and services_Cleaning and caretaking",
        "Water and sewerage": "Utilities_Water and sewerage",
        "Energy": "Utilities_Energy",
        "Rent and Rates": "Other costs_Rent and rates",
        "Other occupation costs": "Premises staff and services_Other occupation costs",
        "Special facilities": "Other costs_Special facilities",
        "Learning resources (not ICT equipment)": "Educational supplies_Learning resources (not ICT equipment)",
        "ICT learning resources": "Educational ICT_ICT learning resources",
        "Examination fees": "Educational supplies_Examination fees",
        "Educational Consultancy": "Teaching and Teaching support staff_Educational consultancy",
        "Administrative supplies - non educational": "Administrative supplies_Administrative supplies (non educational)",
        "Agency supply teaching staff": "Teaching and Teaching support staff_Agency supply teaching staff",
        "Catering supplies": "Catering staff and supplies_Catering supplies",
        "Other insurance premiums": "Other costs_Other insurance premiums",
        "Legal & Professional": "Non-educational support staff and services_Professional services (non-curriculum)",
        "Auditor costs": "Non-educational support staff and services_Audit cost",
        "Interest charges for Loan and Bank": "Other costs_Interest charges for loan and bank",
        "Direct revenue financing (Revenue contributions to capital)": "Other costs_Direct revenue financing",
        "PFI Charges": "Other costs_PFI charges",
    },
    "maintained_schools": {
        "LA (code)": "LA Code",
        "LA (name)": "LA Name",
        "E22 Administrative supplies": "Administrative supplies_Administrative supplies (non educational)",
        "E06 Catering staff": "Catering staff and supplies_Catering staff",
        "E25  Catering supplies": "Catering staff and supplies_Catering supplies",
        "E21  Exam fees": "Educational supplies_Examination fees",
        "E19  Learning resources (not ICT equipment)": "Educational supplies_Learning resources (not ICT equipment)",
        "E20  ICT learning resources": "Educational ICT_ICT learning resources",
        "E05 Administrative and clerical staff": "Non-educational support staff and services_Administrative and clerical staff",
        # '':'Non-educational support staff and services_Auditor costs',
        "E07  Cost of other staff": "Non-educational support staff and services_Other staff",
        "E28a  Bought in professional services - other (except PFI)": "Non-educational support staff and services_Professional services (non-curriculum)",
        "E30 Direct revenue financing (revenue contributions to capital)": "Other costs_Direct revenue financing",
        "E13  Grounds maintenance and improvement": "Other costs_Grounds maintenance",
        "E08  Indirect employee expenses": "Other costs_Indirect employee expenses",
        "E29  Loan interest": "Other costs_Interest charges for loan and bank",
        "E23  Other insurance premiums": "Other costs_Other insurance premiums",
        "E28b Bought in professional services - other (PFI)": "Other costs_PFI charges",
        "E17  Rates": "Other costs_Rent and rates",
        "E24  Special facilities ": "Other costs_Special facilities",
        "E09  Development and training": "Other costs_Staff development and training",
        "E11  Staff related insurance": "Other costs_Staff-related insurance",
        "E10  Supply teacher insurance": "Other costs_Supply teacher insurance",
        "E14  Cleaning and caretaking": "Premises staff and services_Cleaning and caretaking",
        "E12  Building maintenance and improvement": "Premises staff and services_Maintenance of premises",
        "E18  Other occupation costs": "Premises staff and services_Other occupation costs",
        "E04  Premises staff": "Premises staff and services_Premises staff",
        "E26 Agency supply teaching staff": "Teaching and Teaching support staff_Agency supply teaching staff",
        "E03 Education support staff": "Teaching and Teaching support staff_Education support staff",
        "E27  Bought in professional services - curriculum": "Teaching and Teaching support staff_Educational consultancy",
        "E02  Supply teaching staff": "Teaching and Teaching support staff_Supply teaching staff",
        "E01  Teaching Staff": "Teaching and Teaching support staff_Teaching staff",
        "E16  Energy": "Utilities_Energy",
        "E15  Water and sewerage": "Utilities_Water and sewerage",
        "PFI": "Is PFI School",
        "Total Expenditure  E01 to E32": "Total Expenditure",
        "E31  Community focused school staff": "Other costs_School staff",
        "E32 Community focused school costs": "Other costs_School costs",
    },
}

rag_category_settings = {
    "Teaching and Teaching support staff": {
        "type": "Pupil",
        "outstanding_10": [
            "amber",
            "amber",
            "amber",
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "red",
            "red",
        ],
        "outstanding": [
            "amber",
            "amber",
            "amber",
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "amber",
            "red",
        ],
        "other_10": [
            "red",
            "red",
            "amber",
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "red",
            "red",
        ],
        "other": [
            "red",
            "amber",
            "amber",
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "amber",
            "red",
        ],
    },
    "Non-educational support staff and services": {
        "type": "Pupil",
        "outstanding_10": [
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "amber",
            "amber",
            "amber",
            "red",
            "red",
        ],
        "outstanding": [
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "amber",
            "amber",
            "amber",
            "red",
            "red",
        ],
        "other_10": [
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "amber",
            "amber",
            "amber",
            "red",
            "red",
        ],
        "other": [
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "amber",
            "amber",
            "amber",
            "red",
            "red",
        ],
    },
    "Educational supplies": {
        "type": "Pupil",
        "outstanding_10": [
            "amber",
            "amber",
            "amber",
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "red",
            "red",
        ],
        "outstanding": [
            "amber",
            "amber",
            "amber",
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "amber",
            "red",
        ],
        "other_10": [
            "red",
            "red",
            "amber",
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "red",
            "red",
        ],
        "other": [
            "red",
            "amber",
            "amber",
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "amber",
            "red",
        ],
    },
    "Educational ICT": {
        "type": "Pupil",
        "outstanding_10": [
            "amber",
            "amber",
            "amber",
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "red",
            "red",
        ],
        "outstanding": [
            "amber",
            "amber",
            "amber",
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "amber",
            "red",
        ],
        "other_10": [
            "red",
            "red",
            "amber",
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "red",
            "red",
        ],
        "other": [
            "red",
            "amber",
            "amber",
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "amber",
            "red",
        ],
    },
    "Premises staff and services": {
        "type": "Building",
        "outstanding_10": [
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "amber",
            "amber",
            "amber",
            "red",
            "red",
        ],
        "outstanding": [
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "amber",
            "amber",
            "amber",
            "red",
            "red",
        ],
        "other_10": [
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "amber",
            "amber",
            "amber",
            "red",
            "red",
        ],
        "other": [
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "amber",
            "amber",
            "amber",
            "red",
            "red",
        ],
    },
    "Utilities": {
        "type": "Building",
        "outstanding_10": [
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "amber",
            "amber",
            "amber",
            "red",
            "red",
        ],
        "outstanding": [
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "amber",
            "amber",
            "amber",
            "red",
            "red",
        ],
        "other_10": [
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "amber",
            "amber",
            "amber",
            "red",
            "red",
        ],
        "other": [
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "amber",
            "amber",
            "amber",
            "red",
            "red",
        ],
    },
    "Administrative supplies": {
        "sub_categories": {"Energy", "Water and sewerage"},
        "type": "Pupil",
        "outstanding_10": [
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "amber",
            "amber",
            "amber",
            "red",
            "red",
        ],
        "outstanding": [
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "amber",
            "amber",
            "amber",
            "red",
            "red",
        ],
        "other_10": [
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "amber",
            "amber",
            "amber",
            "red",
            "red",
        ],
        "other": [
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "amber",
            "amber",
            "amber",
            "red",
            "red",
        ],
    },
    "Catering staff and supplies": {
        "sub_categories": {"Energy", "Water and sewerage"},
        "type": "Pupil",
        "outstanding_10": [
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "amber",
            "amber",
            "amber",
            "red",
            "red",
        ],
        "outstanding": [
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "amber",
            "amber",
            "amber",
            "red",
            "red",
        ],
        "other_10": [
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "amber",
            "amber",
            "amber",
            "red",
            "red",
        ],
        "other": [
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "amber",
            "amber",
            "amber",
            "red",
            "red",
        ],
    },
    "Other costs": {
        "type": "Pupil",
        "outstanding_10": [
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "amber",
            "amber",
            "amber",
            "red",
            "red",
        ],
        "outstanding": [
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "amber",
            "amber",
            "amber",
            "red",
            "red",
        ],
        "other_10": [
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "amber",
            "amber",
            "amber",
            "red",
            "red",
        ],
        "other": [
            "green",
            "green",
            "green",
            "amber",
            "amber",
            "amber",
            "amber",
            "amber",
            "red",
            "red",
        ],
    },
}
