academies_output = [
    "of which: Coronavirus Government Funding",
    "number of pupils whose first language is known or believed to be other than English",
    "Water and sewerage",
    #"Valid to",
    #"Valid From",
    "UrbanRural (name)",
    "URN",
    "UKPRN",
    "TypeOfEstablishment (name)",
    "TypeOfEstablishment (code)",
    "Type of Provision - Phase",
    #"Trust Type",
    "Trust Financial Position",
    "Trust Balance",
    "Total pupils",
    "Total Staff Costs",
    "Total Self Generated Funding",
    "Total School Workforce (Headcount)",
    "Total School Workforce (Full-Time Equivalent)",
    "Total Number of Teaching Assistants (Headcount)",
    "Total Number of Teaching Assistants (Full-Time Equivalent)",
    "Total Number of Teachers in the Leadership Group (Headcount)",
    "Total Number of Teachers in the Leadership Group (Full-time Equivalent)",
    "Total Number of Teachers (Headcount)",
    "Total Number of Teachers (Full-Time Equivalent)",
    "Total Number of Auxiliary Staff (Headcount)",
    "Total Number of Auxiliary Staff (Full-Time Equivalent)",
    "Total Internal Floor Area",
    "Total Income",
    "Total Grant Funding",
    "Total Expenditure",
    "Total Costs of Supplies and Services",
    "Total Costs of Educational Supplies",
    "Territory",
    "TelephoneNum",
    "Teaching staff",
    "Teachers with Qualified Teacher Status (%) (Headcount)",
    "Targeted Grants",
    "Supply teaching staff",
    "Supply teacher insurance",
    "Supply Staff Costs",
    "Statutory Low Age",
    "Status",
    "Staff-related insurance",
    "Staff development and training",
    "Special facilities",
    '"Share of Revenue Reserve, distributed on per pupil basis\n"',
    "SchoolWebsite",
    #"SchoolPhaseType",
    "SchoolCapacity",
    "SEN funding",
    "Revenue reserve",
    "Rent and Rates",
    "Regional School Commissioner",
    "Receipts from supply teacher insurance claims",
    "Pupil: Teacher Ratio (Full-Time Equivalent of qualified and unqualified teachers)",
    "Prov_VI",
    "Prov_SPLD",
    "Prov_SLD",
    "Prov_SLCN",
    "Prov_SEMH",
    "Prov_PMLD",
    "Prov_PD",
    "Prov_OTH",
    "Prov_MSI",
    "Prov_MLD",
    "Prov_HI",
    "Prov_ASD",
    "Progress8Measure",
    "Progress8Banding",
    "Primary Need VI",
    "Primary Need SPLD",
    "Primary Need SLD",
    "Primary Need SLCN",
    "Primary Need SEMH",
    "Primary Need PMLD",
    "Primary Need PD",
    "Primary Need OTH",
    "Primary Need MSI",
    "Primary Need MLD",
    "Primary Need HI",
    "Primary Need ASD",
    #"PreviousLA (name)",
    #"PreviousLA (code)",
    #"PreviousEstablishmentNumber",
    "Premises staff",
    "Premises Costs",
    "Postcode",
    #"PhaseOfEducation (name)",
    #"PhaseOfEducation (code)",
    "Percentage SEN",
    "Percentage Free school meals",
    "PFI School",
    "PFI Charges",
    "Other staff",
    "Other self-generated income",
    "Other occupation costs",
    "Other insurance premiums",
    "Other income - LA & other Government grants",
    "Other Staff Costs",
    "Other DfE/EFA Revenue Grants",
    #"OpenDate",
    "OfstedRating (name)",
    "OfstedLastInsp",
    "OfficialSixthForm (name)",
    #"OfficialSixthForm (code)",
    "Occupation Costs",
    "NurseryProvision (name)",
    #"NumberOfPupils",
    #"NumberOfGirls",
    #"NumberOfBoys",
    #"Number of pupils",
    "Number of Vacant Teacher Posts",
    "Number of Academies in Trust",
    "Non-Government",
    "Maintenance & Improvement Costs",
    "MSOA (code)",
    "Legal & Professionalservices",
    "Learning resources (not ICT equipment)",
    "LastChangedDate",
    "LSOA (code)",
    "LA Name",
    "LA Establishment Number",
    "LA (name)",
    "LA (code)",
    "Ks2Progress",
    "Investment income",
    "Interest charges for Loan and Bank",
    "Indirect employee expenses",
    #"Incorporation Date",
    "Income from catering",
    "ICT learning resources",
    #"HeadTitle (name)",
    #"HeadPreferredJobTitle",
    "HeadName",
    #"HeadLastName",
    #"HeadFirstName",
    '"Government source, non-grant"',
    "Gender (name)",
    "Gender (code)",
    "GOR (name)",
    "FullTimeOtherHeadCount",
    "FullTimeOther",
    "Examination fees",
    "EstablishmentStatus (name)",
    "EstablishmentStatus (code)",
    "EstablishmentNumber",
    "EstablishmentName",
    "Energy",
    "Educational Consultancy",
    "Education support staff",
    "EHC plan",
    "Donations and/or voluntary funds",
    "Direct revenue financing - Revenue contributions to capital",
    "Direct Grants",
    #"Date left or closed if in period",
    #"Date joined or opened if in period",
    #"Date Opened",
    "DFE/EFA Revenue grants (includes Coronavirus Government Funding",
    "Costs of Brought in Professional Services",
    "Company Registration Number",
    "Community Grants",
    "CloseDate",
    "Cleaning and caretaking",
    "Central Services Financial Position",
    "Central Services Balance",
    #"CensusDate",
    "Catering supplies",
    "Catering staff",
    "Catering Expenses",
    "Building and Grounds maintenance and improvement",
    #"BoardingEstablishment (name)",
    "Boarders (name)",
    #"Boarders (code)",
    "AverageAttainment",
    "Auditor costs",
    "All income from facilities and services",
    "Agency supply teaching staff",
    "Age Average Score",
    #"AdmissionsPolicy (name)",
    #"AdmissionsPolicy (code)",
    "Administrative supplies - non educational",
    "Administrative and clerical staff",
    "Academy UPIN",
    "Academy UKPRN",
    "Academy Trust UPIN",
    "Academy Trust Status",
    "Academy Trust Name",
    "Academy Status",
    #"Academy Name",
    "Academy Financial Position",
    "Academy Balance_y",
    "Academy Balance_x",
    "Academies",
    "% of pupils known to be eligible for and claiming free school me",
]

maintained_schools = [
    "number of pupils whose first language is known or believed to be other than English",
    "Utilities_Water and sewerage:",
    "Utilities_Energy",
    "UrbanRural (name)",
    #"Urban  Rural",
    "URN",
    "UKPRN",
    #"TypeOfEstablishment (name)",
    #"TypeOfEstablishment (code)",
    "Type",
    "Total pupils",
    "Total School Workforce (Headcount)",
    "Total School Workforce (Full-Time Equivalent)",
    "Total Number of Teaching Assistants (Headcount)",
    "Total Number of Teaching Assistants (Full-Time Equivalent)",
    "Total Number of Teachers in the Leadership Group (Headcount)",
    "Total Number of Teachers in the Leadership Group (Full-time Equivalent)",
    "Total Number of Teachers (Headcount)",
    "Total Number of Teachers (Full-Time Equivalent)",
    "Total Number of Auxiliary Staff (Headcount)",
    "Total Number of Auxiliary Staff (Full-Time Equivalent)",
    "Total Internal Floor Area",
    "Total Income   I01 to I18",
    '"Total Income   I01 to I08, I11 to I15, I18"',
    "Total Expenditure  E01 to E32",
    '"Total Expenditure  E01 to E29 and E31 to E32 minus I9, I10, I16 and I17"',
    "TelephoneNum",
    "Teaching and Teaching support staff_Teaching staff",
    "Teaching and Teaching support staff_Supply teaching staff",
    "Teaching and Teaching support staff_Educational consultancy",
    "Teaching and Teaching support staff_Education support staff",
    "Teaching and Teaching support staff_Agency supply teaching staff",
    "Teachers with Qualified Teacher Status (%) (Headcount)",
    "Statutory Low Age",
    "Status",
    "SchoolWebsite",
    "SchoolPhaseType",
    "SchoolCapacity",
    "School Financial Position",
    "School Balance",
    "Revenue Reserve   B01 plus B02 plus B06",
    "Pupil: Teacher Ratio (Full-Time Equivalent of qualified and unqualified teachers)",
    "Prov_VI",
    "Prov_SPLD",
    "Prov_SLD",
    "Prov_SLCN",
    "Prov_SEMH",
    "Prov_PMLD",
    "Prov_PD",
    "Prov_OTH",
    "Prov_MSI",
    "Prov_MLD",
    "Prov_HI",
    "Prov_ASD",
    "Progress8Measure",
    "Progress8Banding",
    "Primary Need VI",
    "Primary Need SPLD",
    "Primary Need SLD",
    "Primary Need SLCN",
    "Primary Need SEMH",
    "Primary Need PMLD",
    "Primary Need PD",
    "Primary Need OTH",
    "Primary Need MSI",
    "Primary Need MLD",
    "Primary Need HI",
    "Primary Need ASD",
    #"PreviousLA (name)",
    #"PreviousLA (code)",
    #"PreviousEstablishmentNumber",
    "Premises_Premises staff",
    "Premises_Other occupation costs",
    "Premises_Maintenance of premises",
    "Premises_Cleaning and caretaking",
    "Postcode",
    #"PhaseOfEducation (name)",
    #"PhaseOfEducation (code)",
    #"Phase",
    #"Period covered by return (months)",
    "Percentage SEN",
    "Percentage Free school meals",
    #"Partial Years Present",
    "PFI School",
    "Overall Phase",
    "Other grants and payments",
    "Other costs_Supply teacher insurance",
    "Other costs_Staff-related insurance",
    "Other costs_Staff development and training",
    "Other costs_Special facilities",
    "Other costs_Rent and rates",
    "Other costs_PFI charges",
    "Other costs_Other insurance premiums",
    "Other costs_Interest charges for loan and bank",
    "Other costs_Indirect employee expenses",
    "Other costs_Grounds maintenance",
    "Other costs_Direct revenue financing",
    #"OpenDate",
    "OfstedRating (name)",
    "OfstedLastInsp",
    #"OfficialSixthForm (name)",
    "OfficialSixthForm (code)",
    "NurseryProvision (name)",
    #"NumberOfPupils",
    #"NumberOfGirls",
    #"NumberOfBoys",
    #"Number of pupils",
    "Number of Vacant Teacher Posts",
    "Non-educational support staff_Professional services (non-curriculum)",
    "Non-educational support staff_Other staff",
    "Non-educational support staff_Administrative and clerical staff",
    "No of pupils in 6th form",
    "No Teachers",
    "MSOA (code)",
    "Lowest age of pupils",
    "London Weighting",
    "Lead school in federation",
    "LastChangedDate",
    "LSOA (code)",
    #"LAEstab",
    "LA Establishment Number",
    "LA (name)",
    "LA (code)",
    "Ks2Progress",
    "In-year Balance   Total Income (I01 to I18) minus Total Expenditure (E01 to E32)",
    "IT_ICT learning resources",
    "I18  Additional grant for schools",
    "I17  Community focused school facilities income",
    "I16  Community focussed school funding and   or grants",
    "I15  Pupil focussed extended school funding and   or grants",
    "I13  Donations and or private funds",
    "I12  Income from contributions to visits etc",
    "I11  Receipts from other insurance claims",
    "I10  Receipts from supply teacher insurance claims",
    "I08  Income from facilities and services",
    "I06  Other government grants",
    "I05  Pupil Premium",
    "I04  Funding for minority ethnic pupils",
    "I03  SEN funding",
    "I02  Funding for 6th form students",
    "I01  Funds delegated by the LA",
    "Highest age of pupils",
    #"HeadTitle (name)",
    #"HeadPreferredJobTitle",
    "HeadName",
    #"HeadLastName",
    #"HeadFirstName",
    "Gender (name)",
    #"Gender (code)",
    "GOR (name)",
    "FullTimeOtherHeadCount",
    "FullTimeOther",
    #"Federation",
    "FTE of Teaching Assistants",
    "FTE of Support Staff",
    "FTE of Admin Staff",
    #"EstablishmentStatus (name)",
    #"EstablishmentStatus (code)",
    "EstablishmentNumber",
    "EstablishmentName",
    "Educational supplies_Learning resources (not ICT equipment)",
    "Educational supplies_Examination fees",
    "EHC plan",
    "E32 Community focused school costs",
    "E31  Community focused school staff",
    #"Did Not Supply flag",
    #"Did Not Submit",
    #"CloseDate",
    #"CensusDate",
    "Catering_Income from catering",
    "Catering_Catering supplies",
    "Catering_Catering staff",
    "BoardingEstablishment (name)",
    "Boarders (name)",
    #"Boarders (code)",
    "AverageAttainment",
    "Age Average Score",
    "AdmissionsPolicy (name)",
    "AdmissionsPolicy (code)",
    "Administrative supplies_Administrative supplies (non educational)",
    "% of teachers with QTS",
    "% of pupils with EAL",
    "% of pupils who are Boarders",
    "% of pupils known to be eligible for free school meals (Performa",
    "% of pupils known to be eligible for and claiming free school me",
]
