academies_output = [
    "number of pupils whose first language is known or believed to be other than English",
    "Utilities_Water and sewerage",
    "UrbanRural (name)",
    "UKPRN",
    "Overall Phase",
    "Trust Financial Position",
    "Trust Balance",
    "Total pupils",
    "Total Staff Costs",
    "Total Self Generated Funding",
    "Total School Workforce (Headcount)",
    "Total School Workforce (Full-Time Equivalent)",
    "Total Number of Teaching Assistants (Headcount)",
    "Total Number of Teaching Assistants (Full-Time Equivalent)",
    "Total Number of Teachers in the Leadership Group (Headcount)",
    "Total Number of Teachers in the Leadership Group (Full-time Equivalent)",
    "Total Number of Teachers (Headcount)",
    "Total Number of Teachers (Full-Time Equivalent)",
    "Total Number of Auxiliary Staff (Headcount)",
    "Total Number of Auxiliary Staff (Full-Time Equivalent)",
    "Total Internal Floor Area",
    "Total Income",
    "Total Grant Funding",
    "Total Expenditure",
    "Total Costs of Supplies and Services",
    "Total Costs of Educational Supplies",
    "Telephone",
    "Teaching and Teaching support staff_Teaching staff",
    "Teachers with Qualified Teacher Status (%) (Headcount)",
    "Targeted Grants",
    "Teaching and Teaching support staff_Supply teaching staff",
    "Other costs_Supply teacher insurance",
    "Supply Staff Costs",
    "Status",
    "Other costs_Staff-related insurance",
    "Other costs_Staff development and training",
    "Other costs_Special facilities",
    "Website",
    "SchoolCapacity",
    "SEN funding",
    "StatutoryLowAge",
    "StatutoryHighAge",
    "Revenue reserve",
    "Other costs_Rent and rates",
    "Regional School Commissioner",
    "Receipts from supply teacher insurance claims",
    "Pupil: Teacher Ratio (Full-Time Equivalent of qualified and unqualified teachers)",
    "Prov_VI",
    "Prov_SPLD",
    "Prov_SLD",
    "Prov_SLCN",
    "Prov_SEMH",
    "Prov_PMLD",
    "Prov_PD",
    "Prov_OTH",
    "Prov_MSI",
    "Prov_MLD",
    "Prov_HI",
    "Prov_ASD",
 #   "Progress8Measure",
  #  "Progress8Banding",
    "Primary Need VI",
    "Primary Need SPLD",
    "Primary Need SLD",
    "Primary Need SLCN",
    "Primary Need SEMH",
    "Primary Need PMLD",
    "Primary Need PD",
    "Primary Need OTH",
    "Primary Need MSI",
    "Primary Need MLD",
    "Primary Need HI",
    "Primary Need ASD",
    "Premises staff and services_Premises staff",
    "Premises Costs",
    "Postcode",
    "Percentage SEN",
    "Percentage Free school meals",
    "Is PFI School",
    "Other costs_PFI charges",
    "Non-educational support staff and services_Other staff",
    "Other self-generated income",
    "Premises staff and services_Other occupation costs",
    "Other costs_Other insurance premiums",
    "Other income - LA & other Government grants",
    "Other Staff Costs",
    "Other DfE/EFA Revenue Grants",
    "Ofsted Rating Description",
    "Ofsted Inspection Date",
    "Occupation Costs",
    "Has a nursery",
    "Number of Vacant Teacher Posts",
    "Number of Academies in Trust",
    "Non-Government",
    "Maintenance & Improvement Costs",
    "Non-educational support staff and services_Professional services (non-curriculum)",
    "Educational supplies_Learning resources (not ICT equipment)",
    "LastChangedDate",
    "LA Establishment Number",
    "LA Name",
    "LA Code",
   # "Ks2Progress",
    "Investment income",
    "Other costs_Interest charges for loan and bank",
    "Other costs_Indirect employee expenses",
    "Income from catering",
    "Educational ICT_ICT learning resources",
    "Head Teacher Name",
    "Government source, non-grant",
    "Gender (name)",
    "GOR (name)",
    "FullTimeOtherHeadCount",
    "FullTimeOther",
    "Educational supplies_Examination fees",
    "EstablishmentNumber",
    "Establishment Name",
    "Establishment Type",
    "Utilities_Energy",
    "Teaching and Teaching support staff_Educational consultancy",
    "Teaching and Teaching support staff_Education support staff",
    "EHC plan",
    "Donations and/or voluntary funds",
    "Other costs_Direct revenue financing",
    "Direct Grants",
    "DFE/EFA Revenue grants (includes Coronavirus Government Funding",
    "Costs of Brought in Professional Services",
    "Company Registration Number",
    "Community Grants",
    "Premises staff and services_Cleaning and caretaking",
    "Central Services Financial Position",
    "Central Services Balance",
    "Catering staff and supplies_Catering supplies",
    "Catering staff and supplies_Catering staff",
    "Catering Expenses",
    "Premises staff and services_Maintenance of premises",
    "Boarders (name)",
  #  "AverageAttainment",
    "Non-educational support staff and services_Audit cost",
    "All income from facilities and services",
    "Teaching and Teaching support staff_Agency supply teaching staff",
    "Age Average Score",
    "Administrative supplies_Administrative supplies (non educational)",
    "Non-educational support staff and services_Administrative and clerical staff",
    "Academy UPIN",
    "Trust UKPRN",
    "Academy Trust UPIN",
    "Academy Trust Status",
    "Trust Name",
    "Academy Status",
    "Academy Financial Position",
    "Academy Balance_y",
    "Academy Balance_x",
    "Academies",
    "Has a sixth form",
    "Region",
    "Ward",
    "District",
]

maintained_schools_output = [
    "number of pupils whose first language is known or believed to be other than English",
    "Utilities_Water and sewerage",
    "Utilities_Energy",
    "UrbanRural (name)",
    "UKPRN",
    "Total pupils",
    "Total School Workforce (Headcount)",
    "Total School Workforce (Full-Time Equivalent)",
    "Total Number of Teaching Assistants (Headcount)",
    "Total Number of Teaching Assistants (Full-Time Equivalent)",
    "Total Number of Teachers in the Leadership Group (Headcount)",
    "Total Number of Teachers in the Leadership Group (Full-time Equivalent)",
    "Total Number of Teachers (Headcount)",
    "Total Number of Teachers (Full-Time Equivalent)",
    "Total Number of Auxiliary Staff (Headcount)",
    "Total Number of Auxiliary Staff (Full-Time Equivalent)",
    "Total Internal Floor Area",
    "Total Income",
    "Total Expenditure",
    "Telephone",
    "Teaching and Teaching support staff_Teaching staff",
    "Teaching and Teaching support staff_Supply teaching staff",
    "Teaching and Teaching support staff_Educational consultancy",
    "Teaching and Teaching support staff_Education support staff",
    "Teaching and Teaching support staff_Agency supply teaching staff",
    "Teachers with Qualified Teacher Status (%) (Headcount)",
    "StatutoryLowAge",
    "StatutoryHighAge",
    "Status",
    "Website",
    "SchoolPhaseType",
    "SchoolCapacity",
    "School Financial Position",
    "School Balance",
    "Revenue Reserve",
    "Pupil: Teacher Ratio (Full-Time Equivalent of qualified and unqualified teachers)",
    "Percentage SEN",
    "Primary Need SPLD",
    "Primary Need MLD",
    "Primary Need SLD",
    "Primary Need PMLD",
    "Primary Need SEMH",
    "Primary Need SLCN",
    "Primary Need HI",
    "Primary Need VI",
    "Primary Need MSI",
    "Primary Need PD",
    "Primary Need ASD",
    "Primary Need OTH",
    "Percentage Primary Need SPLD",
    "Percentage Primary Need MLD",
    "Percentage Primary Need SLD",
    "Percentage Primary Need PMLD",
    "Percentage Primary Need SEMH",
    "Percentage Primary Need SLCN",
    "Percentage Primary Need HI",
    "Percentage Primary Need VI",
    "Percentage Primary Need MSI",
    "Percentage Primary Need PD",
    "Percentage Primary Need ASD",
    "Percentage Primary Need OTH",
 #   "Progress8Measure",
  #  "Progress8Banding",
    "Primary Need VI",
    "Primary Need SPLD",
    "Primary Need SLD",
    "Primary Need SLCN",
    "Primary Need SEMH",
    "Primary Need PMLD",
    "Primary Need PD",
    "Primary Need OTH",
    "Primary Need MSI",
    "Primary Need MLD",
    "Primary Need HI",
    "Primary Need ASD",
    "Premises staff and services_Premises staff",
    "Premises staff and services_Other occupation costs",
    "Premises staff and services_Maintenance of premises",
    "Premises staff and services_Cleaning and caretaking",
    "Postcode",
    "Percentage SEN",
    "Percentage Free school meals",
    "Overall Phase",
    "Other grants and payments",
    "Other costs_Supply teacher insurance",
    "Other costs_Staff-related insurance",
    "Other costs_Staff development and training",
    "Other costs_Special facilities",
    "Other costs_Rent and rates",
    "Other costs_PFI charges",
    "Other costs_Other insurance premiums",
    "Other costs_Interest charges for loan and bank",
    "Other costs_Indirect employee expenses",
    "Other costs_Grounds maintenance",
    "Other costs_Direct revenue financing",
    "Ofsted Rating Description",
    "Ofsted Inspection Date",
    "Number of Vacant Teacher Posts",
    "Non-educational support staff and services_Professional services (non-curriculum)",
    "Non-educational support staff and services_Other staff",
    "Non-educational support staff and services_Administrative and clerical staff",
    "No of pupils in 6th form",
    "No Teachers",
    "MSOA (code)",
    "Lowest age of pupils",
    "London Weighting",
    "Lead school in federation",
    "LastChangedDate",
    "LSOA (code)",
    "LA Establishment Number",
  #  "Ks2Progress",
    "In-year Balance   Total Income (I01 to I18) minus Total Expenditure (E01 to E32)",
    "Educational ICT_ICT learning resources",
    "I18  Additional grant for schools",
    "I17  Community focused school facilities income",
    "I16  Community focussed school funding and   or grants",
    "I15  Pupil focussed extended school funding and   or grants",
    "Donations and/or voluntary funds",
    "I12  Income from contributions to visits etc",
    "I11  Receipts from other insurance claims",
    "Receipts from supply teacher insurance claims",
    "I08  Income from facilities and services",
    "I06  Other government grants",
    "I05  Pupil Premium",
    "I04  Funding for minority ethnic pupils",
    "SEN funding",
    "I02  Funding for 6th form students",
    "I01  Funds delegated by the LA",
    "Head Teacher Name",
    "Gender (name)",
    "GOR (name)",
    "FullTimeOtherHeadCount",
    "FullTimeOther",
    "FTE of Teaching Assistants",
    "FTE of Support Staff",
    "FTE of Admin Staff",
    "EstablishmentNumber",
    "Establishment Name",
    "Establishment Type",
    "Educational supplies_Learning resources (not ICT equipment)",
    "Educational supplies_Examination fees",
    "EHC plan",
    "E32 Community focused school costs",
    "E31  Community focused school staff",
    "Catering staff and supplies_Income from catering",
    "Catering staff and supplies_Catering supplies",
    "Catering staff and supplies_Catering staff",
    "BoardingEstablishment (name)",
    "Boarders (name)",
   # "AverageAttainment",
    "Age Average Score",
    "Administrative supplies_Administrative supplies (non educational)",
    "% of teachers with QTS",
    "% of pupils with EAL",
    "% of pupils who are Boarders",
    "Percentage Free school meals",
    "Percentage claiming Free school meals",
    "LA Name",
    "LA Code",
    "Has a nursery",
    "Has a sixth form",
    "Region",
    "Ward",
    "District",
    "Is PFI School",
]


schools_table_output = [
   "UKPRN",
  "Establishment Name",
  "Finance Type",
  "Overall Phase",
  # "Ofsted Rating",
  "Ofsted Rating Description",
  "Ofsted Inspection Date",
  "Establishment Type",
  "LA Code",
  "LA Name",
  "Street",
  "Locality",
  "Address 3",
  "Town",
  "County",
  "Postcode",
  "Telephone",
  "Website",
  #  "Contact Email",
  #  "Headteacher email",
  "Head Teacher Name",
  "Trust Name",
  "Trust UKPRN",
  "Federation Name",
  "Federation Lead School UKPRN",
  "Has a sixth form",
  "Has a nursery",
  "Is PFI School",
  "Region",
  "District",
  "Ward",
  "London Weighting"
]