# yaml-language-server: $schema=https://json.schemastore.org/pre-commit-config.json
repos:
  - repo: https://github.com/DFE-Digital/education-benchmarking-and-insights.git
    rev: 377a32d02773decea22439c7ddc4ca8da20a2c56
    hooks:
      - id: terraform-lint
