cs_transparency_file_cols = {
    "default": {
        "Company Registration Number": "Company Number",
        "trust_name": "Company Name",
        "%_pupils_FSM": "Percentage of pupils in trust eligible for FSM",
        "%_pupils_EHCP": "Percentage of pupils in trust with EHCP",
        "%_pupils_SEN": "Percentage of pupils in trust with SEN support",
        "%_pupils_EAL": "Percentage of pupils in trust with EAL",
        "%_pupils_boarders": "Percentage of pupils in trust who are boarders",
        "total_sixth_form": "Total number of sixth form pupils in trust",
        "total_teachers": "Total teachers in trust",
        "Income_Targeted grants": "SEN",
        "Income_Other DFE grants": "Other DfE/EFA Revenue Grants",
        "BNCH11101 (Start-up grants)": "Start-up grants",
        "Income_Other grants": "Other income (LA & other Government grants)",
        "Income_Government source": "Government source, non-grant",
        "Income_Academies": "Academies",
        "BNCH11163 (Non- Government)": "Non-Government",
        "BNCH11201 (Income from facilities and services)": "Income from rentals and lettings",
        "BNCH11205 (Other Income from facilities and services)": "Other Income from Facilities and Services",
        "Income_Catering services": "Income from catering",
        "Income_Receipts supply teacher insurance": "Receipts from supply teacher insurance claims",
        "Income_Other self-generated income": "Other self-generated income",
        "Income_Donations and voluntary funds": "Donations and/or voluntary funds",
        "Income_Investment income": "Investment income",
        "Teaching and Teaching support staff_Teaching staff": "Teaching staff",
        "Teaching and Teaching support staff_Supply teaching staff": "Supply teaching staff",
        "Teaching and Teaching support staff_Education support staff": "Education support staff",
        "Non-educational support staff and services_Administrative and clerical staff": "Administrative and clerical staff",
        "Premises staff and services_Premises staff": "Premises staff",
        "Catering staff and supplies_Catering staff": "Catering staff",
        "Non-educational support staff and services_Other staff": "Other staff",
        "Other costs_Indirect employee expenses": "Indirect employee expenses",
        "Other costs_Staff development and training": "Staff development and training",
        "Other costs_Supply teacher insurance": "Supply teacher insurance",
        "Other costs_Staff-related insurance": "Staff-related insurance",
        "Premises staff and services_Maintenance of premises": "Maintainance of Premises",
        "Premises staff and services_Cleaning and caretaking": "Cleaning and caretaking",
        "Utilities_Water and sewerage": "Water and sewerage",
        "Utilities_Energy": "Energy",
        "Other costs_Rent and rates": "Rent and Rates",
        "Other costs_Grounds maintenance": "Grounds Maintenance",
        "Premises staff and services_Other occupation costs": "Other occupation costs",
        "Other costs_Special facilities": "Special facilities",
        "Educational supplies_Learning resources (not ICT equipment)": "Learning resources (not ICT equipment)",
        "Educational ICT_ICT learning resources": "ICT learning resources",
        "Educational supplies_Examination fees": "Examination fees",
        "Teaching and Teaching support staff_Educational consultancy": "Educational Consultancy",
        "Teaching and Teaching support staff_Agency supply teaching staff": "Agency supply teaching staff",
        "Catering staff and supplies_Catering supplies": "Catering supplies",
        "Non-educational support staff and services_Audit cost": "Auditor costs",
        "Other costs_Other insurance premiums": "Other insurance premiums",
        "Administrative supplies_Administrative supplies (non educational)": "Administrative supplies - non educational",
        "Income_Direct revenue finance": "Direct revenue financing (Revenue contributions to capital)",
        "Non-educational support staff and services_Professional services (non-curriculum)": "Legal & Professional",
        "Other costs_PFI charges": "PFI Charges",
        "Other costs_Interest charges for loan and bank": "Interest charges for Loan and Bank",
        "Revenue reserve": "Revenue Reserve",
        "In year balance": "In Year Balance",
        "total_pupils": "Total number of Pupils",
        "total_prop_pupils": "Number of pupils at end of period based on time in trust",
        "Central Services Revenue Reserve per pupil at end of period based on time in trust": "Central Services RR per pupil",
        "sum_of_academy_rr": "Sum of Academy RR",
        "Revenue reserve_app": "Sum of Trust + Academy Revenue Reserve",
        "Income_Total grant funding": "Grant Funding",
        "Income_Direct grants": "Direct Grant",
        "Income_Other Revenue Income": "Community Grants",
        "Income_Total self generated funding": "Self Generated Funding",
        "Total Income": "Total Income",
        "Supply Staff": "Supply Staff",
        "Other Staff Costs": "Other Staff Costs",
        "Staff Total": "Staff Total",
        "Maintenance & Improvement": "Maintenance & Improvement",
        "Premises": "Premises",
        "Catering Exp": "Catering Exp",
        "Occupation": "Occupation",
        "Supplies and Services": "Supplies and Services",
        "Educational Supplies": "Educational Supplies",
        "Brought in Professional Services": "Bought in Professional Services",
        "Total Expenditure": "Total Expenditure",
    }
}

transparency_file_cols = {
    "default": {
        "LAEstab": "LAEstab",
        "LA Code": "LA",
        "Estab": "Estab",
        "URN": "URN",
        "Academy UPIN": "Academy UPIN",
        "EstablishmentName": "School Name",
        "Period covered by return": "Period covered by return",
        "Company Registration Number": "Company Number",
        "Trust Name": "Trust or Company Name",
        "OpenDate": "Date opened",
        "CloseDate": "Date closed",
        "Date left or closed if in period": "Date left or closed if in period",
        "Date joined or opened if in period": "Date joined or opened if in period",
        "Number of pupils": "Number of pupils in academy (FTE) plus dual subsidiary registrations",
        "Total Number of Teachers (Full-Time Equivalent)": "Number of teachers in academy (FTE)",
        "Gender (name)": "Gender",
        "Overall Phase": "Overall Phase",
        "PhaseOfEducation (name)": "Phase",
        "TypeOfEstablishment (name)": "Type",
        "UrbanRural (name)": "Urban/Rural",
        "GOR (name)": "Region",
        "London Borough": "London Borough",
        "London Weighting": "London Weighting",
        "Is PFI": "PFI",
        "Percentage Free school meals": "% of pupils eligible for FSM",
        "Percentage with EHC": "% of pupils with EHCP",
        "% of pupil with SEN support": "% of pupil with SEN support",
        "% of pupils whose first language is known or believed to be other than English": "% of pupils with English as an additional language",
        "% of pupils who are Boarders": "% of pupils who are Boarders",
        "Has Sixth Form": "Has a 6th form",
        "TotalPupilsSixthForm": "No of pupils in 6th form",
        "StatutoryLowAge": "Lowest age of pupils",
        "StatutoryHighAge": "Highest age of pupils",
        "BNCH11122 (Other)": "DFE Revenue grants",
        "BNCH11123-BAI011-A (Academies - Income)": "16 to 19 allocations",
        "BNCH11131 (DfE Family Revenue Grants)": "Other DfE Group grants (revenue)",
        "Income_Targeted grants": "SEN Funding",
        "Income_Other DFE grants": "Other DfE Revenue Grants",
        "BNCH11101 (Start-up grants)": "Grants for trust activity",
        "Income_Other grants": "Other income - LA & other Government grants",
        "Income_Government source": "Government source (non-grant)",
        "Income_Academies": "Academies",
        "BNCH11163 (Non- Government)": "Non-Government",
        "BNCH11201 (Income from facilities and services)": "Income from rentals and lettings",
        "BNCH11205 (Other Income from facilities and services)": "Income from facilities and services - other",
        "Income_Catering services": "Income from catering",
        "Income_Receipts supply teacher insurance": "Receipts from supply teacher insurance claims",
        "Income_Other self-generated income": "Other self-generated income",
        "Income_Donations and voluntary funds": "Donations and/or voluntary funds",
        "Income_Investment income": "Investment income",
        "Teaching and Teaching support staff_Teaching staff": "Teaching staff",
        "Teaching and Teaching support staff_Supply teaching staff": "Supply teaching staff",
        "Teaching and Teaching support staff_Education support staff": "Education support staff",
        "Non-educational support staff and services_Administrative and clerical staff": "Administrative and clerical staff",
        "Premises staff and services_Premises staff": "Premises staff",
        "Catering staff and supplies_Catering staff": "Catering staff",
        "Non-educational support staff and services_Other staff": "Other staff",
        "Other costs_Indirect employee expenses": "Indirect employee expenses",
        "Other costs_Staff development and training": "Staff development and training",
        "Other costs_Supply teacher insurance": "Supply teacher insurance",
        "Other costs_Staff-related insurance": "Staff-related insurance",
        "Premises staff and services_Maintenance of premises": "Maintenance of Premises",
        "Premises staff and services_Cleaning and caretaking": "Cleaning and caretaking",
        "Utilities_Water and sewerage": "Water and sewerage",
        "Utilities_Energy": "Energy",
        "Other costs_Rent and rates": "Rent and Rates",
        "Other costs_Grounds maintenance": "Grounds maintenance",
        "Premises staff and services_Other occupation costs": "Other occupation costs",
        "Other costs_Special facilities": "Special facilities",
        "Educational supplies_Learning resources (not ICT equipment)": "Learning resources (not ICT equipment)",
        "Educational ICT_ICT learning resources": "ICT learning resources",
        "Educational supplies_Examination fees": "Examination fees",
        "Teaching and Teaching support staff_Educational consultancy": "Educational Consultancy",
        "Teaching and Teaching support staff_Agency supply teaching staff": "Agency supply teaching staff",
        "Catering staff and supplies_Catering supplies": "Catering supplies",
        "Non-educational support staff and services_Audit cost": "Auditor costs",
        "Other costs_Other insurance premiums": "Other insurance premiums",
        "Administrative supplies_Administrative supplies (non educational)": "Administrative supplies - non educational",
        "Income_Direct revenue finance": "Direct revenue financing (Revenue contributions to capital)",
        "Non-educational support staff and services_Professional services (non-curriculum)": "Legal & Professional services",
        "Other costs_PFI charges": "PFI Charges",
        "Other costs_Interest charges for loan and bank": "Interest charges for Loan and Bank",
        "Revenue reserve": "Revenue Reserve",
        "RR apportionment from CS": "Share of Central Services Revenue Reserve, distributed on per pupil basis, at end of period based on time spent in trust",
        "In year balance": "In year balance",
        "Income_Total grant funding": "Total Grant Funding",
        "DFE/EFA Revenue grants": "DFE/EFA Revenue grants",
        "Income_Direct grants": "Direct Grants",
        "Community Grants": "Community Grants",
        "Income_Total self generated funding": "Total Self Generated Funding",
        "Total Income": "Total Income",
        "Supply Staff Costs": "Supply Staff Costs",
        "Other Staff Costs": "Other Staff Costs",
        "Total Staff Costs": "Total Staff Costs",
        "Maintenance & Improvement Costs": "Maintenance & Improvement Costs",
        "Premises Costs": "Premises Costs",
        "Catering Expenses": "Catering Expenses",
        "Occupation Costs": "Occupation Costs",
        "Total Costs of Supplies and Services": "Total Costs of Supplies and Services",
        "Total Costs of Educational Supplies": "Total Costs of Educational Supplies",
        "Costs of Brought in Professional Services": "Costs of Brought in Professional Services",
        "Total Expenditure": "Total Expenditure",
        "Revenue reserve_app": "RR + share of CS RR distributed on proportional per pupil basis",
    }
}
