displayName: Peak_API_Benchmark - Comparator Set
testPlan: url-test.json
description: Peak load test for GET /comparator-set/school/{identifier}/default
engineInstances: 1
testId: b2169cfc-f186-4452-8717-d64aed36202c
testType: URL
subnetId: /subscriptions/a5c0a8d7-a54d-4a6d-ab79-4ca64a3b750f/resourceGroups/s198t01-ebis-core/providers/Microsoft.Network/virtualNetworks/s198t01-app-service-network/subnets/s198t01-load-test-subnet
publicIPDisabled: true
splitAllCSVs: False
configurationFiles:
- schools.csv
failureCriteria:
- p75(response_time_ms) > 200
- p95(response_time_ms) > 300
- p99(response_time_ms) > 500
- percentage(error) > 1
secrets:
- name: benchmark-host-key
  value: https://s198t01-ebis-keyvault.vault.azure.net/secrets/benchmark-host-key
autoStop:
  errorPercentage: 90
  timeWindow: 60
