displayName: Average_Web - School Resources
testPlan: url-test.json
description: Average load test for GET /school/{identifier}/find-ways-to-spend-less
engineInstances: 1
testId: f23b0c7c-217a-4976-80a5-996db09a504e
testType: URL
splitAllCSVs: False
configurationFiles:
- schools.csv
failureCriteria:
- p75(response_time_ms) > 500
- p95(response_time_ms) > 1000
- p99(response_time_ms) > 2000
- percentage(error) > 0.1
autoStop:
  errorPercentage: 90
  timeWindow: 60
