# yaml-language-server: $schema=https://json.schemastore.org/pre-commit-config.json
repos:
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.18.1
    hooks:
      - id: markdownlint-cli2
