/* eslint-disable react-refresh/only-export-components */
export * from "src/views/compare-your-census-2/partials/types";
export * from "src/views/compare-your-census-2/partials/auxiliary-staff";
export * from "src/views/compare-your-census-2/partials/headcount";
export * from "src/views/compare-your-census-2/partials/non-classroom-support";
export * from "src/views/compare-your-census-2/partials/school-workforce";
export * from "src/views/compare-your-census-2/partials/senior-leadership";
export * from "src/views/compare-your-census-2/partials/teaching-assistants";
export * from "src/views/compare-your-census-2/partials/total-teachers";
export * from "src/views/compare-your-census-2/partials/total-teachers-qualified";
