parameters:
  subscription: ''
  environmentPrefix: ''
  environment: 'feature'
  cipEnvironment: ''
  disablePurgeProtection: ''
  supportAlertEmail: ''
  dependsOn: []
  workspaceDir: '$(Pipeline.Workspace)'

jobs:
  - deployment: CoreDeployment
    displayName: 'Core deployment to ${{ parameters.environment }}'
    dependsOn: ${{ parameters.dependsOn }}
    pool:
      vmImage: ubuntu-latest
    environment: ${{ parameters.environment }}
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: none

            - download: current
              displayName: 'Download core db artifacts'
              artifact: core-db

            - download: current
              displayName: 'Download core terraform artifacts'
              artifact: core-terraform

            - template: ..\common\run-terraform.yaml
              parameters:
                subscription: ${{ parameters.subscription }}
                environmentPrefix: ${{ parameters.environmentPrefix }}
                environment: ${{ parameters.environment }}
                cipEnvironment: ${{ parameters.cipEnvironment }}
                disablePurgeProtection: ${{ parameters.disablePurgeProtection }}
                supportAlertEmail: ${{ parameters.supportAlertEmail }}
                module: 'core'

            - task: AzureKeyVault@2
              displayName: 'Import key vault vars'
              inputs:
                azureSubscription: ${{ parameters.subscription }}
                KeyVaultName: '${{ parameters.environmentPrefix }}-ebis-keyvault'
                SecretsFilter: '*'
                RunAsPreJob: false

            - task: ExtractFiles@1
              displayName: 'Extract core database'
              inputs:
                archiveFilePatterns: '${{ parameters.workspaceDir }}/core-db/Core.Database.zip'
                destinationFolder: '${{ parameters.workspaceDir }}/db'

            - bash: |
                AGENT_IP=$(curl -s https://ifconfig.me)
                echo "##vso[task.setvariable variable=agent-ip]$AGENT_IP"
                echo "Pipeline Runner IP: $AGENT_IP"
              displayName: 'Get pipeline runner IP'

            - task: AzureCLI@2
              displayName: 'Set firewall rule for SQL server network access'
              inputs:
                azureSubscription: ${{ parameters.subscription }}
                scriptType: 'bash'
                scriptLocation: 'inlineScript'
                inlineScript: |
                  echo "Adding firewall rule for pipeline runner IP"
                  az sql server firewall-rule create \
                    --resource-group $(core-sql-server-resource-group) \
                    --server $(core-sql-server-name) \
                    --name pipeline-runner-ip \
                    --start-ip-address $(agent-ip) \
                    --end-ip-address $(agent-ip)

            - task: AzureCLI@1
              displayName: 'Run core database migrations'

              inputs:
                azureSubscription: ${{ parameters.subscription }}
                scriptLocation: inlineScript
                inlineScript: ./Core.Database -c '$(core-sql-connection-string-default)'
                workingDirectory: '${{ parameters.workspaceDir }}/db'

#            - script: ./Core.Database -c '$(core-sql-connection-string-managed-identity)'
#              workingDirectory: '${{ parameters.workspaceDir }}/db'
#              failOnStderr: true
#              displayName: 'Run core database migrations'

            - task: AzureCLI@2
              displayName: 'Remove firewall rule for SQL server network access'
              condition: always()
              inputs:
                azureSubscription: ${{ parameters.subscription }}
                scriptType: 'bash'
                scriptLocation: 'inlineScript'
                inlineScript: |
                  echo "Removing firewall rule for pipeline runner IP"
                  az sql server firewall-rule delete \
                    --resource-group $(core-sql-server-resource-group) \
                    --server $(core-sql-server-name) \
                    --name pipeline-runner-ip
