parameters:
  subscription: ''
  environmentPrefix: ''
  environment: 'feature'
  cipEnvironment: ''
  disablePurgeProtection: ''
  dependsOn: []
  workspaceDir: '$(Pipeline.Workspace)'

jobs:
  - deployment: CoreDeployment
    displayName: 'Core deployment to ${{ parameters.environment }}'
    dependsOn: ${{ parameters.dependsOn }}
    pool:
      vmImage: ubuntu-latest
    environment: ${{ parameters.environment }}
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: none

            - download: current

            - template: ..\common\run-terraform.yaml
              parameters:
                subscription: ${{ parameters.subscription }}
                environmentPrefix: ${{ parameters.environmentPrefix }}
                environment: ${{ parameters.environment }}
                cipEnvironment: ${{ parameters.cipEnvironment }}
                disablePurgeProtection: ${{ parameters.disablePurgeProtection }}
                module: 'core'

            - task: AzureKeyVault@1
              inputs:
                azureSubscription: ${{ parameters.subscription }}
                KeyVaultName: '${{ parameters.environmentPrefix }}-ebis-keyvault'
                SecretsFilter: '*'
                RunAsPreJob: false

            - task: ExtractFiles@1
              displayName: 'Extract core database'
              inputs:
                archiveFilePatterns: '${{ parameters.workspaceDir }}/core-db/Core.Database.zip'
                destinationFolder: '${{ parameters.workspaceDir }}/db'

            - script: ./Core.Database -c '$(core-sql-connection-string)'
              workingDirectory: '${{ parameters.workspaceDir }}/db'
              failOnStderr: true
              displayName: 'Deploy core database'