parameters:
  subscription: ''
  environmentPrefix: ''
  environment: ''
  pipelineEnvironment: ''
  cipEnvironment: ''
  workspaceDir: '$(Pipeline.Workspace)'
  dependsOn: []

jobs:
  - job: CoreDestroyManualValidation
    displayName: 'Validate destruction of Core resources'
    dependsOn: ${{ parameters.dependsOn }}
    pool: server
    steps:
    - task: ManualValidation@0
      displayName: 'Validation'
      inputs:
        instructions: 'Approve this step to destroy all Core resources in ${{ parameters.environmentPrefix }}'

  - deployment: CoreDestroy
    displayName: 'Destroy core infrastructure'
    dependsOn: [ CoreDestroyManualValidation ]
    pool:
      vmImage: ubuntu-latest
    environment: ${{ parameters.pipelineEnvironment }}
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self

            - template: ..\common\destroy-terraform.yaml
              parameters:
                workspaceDir: '$(System.DefaultWorkingDirectory)/core-infrastructure/terraform'
                subscription: ${{ parameters.subscription }}
                environmentPrefix: ${{ parameters.environmentPrefix }}
                environment: ${{ parameters.environment }}
                cipEnvironment: ${{ parameters.cipEnvironment }}
                module: 'core'
                deleteStorageAccount: true