parameters:
  subscription: ''
  environmentPrefix: ''
  environment: ''
  pipelineEnvironment: ''
  cipEnvironment: ''
  workspaceDir: '$(Pipeline.Workspace)'
  dependsOn: []
  disablePurgeProtection: ''
  supportAlertEmail: ''

jobs:
  - deployment: CoreSync
    displayName: 'Sync core infrastructure'
    dependsOn: ${{ parameters.dependsOn }}
    pool:
      vmImage: ubuntu-latest
    environment: ${{ parameters.pipelineEnvironment }}
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self

            - template: ..\common\sync-terraform.yaml
              parameters:
                workspaceDir: '$(System.DefaultWorkingDirectory)/core-infrastructure/terraform'
                subscription: ${{ parameters.subscription }}
                environmentPrefix: ${{ parameters.environmentPrefix }}
                environment: ${{ parameters.environment }}
                cipEnvironment: ${{ parameters.cipEnvironment }}
                module: 'core'
                disablePurgeProtection: ${{ parameters.disablePurgeProtection }}
                supportAlertEmail: ${{ parameters.supportAlertEmail }}