name: "Require PR Labels"

on:
  pull_request:
    types: [opened, edited, labeled, unlabeled, synchronize]

jobs:
  check-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Check for PR labels and leave review once
        uses: actions/github-script@v6
        with:
          script: |
            const pr = github.event.pull_request;
            if (!pr) {
              core.warning("This workflow only runs on pull_request events.");
              return;
            }

