name: "Require PR Labels"

on:
  pull_request:
    types: [opened, edited, labeled, unlabeled, synchronize]

jobs:
  check-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR labels
        uses: actions/github-script@v6
        with:
          script: |
            const pr = context.payload.pull_request;
            if (!pr) {
              core.warning("This workflow only runs on pull_request events.");
              return;
            }

            const labels = pr.labels.map(label => label.name);

            if (labels.length === 0) {
              core.setFailed("❌ This pull request must have at least one label.");
            } else {
              console.log(`✅ PR has labels: ${labels.join(", ")}`);
            }
