name: "Require PR Labels"

on:
  pull_request:
    types: [opened, edited, labeled, unlabeled, synchronize]

jobs:
  check-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Check for PR labels and leave review once
        uses: actions/github-script@v6
        with:
          script: |
            if (!context.payload.pull_request) {
              core.warning("This workflow only runs on pull_request events.");
              return;
            }

            const pr = context.payload.pull_request;
            const prNumber = pr.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const labels = pr.labels.map(label => label.name);

            if (labels.length === 0) {
              await github.rest.pulls.createReview({
                owner,
                repo,
                pull_number: prNumber,
                event: "REQUEST_CHANGES",
                body: "⚠️ Please add at least one label to this pull request before it can be merged."
              });
              core.setFailed("❌ PR has no labels.");
            } else {
              console.log(`✅ PR has labels: ${labels.join(", ")}`);
            }
