pool:
  vmImage: 'ubuntu-latest'

trigger:
  batch: true
  branches:
    include:
      - main
  paths:
    include:
      - support-analytics
      - pipelines/support-analytics
      - pipelines/common

pr:
  paths:
    include:
      - support-analytics

variables:
  - group: 'support'
  - name: TerraformFolder
    value: 'support-analytics/terraform'
  - name: TerraformDirectory
    value: '$(System.DefaultWorkingDirectory)/$(TerraformFolder)'
  - name: 'ShouldDeploy'
    value: $[and(eq(variables['Build.SourceBranch'], 'refs/heads/main'), ne(variables['Build.Reason'], 'PullRequest'))]
  - name: 'Version'
    value: $[format('{0:yyyy}.{0:MM}', pipeline.startTime)]
  - name: 'Version.Revision'
    ${{ if and(eq(variables['Build.SourceBranch'], 'refs/heads/main'), ne(variables['Build.Reason'], 'PullRequest')) }}:
      value: $[counter(variables['Version'], 0)]
    ${{ else }}:
      value: 'XX'
  - name: 'Version.BuildNumber'
    value: $(Version).$(Version.Revision)

stages:
  - stage: Build
    displayName: 'Build artifacts'
    jobs:
      - job: SetBuildNumber
        displayName: 'Set build number'
        steps:
          - checkout: none
          - bash: |
              echo "##vso[task.setvariable variable=Version.BuildNumber]$(Version.BuildNumber)"
              echo "##vso[task.setvariable variable=Version.BuildVersion]$(Version.BuildNumber)"
              echo "##vso[build.updatebuildnumber]$(Version.BuildNumber)"
              echo "##vso[build.addbuildtag]$(Version.BuildNumber)"
            displayName: 'Set release number'
            condition: and(succeeded(), eq(variables['ShouldDeploy'],'true'))

      - job: PackageValidate
        displayName: "Validate open source packages"
        steps:
          - template: ..\common\validate-packages.yaml
            parameters:
              WorkingDir: '$(System.DefaultWorkingDirectory)/support-analytics'

      - job: FmtValidateTf
        displayName: "Lint and validate terraform"
        steps:
          - template: ..\common\fmt-validate-terraform.yaml
            parameters:
              TerraformDirectory: $(TerraformDirectory)

      - job: RunCheckOv
        displayName: "Static analysis terraform"
        steps:
          - template: ..\common\scan-terraform.yaml
            parameters:
              TerraformDirectory: $(TerraformDirectory)

      - job: MarkdownLint
        displayName: 'Markdown lint'
        steps:
          - template: ..\common\markdown-lint.yaml
            parameters:
              DocumentsDirectory: '$(System.DefaultWorkingDirectory)/support-analytics'

      - job: ZipStaticArtifacts
        dependsOn: [FmtValidateTf, RunCheckOv]
        displayName: 'Zip static artifacts'
        steps:
          - template: ..\common\publish-terraform-artifacts.yaml
            parameters:
              TerraformFolder: $(TerraformFolder)
              Module: 'support-analytics'

  - stage: DeployDevelopment
    dependsOn: [ Build ]
    condition: and(succeeded(), eq(variables['ShouldDeploy'],'true'))
    displayName: 'Development'
    jobs:
      - template: deployment.yaml
        parameters:
          subscription: 's198d.azdo-deployment'
          environmentPrefix: 's198d01'
          environment: 'development'
          cipEnvironment: 'Dev'

  - stage: DeployAutomatedTest
    dependsOn: [ Build ]
    condition: and(succeeded(), eq(variables['ShouldDeploy'],'true'))
    displayName: 'Automated test'
    jobs:
      - template: deployment.yaml
        parameters:
          subscription: 's198d.azdo-deployment'
          environmentPrefix: 's198d02'
          environment: 'automated-test'
          cipEnvironment: 'Dev'

  - stage: DeployTest
    dependsOn: [ Build ]
    condition: and(succeeded(), eq(variables['ShouldDeploy'],'true'))
    displayName: 'Test'
    jobs:
      - template: deployment.yaml
        parameters:
          subscription: 's198t.azdo-deployment'
          environmentPrefix: 's198t01'
          environment: 'test'
          cipEnvironment: 'Test'

  - stage: Approval
    dependsOn: [ DeployDevelopment, DeployAutomatedTest, DeployTest ]
    condition: and(succeeded(), eq(variables['ShouldDeploy'],'true'))
    displayName: 'Approval'
    jobs:
      - job: ManualValidation
        displayName: 'Validate lower environments'
        pool: server
        steps:
          - task: ManualValidation@0
            displayName: 'Validation'
            inputs:
              instructions: 'Validate changes in lower environments before continuing'

  - stage: DeployPreProd
    dependsOn: [ Approval ]
    condition: and(succeeded(), eq(variables['ShouldDeploy'],'true'))
    displayName: 'Pre-production'
    jobs:
      - template: deployment.yaml
        parameters:
          subscription: 's198p.azdo.deployment'
          environmentPrefix: 's198p02'
          environment: 'pre-production'
          cipEnvironment: 'Prod'

  - stage: DeployProd
    dependsOn: [ DeployPreProd ]
    condition: and(succeeded(), eq(variables['ShouldDeploy'],'true'))
    displayName: 'Production'
    jobs:
      - template: deployment.yaml
        parameters:
          subscription: 's198p.azdo.deployment'
          environmentPrefix: 's198p01'
          environment: 'production'
          cipEnvironment: 'Prod'